lerna.json, packages/jbrowse-web/.editorconfig, packages/jbrowse-web/.eslintrc.json
@rbuels, these are just a couple changes to repo infra houskeeping things:
* Specifies yarn as the NPM client so `lerna bootstap` uses that instead of NPM (and stops trying to create the package-lock.json file)
* Make .eslintrc.json look a little nicer
* Add to .editorconfig file
=> A couple updates to repo structure files

packages/generator-jbrowse/generators/app/index.test.js, packages/jbrowse-web/src/JBrowse.js, packages/jbrowse-web/src/index.js, packages/jbrowse-web/src/plugins/MainMenuBar/components/AboutDrawerWidget.js, packages/jbrowse-web/src/plugins/MainMenuBar/components/DropDownMenu.js, packages/jbrowse-web/src/plugins/MainMenuBar/components/HelpDrawerWidget.js, packages/jbrowse-web/src/plugins/MainMenuBar/components/MainMenuBar.js, packages/jbrowse-web/src/plugins/MainMenuBar/index.js, packages/jbrowse-web/src/plugins/MainMenuBar/model.js
This adds a main menu bar that includes two built-in entries ("Help" and "About") and can be extended to add other entries.
The built-in entries each include a drawer widget that they open when clicked.
Closes #5
=> Add a main menu bar

package.json, yarn.lock
I was going to bump webpack-dev-server here just to avoid some minor warnings from audit. I used yarn add webpack-dev-server at project root, which gave warnings about workspace but seemed valid
I also notice many dependencies listed are pinned to exact version numbers
Any reason for this?
=> Bump webpack-dev-server

packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/CallbackEditor.js, packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/ColorEditor.js, packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/ConfigurationEditor.js, packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/SlotEditor.js, packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap
@rbuels Some of the CSS controlling the slot mode button is not quite working right, so you might not want to merge exactly like this, but here are some ideas for using the MUI components and themes. It makes it so you can toggle light and dark mode out of the box. We'll probably want to figure out how to switch the code syntax highlighting to a dark theme, too, if we ever want to use it.
=> Add some MUI styling

packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
@cmdcolin I like this way of positioning the zoom controls a lot better. I've got a couple mostly code-style-related suggestions, but didn't want to commit directly to your PR. In keeping with [this advice](https://material-ui.com/getting-started/faq/#when-should-i-use-inline-style-vs-classes), I've been trying to use the inline `style` prop only for dynamic style properties and use `classNames` with a styles class for other things. This particular file is a bit of an exception since I've left the `grid`-related stuff (event the static stuff) all in the `style` props just to keep it all together and easier to read, but I've still tried to keep everything else using the JSS styles with `classNames`.
I also added just a little bit of padding to the right of the zoom controls since it was …
=> Rearrange styling elements a bit

packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
I added a extra container element which aids in positioning the zoom controls
Fixes issue observed in #89 "The zoom icons for magnifying glass go behind track when it is scrolled down"
Reviewing this change with &w=1 removes whitespace changes
=> Use "position: relative" on container to position zoom controls

packages/jbrowse-web/src/BaseAdapter.js, packages/jbrowse-web/src/BaseAdapter.test.js, packages/jbrowse-web/src/configuration/configurationSchema.js, packages/jbrowse-web/src/configuration/configurationSlot.js, packages/jbrowse-web/src/configuration/index.js, packages/jbrowse-web/src/index.js, packages/jbrowse-web/src/mst-types.js, packages/jbrowse-web/src/plugins/AlignmentsTrack/model/alignmentsTrack.js, packages/jbrowse-web/src/plugins/BamAdapter/BamAdapter.js, packages/jbrowse-web/src/plugins/BamAdapter/BamAdapter.test.js, packages/jbrowse-web/src/plugins/DivSequenceRenderer/components/DivSequenceRendering.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/__snapshots__/calculateBlocks.test.js.snap, packages/jbrowse-web/src/plugins/LinearGenomeView/models/baseTrack.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/calculateBlocks.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/calculateBlocks.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/serverSideRenderedBlock.js, packages/jbrowse-web/src/plugins/PileupRenderer/components/PileupRendering.test.js, packages/jbrowse-web/src/plugins/PileupRenderer/components/__snapshots__/PileupRendering.test.js.snap, packages/jbrowse-web/src/plugins/SvgFeatureRenderer/components/SvgFeatureRendering.test.js, packages/jbrowse-web/src/plugins/TwoBitAdapter/TwoBitAdapter.js, packages/jbrowse-web/src/plugins/TwoBitAdapter/TwoBitAdapter.test.js, packages/jbrowse-web/src/render.worker.js, packages/jbrowse-web/src/render.worker.test.js, packages/jbrowse-web/src/renderers/boxRenderer.js, packages/jbrowse-web/src/renderers/serverSideRenderer.js, packages/jbrowse-web/src/rootModel.js, packages/jbrowse-web/src/util/index.js, packages/jbrowse-web/src/util/workerDataAdapterCache.js
This moves a lot of the data adapter functionality to a shared BaseAdapter class so that name regularization can all happen in a single place. Individual adapters will only have to provide an array of reference sequences names they use, and everything else will be handled by the base class. Each individual adapter should implement:
- `loadData` this is where any metadata loading, etc. should happen and should return a promise for an array of reference sequence names
- `getFeaturesInRegion` returns a promise for an Observable, same as before. Does not need to do anything with assemblyName, as that is handled in the base class
- `freeResources` not used in any of our adapters yet
I've updated the BamAdapter and TwoBitAdapter to use this model, so you can look at those for an example. …
=> Regularize assembly and sequence names

packages/jbrowse-web/src/index.js, packages/jbrowse-web/src/plugins/DataHubManagerDrawerWidget/components/__snapshots__/ConfirmationDialog.test.js.snap, packages/jbrowse-web/src/plugins/HierarchicalTrackSelectorDrawerWidget/components/Contents.js
This makes the tracklist more compact. Subclassing material ui is a non trivial task but hopefully something that doesn't need doing all the time
Let me know if there is any feedback
Before
https://user-images.githubusercontent.com/6511937/52390225-4f2e2b00-2a65-11e9-8930-23f2dc7c606a.png
After
https://user-images.githubusercontent.com/6511937/52390283-92889980-2a65-11e9-9e22-a02bc3c5b58f.png
Addresses #99
=> Compact tracklist

package.json, yarn.lock
Greenkeeper caught some missing devDependencies for protein-viewer. It was working before, but only because the exact combination of installed packages happened to include those devDependencies, and the problem became apparent when greenkeeper tested with an updated version of babel.
Fixes #162
=> Add missing devDependencies in protein-viewer

packages/jbrowse-web/package.json, packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, yarn.lock
Updating this to the latest version and pinning to that version for the same reason `material-ui` is pinned: minor or patch version updates may break snapshots.
=> Update and pin react-simple-code-editor

packages/jbrowse-web/src/plugins/BamAdapter/BamAdapter.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/serverSideRenderedBlock.js, packages/jbrowse-web/src/render.js, packages/jbrowse-web/src/renderers/serverSideRenderer.js, packages/jbrowse-web/src/rpc.worker.js, packages/jbrowse-web/src/rpc/WebWorkerRpcDriver.js, packages/jbrowse-web/src/rpc/remoteAbortSignals.js, packages/jbrowse-web/src/util/index.js, packages/jbrowse-web/src/util/io/rangeFetcher.js
Adds AbortController-based cancellation to much of the rendering machinery. Passes AbortSignals to data backends, which can pay attention to them if they want.
resolves #155
=> render cancellation

packages/core/PluginManager.js, packages/jbrowse-web/src/plugins/IndexedFastaAdapter/BgzipFastaAdapter.js, packages/jbrowse-web/src/plugins/IndexedFastaAdapter/BgzipFastaAdapter.test.js, packages/jbrowse-web/src/rootModel.js
@rbuels I took out rootModel from PluginManager, and just tweaked a couple things and everything seems to still work. Luckily it was easier than I though.
I thought I remembered that the reason it was there in the first place was something to do with making the "configure track" button work on a ReferenceSequence track type (which is a sequence track but without the ability to edit the name, category, or description). I had to register it via some weird MST introspection in `packages/jbrowse-web/src/plugins/ConfigurationEditorDrawerWidget/model.js` which required the rootModel to be visible from the PluginManger (or something? I don't quite remember).
Whatever the case, though, the "configure track" button is working just fine for the ReferenceSequence track, so the original problem must …
=> Remove rootModel from PluginManager

packages/jbrowse-web/package.json, packages/jbrowse-web/src/plugins/DataHubManagerDrawerWidget/components/DataHubDrawerWidget.test.js, packages/jbrowse-web/src/plugins/DataHubManagerDrawerWidget/components/GenomeSelector.js, packages/jbrowse-web/src/plugins/DataHubManagerDrawerWidget/components/UrlInput.js, yarn.lock
@cmdcolin this PR is into your react_16.9_upgrade branch. I think this fixes the warnings about updating state after unmount (in both the tests and the browser), but might be good to test on another machine to be sure. It also finishes the UrlInput test so that it actually does all the steps for adding a connection. The line `await waitForElement(() => getByText('Assemblies'))` didn't work before React 16.9, so hopefully that's a good sign that testing should be easier with your update.
Also includes an version bump for react-sizeme to avoid a deprecation warning in the tests.
=> Try to fix UrlInput and test

packages/jbrowse-web/src/plugins/LinearGenomeView/components/ScaleBar.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/TrackBlocks.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/jbrowse-web/src/plugins/LinearGenomeView/models/blockBasedTrack.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/index.js, packages/jbrowse-web/src/plugins/LinearGenomeView/util/__snapshots__/calculateStaticBlocks.test.js.snap, packages/jbrowse-web/src/plugins/LinearGenomeView/util/blockTypes.js, packages/jbrowse-web/src/plugins/LinearGenomeView/util/calculateDynamicBlocks.js, packages/jbrowse-web/src/plugins/LinearGenomeView/util/calculateDynamicBlocks.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/util/calculateStaticBlocks.js, packages/jbrowse-web/src/plugins/LinearGenomeView/util/calculateStaticBlocks.test.js
Initially this just adds "elided" blocks, that represent one or more blocks that are too small to draw on their own and have been folded together.
This same mechanism can be expanded to draw things like breakpoint boundaries, joins, etc.
fixes #295
=> added support for different types of blocks

.travis.yml, package.json, packages/integration-tests/integration.test.js
This adds a BUILT_TESTS flag to the CI. This can allow tests to fail faster on CI. It doesn't necessarily give you a green light faster but it gives you a red light faster.
=> Add a BUILT_TESTS flag for the fs.exists tests

packages/jbrowse-web/src/plugins/VcfTabixAdapter/VcfFeature.ts, packages/jbrowse-web/src/plugins/VcfTabixAdapter/__snapshots__/VcfTabixAdapter.test.ts.snap
When I re-did JB1's VcfFeature after the create of vcf-js, I had to keep a lot of things compatible with the old VCF features. Since we're not bound by that in JB2, I'd like to propose some changes:
- Just assume what's in `get()` is the correct case, don't mess with `toLowerCase()` at all.
- Get rid of references to "genotypes", since really it's actually sample-specific data that can contain a lot more than just genotypes
- Just have `get()` access the variant information as-is. Only store in `data` things that are derived from the variant info (like SO terms).
- Don't copy INFO fields into `data`. This has the danger of overriding other fields and I think can be a bit confusing.
Here's what's available via `get()`:
```js
console.log(feature.tags())
// ["refName", "start", "end", …
```
=> Proposed updates to VCF Feature

packages/data-management/package.json, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/Contents.js, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/HierarchicalTrackSelector.test.js, packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/package.json, packages/linear-genome-view/src/LinearGenomeView/components/ServerSideRenderedContent.js, packages/linear-genome-view/src/LinearGenomeView/components/buttonStyles.js, yarn.lock
This proposes speeding up scrolling noted in #365 by using the timeout on requestIdleCallback, which I set to a very short value. This requires unpolyfilled requestIdleCallback due to the shim library not passing the options to the global.requestIdleCallback (see https://github.com/santiagogil/request-idle-callback/issues/2)
If a polyfill is strongly needed for a particular browser we can find a workaround.
I also removed the nested requestIdleCallback because I wasn't sure if it was aiding smoothness, but I could restore. Also, more speculative outside-the-viewport data rendering could make it perceived as smoother since the content would just be ready before you arrive there via scrolling
=> Fix sidescrolling smoothness

packages/core/rpc/RpcManager.js
This proposes a fix to warnings like this in the tests
```
console.warn node_modules/mobx-state-tree/dist/mobx-state-tree.js:3007                                                                                                                             [28/28]
Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type was 'AnonymousModel'). Either detach nodes first, or don't use objects after 
removing / replacing them in the tree.           
```
We check isAlive before updating the statetree, and also check whether it is a state tree at all because it appears some not state tree things can come through here.
=> Avoid writing to mst if the model isn't alive anymore

packages/config/src/ConfigurationEditorDrawerWidget/components/SlotEditor.js
This adds a combo of two things
1) Adds a useState for the field value and a useEffect for updating the widget
2) Fixes the fact that Number('')==0 by using parseInt and parseNumber :face_with_head_bandage: 
Addresses #267
=> Fix being unable to set negative numbers in config editor

packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.js, packages/linear-genome-view/src/LinearGenomeView/index.js
This is a proposal to add a rendering of an extra block on each side of the screen. There is a cost associated with this in terms of data fetching. At high zoom levels it makes scrolling look much better though. Potentially an extra block could be fetched only if you are at more zoomed-in levels so that it would not incur heavy amounts of data fetching.
=> Extra block render

packages/alignments/src/BamAdapter/BamSlightlyLazyFeature.ts, packages/alignments/src/BamAdapter/__snapshots__/BamAdapter.test.js.snap, packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.js, packages/jbrowse-web/public/test_data/config_human.json, packages/svg/src/SvgFeatureRenderer/configSchema.js
This modifies how SimpleFeature.fromJSON is called, which helps fix issues we were seeing in #396 
The features being received are raw objects that contain a uniqueId
SimpleFeature actually expects the uniqueId to be inside of {data:{uniqueId:..., ...}} though
By placing the fromJSON call to expect the data to be in a "data" property the code works again. It reduces confusion about when a feature actually has an "id" as in column 9 of GFF
This also says that we do not display a feature name as feature.id(), since this is often autocomputed. We only display an "id" if it is from feature.get('id')
=> Modify how SimpleFeature.fromJSON is called to fix NCList features

packages/jbrowse-web/package.json, packages/jbrowse-web/src/ui/App.js, packages/jbrowse-web/src/ui/Drawer.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.js, packages/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/menus/src/MainMenuBar/components/MainMenuBar.js, packages/menus/src/MainMenuBar/components/__snapshots__/MainMenuBar.test.js.snap, yarn.lock
This proposes to remove the fake scrolling that existed in jbrowse-web
The react-custom-scrollbars is removed along with the flexbox containment
This gives an outer scrollbar addressing concerns of #299  (note, it is outer, to the right of the drawer widget)
If there is a strong reason to keep everything in a container then maybe this will not pass but I think that using the native scroll is basically preferable
=> Remove custom scrolling

packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/wiggle/src/DensityRenderer/components/WiggleRendering.js, packages/wiggle/src/DensityRenderer/components/__snapshots__/WiggleRendering.test.js.snap, packages/wiggle/src/WiggleTrack/components/WiggleTrackComponent.js
This proposes a fix for #347 
It requires changing some CSS at two locations (the WiggleRendering div and removing the wrapper div around the SVG)
I don't fully *get it* but this seems to work and is at least a fairly minimal change set
=> Wiggle remove scrollbar

packages/linear-genome-view/src/BasicTrack/components/Track.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
This makes it so that scroll events are always get event.preventDefault()'d but they get propagated "appropriately" via callback props. The track rendering container handles the vertical scroll so it is propagated to there. A modularized "TrackContainer" containing current scroll state is extracted from inside the LinearGenomeView
Addresses #437
=> Fix vertical scrolling

packages/alignments/src/PileupRenderer/components/PileupRendering.js, packages/jbrowse-web/src/ui/App.js, packages/linear-genome-view/src/BasicTrack/components/Track.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.js
This addresses #440 
Some app notes:
The preventDefault at the lower level appears to prevent scrolling at all levels
You can see this in a basic html script like this where scrolling in the inner div, which preventDefault's the wheel event, makes it so the outer one does not scroll (I think this is basically equivalent circumstances
```
<html>
<body>
<div id="out" style="background:green;width:200px;height:200px;padding:10px;overflow:auto">
<div id="in" style="background:red;width:100px;height:500px;padding:10px;">
</div>
</div>
<script>
document.getElementById('out').addEventListener('wheel', function(event) {
console.log('outer')
}, {passive:false})
document.getElementById('in').addEventListener('wheel', function(event) {
console.log('in')
event.preventDefault()
},{passive:false}) …
```
=> Fix scrolling the App pane

packages/circular-view/src/CircularView/components/CircularView.js, packages/circular-view/src/CircularView/models/CircularView.js
This adds the concept of "shouldntScroll" to the circular view. It makes it so that the app view does not scroll while any scrolling is happening in the circular view panel. It also makes the width 100% for the circular view which causes it to naturally display the scrollbar because previously it is missing (the manual setting of the width makes it go behind the drawer widget)
=> Modify scroll behavior for circular view

packages/jbrowse-web/public/test_data/config.json
This proposes removing the admin menu, at least the way it is configured by default in the config.json. It doesn't make sense to me to provide this as an admin function.
I moved the functions to the file menu.
If it is not supposed to be available to end users at all, then I would suggest removing it completely.
=> Remove Admin menu

packages/core/util/index.ts, packages/jbrowse-web/public/test_data/config_intergration_test_displayed_region_list.json, packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/package.json, packages/linear-genome-view/src/BasicTrack/util/__snapshots__/calculateStaticBlocks.test.js.snap, packages/linear-genome-view/src/BasicTrack/util/blockTypes.js, packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/linear-genome-view/src/LinearGenomeView/components/Rubberband.js, packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap.orig, packages/linear-genome-view/src/LinearGenomeView/index.js, packages/linear-genome-view/src/LinearGenomeView/index.test.js, yarn.lock
This is a preview of what a header for the Linear genome view could possibly look like
It does these things
* restores ability to horizontally flip the view
* has a vertical ... menu format
* allows itself to show/hide the header
* has ability to view the entire set of displayed regions from a zoomed-out point of view
Some of my proposed features including locstring input and refseq name dropdown are in some sense very problematic with our arbitrary notion of displayed regions. Therefore, these features may have to be removed, or linked to only show when the displayedRegions are tied to the assembly.
Marked as a draft
=> LGV header

packages/jbrowse-web/src/index.js
This is very basic and just checks `window.chrome`, which should allow chromium-based browsers like Chrome, Chromium, Opera, etc. (I tested on Opera and jbrowse-web appears to work fine).
Since this is just a temporary measure, I think it should be ok.
resolves #21
=> Show error on unsupported browsers

packages/core/BaseConnectionModel.js, packages/core/docs/connections.md, packages/data-management/src/ucsc-trackhub/model.js, packages/jbrowse-web/src/JBrowse.js, packages/jbrowse-web/src/jbrowseModel.js, packages/jbrowse-web/src/ui/DevTools.js, packages/jbrowse1/src/JBrowse1Connection/model.js, packages/trackhub-registry/src/trackhub-registry/model.js
This fixes a bug where refreshing the screen with a connection open caused a crash. It also adds some session-related options to the DevTools (updates the "clear session" button and adds toggling of url and localStorage session storing).
=> Session updates

packages/linear-genome-view/src/BasicTrack/components/Block.js, packages/linear-genome-view/src/BasicTrack/components/BlockBasedTrack.js, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.js, packages/linear-genome-view/src/LinearGenomeView/components/Ruler.js, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.js
This is a sort of intricate stringing through of observer() that ends up reducing Ruler bar re-renderings
It also makes calculateStaticBlocks not return a new object if it is unchanged, which possibly could be done more intelligently, but it is effective in it's current state in reducing the re-renders
Addresses #434
=> Reduce ruler rerendering

packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js
This makes the actual feature.get('start') coordinate get passed to the layout, because the layout is actually performed without horizontal flipping. Ref #468
=> Fix feature not found in precomputed layout error

package.json, packages/alignments/package.json, packages/config/package.json, packages/config/src/ConfigurationEditorDrawerWidget/components/SlotEditor.js, packages/core/package.json, packages/data-management/package.json, packages/filtering/package.json, packages/jbrowse-web/package.json, packages/jbrowse1/package.json, packages/linear-genome-view/package.json, packages/menus/package.json, packages/protein-widget/package.json, packages/sequence/package.json, packages/trackhub-registry/package.json, packages/variants/package.json, packages/wiggle/package.json, yarn.lock
Turns out there was only one place that wasn't using mst-reflection that caused the tests to fail. Updating it to use that instead of calling MST reserved properties directly fixed it.
resolves #193
=> Update to latest MST version (3.14.1)

packages/alignments/src/PileupRenderer/PileupRenderer.ts, packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/core/pluggableElementTypes/renderers/BoxRendererType.js, packages/core/util/layouts/BaseLayout.ts, packages/core/util/layouts/GranularRectLayout.ts, packages/core/util/layouts/PrecomputedLayout.js, packages/jbrowse-web/src/__snapshots__/rpcMethods.test.js.snap, packages/jbrowse-web/src/rpcMethods.test.js, packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js, packages/svg/src/SvgFeatureRenderer/configSchema.js
This adds the concept of the maxHeight for SVG tracks
Note that the features that are not in final layout are not shipped to the frontend from the webworker so that PrecomputedLayout doesn't complain about the features not being in the layout
Addresses #391
=> Set the maxHeightReached on the render results

packages/__mocks__/@testing-library/react.js, packages/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap, packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/data-management/src/AddConnectionDrawerWidget/components/__snapshots__/AddConnectionDrawerWidget.test.js.snap, packages/data-management/src/AddTrackDrawerWidget/components/__snapshots__/AddTrackDrawerWidget.test.js.snap, packages/data-management/src/AddTrackDrawerWidget/components/__snapshots__/ConfirmTrack.test.js.snap, packages/data-management/src/AddTrackDrawerWidget/components/__snapshots__/TrackSourceSelect.test.js.snap, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/menus/src/MainMenuBar/components/__snapshots__/DropDownMenu.test.js.snap, packages/menus/src/MainMenuBar/components/__snapshots__/MainMenuBar.test.js.snap, packages/menus/src/SessionManager/components/__snapshots__/SessionManager.test.js.snap, packages/variants/src/VariantFeatureDrawerWidget/__snapshots__/VariantFeatureDrawerWidget.test.js.snap
This creates a mock for @testing-library/react in packages/__mocks__/@testing-library/react.js that wraps all calls to render() in the <StylesProvider> with a generateClassName function to removes the numerical suffix
Fixes #500
=> Mock testing lib render

packages/linear-genome-view/src/BasicTrack/util/__snapshots__/calculateStaticBlocks.test.js.snap, packages/linear-genome-view/src/BasicTrack/util/calculateDynamicBlocks.js, packages/linear-genome-view/src/BasicTrack/util/calculateDynamicBlocks.test.js, packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.js, packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.test.js, packages/linear-genome-view/src/LinearGenomeView/index.ts
This makes the concept of the displayedRegions being horizontallyFlipped into a view called effectiveRegions. I could have modified it so that "displayedRegions" itself was a view, but that would sort of change the "public API" of setting displayedRegions from config files for example, which seems to be something that might be worth keeping. Therefore I chose to make "effectiveRegions" the name of the view.
fixes #502
=> Fix horizontal flip on displayed regions

packages/core/util/layouts/GranularRectLayout.test.js, packages/core/util/layouts/GranularRectLayout.ts
Fixes #486 
This bug was a bit tricky
This error actually wasn't occurring on master because the max height for SVG bugfix introduced a concept that hard-filters undefined features from the layout, however, there was a actual issue with serializeRegion where it was filtering out things that were getting missed due to the pitchX resolution apparently missing things
I added a pitchX adjustment of -1 and +1 on the left and right to avoid missing layout'd features that should actually be included
=> Fix issue with some undefined features being found in layout due to granular rect resolution

packages/jbrowse-web/src/ui/App.js
This uses React.memo to optimize the re-rendering of the drawer widget
This is pretty helpful for performance, you can see in all our performance traces that the Drawer widget will get constantly re-rendered without this
=> Optimize drawer rerendering

packages/core/util/layouts/GranularRectLayout.ts
The granular rect layout was producing two errors
1) Maximum stack size exceeded due to the spread being bad
2) Excessive layout being thrown away and re-initialized due to apparently the Math.max being used and being set to this.offset, which was way larger than the additionalLength that was proposed to be added
This reverts those changes to a jbrowse 1 style code (currLength - oLeft == this.offset - left + currLength  from jb1's granular rect layout)
=> Update granular rect layout extension to use original jbrowse 1 code

packages/core/util/layouts/GranularRectLayout.test.js, packages/core/util/layouts/GranularRectLayout.ts
This fixes #553 by making sure to take into account this.rowState.offset in all cases (specifically, it seems that oRight was not re-initialized with right-this.rowState.offset after the block in question). If you console.log this.rowState.offset before and after the loop, it can change in some cases, and oRight was specifically not updated.
This also re-initializes this.rowState=initialize(left,right) as calling initialize(left,right) with no assignment would be void when the layout width is exceeded.
=> Fix layout bug #553

packages/linear-genome-view/src/LinearGenomeView/components/Ruler.tsx, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.test.tsx, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.ts
This gets rid of the idea of refName labels being part of both Ruler and ScaleBar in slightly different ways, making it all a part of ScaleBar, and also fixes #554 by making the zIndex of the label on the right bigger than the one on the left
=> Fix refName labeling zIndex issue and unify implementation of refName labels

packages/config/src/ConfigurationEditorDrawerWidget/components/SlotEditor.js, packages/core/configuration/configurationSlot.js
This fixes #519 
This is a small PR to reset a config slot to it's default value, which I thought was valid for invalid inputs to the number editor for example
=> Add reset method for config slot and use it to go to the default value

packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.ts
This restores the button for the track selector instead of having to use the dropdown menu for accessing it. I think the UI is probably a little better off this way, and it appears to fit within the UI just fine
Here are screenshots with and without the LGV header turned on
=> Restore track selector button

packages/jbrowse-web/src/JBrowse.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, packages/linear-genome-view/src/LinearGenomeView/components/Ruler.tsx, packages/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.ts
* Use rAF for scrolling to prevent multiple scroll events per frame, this is a big fps win. You could see in performance traces multiple wheel events would fire per-frame and this would cause lots of excessive CPU burn (https://calendar.perfplanet.com/2013/the-runtime-performance-checklist/)
* Remove need for LinearGenomeView to re-render on each frame
* Switch from toLocaleString to a "mathPower" function in Ruler. This is faster and the Ruler re-rendering can cause a significant frame rate stutter if it is slow (https://jsperf.com/locale-number-formatting/16)
* Debounce the session updater
=> Add optimizations for faster FPS

README.md, package.json, packages/jbrowse-desktop/package.json, packages/jbrowse-desktop/public/electron.js, packages/jbrowse-web/package.json, packages/jbrowse1/src/NCListAdapter/NCListAdapter.test.js, packages/protein-widget/package.json, yarn.lock
In order to make sure the desktop version works well on Windows, I made some changes so our whole development toolchain can be done purely on Windows. Also now url encodes/decodes session file names on desktop so people can put whatever characters they want in their session name and the filesystem on any OS shouldn't complain.
=> Enable development on Windows

packages/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap, packages/bed/package.json, packages/core/BaseFeatureDrawerWidget/BaseFeatureDetail.tsx, packages/core/BaseFeatureDrawerWidget/__snapshots__/index.test.js.snap, packages/core/BaseFeatureDrawerWidget/declare.d.ts, packages/core/package.json, packages/jbrowse-web/public/test_data/config.json, packages/variants/src/VariantFeatureDrawerWidget/__snapshots__/VariantFeatureDrawerWidget.test.js.snap, packages/wiggle/package.json, yarn.lock
This adds clinvar and clinvar CNV for hg19 and hg38, and fixes a bug in @gmod/bbi and @gmod/bed that was stopping these from being loaded
Note that these contain some raw html in their feature detail panels, can do a safe rendering of this?
=> Update @gmod/bed and @gmod/bbi for bigbed fix, and add some clinvar tracks

packages/jbrowse-desktop/public/electron.js
This is a small PR to just make the config/session json have some whitespace
=> Stringify config.json with whitespace on desktop

packages/linear-genome-view/src/BasicTrack/components/BlockBasedTrack.js, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.tsx
This is a miscellaneous change but it looked like it was unnecessary to pass blockState manually to the tracks, as the track models contain this info
=> Remove blockState as a extra prop, assume it comes from track model

packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.js, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts, packages/linear-genome-view/src/LinearGenomeView/components/BlockError.js
This just adds a simple "reload" button to the block error message that reloads the block. I tested by disconnecting my network, getting the error, reconnecting, and then clicking "reload". It seemed to work.
Resolves #445
=> Add button to reload errored block

packages/jbrowse-desktop/public/electron.js
Discussed with @garrettjstevens 
This allows easier fetching of resources that have CORS blocked without stepping into node-fetch territory and there is no nodeIntegration on these workers
=> Turn off webSecurity on the web worker for the purpose of disabling same origin policy

packages/core/util/io/ElectronLocalFile.ts, packages/core/util/io/ElectronRemoteFile.ts, packages/jbrowse-desktop/package.json, packages/jbrowse-desktop/public/electron.js, packages/jbrowse-desktop/public/windowWorker.js, packages/jbrowse-desktop/src/JBrowse.js, packages/jbrowse-desktop/src/index.js, packages/jbrowse-desktop/src/jbrowseModel.js, packages/jbrowse-desktop/src/rootModel.js, packages/jbrowse-desktop/src/ui/RecentSessionCard.js, packages/jbrowse-desktop/src/ui/StartScreen.js, packages/jbrowse-web/src/rootModel.ts, packages/menus/src/MainMenuBar/components/MainMenuBar.js, packages/menus/src/MainMenuBar/components/__snapshots__/MainMenuBar.test.js.snap
This has some bugfixes and improvements to desktop user and dev experience:
- Electron window worker logs now appear in the main window's devtools console
- Recent session card names show full name in a tooltip
- Session renaming bugfixes, and also now renaming the current session from the menu bar is supported in desktop
- When in development, most recent session automatically loads on first load or refresh, so you can essentially refresh to the same session when developing
=> Desktop improvements

packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js
Selecting a feature currently causes a full re-render and can take over 1.5 seconds with two tracks on the screen, causing the window to feel slow
This avoids a re-render by just drawing to the overlay
This will feel much snappier on human data
=> Remove selected feature concept

package.json, packages/__mocks__/electron.ts, packages/core/ui/StartScreen.js, packages/jbrowse-desktop/src/JBrowse.js, packages/jbrowse-desktop/src/JBrowse.test.tsx, yarn.lock
This adds a bare electron mock for doing some unit testing
The electron-mock-ipc does not appear to implement invoke/handle so this is kind of done in a hacky way, but still works for some purposes.
Note that window.electron is read inside the component for this to work
Also I was getting a crazy infinite loop because a lint rule changed this
```
async function getSessions() {
setSessions(await ipcRenderer.invoke('listSessions'))
}
useEffect(() => {
getSessions()
}, [])
```
Into this
```
async function getSessions() {
setSessions(await ipcRenderer.invoke('listSessions'))
}
useEffect(() => {
getSessions()
}, [getSessions])
```
And that made it re-render infinitely 
Changed to this
```
;(async function getSessions() {
setSessions(await ipcRenderer.invoke('listSessions'))
})()
}, …
```
=> Add basic electron mock unit testing

packages/core/ui/App.js, packages/core/ui/ErrorSnackbar.tsx, packages/core/ui/NewSessionCards.js, packages/core/ui/Snackbar.tsx, packages/data-management/src/AddTrackDrawerWidget/components/AddTrackDrawerWidget.js, packages/jbrowse-desktop/src/sessionModelFactory.js, packages/jbrowse-web/src/sessionModelFactory.ts
This adds a bare-bones "Open new track" and "Open new connection" icons to the menubar. I think that this improves some discoverability of the mechanism
It also adds a global "snackbar message" on the session, and it opens one of these when the "Open new track" function ends up not automatically adding a track to a view
=> Put menu items for 'Open new track' and 'Open new connection' on menu

packages/breakpoint-split-view/src/components/AlignmentConnections.tsx, packages/breakpoint-split-view/src/components/BreakpointSplitView.tsx, packages/breakpoint-split-view/src/model.ts
This creates a basic paired read connection overlay
Even though this is not fully implemented to take advantage of all the details of paired reads, I think this is basically a sound contribution that can provide a solid starting point
It does a basic search of "hasPairedReads" similar to the existing switch on "hasTranslocations" and then calls some paired code, which then only plots the "not paired correctly" reads using the connectors, which is always turned on for cross-chromosomal pairs and other types of discordancies, and therefore filters out all the other normal paired end connections
=> Paired read connections

packages/breakpoint-split-view/src/BreakpointSplitView.ts, packages/circular-view/src/StructuralVariantChordTrack/models/StructuralVariantChordTrack.js, packages/core/assemblyManager.js
This is a template that could fix elided region click (#669 ) by manually finding in the views displayedRegions rather than the blocks which can be elided blocks
Note that this loses refName renaming
=> Fix elided region click

packages/alignments/src/PileupRenderer/components/PileupRendering.js, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.ts, packages/core/ui/Tooltip.tsx, packages/jbrowse-desktop/src/rpcMethods.js, packages/linear-genome-view/src/BasicTrack/blockBasedTrackModel.ts, packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.js, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts, packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js, packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.test.js, test_data/config_in_dev.json
Some work was done earlier to make fast mouseovers happen with an rtree, but the features from all the blocks, regardless of whether it was across totally different chromosomes, would be combined into the same rtree.
This PR makes it so the rtree is actually block specific, so that multiple independent layouts do not clobber each other
=> Fix issue with mouseover/feature selection appearing across chromosomes

packages/circular-view/src/CircularView/models/CircularView.js, packages/core/ui/ResizeHandle.js, packages/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.js, packages/sv-inspector/src/SvInspectorView/components/SvInspectorView.js, packages/sv-inspector/src/SvInspectorView/models/SvInspectorView.js
This fixes #667 
It uses flexbox layout instead of absolute positioning for the SV inspector
Also the drag handle height was undefined, leading to there being no drag handle, this simply restores that
=> Use display:flex to fix SV inspector layout, and fix drag handle

packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/HierarchicalTrackSelector.js, packages/jbrowse-desktop/src/sessionModelFactory.js, packages/jbrowse-web/src/declare.d.ts, packages/jbrowse-web/src/sessionModelFactory.ts
When closing a connection, if any of its tracks are open in a view or a configuration editor drawer widget, it opens a prompt making sure you want to close before closing.
fixes #653
=> Dereference tracks on connection close

packages/jbrowse-desktop/public/electron.js
Mac requires an app menu to be registered for any of the normal copy paste shortcuts
Therfore, we are just going to create the app menu on mac, on other platforms we'll leave it null because on linux and windows @garrettjstevens confirmed paste works fine
=> Make paste shortcut on Mac work in desktop

packages/core/BaseConnectionModel.js, packages/core/assemblyManager.js, packages/core/util/tracks.js, packages/data-management/src/ucsc-trackhub/model.js, packages/jbrowse1/src/JBrowse1Connection/index.d.ts, packages/jbrowse1/src/JBrowse1Connection/jb1ConfigParse.ts, packages/jbrowse1/src/JBrowse1Connection/jb1ToJb2.ts, packages/jbrowse1/src/JBrowse1Connection/model.js
This fixes a few things found while @keiranmraine has been testing connections with his JBrowse 1 configs
- Connections can no longer provide reference sequences for datasets. It was unused, complicated, and probably didn't actually work correctly. We'll add back in the ability to add assembly sequences from certain types of sources (like JBrowse 1) later as part of dataset management.
- If the JBrowse 1 track is recognized as valid, it just flags it as unsupported and moves on instead of erroring out
- JBrowse 1 store classes are used to guess the JBrowse 2 track and adapters, and if the store class isn't recognized it falls back to guessing based on the `urlTemplate` filename
- When falling back to `urlTemplate` filename, it now recognizes the `.bgz` file extension for block-gzipped …
=> JBrowse 1 Connection updates

packages/breakpoint-split-view/src/components/AlignmentConnections.tsx, packages/breakpoint-split-view/src/components/Breakends.tsx, packages/breakpoint-split-view/src/components/Translocations.tsx, packages/breakpoint-split-view/src/util.ts
Fixes #773 
The synteny_demo branch worked a bit on the getPxFromCoordinate concept so this enhances the getPxFromCoordinate call for the breakpoint split view which takes into account horizontal flipping and has a further bugfix (see removed TODO comment in this PR) that is relevant to the code being scalable to there being multiple displayedRegions in a single row of the breakpoint split view (previously assumed just one displayedRegion in the split view)
=> Fix horizontal flip in translocation

docs/plugin-development.md
This is a small README update that removes the plugin development notes and moves it to the docs folder. It also suggests running yarn start in jbrowse-web or jbrowse-desktop
=> Re-organize the readme

packages/data-management/src/AddConnectionDrawerWidget/components/AddConnectionDrawerWidget.js, packages/data-management/src/AddConnectionDrawerWidget/components/AddConnectionDrawerWidget.test.js, packages/data-management/src/ucsc-trackhub/model.js, packages/data-management/src/ucsc-trackhub/ucscTrackHub.js, packages/jbrowse-web/src/sessionModelFactory.ts, packages/jbrowse1/src/JBrowse1Connection/model.js
This is from a pairing between @peterkxie and me today.
When a UCSC hub or JBrowse 1 connection fails to connect, it shows a snackbar message and turns the connection off. It also tries to connect as soon as the connection is added, mirroring the behavior of when you add a track.
fixes #805
=> Show snackbar when connection fails to connect

packages/alignments/src/CramAdapter/CramAdapter.ts, test_data/config_in_dev.json
This contains some deep sequencing data, also called amplicons or targetted sequencing (not sure if the terms are all interchangeable but main thing we see is high coverage of specific areas). The illumina file is only 13MB and has 12,000x sequence depth and works pretty good I think
Then I also found nanopore data and it is a 400MB BAM, 200+MB CRAM and it ends up crashing with out of memory with both
=> Deep sequencing data examples

packages/core/assemblyManager.js
This is a fix that patches the #826 bug
This is probably a good fix to put in place, and we could streamline it into master
Additional efforts could include
(a) wire a proper assemblyName to this code from SV inspector
(b) create an integration test for SV inspector
=> Check for assemblyConfig existing to avoid assembly name being undefined

packages/linear-genome-view/src/BasicTrack/util/__snapshots__/calculateStaticBlocks.test.js.snap, packages/linear-genome-view/src/BasicTrack/util/calculateDynamicBlocks.ts, packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.ts
Fixes #839 
Dynamic blocks were missing InterRegionPaddingBlocks, but just adding those didn't fix it completely: 
The only way to keep everything in sync was to have both block types allocate space in the offset for all potential padding blocks, whether or not they were in the returned block set.
Also includes a bug fix where a dynamic block got elided when it was scrolled to be almost off screen.
=> Keep static and dynamic blocks in sync

package.json, yarn.lock
The 7.9 release of babel allows using "import type" and "export type" which are interesting features, this PR just solely upgrades babel. See https://babeljs.io/blog/2020/03/16/7.9.0#typescript-38-type-only-imports-and-exports-11171-https-githubcom-babel-babel-pull-11171
Note that doing these upgrades (which just involved `yarn upgrade-interactive` and checking the babel boxes) required manually adding babel-jest to the project root
=> Update @babel namespace packages

packages/core/assemblyManager.js, packages/core/package.json, packages/wiggle/package.json, yarn.lock
This is a small change that aims to improve the logic around the refNameMap code. It seems the logic for addRefNameMap and getRefNameMap could be combined into a single abortable-promise-cache
=> Refnamemap cache

package.json, packages/breakpoint-split-view/src/components/__snapshots__/BreakpointSplitView.test.js.snap, packages/breakpoint-split-view/src/model.ts, packages/circular-view/src/CircularView/models/CircularView.js, packages/core/BaseViewModel.ts, packages/core/ReExports.js, packages/core/ui/App.js, packages/core/ui/ViewContainer.tsx, packages/jbrowse-desktop/src/sessionModelFactory.ts, packages/jbrowse-web/src/__snapshots__/sessionModelFactory.test.js.snap, packages/jbrowse-web/src/sessionModelFactory.test.js, packages/jbrowse-web/src/sessionModelFactory.ts, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts, packages/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.js, packages/sv-inspector/src/SvInspectorView/models/SvInspectorView.js, yarn.lock
We were measuring the whole app width and passing that to the session, which had an autorun that then updated the view widths.
This simplifies things by just measuring the view widths directly and setting them, and not worrying about the whole app width at all. Since it measures the actual view widths, if a view shrinks due to a scroll bar appearing, everything updates accordingly and there isn't a problem with unwanted horizontal scroll bars.
The second commit adds a BaseViewModel for views to compose so they will be sure to have the basic requirements of a view (id, width, optional displayName, optional menuOptions).
Resolves #727
=> Measure View width instead of App width

packages/core/ui/Menu.tsx
This add a "subHeader" option to the Menu, can be used for naming groups, like the sketch in https://github.com/GMOD/jbrowse-components/issues/792#issuecomment-612153759
Looks like this:
=> Add subHeader to Menu

packages/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
The usage of setState to batch event updates in the LGV on side scroll was causing double renders as any setState will cause a re-render and slowness. I am not sure if it was just less obvious before but it became more noticeable following the LGV UI update. This makes the event updates batched using refs instead of state
Similar stuff to what Ian was seeing in his work on abrowse :)
=> Speedup side scrolling in LGV

packages/alignments/src/AlignmentsTrack/model.ts, packages/alignments/src/CramAdapter/CramAdapter.ts, packages/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts, packages/circular-view/src/StructuralVariantChordTrack/models/renderReaction.js, packages/core/assemblyManager.js, packages/core/data_adapters/dataAdapterCache.ts, packages/dotplot-view/src/DotplotTrack/index.ts, packages/jbrowse-desktop/src/rpcMethods.js, packages/jbrowse-web/src/rpcMethods.js, packages/jbrowse-web/src/rpcMethods.test.js, packages/jbrowse-web/src/sessionModelFactory.ts, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts, packages/protein-widget/src/rpcMethods.js, packages/wiggle/src/WiggleTrack/model.ts
as long as we are in the business of simplifying the RPC interface, getAdapter does not really seem to strictly need adapterType, the config will contain this in itself. I can't think of a reason for manually have it like this, so I just tried removing it
=> Remove need to manually pass in adapterType to RPC

packages/jbrowse-web/src/workerPolyfill.js
Adds a missing `removeAttribute` method to the workerPolyfill.js element. (workerPolyfill basically exists just to fake out `style-loader`, I wonder if there's a more robust way to do that...)
fixes #920
=> Add `removeAttribute` to workerPolyfill element

packages/dotplot-view/src/DotplotView/components/DotplotView.tsx
This performs a simple self avoidance of the labels, based on a hardcoded font height
Some notes:
a) It does not try to hide the "smaller" regions or prioritize "larger regions"
b) We are not doing region ellision
=> 921 dotplot labels

packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.js.snap, packages/svg/src/SvgFeatureRenderer/configSchema.ts
This was a carry-over from #886 
I propose not allowing feature.id() as a feature label. I think it is reserved as an internal id system and does not help to give features that have no name or id a label
=> Remove setting to have feature.id() as a label

packages/alignments/src/AlignmentsTrack/components/AlignmentsTrackBlocks.tsx, packages/alignments/src/PileupRenderer/components/PileupRendering.tsx, packages/alignments/src/PileupTrack/model.ts, packages/linear-genome-view/src/BasicTrack/blockBasedTrackModel.ts
Some stuff got removed during the cleanup to blockbasedtrackmodel and typescriptifying pileuprendering, these commits fix up the functionality to have right clicking on alignment features working again
=> Have alignments context menu functional again

packages/sv-inspector/src/SvInspectorView/models/SvInspectorView.js
This is an add on fix for a console related error in #950, just checks for an assembly existing before destructuring
=> Fix error of destructuring on initial load of the sv inspector view

packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/data-management/src/AddTrackDrawerWidget/components/__snapshots__/AddTrackDrawerWidget.test.js.snap, packages/data-management/src/AddTrackDrawerWidget/components/__snapshots__/TrackSourceSelect.test.js.snap, packages/generator-jbrowse/generators/app/index.test.js, packages/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, yarn.lock
In the ever-evolving js ecosystem, it is nice to stay updated
This gave a warning about our autocomplete mixing controlled and uncontrolled state however, probably due to a typescript correction that first made me change null->undefined, and then triggered this material-ui warning
https://github.com/mui-org/material-ui/issues/18173
I tried fixing this by making it so the key changes when it is correctly initialized.
=> Update deps and fix a material-ui warning

packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/src/BasicTrack/baseTrackModel.tsx, packages/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.tsx, packages/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx, packages/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx, packages/linear-genome-view/src/LinearGenomeView/components/VerticalGuides.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, test_data/config.json
There were quite a few things that get constantly re-rendered at each frame including
TrackContainer and all children such as TrackLabels
RubberBand which included all children
All VerticalGuides
All scale bar contents
Also removes the usage of children in VerticalGuides/RubberBand because I observed that the  usage of it was
```
<>
<SomeStuff>
{children}
</>
```
This implied to me that since it was a React fragment, it didn't really need to actually be using children
FPS for various parts of the app are restored to 60FPS
Applies to #117 (side scroll slow on firefox) but similarly accelerates chrome just because it accelerates a lot of per frame work
Fails opening the zoom scroll menu currently but should be fixable
=> Add some optimizations to improve FPS

packages/core/util/calculateStaticBlocks.ts, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.tsx
This suggests to remove the index parameter from the TrackBlocks in favor of blockKey which can incorporate the index from the displayedRegions (ref 2362665866)
=> Reduce re-rendering of track blocks

packages/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
May or may not be something we want to do, but this is just a small change that adds the refNameColor (currently used in the circular view) to the LGV overview.
=> Add refNameColor to LGV overview

.eslintrc.json
I think maybe we can remove @typescript-eslint/recommended-requiring-type-checking rules
It was something I added in the first place but I think it just wastes cpu
Running eslint ~20 second less without it for me, and I think the rules in it are not that interesting, garretts script/getSuggestions is basically doing the same thing probably
=> Remove @typescript-eslint/recommended-requiring-type-checking

packages/linear-genome-view/src/LinearGenomeView/components/Header.tsx, packages/linear-genome-view/src/LinearGenomeView/index.ts
This fixes #987 by navigating to a new refName causing basically a "showAllRegions" but I make it slightly zoomed in because it looks a little nicer that way (has a nice trapezoid pattern a la jbrowse 1 rather than both overview bars being square with each other)
=> Make navigating via RefNameAutocomplete create a "showAllRegions" type view

packages/alignments/package.json, packages/alignments/src/BamAdapter/BamSlightlyLazyFeature.ts, packages/alignments/src/BamAdapter/MismatchParser.test.ts, packages/alignments/src/BamAdapter/MismatchParser.ts, packages/alignments/src/PileupRenderer/PileupRenderer.ts, packages/alignments/src/PileupRenderer/sortUtil.ts, packages/jbrowse-web/package.json, yarn.lock
This addresses #969 
The performance is about 3x as fast, measured here
https://jsperf.com/md-parsing
This does so by adjusting CIGAR parsing and MD usage of the CIGAR
=> BAM parsing optimization

packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/src/LinearGenomeView/components/Header.tsx, packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts
This makes sure that all places in the LGV model that modify `bpPerPx` or `offsetPx` use `zoomTo(bpPerPx)` and `scrollTo(bpPerPx)`, which makes sure they are properly clamped. Before this, using setDisplayedRegion might result in the new region being completely offscreen (the root cause of #987), but now the clamping ensures that any new regions are on screen.
Also removes `showAllRegionsButSlightlyZoomedIn` since with bpPerPx being clamped, you never end up with the displayed regions square with the overview scale bar.
=> Make sure bpPerPx and offsetPx are clamped

.eslintrc.json, packages/jbrowse-cli/.gitignore, packages/jbrowse-cli/README.md, packages/jbrowse-cli/bin/run, packages/jbrowse-cli/bin/run.cmd, packages/jbrowse-cli/package.json, packages/jbrowse-cli/src/commands/hello.test.ts, packages/jbrowse-cli/src/commands/hello.ts, packages/jbrowse-cli/src/index.ts, packages/jbrowse-cli/tsconfig.json, yarn.lock
This adds boilerplate (just a simple hello world command) for jbrowse-cli so that we can decide if we agree on this before adding any specific commands. The framework used is [oclif](https://oclif.io/).
If you're in the jbrowse-cli package, the base command is `./bin/run`, which will show the help and the availabe commands. The hello world command can be run with `./bin/run hello`. Here's some example output:
```
$ ./bin/run
A command line tool for working with JBrowse 2
VERSION
@gmod/jbrowse-cli/0.0.0 linux-x64 node-v12.14.1
USAGE
$ jbrowse [COMMAND]
COMMANDS
hello  describe the command here
help   display help for jbrowse
```
```
$ ./bin/run hello --help
describe the command here
USAGE
$ jbrowse hello [FILE]
OPTIONS
-f, --force
-h, --help       show CLI help
-n, --name=name  name to …
```
=> jbrowse-cli boilerplate

packages/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx, packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts
I was navigating using the new overview rubber band, and found a situation where selecting a region caused a crash. See the added failing test in 2ebe710c2ce7825a117180725298c79ee9ce4fc6.
While looking at the zoomToDisplayedRegions code, I had an idea for a new algorithm for determining where to navigate to. Basically it does this:
- For each displayed region, check if it intersects with any the selection regions
- If it does, use that region and selection to calculate a start offset and an end offset
- Only set the start offset once, and update the end offset with each new overlap
- If there were any overlaps, use moveTo to navigate to the offsets (no longer uses navToMultiple)
This change passes all the previously existing tests as well as the one I added that was originally failing. …
=> Overview rubber band fixes

.travis.yml, packages/jbrowse-web/src/JBrowse.test.js
Unfortunately the cause of some slowness in #1008 is sort of unclear. There are some patterns I observed
- Using only pako can improve some performance, e.g. remove nodeUnzip
- Using gunzipSync can improve some performance, e.g. change nodeUnzip to use gunzipSync 
- There was another thing where we can sometimes reduce the amount of data we unzip in the BAM header because it by default adds two BGZIP blocks onto the end of the first request (indexData.firstDataLine + 65535 and then again). These added blocks are probably paranoid, and can likely be removed, only unzipping up to firstDataLine which improves some performance
- Other general BAM header and BAI index parsing improvements could be made (the babelization of the BAI parsing seems to result in some inefficient code sometimes, too …
=> Add longer timeout for jbrowse test

packages/circular-view/src/StructuralVariantChordTrack/models/renderReaction.js, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.ts, packages/core/util/index.ts, packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.tsx, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts
This changes the mobx reaction to our custom makeAbortableReaction for the serverSideRenderedBlock code
See #1012 for issue
I haven't seen the issue happen since using this. There was a think where the regions array would be marked as a dead state tree node and I had to manually serialize it here, which I'm not exactly sure why. The older code did not require this
=> Abortable reaction for blocks

packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.tsx
I was having trouble with test timeouts on my branch and noticed that the linear track block loading animation seemed to be causing it. This PR reverts the loading animation to the Material-UI LinearProgress, and is then able to reduce or remove several test timeout increases.
The LinearProgress component is probably not the best, so if we decide to merge this we should probably re-open https://github.com/GMOD/jbrowse-components/issues/968, but seems like a good quick fix for now.
=> Change block loading to decrease test timeouts

packages/svg/src/SvgFeatureRenderer/components/Box.js, packages/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.js.snap
This accomplishes a tentative fix for #1030 
It does not address the issue for non-box features though. I'd be curious if there are any ideas on whether that is needed or whether there is a good way to apply this fix through other SVG feature shapes
=> Clamp SVG values to the current block area

packages/variants/src/VcfTabixAdapter/VcfFeature.test.ts, packages/variants/src/VcfTabixAdapter/VcfFeature.ts
This is a follow up on a gitter comment where https://solgenomics.net/projects/tomato100 has vcf with END in the INFO field that is less than the start, and actually appears to be basically a bogus value so it is ignored
@garrettjstevens  suggested that we check if it is truly a symbolic field to see if we interpret the END
I tried this out here in this PR but I did have a couple of concerns
1) It is a little unclear of the checking of the symbolic field is really the right behavior here? It seems to work, so as a stop gap it does help this situation
2) It is sort of clear to me that, given that there can be multiple alternative alleles, each alternative allele could have it's own "END" field potentially. this is a little weird, and we could consider this maybe a non-issue and say our …
=> Add testing for valid VCF END

packages/circular-view/src/CircularView/models/__snapshots__/slices.test.js.snap, packages/core/util/index.test.ts, packages/core/util/index.ts, packages/linear-genome-view/src/BasicTrack/util/__snapshots__/calculateDynamicBlocks.test.js.snap, packages/linear-genome-view/src/BasicTrack/util/__snapshots__/calculateStaticBlocks.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/components/Header.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts
This proposes allowing comma-ified numerical inputs. I would like to parse it but I think generating it in the locstring by default is nice too. It's not the best experience to "count the zeros" in a number to see where you are
=> Allow and generate comma-ified locstrings

packages/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
The insertions were being expanded to cover a range of genome coordinates, causing some weirdness as seen in the below screenshots
IGV
JBrowse 2
Samtools tview
There is a large insertion to the left of these, and the code would expand it so that the insertion would cover the range to the right of the insertions, but that would be incorrect
Now one thing that may be worth noting is that insertions are not not plotted from snpcoverage, and already deletions are also not plotted. Indeed
=> Fix insertion calculation for SNPCoverage

packages/core/CHANGELOG.md, packages/core/assemblyManager/assemblyManager.ts
Due to code from this PR https://github.com/GMOD/jbrowse-components/pull/1038
The waiting for assembly to load was broken
These lines in particular
https://github.com/GMOD/jbrowse-components/pull/1038/files#diff-de94407b67871344a97594d4eb5e8cbfL731-L738
This PR restores an when(() => {}) on the assembly being loaded from the reaction
=> Use a when to wait on the assembly from the reaction

packages/jbrowse-cli/tsconfig.json, yarn.lock
Since fancy-test merged https://github.com/oclif/fancy-test/pull/50, we're able to get rid of `@types/mocha` in our yarn.lock and re-enable lib checks in the CLI tsconfig.json.
=> Re-enable CLI TS lib check

packages/alignments/package.json, packages/development-tools/package.json, packages/development-tools/src/build.ts, packages/variants/package.json, yarn.lock
This adds style loading to the plugin webpack configuration, so that plugins can use CSS and SCSS files. Based off the webpack config in jbrowse-protein-widget.
It also moves webpack to a peer dependency, so that it will just use the webpack of whatever imports it instead of requiring one of its own.
=> Add style loader to plugin webpack

packages/jbrowse-web/src/Loader.test.tsx, packages/jbrowse-web/src/Loader.tsx, packages/jbrowse-web/src/Loading.tsx, packages/jbrowse-web/src/index.js
Results in about 200kb of JS being downloaded before rendering a Loading indicator. Current master is about 3MB
Ref #1056
=> Add code splitting to make loading bar appear faster

packages/jbrowse-cli/src/commands/add-track.test.ts, packages/jbrowse-cli/src/commands/add-track.ts, packages/jbrowse-cli/test/data/test_config.json
Current master branch fails to add a track if there are multiple assemblies present
This adds a test for it, and this additionally fixed some weirdness in the sequenceAdapter search logic for AlignmentsTracks (findIndex was not behaving appropriately and returning 0 for an index that did not exist for some reason...I switched it to use simple find instead of findIndex)
=> Fix add track when there are multiple assemblies

packages/development-tools/babel.config.js, packages/development-tools/package.json, packages/development-tools/src/build.ts
Have babel target be node 10 instead of current node version. Also remove `--root-mode upward` since the package has its own babel.config.js and doesn't need to look for the monorepo root one.
=> Support node >=10 in development-tools

packages/linear-genome-view/src/LinearGenomeView/components/Header.tsx, packages/linear-genome-view/src/LinearGenomeView/index.ts
https://github.com/GMOD/jbrowse-components/pull/945 added logic described in https://github.com/GMOD/jbrowse-components/issues/899 for navigating to locStrings, especially in the case that there may be multiple locations in one locString. The logic got added to the Header so the the location box could use it. This PR proposes that  the logic be moved to the LGV model so other things can use it too.
This is a change I made to make the embedded linear view work, but I wanted to bring it in separately while the embedded linear view build gets worked out.
=> Move navToLocString logic from Header to model

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx, packages/variants/src/VariantFeatureWidget/VariantFeatureWidget.js, packages/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.js.snap
This adds the possibility of adding descriptions to FeatureDetail widgets (for the fields or the values of a drawer). 
An example of how it is used can be found in packages/variants/src/VariantFeatureWidget/VariantFeatureWidget.js . 
This addition is made possible through the use of Tooltips provided by Material-UI.
=> add Tooltip descriptions to FeatureDetail Widgets

packages/alignments/src/PileupRenderer/sortUtil.ts
This proposes a fix for #1102 
Note that this does not try to handle sorting insertion alleles
Example of a position with multiple deletion allele lengths
http://localhost:3000/?config=test_data%2Fconfig_demo.json&session=eJztVU1v2kAQ_StoT61EjDEQsG9JqiZpKUVAS5OqQmt7sLex1-7umo8g__fO2hRMIVEjVeqlBx92vt6b2beeDeE0BuKQASxrY5CSJbxmmZZ5Zp6fWebEbDpWy-l0jY7duyd1ElMRME4cs058QZcgpsxXIXFavXadLBgsJXG-bgjzsWQ4fTf9MuT3Geb5TKYRXQ9KsDBo2mhU61Sf-owDFdfAkxg-Ywn0JPO5BDVcEafX7va6tmF2283zc8vu2nXipkMQ2mcaprUrDf4IAmRfEhAw32I1sZxUVKiCNHBkZrVtq2OeW806xi1ASEDjnEYS6oRKCbEbHTDNvyFXQb2HSnNtz77PLj9BuO_jImIBj4ErOdHB6AiBBSECd9o4HS_hcxZkgipkieE8iCMxQ-5MKeSA4UMWQZaWyc4WZ5X-EO6du7yL90DVuD1I0zSPQDanU4pmbv1jErO0iJut1o8YtpXG-P3lqFVLqeeypPZqcP2hP3pd26XUEh6ta2UeOZyfHlc5QRygRxUEiVhrW1FRG6lPUyxSIXpJ44utEW-axv3E2_WSCaavRKlUOo2GbBk0po …
=> Fix pileup sorting of deletion alleles

packages/jbrowse-web/src/tests/BasicLinearGenomeView.test.js, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.tsx, packages/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
This addresses #1026 
The logic using pointer events ends up actually being simpler because "setPointerCapture" lets us track the pointer outside of the event, which is what the complicated useEffect was doing
Unfortunately the tests appear to not support setPointerCapture/releasePointerCapture and it is called undefined in the jest test, so this test is xit'd out
=> Allow touchscreen using pointer events

packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.ts
Addresses #1053 
I added some sort of random heuristics but it disables the zoom in button when the slider is fully to the right or left, and also disables the zoomTo function behavior if there is basically a value that it interprets to be too close (and console.warn's rounding error)
=> Fix weird behavior found when zooming close to the max/min values of the slider

packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, packages/linear-genome-view/src/LinearGenomeView/components/MiniControls.tsx, packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
This adds a concept of minicontrols when the header is hidden
This is helpful in synteny because having the header visible is obtrusive
screenshot with and without synteny enabled
=> Add minicontrols

packages/alignments/src/BamAdapter/BamAdapter.ts, packages/alignments/src/CramAdapter/CramAdapter.ts, packages/core/assemblyManager/assembly.ts, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.ts, packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.tsx, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts, packages/wiggle/src/BigWigAdapter/BigWigAdapter.ts, yarn.lock
In looking at block level status as in #1136, I concluded that we might need block level and track level status
I tried using block level status only but for example, the first thing that is done is getRefNames for the track, and this is initiated from a block, which then does renameRegionsIfNeeded, which then does a getRefNames guarded by an AbortablePromiseCache, so only one request to getRefNames actually ever goes out for the multiple blocks requesting it. Therefore, in order to properly handle this, it might be that abortable-promise-cache itself needs to handle statusCallback and dispatch the status requests to all waiting requests.
An alternative, presented in this PR, is a little weirder, and implies usage of a trackLevel status and a blockLevel status.
This makes it so that, for …
=> Block level status and track level status

packages/core/util/Base1DViewModel.ts, packages/dotplot-view/src/DotplotView/components/DotplotView.tsx, packages/dotplot-view/src/DotplotView/model.ts
The dotplot was in need of some notion of a hover to keep the user oriented
This uses a simple div based tooltip with mouse hover next to crosshair cursor
Note that there are a couple tuned values that make it look better for this example, and could possible look weirder with long refnames (the top left coordinate indictor would not automatically put its endpoint right on the top left corner of the red box, thats a coincidence here)
The code is noticeably using both client coordinates vs offset coordinates, which is not great, maybe there's an easier way. The logic is that we want the operations inside the dotplot grid to be actual pixel offsets in that grid, but we want the tooltip div to be coordinates calculated relative to the whole dotplotview div container.
=> Dotplot coordinate indicator

packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts
Fixes #1171 
Uses a centerAtBase logic when the start displayed region === end displayed region
I wasn't necessarily ready to tackle this in the general case
To test, you can see that navigating to
ctgA:1000-1001 will center on this base, but navigating to a broader region like ctgA:500-1000 not have any offset related to centering
=> Add logic to "center at base" for locstring navigation

.travis.yml
This removes the node 14 from the test matrix. I believe it causes issues related to timeouts. I have seen this issue locally where node 14 instantiates the node modules and then node 10 runs a yarn build
The oclif seems to be a particular step that hangs in the yarn build possibly
The yarn cache is shared between node 10 and node 14 from what I can tell because the "Show repository caches" has only one master branch cache for example
I think removing one node version from the build matrix might help, or we can remove yarn caching.
=> Remove node 14 testing

packages/dotplot-view/package.json, packages/dotplot-view/src/DotplotView/components/DotplotView.tsx, packages/dotplot-view/src/DotplotView/components/declare.d.ts, packages/dotplot-view/src/DotplotView/model.ts
This adds a ctrl+zoom handle for dotplot similar to linear genome view
Doesn't have the ability to "zoom to mouse pointer", same limitation as lgv, but I think this is nice in terms of aided zooming navigation in the dotplot
=> Add dotplot ctrl zoom

packages/spreadsheet-view/src/index.ts
Calling it what it is.... a spreadsheet! Could also just say Spreadsheet instead of Spreadsheet view. But I think it makes it clear that what you are adding is a viewable spreadsheet. It could be interpreted to be a "track containing tabular data" or something the way it is currently worded
=> Change wording from "tabular data" to "spreadsheet view"

packages/core/assemblyManager/assemblyManager.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts, packages/spreadsheet-view/package.json, packages/spreadsheet-view/src/SpreadsheetView/components/Spreadsheet.js, packages/spreadsheet-view/src/SpreadsheetView/importAdapters/BedImport.ts, packages/spreadsheet-view/src/SpreadsheetView/importAdapters/ImportUtils.ts, packages/spreadsheet-view/src/SpreadsheetView/importAdapters/VcfImport.ts, packages/spreadsheet-view/src/SpreadsheetView/importAdapters/__snapshots__/VcfImport.test.ts.snap, packages/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/LocString.js, packages/spreadsheet-view/src/SpreadsheetView/models/Row.ts, packages/spreadsheet-view/src/SpreadsheetView/models/Spreadsheet.ts, packages/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.ts
This provides a clickable locstring for BED and VCF format imports
The locstring can be clicked
Things to observe
There is a `cellsWithDerived` which instantiates cells that contain derived functions
Contains a lightweight copy of some VcfFeature processing code for determining the end of a VCF feature
General observation
- The assembly manager stuff is sort of complex with this deep poking with when, as indicated by the code below needed to do two when calls. The second one (checking for assembly.region) was found to be needed if open a tabular view before any LGV usage. Would really like some more simplicity here
- The LGV has to instantiate a displayedRegion before doing a navigation, which is somewhat burdensome here
- This always launches a new view but potentially navigating an …
=> Derived column containing locstring for BED and VCF imports

products/jbrowse-cli/src/commands/create.ts, products/jbrowse-cli/tsconfig.json
Fixes #1187 
This uses noEmit: false in the CLI but an alternative would be to remove noEmit: true in root tsconfig.json
No sure the ramifications of that, but seems a little more straightforward. I think using --noEmit as a CLI option is a bit better when we want noEmit
=> Use noEmit: false to get lib output and fix cli build

packages/core/util/index.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/BedImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/ImportUtils.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/VcfImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/__snapshots__/VcfImport.test.ts.snap, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/LocString.js
I replaced this older PR for sorting with a new approach that stores cell.extendedData on LocString cells
This is facilitated by
a) ImportUtils, which performs a parseLocString on all rows when LocString column type is detected
b) the derivation callbacks for generated LocString columns
This has fairly good behavior on both importing and the generated columns that we have
It would not work if someone manually changed their column to LocString and it was not previously guessed to be a LocString column. The SpreadsheetModel.setColumnType would need to be able to handle this if that was the case
Nevertheless, this is basically working nicely for the simple circumstances we are using now
The alternative would be using parseLocString maybe as a computed property but it requires a lot of work …
=> Add locstring sort

.github/workflows/jbrowse-web.yml, package.json, packages/core/CHANGELOG.md, packages/development-tools/CHANGELOG.md, scripts/pre-commit.js
When writing JS/TS code, ESLint gives us feedback about the Prettier formatting. For non-JS/TS code, though, we don't get that feedback, although Prettier is able to format several different file types.
This adds a pre-commit git hook that checks if any of the changed files are not JS/TS files and runs Prettier on them if there are any. If all the changed files are JS/TS files, the hook doesn't add noticeable time when committing.
This will also help with files that have auto-generated content, like CHANGELOG files.
The hook also keeps the existing behavior of regenerating the CLI docs if any files in `products/jbrowse-cli` change.
=> Format non-JS/TS files in pre-commit hook

packages/core/ui/EditableTypography.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.test.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts
This fixes #1188, which looks like it was introduced in 69fa77d88b277914c9d7be3e09cd34d661cf6f69. This is the same idea as 69fa77d88b277914c9d7be3e09cd34d661cf6f69 (in moveTo, center a region that's smaller than the screen width), implemented in a different way.
Also includes a small fix since my editor was warning me that `event.keyCode` is deprecated.
=> Center moveTo region bugfix

.travis.yml, package.json
This is a possible fix for #1184 
The syntax
git push origin tag "v2*"
Ref https://stackoverflow.com/a/60802071/2129219, tested and does work. So it first does a
`git push origin tag "@gmod/jbrowse-web*"` and then a `git push --follow-tags` to push the rest
=> Slow push tags

products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/create.test.ts, products/jbrowse-cli/src/commands/create.ts, products/jbrowse-cli/src/commands/upgrade.test.ts, products/jbrowse-cli/src/commands/upgrade.ts
This is a method to paginate multiple pages of output from Github
It fetches one page at a time with await in loop and stops when it gets an empty array response
Check `curl "https://api.github.com/repos/GMOD/jbrowse-components/releases?page=2"` for example of the empty response
=> GitHub paginate

.prettierignore, package.json, plugins/config/src/FromConfigAdapter/FromConfigAdapter.ts, plugins/sequence/src/TwoBitAdapter/TwoBitAdapter.ts, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts, products/jbrowse-web/public/index.html, scripts/pre-commit.js, yarn.lock
Originally noticed by @elliothershberg, in the pre-commit hook, if the prettier didn't recognize any of the file types it tried to format, it threw an error:
Fixed by using the `--ignore-unknown` prettier CLI flag, new in v2.1.0.
=> Pre-commit formatting bugfix

package.json, products/jbrowse-desktop/package.json, yarn.lock
This produces an exe name that is jbrowse-desktop on all platforms
I think that it is better this way because the "JBrowse 2" exe name is somewhat awkward on linux for example, and could be confused with jbrowse CLI
Also gives the package name a @gmod namespace
=> Update so the exe name is jbrowse-desktop

plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.test.ts, plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
Fixes #1222 (git checkout skbr3_rnaseq; git pull --rebase origin speedup_snpcoverage to test)
A more scalable solution might be helpful since it could be useful to render large regions, but this helps with sparse ones a lot
=> Speedup for sparse SNPCoverage tracks

plugins/alignments/src/BamAdapter/MismatchParser.test.ts, plugins/alignments/src/BamAdapter/MismatchParser.ts
Fix for #1235 
Instead of making "getTemplateLocalCoord ignore the N" which is what it currently does, and works ok when there was just one N in a read, we incorporate N for getTemplateLocalCoord which helps with isoseq which can have many N segments
Still draft PR for the moment
=> Fix hq_isoform.bam rendering with fixes to getTemplateLocalCoord

plugins/alignments/src/PileupRenderer/PileupRenderer.ts
This was a rendering bug with the skip/intron rendering that was triggered by long isoseq reads
fixed
Possibly caused by long off-screen rendering of canvas, but kind of surprising still
=> Add a bugfix to PileupRenderer

packages/core/util/Base1DViewModel.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts
On current master when hovering over a base, the coordinate changes in the middle of the base. This is due to a math.round in pxToBp, and changing to a Math.floor appears to fix in both forward and horizontally flipped versions
=> Fix issue where the rubberband guide would change basepair label in the middle of basepair

plugins/alignments/src/BamAdapter/MismatchParser.test.ts, plugins/alignments/src/BamAdapter/MismatchParser.ts, plugins/alignments/src/BamAdapter/__snapshots__/BamAdapter.test.ts.snap, plugins/alignments/src/CramAdapter/CramSlightlyLazyFeature.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts
This uses 0 length insertions to correctly position the insertions in both forward and reversed (horizontally flipped) modes
Note that the real bug started because CRAM encoded the insertion length into the mismatch.length field but this is meant for length-on-reference, so this caused an issue
BAM used insertion length 1, and had a comment that was carried from jb1-jb2 but was originally committed in 2013 that said
//// GAH: shouldn't length of insertion really by 0, since JBrowse internally uses zero-interbase coordinates?
commit 7bdcebe8947815d657d5ea9832e73dc35965c6e7
Well, now it is length 0
We will need to see if there are ramifications to this but this fixes forward and reverse rendering of insertions in my initial testing
=> Fix insertion positioning in horizontally flipped mode

packages/core/configuration/configurationSchema.ts, packages/core/util/index.ts, plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.test.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/Contents.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.test.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/TrackEntry.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap, plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js, plugins/data-management/src/index.ts, plugins/linear-genome-view/src/BasicTrack/baseTrackModel.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, products/jbrowse-web/src/__snapshots__/sessionModelFactory.test.js.snap, products/jbrowse-web/src/rootModel.ts, products/jbrowse-web/src/sessionModelFactory.ts, products/jbrowse-web/src/tests/JBrowse.test.js, products/jbrowse-web/src/tests/util.js
This is a very simple minimal set of changes to allow session tracks
Notes
1) Very minimal set of changes, checks if admin mode in addTrackConf, diverts to rootModel.jbrowse if so, otherwise adds to session.sessionTracks
2) Then we generateHierarchy(session.tracks.concat(session.sessionTracks)) for the hierarchical track selector
This is very minimal nicely and allows refreshing the page and keeping your added track if it is a URL
Other notes
1) Does not know how to handle refreshing a local file that was opened, might want to check for that
2) Has xss related to config callbacks in the URL
=> Session tracks

products/jbrowse-cli/src/commands/admin-server.test.ts, products/jbrowse-cli/src/commands/admin-server.ts
I was able to reproduce the flaky error in the tests for `admin-server` from #1246 .
Occasionally, there would be an error where the string match in `killExpress()` which I use to kill the express server after tests where it is started would return `null`. I got rid of posting `adminKey` for the shutdown, and the flakiness seemed to go away. 
I'm not totally sure what would cause this to intermittently fail, since the match would have to work once before hitting this code. But seems to be solved. The adminKey would already have been checked in the test, and this change doesn't affect test logic.
=> 1246 flaky admin test

packages/core/ui/Menu.tsx, packages/core/ui/ViewContainer.tsx, packages/core/ui/theme.js, packages/core/util/blockTypes.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
This is an attempt at a more compact user interface
Things that it touches
1) More compact menus
2) Making global typography smaller
3) Use FormGroup row to keep controls inline in the header, and make them all the same height (kind of annoyingly intricately hardcoded still but might be a little better). There was some sensitivity to changing things like theme.spacing e.g. from 4->8 caused the lgv header layout to get distorted, so hopefully this is a little better
4) Removes the little x icon on the refseq dropdown
It has to manually specify the height of certain things, but it puts them all in a little better and more consistent vertical spacing
=> More compact UI

plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx
Looking at #1193 a clue was that changing Popover to divs stopped this from happening
Then I found this issue thread https://github.com/mui-org/material-ui/issues/10072
This appears to fix #1193
=> Add disableRestoreFocus to Popovers in rubberband

jest.config.js, products/jbrowse-desktop/package.json, products/jbrowse-protein-widget/package.json, products/jbrowse-web/package.json, products/jbrowse-web/src/Loader.tsx, yarn.lock
Currently I was seeing a warning (on master, have seen it for awhile) where dragging on the overview scale bar would cause a React warning about setState from another component running 
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render
Looking at the stack trace as recommended yielded a useForceUpdate in mobx code.
Found a lengthy thread that I didn't read entirely but found that updating mobx-react made the warning go away. Looks like it does something like "queued force updating now"
https://github.com/mobxjs/mobx-react-lite/issues/274 
https://github.com/mobxjs/mobx-react-lite/pull/299/files
Upgrading to the latest version printed a console log message said batchingForReactDom is not needed, so that is removed now too
=> Bump mobx-react version

plugins/circular-view/src/CircularView/models/CircularView.js, plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.js
PR #1249 broke SV inspector view unfortunately. Basically the cause was that we created generatedTrackConf but this was not added to the tree so using showTrack(generatedTrackConf.trackId) and then using resolveIdentifier did not work
I made it so there is an alternative interface, addTrackConf, on the circular view model, that helps with this scenario
I tried using a viewTrackConfs similar to what exists on dotplot/synteny views, e.g. adding the config to the tree to a specialized spot on the view only, but this made the live updating after spreadsheet filters were applied not update the view.
=> Fix SV inspector view

plugins/sequence/package.json, plugins/sequence/src/IndexedFastaAdapter/IndexedFastaAdapter.ts, yarn.lock
This adds a sequence cache for the indexed fasta
I found that trying to view the HG0096 high cov dataset was quite slow even when pretty zoomed in
Performance tracking revealed many many unzipping operations for tiny chunks of the bgzip indexed fasta
This is due to seqFetch calculating the MD tag for BAM, trying to unzip very tiny chunks sequence data repeatedly, e.g. each feature. Note that CRAM also benefits here since it uses the same seqFetch strategy
This adds a cache layer that extracts sequence chunks 128kb in size, and then slicing that as needed, for all operations involving sequence fetches. This is easier than trying to optimize the seqFetch operation specifically
Speedup
Before: 110s 
After: 20s
Viewing a 45kb region
=> Add a sequence cache backing indexed fasta

plugins/alignments/package.json, plugins/alignments/src/PileupRenderer/components/PileupRendering.tsx, plugins/linear-comparative-view/package.json, yarn.lock
I can't remember what this was for. Originally was probably having some trouble with something related to reactivity in the PileupRenderer. Doesn't seem affected when removed
=> Remove mobx-run-in-reactive-context runner

plugins/alignments/src/AlignmentsTrack/model.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/alignments/src/PileupRenderer/components/PileupRendering.tsx, plugins/alignments/src/PileupRenderer/sortUtil.ts, plugins/alignments/src/PileupTrack/components/PileupTrackBlurb.tsx, plugins/alignments/src/PileupTrack/model.ts, plugins/alignments/src/SNPCoverageTrack/model.ts
This is a breakout from the #1231 branch
Moves sorting from volatile to real track state
This also required updating AlignmentsTrack's autorun to make it capable of reloading the subtrack state
This would allow you to send a "session link" with a sort enabled on it. I like to imagine a screenshot service if that seems kind of unuseful.
Other track states like color scheme, linking reads etc were attempted in #1231
=> Make sort, show soft clipping stateful aspects of the track

products/jbrowse-web/src/tests/util.js
Possible fix for #1277 
This simply silences the warning
The alternatives to this approach could be
(a) Reverting to older mobx-react
(b) Fix mainthreadrendering to not use SSR
=> Silence useLayoutEffect warning in tests

package.json, yarn.lock
This was causing an error on jbrowse desktop startup, possibly since the electron@9.3.1 bump
```
yarn start
yarn run v1.22.4
$ concurrently "yarn serve" "wait-on http://localhost:3000 && yarn develop"
$ cross-env BROWSER=none yarn cra-start
$ rescripts start
[0] ℹ ｢wds｣: Project is running at http://10.0.0.41/
[0] ℹ ｢wds｣: webpack output is served from
[0] ℹ ｢wds｣: Content not from webpack is served from /home/cdiesh/src/jbrowse-components/products/jbrowse-desktop/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[0] [BABEL] Note: The code generator has deoptimised the styling of /home/cdiesh/src/jbrowse-components/products/jbrowse-desktop/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
[0] Compiled successfully!
[0] …
```
=> Remove devtron

packages/core/ui/theme.test.ts, packages/core/ui/theme.ts
Tiny PR, removes dense from MuiInputLabel
before
after
=> Remove dense from MuiInputLabel

products/jbrowse-desktop/package.json, products/jbrowse-desktop/src/index.js, products/jbrowse-protein-widget/package.json, products/jbrowse-protein-widget/src/Viewer.js, products/jbrowse-web/package.json, products/jbrowse-web/src/Loader.tsx, yarn.lock
Just a small change. [typeface-roboto](https://www.npmjs.com/package/typeface-roboto) is now deprecated, and they suggest [fontsource-roboto](https://www.npmjs.com/package/fontsource-roboto) as a drop-in replacement.
=> Use fontsource-roboto instead of typeface-roboto

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/add-assembly.test.ts, products/jbrowse-cli/src/commands/add-assembly.ts, products/jbrowse-cli/src/commands/add-connection.ts, products/jbrowse-cli/src/commands/add-track-json.ts, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-cli/src/commands/admin-server.ts, products/jbrowse-cli/src/commands/set-default-session.ts
With this PR I can say
jbrowse create mydir
jbrowse add-assembly ~/volvox.fa --out mydir --load copy
This will copy the files in there and copy them
I also make --out a synonym of --target, and allow using only the foldername instead of directly pointing to a config.json file. This much more commonly matches my expectations of a "data directory", which is what we are building with these commands (files are copied to the directory, etc making the fact that this is a directory an important feature)
I can propagate this through other files beyond add-assembly if it makes sense.
I also remove the check for manifest.json
I find this check for manifest.json does not fit with my expected workflow with the jbrowse app, and propose removing it. I prefer to not have to type --skipCheck or --force …
=> Add assembly fix when outside of directory

products/jbrowse-cli/README.md, products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/add-connection.test.ts, products/jbrowse-cli/src/commands/add-connection.ts, products/jbrowse-cli/src/commands/add-track-json.ts, products/jbrowse-cli/src/commands/add-track.test.ts, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-cli/src/commands/admin-server.test.ts, products/jbrowse-cli/src/commands/admin-server.ts, products/jbrowse-cli/src/commands/set-default-session.test.ts, products/jbrowse-cli/src/commands/set-default-session.ts, products/jbrowse-cli/src/commands/upgrade.test.ts, products/jbrowse-cli/src/commands/upgrade.ts, website/docs/faq.md
This PR
- Removes the checkLocation concept (e.g. checking for a manifest.json) except for in the case of jbrowse upgrade which should supply a path with a manifest.json
- Removes resolveFileLocationWithProtocol in add-track replacing it with an inline logic
- Removes the live-checking that a URL exists before adding it. If this is really desirable, we can add it back but I think it's better to let the tool be something that just does stuff rather than validate everything down to whether a url that they supplied is valid
- Adds --subDir argument to add-track so that when I say --load copy --subDir bam then it copies the file to a bam subdirectory near target
- Adds a --protocol argument that allows the user to manually specify the protocol used for the user to manually supply this, since …
=> Fix add track relative urls

products/jbrowse-cli/src/commands/add-track.test.ts, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-cli/src/commands/set-default-session.test.ts
This proposes having a --index argument so that we can supply an alternative index location to a BAM, CRAM, or VCF
It also removes the concept of supplying an index file directly to the positional argument
It does not try to tackle the double index of indexedfasta, suggesting that this should be more or less standardized. If needed, we can create an index2 option for this though
=> Add ability to specify an optional --index file for add-track

packages/core/ui/FileSelector.tsx, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, plugins/data-management/src/AddTrackWidget/components/__snapshots__/AddTrackWidget.test.js.snap, plugins/data-management/src/AddTrackWidget/components/__snapshots__/TrackSourceSelect.test.js.snap, plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.js
Having the file option but only having it disabled is somewhat difficult to understand. I propose removing the local file option
- except for desktop, where localFileAllowed = isElectron
- except for the SV inspector on web, which manually passes localFileAllowed to the FileSelector component's props
Addresses #694
=> Only render "url" file selector on web since "local file" not allowed currently

plugins/config/src/ConfigurationEditorWidget/components/SlotEditor.js, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap
Fixes #799. ~~Based on #513 since that moves the slot editor around.~~
Thought this small change was important since the config editor might be otherwise more confusing to users on release.
=> Hide callback option if function signature has no args

packages/core/assemblyManager/assembly.ts, packages/core/assemblyManager/assemblyManager.ts, plugins/data-management/src/AssemblyManager/AssemblyAddForm.tsx, plugins/data-management/src/AssemblyManager/AssemblyEditor.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.test.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.tsx, plugins/data-management/src/AssemblyManager/AssemblyTable.tsx, plugins/data-management/src/AssemblyManager/index.ts, plugins/data-management/src/index.ts, products/jbrowse-web/src/JBrowse.js, products/jbrowse-web/src/__snapshots__/rootModel.test.js.snap, products/jbrowse-web/src/jbrowseModel.js, products/jbrowse-web/src/rootModel.ts
This is a PR with the new location for the AssemblyManager GUI, for #513 . @rbuels and I moved the components into the `data-management` plugin, and use it from there.
I still want to do some more manual testing and look through the previous commit history to make sure nothing was missed. For example, need to grab the logic for making it only available in admin mode, and make sure it works fine from there.
Would be curious to get thoughts from @garrettjstevens  and @cmdcolin
=> New assembly manager

products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/rootModel.ts
Attempts to filter out undefined references in sessions at load time as much as possible. It can't get everything, but it does validate all the references at the time that you set the session, so at least you can handle the undefined ref at session load time.
Adds logic in Loader.tsx to handle the new undefined ref errors thrown setSession, which is what actually addresses the problem in #1275.
this is an alternate approach to #1275, but they might possibly be able to work together, could consider testing that.
=> make rootModel setSession check and attempt to remove undefined MST refs

packages/core/util/types/mst.ts, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.ts
[Issue: 1367 ](https://github.com/GMOD/jbrowse-components/issues/1367)
(with approach # 1 in this [pr](https://github.com/GMOD/jbrowse-components/pull/1363))
This PR fixes that (with approach # 2)
Volatile parentStart and parentEnd cause bug when identifying if a region is smaller than its parent region.
Proposal:
Either 
1) move the parentStart and parentEnd back to the model 
2) remove the parent Info from the model and use helper methods to fetch parent Info
3) discuss other options
=> Bug volatile parentinfo

plugins/config/src/ConfigurationEditorWidget/components/SlotEditor.js
Fixes #1341. @elliothershberg and I ran into the bug during our pairing and found this fix. The slot editor was getting rid of the baseUri when setting a new URI.
=> Keep existing slot attributes when setting URI

.travis.yml, package.json, products/jbrowse-lambda-functions/saved-sessions/save-session-jbrowse.js, products/jbrowse-web/package.json, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/ShareButton.tsx, products/jbrowse-web/src/sessionSharing.ts, products/jbrowse-web/src/tests/Loader.test.tsx, yarn.lock
Following #1356 and also #1326 I made this PR to have a simpler crypto implementation. The bundle size improvements are not updated yet AFAIK but I think this result is a good code change anyways
I think the results are easier to read in the code though and it doesn't use a fake key, just a random password 
Also updates the lambda to make the session id shorter and the full hash is not generally needed, just a small amount of randomness. This change is already live
Note that this change would make currently shared sessions obsolete so deploying to yet a new base URI. I do this by removing the beta prefix
=> Simpler crypto

products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/admin-server.ts, products/jbrowse-web/src/JBrowse.js, products/jbrowse-web/src/Loader.tsx, yarn.lock
This attempts to help with the issue #1297 
The admin-server prints out a message for how to run it in dev mode e.g. when yarn start is running on port 3000 and the admin server is running on port 9000
The URL format looks like
http://localhost:3000/?adminKey=ebcd0bd95f&adminServer=http%3A%2F%2Flocalhost%3A9090%2FupdateConfig&config=test_data%2Fvolvox%2Fconfig.json&session=local-WlWepLIjl
To work with volvox I run
cd test_data/volvox
../../products/jbrowse-cli/bin/run admin-server
http://localhost:3000?adminKey=320ffbf8eb&adminServer=http://localhost:9090/updateConfig
=> Add ability to use admin-server in dev mode

packages/core/assemblyManager/assembly.ts
This is a small change that checks if the Assembly Manager GUI is open before cascading errors loading an assembly up to the root model of the app and crashing it. This fixes issues with live editing values using the config editor for assemblies (#1375 ).
I'm going to open a separate PR with an improved form for adding assemblies, but think this should go in now, depending on how long creating the new form takes me.
=> Don't crash app when live editing assembly

products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-web/src/sessionModelFactory.ts
Currently the removeReferring uses hasWidget to check if anything is referring to a track. This searches all widgets including hidden ones from self.widgets in the session
This would fix #1342 
Alternative fixes might involve not keeping track of hidden widgets
=> Make hasWidget check hidden widgets

test_data/breakpoint/config.json, test_data/config.json, test_data/config_chrom_sizes_test.json, test_data/config_demo.json, test_data/config_dotplot.json, test_data/config_human_dotplot.json, test_data/config_longread.json, test_data/config_longread_linear.json, test_data/config_synteny_grape_peach.json, test_data/yeast_synteny/config.json
`savedSessions` no longer gets loaded from the config file after #1240. This removes references to it in demo configs, and moves a saved session to `defaultSession` where applicable.
=> Remove savedSessions from configs

packages/core/assemblyManager/assembly.ts
Currently on master searching chr5:1-100 does not work since chr5 is an alias
This fixes that.. This is a knock on from #1369 
Note that having an integration test for this would be great. Have tried to do this here recently but didn't get it completed https://github.com/GMOD/jbrowse-components/compare/search_test
=> Fix usage of aliases for isValidRefName

packages/core/assemblyManager/assembly.ts
Restores previous functionality to return a list of all refNames and aliases.
=> Fix allRefNames on assembly

plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/VcfImport.ts
If a VCF that is uploaded to the spreadsheet view has no FORMAT then it crashes
This avoids the crash by making a fake FORMAT column
=> Add blank FORMAT column for spreadsheet view VcfImporter if none exists

plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.js, plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts
This is a tiny PR for suggesting that the error be a volatile state for spreadsheet/sv inspector import wizards
Any error during import persists across refreshes. I can't think of a great reason why that would be a good thing to do
=> Volatile error for spreadsheet/import wizard

plugins/menus/src/HelpWidget/components/HelpWidget.tsx, plugins/menus/src/HelpWidget/components/__snapshots__/HelpWidget.test.js.snap
Screenshot
Adds the user guide
Makes the version display similar to the about dialog
Uses less prose when offering links, instead providing a short list
=> Resource list for helpwidget

products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/admin-server.test.ts, products/jbrowse-cli/src/commands/admin-server.ts, yarn.lock
Inspired by [serve](https://www.npmjs.com/package/serve), this tries to make the admin-server message a bit more readable.
**Before:**
**After:**
=> Update admin-server log message

packages/core/assemblyManager/assembly.ts, plugins/spreadsheet-view/src/SpreadsheetView/components/Spreadsheet.js, plugins/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetView.js, plugins/spreadsheet-view/src/SpreadsheetView/models/Spreadsheet.ts, plugins/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.ts
Alternative version of #1400 
This waits for assembly to be initialized before loading, and avoids some of the async complications of #1400
=> Make spreadsheet view wait for assembly to be loaded

plugins/variants/src/VcfTabixAdapter/VcfFeature.ts, test_data/config_demo.json
This fixes a crash that occured loading the NCBI clinvar vcf. The ALT is null
It is some question to me whether replacing '.' with null is the proper behavior, because we also in many places render the literal string null in our feature dialogs
However, this fixes the code as is
It adds the NCBI clinvar vcf as a track here
I also just for fun added some more cool tracks from UCSC (ClinGen)
=> Fix VCF crash with null ALT field

products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/create.test.ts, products/jbrowse-cli/src/commands/upgrade.test.ts
I didn't fully test this but it looks like their pagination system has numbering starting from 1 where we attempted to start from 0, resulting in the duplication. Also filter out @jbrowse/web tags only #1415
=> Pagination starts at page 1, and also filter out jbrowse/web tags

plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js
Fixes a bug introduced in #1398. This makes the connection track filtering logic the same as the regular track filtering.
Fixes #1424
=> Fix connection tracks not showing up in track selector

products/jbrowse-web/src/JBrowse.js, products/jbrowse-web/src/Loader.tsx
~[Issue 1417](https://github.com/GMOD/jbrowse-components/issues/1417)~
Issue: Window session object did not get set after going through the splash screen. Kept the JBrowseRootModel and JBrowseSession in prod for debugging purposes.
=> Window Session and rootModel do not get set after Splash Screen 

packages/core/util/tracks.ts, plugins/sequence/src/index.ts, plugins/sequence/src/referenceSeqTrackConfig.ts
I noticed that after the (awesome) changes to the display methods, there were some fields that seemed unnecessary for the ReferenceSequenceTrack config schema.
For example, this is the config editor after the changes:
Probably not useful graphically, or in the config in general. In pairing, @garrettjstevens and I created a smaller base config schema for the ReferenceSequenceTrack.
Now, the slots look like this:
Removing some of the unnecessary slots for a ReferenceSequenceTrack.
=> Create separate config schema for ReferenceSequenceTrack

plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.js
This expands what the add track widget is looking for in an absolute URL so things like `/my.bam` and `//mysite.com/my.bam` don't give warnings, since they are valid [absolute URLs](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#Absolute_URLs_vs_relative_URLs).
=> Make add track warning a bit more lenient

package.json, website/docs/quickstart_desktop.md, website/docs/quickstart_gui.md, website/docs/tex_parser.js, website/docs/user_guide.md
The website currently won't build. This fixes the build and adds the website build to the root `yarn build` command so that if it breaks again it will show up in CI (website used to be built in CI before https://github.com/GMOD/jbrowse-components/pull/1336).
Some fixes are because there seems to a bug in docusaurus that if a markdown image alt-text has double quotes (like this: `![alt text with "quotes"!](../static/img/logo.svg)`), the build breaks: https://github.com/facebook/docusaurus/issues/3751
Another fix updates `tex_parser.md` so that it only tries to extract a caption for an image if there is no alt-text, and only extracts the caption if it's on the next line (no blank lines after it).
=> Fix website build

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
[Issue 1419](https://github.com/GMOD/jbrowse-components/issues/1419)
Before
Now
Also working in Safari
=> Bug:  search box disappears from LGV header on smaller widths

products/jbrowse-cli/src/commands/add-assembly.ts, products/jbrowse-cli/src/commands/add-connection.ts, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-cli/src/commands/admin-server.ts, products/jbrowse-cli/src/commands/create.ts, products/jbrowse-cli/src/commands/set-default-session.ts
Fixes #1440 
This is kind of a weird one but
```
nvm install 10.9
yarn
cd products/jbrowse-cli
bin/run create t1
bin/run add-assembly volvox.fa --out t1
```
This fails with the lstat error described in #1440 
With this PR though it is fixed
Note that `yarn test products/jbrowse-cli` does not pass with node 10.9 still due to something weird about testUtil, full error
```
TypeError: Patterns must be a string or an array of strings
at assertPatternsInput (node_modules/globby/index.js:17:9)
at generateGlobTasks (node_modules/globby/index.js:42:2)
at Object.<anonymous>.module.exports (node_modules/globby/index.js:116:20)
at Object.<anonymous>.module.exports (node_modules/del/index.js:66:23)
at _callee2$ (products/jbrowse-cli/src/testUtil.ts:128:37)
at tryCatch …
```
=> Alternative fsPromises usage

products/jbrowse-cli/package.json, website/docs/quickstart_web.md
Unfortunately this isn't properly testable (noting issues in #1461)
But we can set a minimum node 10.4 in the jbrowse-cli engines, and then still run add-assembly subcommand
=> Min node 10.4

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.js
Avoids rendering null and undefined values in the feature details widget
Also restores the '.' notation in the genotype table for variantfeaturedetails, because there, the '.' sort of has a meaning e.g. "no call"
=> Fix rendering null

packages/core/assemblyManager/assembly.ts, packages/core/assemblyManager/assemblyManager.ts, packages/core/data_adapters/BaseAdapter.ts, plugins/alignments/src/CramAdapter/CramAdapter.ts, plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts, plugins/linear-comparative-view/src/MCScanAnchorsAdapter/MCScanAnchorsAdapter.ts, products/jbrowse-desktop/src/rootModel.ts, products/jbrowse-web/src/rootModel.ts
After #1438, the React Linear Genome View wasn't working. It turned out to be because the assembly manager was looking for the plugin manager on the root model, which doesn't exist in the React Linear Genome View. I thought about adding `pluginManager` to `AbstractRootModel`, but that caused typescript errors elsewhere. Instead, I decided to pass the plugin manager as an arg when creating the assembly manager model, which is similar to the way a session model is created.
This seems to work fine, but it led to `pluginManager` being correctly typed in `assembly.ts` (before this it was implicitly `any`), which required some typescript fixes. Basically what it amounted to was that `getSubAdapter` was marked as required in `AdapterConstructor`, but from what I understand, it should actually be …
=> Have assembly manager get plugin manager from factory function args

plugins/linear-genome-view/src/LinearGenomeView/index.ts
Fixes #1467 
Related to the #1438 because it made linear-genome-view become initialized only after the assembly manager says it's assemblies were loaded, but the "read assembly" never is added to the assembly manager proper (which i think is a valid thing...just a contextual assembly that bypasses assemblyManager)
=> Wait on assemblies that are being tracked by the assemblyManager only

plugins/data-management/src/ucsc-trackhub/ucscTrackHub.js
Added support for new track types added to trackhub spec recently seen here https://genome.ucsc.edu/goldenPath/help/trackDb/trackDbHub.html
types added
- bigGenePred: opens a bb track
- hic: opens a hic track
- bigNarrowPeak: opens an unsupported track
- halSnake: opens an unsupported track
also fixes another issue that came up in #1426, if it is an unlisted unsupported track, the default case will make an unsupportedTrackConf instead of throwing an error so it doesn't break loading the trackHub on any unsupported track
=> Add Support to new track types in TrackHub spec + fallback for unsupported types

package.json, yarn.lock
This is an alternative to #1279 
It uses github PRs as a proxy for fixes to the repo
I tried this before but probably didn't have something working quite right, as it worked in the latest test
I did the following
Added the "bug" label to the #1422 PR
Ran `yarn lerna-changelog`
This generated a changelog with that PR mentioned
This is less granular than the conventional commits changelog, but may be more in line with how we expect changelogs to be developed
=> Use lerna-changelog for changelog generation

plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx
Fixes #1486 
Kind of a tricky one, just make sure to follow the direction of the renderings when rendering the CIGAR substructure of a synteny feature
=> Flip cigar rendering direction for synteny view

plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.tsx
Fixes #1447 
Pretty minor warning but thought it'd be a reasonable fix. This defers unboxing the model.region
The warning appeared to come from even destructuring region from model at the start of doHydrate but this defers it a little
=> Avoid stale region reference in block hydrate

packages/core/util/tracks.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, test_data/volvox/config.json
This adds a fake synteny track on volvox, and fixes the ability to specify your own synteny track with PAFAdapter in add-track
=> Fix ability to add a PAF synteny track with add-track

plugins/spreadsheet-view/package.json, plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts, plugins/spreadsheet-view/src/SpreadsheetView/models/declare.d.ts, yarn.lock
This enables opening bgzipped files like vcf.gz in the spreadsheet view
Also makes fileSource volatile because otherwise it is sticky across refresh and confuses the system
=> Allow bgzip imports to the spreadsheet

products/jbrowse-cli/src/commands/add-assembly.test.ts
In #1471, it's noted that one of the CLI test files sometimes times out in CI. In `fancy-test` (which is what `oclif-test` is based on), there's a syntax for increasing the timeout for a test that looks like
```ts
const wait = (ms = 10) => new Promise(resolve => setTimeout(resolve, ms))
describe('timeout', () => {
fancy
.timeout(50)
.it('times out after 50ms', async () => {
await wait(100)
})
})
```
However, this appears to be dependent on the test running under Mocha and doesn't work when run with Jest. I tried duplicating the behavior with a Jest-specific action, but didn't have any luck, since Jest and Mocha seem to handle timeouts too differently. We can set a longer timeout for all the tests in a single file, though, using `jest.setTimeout()`. I think this works well enough, and may …
=> Increase test timeout using jest.setTimeout

lerna.json, scripts/blog_template.txt, scripts/changelog.js, scripts/release.sh, website/docs/quickstart_web.md
While trying to integrate changelog generation into the release process, I was having trouble making things clear to someone looking at the changelog. The biggest problem was that usually changelogs are grouped under a version number, but since all our packages are versioned independently, and the changelog is for the whole repository, that didn't work. Also, not every package is published during every release. Packages that have no changes are not published and don't have their versions bumped. I tried creating a table in the changelog of all the packages that were changed, what their new version is, if they are published to NPM or not, etc., but it got a bit complicated. It also seems like it would be difficult to decide individually for every package in each release whether the changes …
=> Updates to release workflow

products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/create.test.ts, products/jbrowse-cli/src/commands/upgrade.test.ts
This is a possible fix for the jbrowse CLI to move to the new tagging style
=> Fix CLI to allow jbrowse create to download newer monorepo tag format

plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
Small fix to make it so that the translation frames flip from top to bottom when horizontally flipped. A last minute change on the sequence branch (making it so that it packs the position towards y=0 when certain things are hidden) made this get missed
=> Fix horizontally flipped translation frames position

plugins/circular-view/src/CircularView/components/CircularView.js, plugins/dotplot-view/src/DotplotView/components/Controls.tsx, plugins/dotplot-view/src/DotplotView/model.ts, plugins/linear-comparative-view/src/LinearComparativeView/model.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/linear-genome-view/src/LinearGenomeView/index.ts, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, products/jbrowse-web/src/sessionModelFactory.ts
This code has been a tricky thing to maintain properly since it pokes deeply into the state of the drawerwidget, so I propose removing it. Alternatively we could refactor to extract this, but another area of the code (the "Select tracks" button) removed the toggle state already.
fixes #1411 
fixes #1499
=> Change track selector togglebutton to normal button

.github/workflows/jbrowse-web.yml, .github/workflows/website.yml, package.json, plugins/circular-view/package.json, products/jbrowse-cli/README.md, products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/create.ts, products/jbrowse-cli/src/commands/upgrade.ts, scripts/blog_template.txt, scripts/changelog.js, scripts/release.sh
These are some more changes to the release process after learning some things doing the last release. Using our new synchronized versioning scheme, lerna just does one tag for each version and not a tag for each package. Big changes:
- Build jbrowse-web for each version tag, even if internally the jbrowse-web package doesn't change
- Make workflow-generated GitHub release a draft so we can manually change the description (e.g. add changelog) before publishing
- Fix website build (was missing a texlive package)
- Publish `@jbrowse/plugin-circular-view` (see #1502)
=> Updates to release process

packages/core/ui/App.js
This closes #1500 by adding explicit CSS to make the scrollbar show up. Works for me, I'd be curious to hear from Linux users  (@garrettjstevens and @cmdcolin )
View:
Should work on all modern browsers.
=> Add explicit scrollbar

packages/core/ui/FileSelector.tsx, packages/core/util/io/ElectronLocalFile.ts, plugins/data-management/src/AssemblyManager/AssemblyAddForm.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.test.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.tsx, plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx, plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx, products/jbrowse-desktop/src/worker.ts
=> Fix desktop loading of local files

package.json, products/jbrowse-cli/package.json, yarn.lock
The new version of `@oclif/dev-cli` makes it so that we don't have to copy the yarn.lock into the package folder before building.
Ref: https://github.com/oclif/dev-cli/releases/tag/v1.25.1
=> Update oclif and remove now unnecessary file copy

plugins/bed/package.json, plugins/bed/src/BigBedAdapter/BigBedAdapter.ts, test_data/config_demo.json, yarn.lock
Just a small proposal to add functional tracks for protein-to-genome mappings
Source
http://genome.ucsc.edu/goldenPath/newsarch.html#120220
Directly linked to bigbeds on the ucsc server
Used script like this to load
```
while read p; do echo $p; jbrowse add-track $p --out test_data/config_demo.json --category Uniprot --assemblyNames hg38 --trackId `basename $p .bb`_hg38; done < test.txt
```
after creating a text.txt with multiple URLs
=> Add some uniprot tracks to demo data

plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts
This is a small change to make the spreadsheet loading flag volatile to avoid it accidentally persisting across refreshes
=> Move loading flag for spreadsheet import wizard to volatile to avoid it persisting across refresh

.github/labeler.yml, .github/workflows/pull_request_label.yml, .github/workflows/push.yml, README.md, package.json, products/jbrowse-cli/package.json, scripts/changelog.js, scripts/release.sh, yarn.lock
These are some adjustments to the release process determined after releasing v1.0.2. The biggest change is that the release script uses `semver` to get the new version number before `yarn lerna publish` is run. That way it can generate the blog post and changelog with the new version number and commit them before tagging and publishing the release.
Also includes a couple GitHub workflow updates:
- update the build job to install the website deps with a cache to help it be a bit faster
- add a new workflow that will add a "needs label triage" label to a PR if it doesn't have a changelog label
=> Release and workflow updates

plugins/spreadsheet-view/src/SpreadsheetView/components/Spreadsheet.js, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/Number.js, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/Text.js, plugins/spreadsheet-view/src/SpreadsheetView/models/FilterControls.ts
#1158 introduced derived columns for BED and VCF files. This caused issues with the filtering functionality in the spreadsheet. This PR adds minor fixes to add support for filtering the spreadsheet using these derived columns.
=> Add spreadsheet filter support for derived columns

packages/core/data_adapters/BaseAdapter.ts
Found with @elliothershberg on #1518 
The SV inspector makes a FromConfigAdapter of the features in the spreadsheet, but the BaseAdapter calculates a adapter ID using objectHash of the constructor's args (comment in diff explains purpose of that id)
We saw that the objectHash was consuming an endlessly large amount of memory (2gb, at which point it seemed to be struggling, which is good to know maybe....probably keeping whole app memory under 2gb is a good marker) basically with the large config.features input
This uses math.random just out of convenience but could use shortid, etc.
=> Avoid large object hash on SV inspector load

plugins/breakpoint-split-view/src/model.ts
The breakpoint split view when plotting the paired read connections across chromosomes uses the fact that the flag is NOT "read mapped in proper pair" https://broadinstitute.github.io/picard/explain-flags.html?flag=100
But it was using the old flag helpers which were removed. Instead we check bitwise ops on the flag
=> Fix breakpoint split view showing too many connections for paired end ends

plugins/circular-view/src/BaseChordDisplay/components/RpcRenderedSvgGroup.js, plugins/dotplot-view/src/ServerSideRenderedContent.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.tsx
There was possibly a memory leak from side scrolling blocks. I saw memory increasing pretty high from sidescrolling lgv
I looked and this code was not called for example
```
diff --git a/plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.t>
index efd6e3600..66dd4de57 100644
--- a/plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.tsx
+++ b/plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.tsx
@@ -75,6 +75,7 @@ function ServerSideRenderedContent(props: { model: BlockModel }) {
return () => {
if (domNode && isHydrated) {
+        console.log('here')
unmountComponentAtNode(domNode)
}
}
lines 1-12/12 (END)
```
We could adjust the use of the isHydrated variable but also it seems this fix …
=> Fix memory leak when side scrolling LGV blocks

plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx, plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx
This was a carry over from #1539 to try to improve the synteny import form
Screenshot here
Makes it clear that PAF is optional, that PAF is "pairwise mapping format", and details about how the assemblies you pick correspond to the columns in the paf
=> Add more info about adding a PAF file to the synteny import form

plugins/alignments/package.json, plugins/alignments/src/BamAdapter/BamAdapter.ts, plugins/alignments/src/CramAdapter/CramAdapter.ts, plugins/bed/package.json, plugins/bed/src/BedTabixAdapter/BedTabixAdapter.ts, plugins/gff3/package.json, plugins/gff3/src/Gff3TabixAdapter/Gff3TabixAdapter.ts, plugins/linear-genome-view/src/LinearGenomeView/components/AboutDialog.tsx, plugins/variants/package.json, plugins/variants/src/VcfTabixAdapter/VcfTabixAdapter.ts, products/jbrowse-web/src/tests/JBrowse.test.js, yarn.lock
This is a proposal that was started when trying to make gff3tabix track display nice "About this track" header information
The VcfTabixAdapter already has has a "About this track" based on the vcf header, and does mild parsing of the header to make it display using a "feature details" style box
This modifies it to not do parsing of the header, and instead print the raw header using a `<pre>` text box
This then applies across many header types including BAM,CRAM,BEDTabix,GFF3Tabix,VCFTabix
In some situations, this could be better, and in some it could be worse. If the tracks have many thousands of refseqs, then there would be many thousands of not-very-informative header lines. Those can be collapsed when we do the mild parsing approach, but not with this raw approach. Is there any …
=> Display file headers in pre tag in about dialogs and bump @gmod/bam and @gmod/tabix package versions

products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/tests/util.js
Fixes #1553 by removing the TextDecoder polyfill we were using
It has different behavior to what exists on the proper https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder
Hard exactly to tell why but the TextDecoder object we were receiving was not a proper instance of a TextDecoder
Possibly related to how this module allows multiple different ways of importing the module
https://github.com/anonyco/FastestSmallestTextEncoderDecoder
Note that caniuse says that all our browsers we target are ok without this https://caniuse.com/textencoder
=> Remove the TextDecoder/TextEncoder polyfill

products/jbrowse-web/src/tests/BasicLinearGenomeView.test.js
[Issue 1548 - Flaky Search Test](https://github.com/GMOD/jbrowse-components/issues/1548)
Trying to reduce the amount of steps in the test.
Found flakiness with: ` fireEvent.keyDown(component, { key: 'Enter', code: 'Enter' }) `.
=> Flaky Search RefNameAutocomplete Test

plugins/breakpoint-split-view/src/util.ts
Seen on master while flipping through SV inspector and launching breakpoint split views
=> Avoid errors from breakpoint split view related to getBoundingClientRect

products/jbrowse-cli/src/commands/add-track.test.ts, products/jbrowse-cli/src/commands/add-track.ts
Renames the current --type option to --trackType
In reference to
https://github.com/GMOD/jbrowse-components/discussions/1545
We could also consider adding an adapterType that overrides guessAdapterType, but that is currently difficult because every data adapter is kind of different (there is no standard based on supplying just urlTemplate...)
=> Rename jbrowse cli add-track --type to --trackType

plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
This removes soft/hard clipping from the snpcoverage
Currently it incorrectly draws softclip in the SNPCoverageRenderer using the color that was used to draw the SNP before it
Before, the clipping increases the count in a base which does not actually have an increased count, and colors it sort of randomly with red because it was what is in the ctx.fillStyle from another SNP
After, no softclipping into in the coverage, no coloring of it
This is a bit anti-thetical to goals like #815 but the way it is being done right now on master is sort of incorrect
=> Remove softclip and hardclip from snpcov

products/jbrowse-desktop/rescripts/webpackRescript.js, products/jbrowse-desktop/src/Loader.tsx, products/jbrowse-web/rescripts/webpackRescript.js, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/tests/Loader.test.tsx, test_data/bad_config_for_testing_error_catcher.json
This is an attempt to improve the loader error
Fixes #1515 
Note that this issue of the infinite CPU only happens due to react-error-overlay in dev but is now fixed by this and attempts to additionally improve the situation by providing a slightly more readable abbreviated error message than the default
Screenshot
This helps us understand potentially the track the failed to load, and the "path" e.g. it is the first track
=> Improve mobx-state-tree type validation errors

.github/workflows/push.yml, products/jbrowse-cli/README.md, products/jbrowse-cli/src/base.ts, products/jbrowse-cli/src/commands/create.ts, products/jbrowse-cli/src/commands/upgrade.ts
This re-instates the upload of a jbrowse-web build to the folder where it is being deployed (this existed in travis but was lost in the github move)
Then it also adds a --branch and a --nightly (alias for --branch master) flags to the `jbrowse create` and `jbrowse upgrade` commands
=> Create --branch and --nightly flags for `jbrowse create` and `jbrowse upgrade` commands

website/src/pages/demos.md
This PR adds the cancer genomics demo to the list of JB2 demos. (closes #1322 )
Also, after talking w/ @rbuels , did some clean up and restructuring of the demo page to make it easier to understand.
Before:
After:
=> Restructure demo page and release cancer demo

website/src/pages/features.md
Xref https://github.com/GMOD/jbrowse-components/discussions/1580
=> Add some features that are missing from jbrowse 2 to the feature comparison table

plugins/trackhub-registry/src/trackhub-registry/TrackHubRegistrySelect.js
Currently on master the trackhub registry names don't display properly
Not sure the regression but I removed the sanitize html element and it worked ok
If we need to actually render html in the labels we could restore the html sanitizer but otherwise works fine without it
On master:
After:
=> Fix the display of trackhub registry results

website/docs/quickstart_cli.md
Ref #1582
Adds a section about loading gff3tabix along with sorting a gff with genometools
Also adds a snippet about loading bigwig and sorting vcf for vcftabix which are carry-overs from #1566 (which is currently stalled)
=> Quickstart gff

packages/core/util/Base1DViewModel.test.ts, packages/core/util/Base1DViewModel.ts, packages/core/util/__snapshots__/calculateDynamicBlocks.test.ts.snap, packages/core/util/__snapshots__/calculateStaticBlocks.test.ts.snap, packages/core/util/blockTypes.ts, packages/core/util/calculateDynamicBlocks.ts, packages/core/util/calculateStaticBlocks.ts, packages/core/util/index.ts, plugins/dotplot-view/src/DotplotView/model.ts, plugins/linear-genome-view/src/BaseLinearDisplay/components/LinearBlocks.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/linear-genome-view/src/LinearGenomeView/hg38DisplayedRegions.json, plugins/linear-genome-view/src/LinearGenomeView/index.test.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
With this change
#1556 
#1532 
Also see refname label positioning issue (X not flush with boundary) in #1556
I also make the minimum block width smaller to make it so realistically human sized chromosomes such as 20-22 of human are displayed even when zoomed out
The refname label positioning  was fixed by updates to calculateStaticBlocks/calculateDynamicBlocks: only needs to add interregionpaddingwidth when it is a content block
This PR also adds ellided blocks to the overview bar so that we avoid rainbow-of-small-displayed regions, and changes it from paper with margins to exact width divs
Note that this is still not perfect: it is visible from the screenshot that the chr1 overview scale bar polygon does not match up perfectly with the end of the display and the chr1 displays some …
=> Updates to improve scalebar tooltips, overview scalebar plotting, and refName label positioning

products/jbrowse-web/src/ShareButton.tsx
Simple fix, disable button from being pressed while short link is being generated, closes #1586
=> disable 'copy to clipboard' while loading

plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/linear-genome-view/src/LinearGenomeView/index.test.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This is a break out from #1531 
This adds a new behavior where we can "Show all regions in assembly" and also changes a behavior so that maxBpPerPx is conditional on totalBp/(self.width*0.9) rather than totalBp/1000
That means on a wide monitor, the behavior for "Show all regions in assembly" would use more of those horizontal pixels than just choosing to squish everything down to 1000
=> Replace 'show all regions' with 'show all regions in assembly'

config/jest/console.js, packages/core/data_adapters/BaseAdapter.ts, packages/core/pluggableElementTypes/models/BaseDisplayModel.tsx, packages/core/pluggableElementTypes/models/BaseTrackModel.ts, packages/core/util/index.ts, packages/core/util/types/index.ts, plugins/alignments/package.json, plugins/alignments/src/LinearPileupDisplay/components/ColorByTag.tsx, plugins/alignments/src/LinearPileupDisplay/components/FilterByTag.tsx, plugins/alignments/src/LinearPileupDisplay/components/SortByTag.tsx, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts, plugins/alignments/src/index.ts, plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.ts, plugins/wiggle/package.json, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts, plugins/wiggle/src/LinearWiggleDisplay/components/SetMinMaxDialog.tsx, plugins/wiggle/src/LinearWiggleDisplay/components/WiggleDisplayComponent.tsx, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts, plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.ts, plugins/wiggle/src/index.ts, plugins/wiggle/src/util.test.js, plugins/wiggle/src/util.ts, products/jbrowse-web/src/rootModel.ts, yarn.lock
This enables a toggle option for the view to make "Show all regions" into "Show all regions in assembly"
Also allows the user to toggle filled histograms on and off, set log scale, and control bigwig coarseness
This helps enable the screenshot in the cancer demo e.g. puts this screenshot into any users grasp who can open a bigwig file
=> Add track menu options for autoscale, log scale, histogram fill, setting min/max score, and zoom level/resolution for wiggle/snpcoverage tracks

products/jbrowse-web/src/ShareButton.tsx, products/jbrowse-web/src/sessionSharing.ts, products/jbrowse-web/src/tests/Loader.test.tsx
I observed an error during sharing session, but the error message I got did not have details about the cause
This is a possible approach that parse the error message from the JSON form and if that fails, display it as is
Alternatively, we could simplify our return from our dynamodb API to not return json formatted errors, but this may be ok as is here
=> Display error message from dynamodb session sharing error

plugins/sequence/package.json, plugins/sequence/src/GCContentAdapter/GCContentAdapter.ts, plugins/sequence/src/GCContentAdapter/configSchema.ts, plugins/sequence/src/GCContentAdapter/index.ts, plugins/sequence/src/index.ts, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts, test_data/config_demo.json
This is a sketch for a GCContent adapter 
Ref #281
Imports some utility functions from @jbrowse/plugin-wiggle, uses the sequenceAdapter/subadapter concept similar to CramAdapter, and there is a track is in config_demo.json for hg19
=> GCContent adapter

plugins/alignments/src/PileupRenderer/configSchema.ts
This is a small proposal to increase pileup maxheight
As part of this, we could also consider
a) making a track menu item to increase maxheight
b) potentially increase maxheight across the board
c) remove the existance of maxheight entirely?
=> Increase pileup maxHeight

packages/core/pluggableElementTypes/renderers/ComparativeServerSideRendererType.ts, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.ts, packages/core/rpc/coreRpcMethods.ts, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/circular-view/src/BaseChordDisplay/models/renderReaction.js, plugins/dotplot-view/src/DotplotDisplay/index.ts, plugins/dotplot-view/src/DotplotRenderer/ComparativeRenderRpc.ts, plugins/linear-comparative-view/src/LinearComparativeDisplay/index.ts, plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
As I was developing the Apollo plugin, I found that sometimes the info I wanted was in `renderArgs` and sometimes it was in `renderArgs.renderProps`. I then noticed that in CoreRender, `renderProps` were getting passed twice, both in `renderArgs.renderProps` and then also spread into the `renderArgs`. After talking with @rbuels, we decided to keep the `renderProps` that were spread and get rid of `renderArgs.renderProps`. This PR does that, and then also unifies how `renderInWorker` and `renderInClient` are called so their arguments are the same.
=> Make renderArgs consistent and don't duplicate data

codecov.yml
Corresponds to this tip https://docs.codecov.io/docs/github-checks-beta#disabling-github-checks-patch-annotations-via-yaml
=> Remove codecov pr annotations

packages/core/data_adapters/BaseAdapter.ts, packages/core/util/stats.test.ts, packages/core/util/stats.ts, plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts, plugins/sequence/src/GCContentAdapter/GCContentAdapter.ts, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.test.ts, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts, plugins/wiggle/src/WiggleRPC/rpcMethods.ts, plugins/wiggle/src/index.ts
This makes it so that base feature adapter can perform basic local stats calculation, removing the need for adapters like SNPCoverageAdapter, GCContentAdapter, and BigWigAdapter to all implement this independently, and enabling anything that returns a feature score to have this (can also leveraged by FromConfigAdapter in nextstrain demo)
=> Move stats calculation to BaseFeatureAdapter

products/jbrowse-cli/README.md, products/jbrowse-cli/package.json
Fixes repository prefix in the CLI package, which didn't get updated when we switched to versioning all packages with the same version.
Fixes #1645
=> Fix "See code" link in CLI docs

packages/core/ReExports/list.ts, packages/core/ReExports/modules.ts
There was a change in how material-ui exports its icons between 4.9.1 and 4.11.2. This adds one more special case name to the re-exports that allows plugins to bundle material-ui/icons using the new versions. Also works with the most recent beta of material-ui 5 (5.0.0-alpha.24).
xref https://github.com/GMOD/jbrowse-plugin-msaview/issues/6
=> Support plugins using material-ui/icons >= 4.11.2

plugins/legacy-jbrowse/src/JBrowse1Connection/jb1ToJb2.ts
Since JBrowse 2 has GFF3Tabix and BEDTabix adapters now, this adds the ability to the JBrowse 1 connection to guess those adapters based on the JBrowse 1 storeClass.
=> Add GFF3Tabix and BEDTabix inference to JB1 connection

plugins/wiggle/src/WiggleRPC/rpcMethods.ts, test_data/config_demo.json
This fixes the use of the global autoscaling selection in #1664 
Static parameters can't be accessed on a instance of the object e.g. can't use  `instance.staticField`, but can use  `instance.constructor.staticField`
For some reason this issue has only existed after the merger of #1629 but the MDN as Garrett found out explains this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#using_static_members_in_classes
=> Fix global autoscale selection in linearwiggledisplay

products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/sessionWarningModal.tsx
Currently if a session is shared with a cross origin config, it produces a warning about that but then fails to load the requested session
The session loading needs the config to be loaded first, so it needs to wait for the config to be "untriaged" using the wording of the PR
This PR adds an autorun so when we get the config is untriaged, then processes the session
Only exists sense the merger of #1632
=> Fix session sharing when using cross origin config

packages/core/assemblyManager/assembly.ts, packages/core/assemblyManager/assemblyManager.ts, plugins/data-management/package.json, plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js, plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts, products/jbrowse-web/src/tests/JBrowse.test.js
Found this as part of other work, but am submitting it separately since it's a self-contained bug fix.
In the case where e.g. as assembly had a `name` of `"hg19"` and `aliases` of `["GRCh37"]`, if a track configuration used `"assemblyNames": ["GRCh37"]`, the track would not show up in the track selector, even though it was using a valid assembly alias.
Fixing that then revealed that the track would not display in the LinearGenomeView because the check comparing the track and displayedRegion assembly names was not being performed properly.
Fixes both bugs and adds a test to confirm the proper behavior.
=> Fix for track using assembly alias not displaying

plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/BedImport.ts
Fixes #1681 
Also adds a fix for any BED parsing of comment '#' prefixed lines
=> Fix parsing of BED and BEDPE files with comment header for spreadsheet view

products/jbrowse-web/src/tests/JBrowse.test.js
Seen on master
https://github.com/GMOD/jbrowse-components/runs/1873190103?check_suite_focus=true#step:5:37
Started in  #1682 but should just be due to flakiness or timeout
=> Add extra timeout to color change test

products/jbrowse-web/src/Loader.tsx
This is a technique that allows a plain JSON string to be put in the session URL
It would look like
http://localhost:3000/?config=test_data%2Fvolvox%2Fconfig.json&session=json-{%22id%22:%22cWzmaLb-c%22,%22name%22:%22Integration%20test%20example%202/3/2021,%207:18:00%20PM%22,%22margin%22:0,%22drawerWidth%22:384,%22views%22:[{%22id%22:%22integration_test%22,%22type%22:%22LinearGenomeView%22,%22offsetPx%22:2000,%22bpPerPx%22:0.05,%22displayedRegions%22:[{%22refName%22:%22ctgA%22,%22start%22:0,%22end%22:50001,%22reversed%22:false,%22assemblyName%22:%22volvox%22}],%22tracks%22:[{%22id%22:%22_XTGJ2EV9%22,%22type%22:%22AlignmentsTrack%22,%22configuration%22:%22volvox-long-reads-sv-bam%22,%22displays%22:[{%22id%22:%22CxRaqiTAM1%22,%22type%22:%22LinearAlignmentsDisplay%22,%22PileupDisplay%22:{%22id …
=> Allow plain json encoding of the session in the URL

website/docs/config_guide.md
Some updates to the config guide in our docs:
1. Update `WiggleTrack` -> `QuantitativeTrack` to update the name change since the addition of displayTypes
2. Add an "Advanced adapters" section which covers the `FromConfigAdapter` and `FromConfigSequenceAdapter`, and an example of how they might be useful. (Closes #1638 )
=> Config guide updates

plugins/alignments/src/PileupRenderer/PileupRenderer.ts, test_data/config_demo.json
Sort of tangential but related goals to elucidating insertions as #1687 
Adds similar insertion indicator seen in igv
Ref fig S2 https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-020-02107-y/MediaObjects/13059_2020_2107_MOESM1_ESM.docx from https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02107-y#Sec22
The insertion signal for the 6000bp insertion is dispersed by complicated mapping, but can be pieced together from the large numbers
I arbitrarily thresholded it so that len<10 it draws line indicator, and larger than than it makes the bold indicator which draws it as wide as needed to accommodate the number
=> Bold insertion indicator for large insertions on pileup track

plugins/dotplot-view/src/DotplotRenderer/DotplotRenderer.ts, plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx
This fixes rendering of read vs ref when the reads use = to represent matches instead of M in the cigar string (seen in 11kb pacbio sample data track)
=> Fix rendering cigar with = sign matches

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/Category.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap
In order to emphasize nestedness of categories, adding a strong border color helps them stand out. This is the first thing I think could help this, more spacing could help but we are very tightly constrained in the drawer so probably avoid it if possible
Before
After
=> Add solid border on hierarchical panels to emphasize nested

plugins/variants/package.json, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, products/jbrowse-desktop/package.json, products/jbrowse-web/package.json, yarn.lock
Currently on master, sorting the table for the genotype column is broken because the data passed to the genotype column is an array instead of a string
This stringifies columns before they are passed to the table
It also adds a "show sample filters" checkbox because sometimes all those filters are overwhelming, and thus allows you to hide them, and also gives a helper text to get all non-zero alleles for example
=> Improve sorting and filtering in variant detail widget

plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
https://github.com/GMOD/jbrowse-components/compare/better_console_warn?w=1
This is minor but there are some cases where if an issue arises a console.error with the exception is not printed, which makes it difficult to debug. This adds a console.error in setError
It also makes it unnecessary to do try/catch in the serverSideRenderedBlock->renderBlockData
See whitespace-ignored-diff here https://github.com/GMOD/jbrowse-components/compare/better_console_warn?w=1
Possibly some error messages could get duplicate printed by this but hopefully better than none, and more reliable than sprinkling errors everywhere
The alternative is sprinkling console.error closer to the source e.g. could do it in the catch handler of makeAbortableReaction but that is a little presumptive
=> Add console.error log in block setError

packages/core/util/offscreenCanvasPonyfill.js, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/PileupRenderer/PileupLayoutSession.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/alignments/src/PileupRenderer/util.ts
Draft PR for doing color-by-base-quality
This definitely creates a high density of information but it can be pretty cool
This has to layer the per base quality on top of a drawn rectangle here for it to still have the strand arrows
=> Add ability to color by per-base quality in alignment tracks

plugins/wiggle/src/LinePlotRenderer/LinePlotRenderer.js, plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.ts, test_data/config_demo.json
currently the default code "whiskers" which renders the min and max in the summary bins looks sort of weird when rendered on things with bicolorPivot
the code could possibly be made clearer but I think there is a need for this change, demoing the phyloP conservation track
before
histogram on
histogram off
after
histogram on
various histogram off resolutions
=> Improve zoomed-out display of quantitative displays tracks when bicolor pivot is active

plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/linear-genome-view/src/LinearGenomeView/index.ts
This is a proposal for a couple more navigation features in the lgv
* "Show all regions in assembly" button on importform
* "Return to import form" view menu item
* Add `showAllRegions` after importform navigation. This causes, for example, if LGV refName chr1 is selected, that the entire chr1 is put into view instead of a small window from chr1:1-1000 that we see currently
=> Add "Show all regions in assembly" to import form and make import form show entire region when refName selected

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx, packages/core/BaseFeatureWidget/index.test.js, packages/core/BaseFeatureWidget/index.ts, plugins/alignments/src/AlignmentsFeatureDetail/AlignmentsFeatureDetail.tsx, plugins/alignments/src/AlignmentsFeatureDetail/index.js, plugins/alignments/src/AlignmentsFeatureDetail/index.test.js, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/index.test.ts, plugins/alignments/src/index.ts, plugins/breakpoint-split-view/src/BreakpointSplitView.ts, plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.test.js, plugins/gff3/src/Gff3TabixAdapter/Gff3TabixAdapter.ts, plugins/linear-comparative-view/src/LinearSyntenyDisplay/index.test.ts, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/linear-genome-view/src/index.ts, plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.js, plugins/variants/src/LinearVariantDisplay/model.ts, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, plugins/variants/src/VariantFeatureWidget/index.js, plugins/variants/src/index.test.js, plugins/variants/src/index.ts
This creates "clickable locstrings" for supplementary alignments in the AlignmentFeatureDetails, and for breakends/translocations on VariantFeatureDetails
Example
=> Add clickable navigation links to supplementary alignments/paired ends locations and BND/TRA endpoints in detail widgets

packages/core/Plugin.ts, packages/core/PluginManager.ts, plugins/linear-genome-view/src/index.ts, products/jbrowse-web/src/jbrowseModel.js, products/jbrowse-web/src/tests/JBrowse.test.js, products/jbrowse-web/src/tests/TestPlugin.ts, test_data/config_demo.json
Proposal for [issue 1535](https://github.com/GMOD/jbrowse-components/issues/1535)
Adds method to PluginManager that retrieves plugin's configuration objects if they exist
Modifies the Jbrowse Model to add the plugin's configurations 
Adds optional configuration param to the base class for a JBrowse plugin 
Adds a test and a test plugin to verify we are able to read and get from the configuration
=> Add plugin top-level configuration

plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js
In UCSC plugin, the feature label was being set to a numeric field. I thought I could shore up what was happening there but I think it is better to stringify the labels at time of use since a user could user-select their own label field via configuration that could result in the same issue
=> Stringify labels before adding to rendering to avoid undefineds on label.length

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.ts
Fixes #1718
This adds a redundancy that avoids an all out crash, and then fixes the navigation so it clamps to the end of the newly navigating displayed region
This is just a general observation but our logic for navigating is fairly complex...I think it is likely that a refactoring probably along the time that name indexing comes around is likely in order
=> Fix for navigation past end of chromosome

packages/core/pluggableElementTypes/renderers/BoxRendererType.ts, plugins/alignments/src/LinearPileupDisplay/components/FilterByTag.tsx, plugins/alignments/src/LinearPileupDisplay/components/SetFeatureHeight.tsx, plugins/alignments/src/LinearPileupDisplay/components/SortByTag.tsx, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/alignments/src/PileupRenderer/configSchema.ts, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap
This allows both manually adjusting feature height and spacing between features via toggling pitchY to 1 using a track setting
Example
For #1693
=> Manually adjust feature height and spacing on alignments track

plugins/alignments/package.json, yarn.lock
In order to preserve old failure link and newer success link, closed #1737 and made new PR here
Comparison of old failure to new once built
http://s3.amazonaws.com/jbrowse.org/code/jb2/fix_cram_long_read/index.html?config=test_data%2Fconfig_demo.json&session=share-3v9jap5SxS&password=EnAYG
http://s3.amazonaws.com/jbrowse.org/code/jb2/fix_cram_long_read2/index.html?config=test_data%2Fconfig_demo.json&session=share-3v9jap5SxS&password=EnAYG
=> Fix some long read tracks failing to load blocks (bump @gmod/cram version)

plugins/alignments/src/CramAdapter/CramAdapter.ts, plugins/alignments/src/LinearAlignmentsDisplay/components/AlignmentsDisplay.tsx, plugins/alignments/src/LinearAlignmentsDisplay/models/model.ts
Currently changing the snpcov subtrack height is not remembered on refresh
This fixes that. There is an old useEffect thing that was hacky that was causing reset to height:45 along with a couple other things
The autorun that propagates state from alignments display model to the SNPCoverage display model is kind of awkward and could be evaluated, but this fixes the particular issue of setting the subtrack height in track state
=> Fix alignment track ability to remember the height of the SNPCoverage subtrack on refresh

products/jbrowse-cli/src/commands/add-track.test.ts, products/jbrowse-cli/src/commands/add-track.ts
This fixes the usage of --inPlace tag to put the exact config without using file.basename(filename) into the config
It also adds some "helpful comments" above each example usage to try to explain what happens in each use case
=> Fix CLI add-track --load inPlace to put exact contents into the config, add better CLI example docs

plugins/linear-genome-view/src/LinearGenomeView/index.test.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts
This tries to instrument some simple navToLocString tests for the LGV for easier testing of corner cases
There is likely more that can be done to ensure reliability but I hope these tests could be a starting point for simulating end-user behavior of using locstring inputs
Fixes #1740
=> Instrument navToLocString tests in the LGV and fix refname navigation

plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts, plugins/wiggle/src/LinePlotRenderer/LinePlotRenderer.js, plugins/wiggle/src/LinearWiggleDisplay/components/WiggleDisplayComponent.tsx, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts, plugins/wiggle/src/WiggleBaseRenderer.ts, plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.test.js, plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.ts, plugins/wiggle/src/configSchema.ts
Adds a setting to display crosshatches, editable via the track menu for wiggle tracks. Moves the "ticks" concept into the model so the renderer can use the ticks
=> Add ability to display crosshatches on the wiggle line/xyplot renderer

plugins/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx
Currently the embedded mode, most clearly, can have an example where the "Zoom to region" menu after a rubberband selection is shown in the wrong place
To properly place the menu using anchorPosition it should use left: event.clientX, top: event.clientY from the mouseup event (these are screen coordinates instead of offset to any particular element)
Found while looking at the storybook :)
=> Fix the position of the popup menu after rubberband select when there is a margin on the component e.g. in embedded

plugins/alignments/src/PileupRenderer/sortUtil.ts
Currently if someone tries to sort based on a string tag, it fails to sort
This tries to determine upfront whether a tag is of type string (looks at first element)
Then it sorts using localeCompare to sort the strings
=> Fix pileup sorting when using string tag

products/jbrowse-web/src/Loader.tsx
Simple approach to fix #1749...chop the error message length at 1000 chars which is pretty sizeable length but shouldn't overflow the screen
=> Add length limit on error message from session loading

packages/core/util/index.ts, plugins/circular-view/src/BaseChordDisplay/components/RpcRenderedSvgGroup.js, plugins/dotplot-view/src/ServerSideRenderedContent.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedContent.tsx
Added a really basic rIC ponyfill that performs setTimeout(cb,1) for @jbrowse/core/util, used it throughout the codebase where needed
The alternative I can think of is adding the requestidlecallback-polyfill to jbrowse-react-linear-genome-view specifically but probably just better to do this
https://github.com/GMOD/jbrowse-components/tree/ric_polyfill
For compatibility with Safari mostly
Fixes #1659
=> Add requestidlecallback ponyfill in @jbrowse/core/util

plugins/alignments/src/LinearAlignmentsDisplay/models/model.ts, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.test.js, plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts
This was sort of inspired by #1754 but does not fix it
I split the long list of track menu items for the combined snpcov+pileup alignments track into submenus, one for pileup, one for snpcoverage options
It also added a custom getter called "extraTrackMenuItems" instead of overriding composedTrackMenuItems in the SNPCoverageDisplay model because it was not possible to properly override composedTrackMenuItems and preserve the wiggle options
=> Split alignments track menu items into "Pileup" and "SNPCoverage" submenus

plugins/dotplot-view/src/index.ts
There might be a better way to make sure the derived Dotplot1DView sets these by default to 0, but currently any instantiation of Dotplot1DView should manually set these to 0
=> Make sure the dotplot view creates views with interRegionPaddingWidth: 0 and minimumBlockWidth: 0

plugins/wiggle/package.json, plugins/wiggle/src/LinearWiggleDisplay/components/SetColorDialog.tsx, plugins/wiggle/src/LinearWiggleDisplay/models/model.ts
This adds a simple color picker for the wiggle track
This is almost going too far in a way, and I believe is starting to call into question the duplication of config items into state
I believe the user experience of having to clone a track and use our config editor is not ideal, and I think the track state and track menu helps, but it is causing duplication of code.
However, I also see that the continued use of track state as a way to open up a new opportunity: it offers a conceptually nice way to get config layers:I can simply say something like
// using concept from @teresam856 for top level config
getConf(getSession(self).WigglePluginSettings, 'someSetting')
Then I can get a "global setting" to apply to all my wiggle tracks a la config layers. This would be otherwise difficult to setup …
=> Add color picker and choice of summary score style for wiggle track

plugins/linear-genome-view/src/index.ts, plugins/variants/src/LinearVariantDisplay/configSchema.ts, plugins/variants/src/LinearVariantDisplay/model.ts, plugins/variants/src/__snapshots__/index.test.js.snap, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
This proposes to make the LinearVariantDisplay derive from the LinearFeatureDisplay
This gives it the ability to hide feature labels via the track menu, and other similar things
The current version has the ability to choose PileupRenderer as its renderer but I think this is probably unneeded
=> Make the variant display derive from the feature display

plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.tsx, plugins/data-management/src/AddTrackWidget/index.test.jsx, plugins/data-management/src/AddTrackWidget/model.ts
The AddTrack MST refactor in #1414 introduced some bugs with local files from jbrowse-desktop
This fixes that issue and also creates some unit tests to help cover more cases
Issue did not affect any "releases" yet but a desktop user from Keiran Raine's collaboration found this issue on desktop
=> Fix "Add track" workflow with local files on desktop and make a bit more testing of this widget

plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ReturnToImportFormDialog.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.ts
Currently there is a "return to import form" helper on the linear genome view, however if it is used accidentally you can lose your current view
This adds a dialog prompt to check if you are sure
It creates a model state for tracking whether a dialog is open
=> Add warning dialog in LGV before returning to import form to prevent accidentally losing the current view

.github/workflows/website.yml
The disable_float setting for the docs pdf is helpful because otherwise figures can be placed very far away from the place that they are referenced
This adds this back to the github workflow
=> Restore disable float tex for pdf

yarn.lock
This bumps generic-filehandle to 2.1.0 which includes a refetch if it receives a presumed CORS error ("Failed to fetch" error message....)
=> Bump generic-filehandle for fixing CORS errors from Chrome cache pollution

CONTRIBUTING.md, scripts/release.sh, website/release_announcement_drafts/v1.0.4.md
This PR makes the release.sh script take release blogpost drafts from `website/release_announcement_drafts` so that we can write them collaboratively with PRs before the release, to make sure everybody is happy with them.
=> Collaborative release announcement editing 

yarn.lock
Used `yarn upgrade-interactive abortable-promise-cache` in the root of the repo
=> Bump abortable-promise-cache

packages/core/rpc/BaseRpcDriver.test.ts, packages/core/rpc/BaseRpcDriver.ts, packages/core/rpc/remoteAbortSignals.ts, packages/core/util/aborting.ts, plugins/hic/src/HicRenderer/HicRenderer.ts
This fixes a bug in the remoteAbort call where the signalId was not being passed at all (it was calling {...1} which is just {}, the signal wasn't given a name on the object)
Then it adds a couple points in the hic code where it checks the abort signal, using a timeout to yield to the webworker to process the abortsignal RPC calls
=> Add hic aborting and fix remoteAbort signal propagation

packages/core/util/Base1DViewModel.test.ts, packages/core/util/Base1DViewModel.ts, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
This is a quick fix for #1792 
There was some indication in https://github.com/GMOD/jbrowse-components/pull/1764
Instead of laboriously making everything worry about the defaults being geared for the LGV, I make it 0 and then lgv specific use cases can override
=> Fix dotplot rendering outside it's allowed bounds

CONTRIBUTING.md, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, test_data/volvox/config.json, website/docs/developer_guide.md
This does not address anything about making factory functions because we have seen that it is unnecessary
In order to try to most accurately direct people to the right place, it puts currently working external plugin links  at the top
Then it also
1) Removes completely the "ring the bell" track type example. Although fun, I could not get it to work, and it was non-functional as written
2) Moves a specific internal codebase example to our CONTRIBUTING guide
3) Fixes a color callback example in jexl, and adds it to volvox just so we can see results easily
=> Update developer guide to cover displays, and highlight working external plugins

plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
Currently the ClinVar CNV bigbed file classifies features as "mRNA" because it uses both thickStart and blockCount (just 1 block, but single exon genes also only have 1 block)
These are heuristics to classify the feature as an mRNA and convert to processed feature
There is nothing really that bad about this, but it tries to show the "CDS" sequence for this feature from #1758 
This adds another heuristic to also have strand not be 0 in order to convert a feature into a gene
It may not be perfect but it is hopefully keeps the current status quo
=> Add another heuristic for returning gene features from BigBed

.github/workflows/push.yml, products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx, website/src/pages/index.js
This is a silly PR but it proposes moving the storybook generated to jbrowse.org/storybook/lgv/master instead of jbrowse.org/storybook/master
This allows us to use the same directory for other components if needed
Also makes it so that storybook is a supplementary link on the homepage
=> Move jbrowse/react-linear-genome-view storybook to lgv subdirectory

plugins/alignments/src/index.ts, plugins/breakpoint-split-view/src/index.ts, plugins/config/src/ConfigurationEditorWidget/index.js, plugins/data-management/src/index.ts, plugins/linear-genome-view/src/index.ts, plugins/variants/src/index.ts
This is a nitpicky change but I thought I would propose to use sentence casing on drawer titles
Seeing a list of items in the new select box makes it more obvious when we are not consistent
Note that "Add a track" and "Add a connection" are currently sentence case so this is more consistent with those examples
=> Standardized sentence casing on drawer widget titles

packages/core/ui/Drawer.js, packages/core/ui/Menu.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/TrackEntry.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap
I sometimes get the sense that the drawer slide-in animations feels laggy
We can remove this animation, and to me, this produces the feeling of the app being faster and snappier. Note that we have a slide in but not a slide out currently so this basically just makes it more even also
Similar things can be done for the menu. Currently, it does a growing expansion that isn't necessarily that laggy but to me, it feels (and is) faster if the menu appears instantly
My operating system menus do not have any delay for example, so it feels more native
=> Remove some animation effects

CONTRIBUTING.md
As discussed in meeting, adds a note about how to preview the changelog if you want it to help write the release announcement.
=> Add note about previewing changelog to CONTRIBUTING.md

plugins/linear-genome-view/src/LinearGenomeView/index.ts
Reported by https://github.com/li153348734 in the gitter chat, this is a small fix where the tracks remained after using "Return to import form" and changing assemblies but the tracks weren't cleared out https://files.gitter.im/5c59cb65d73408ce4fb6f58e/BIz5/image.png
I checked other options in the linear-genome-view state that might also need to be "cleared" but didn't see any. Any further update that might need clearing can go into "clearView"
=> Clear tracks when using "Return to import form"

products/jbrowse-desktop/src/Loader.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/1832
No tag needed since this was intra-release
=> Fix infinite loop on desktop by using reference to pm instead of uninitialized state variable

packages/core/rpc/BaseRpcDriver.ts, packages/core/rpc/ElectronRpcDriver.ts, packages/core/util/calculateStaticBlocks.ts, packages/core/util/index.ts, packages/core/util/io/ElectronLocalFile.ts, packages/core/util/io/ElectronRemoteFile.ts
This is a tiny PR takes some of the logic out of #1125 that changes how `window` is used. This is to help with running JB2 in other contexts than the browser, where `window` might not be defined.
This is related to #1786 . I'm looking into how our React LGV works inside of a vanilla Next.js app, and have run into issues with `window` not being defined.
=> Change usage of window

plugins/breakpoint-split-view/src/model.ts, plugins/variants/package.json, plugins/variants/src/VariantFeatureWidget/BreakendOptionDialog.tsx, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx
This is a demo for launching a breakpoint split view from a variant feature details panel
Note that there could be a similar thing dialog needed for alignments
An add on to this exists for side-by-side breakpoint split view but that may need more work (see branch side_by_side_dialog)
=> Add dialog for launching breakpoint split view from variant feature details

products/jbrowse-react-linear-genome-view/.storybook/preview.js, products/jbrowse-react-linear-genome-view/README.md, products/jbrowse-react-linear-genome-view/stories/NextJsUsage.stories.mdx
This adds a Storybook docs page describing how webpack configuration and dynamic imports work for adding the React LGV component to Next.js apps.
This seems to be based on this aspect of Next.js builds: "The webpack function is executed twice, once for the server and once for the client." (source in Next.js docs: https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config). I think what is going on in #1786  is that there are Node environment variables that are still set when the client code is being compiled, leading to weird issues.
Since this is pretty specific to Next.js builds, and can be fixed using their own config, I think that this added documentation is probably enough to close #1786 .
=> Add storybook docs page for nextjs usage

products/jbrowse-web/src/Loader.tsx, test_data/config_wormbase.json
Example link when built
s3.amazonaws.com/jbrowse.org/code/jb2/add_wormbase_example/index.html?config=test_data/config_wormbase.json
Needs tracklist optimizations since it has many tracks, but it does at least partially load
=> Add wormbase example with connection to jbrowse 1 data directory 

packages/core/configuration/configurationSlot.test.ts, packages/core/util/jexl.ts, packages/core/util/jexlStrings.test.js, packages/core/util/jexlStrings.ts, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, plugins/filtering/src/LinearFilteringDisplay/model.js, plugins/linear-genome-view/src/LinearBasicDisplay/configSchema.ts, plugins/lollipop/src/LollipopRenderer/configSchema.ts, plugins/svg/src/SvgFeatureRenderer/configSchema.ts, products/jbrowse-react-linear-genome-view/public/nextstrain_covid.json, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, test_data/config.json, test_data/config_demo.json, test_data/config_honeybee.json, test_data/volvox/config.json, website/docs/config_guide.md, website/docs/developer_guide.md
This is a proposal to change our syntax for jexl callbacks
It is based on a belief that the use of transforms, with the bar | syntax, will appear more unfamiliar than simply making everything functions
I propose making a function "get(feature, attribute)" where I can type
get(feature, 'start')
This is similar to
feature.get('start')
And replaces the current feature|getData(attribute)
Some other helper functions are changed from transforms to functions also
I add a section for documenting jexl to the configuration guide also
=> Change jexl callback helpers for features to use more functions and less transforms

packages/core/ui/DrawerWidget.js
This restores the close button for the drawer widgets
The previous PR https://github.com/GMOD/jbrowse-components/pull/1778 removed it, but I think it should be restored. It is not intuitive to me that to close the "About jbrowse" drawer, I have to select it in the list of drawer widgets, and then "can it" with the trash can icon. I would prefer to hit the X button.
I also think the "trash can icon" is not really ideal, and would suggest removing that whole feature of having the can icon in the select box, but that is not part of this PR
=> Restore close button on drawer widget header

website/docs/introduction.md, website/src/pages/index.js
It is not really clear from the (docs) that this (docs) is a separate link, so I made it into a separate part of a sentence
Also linked to the storybook docs from the /jb2/docs/ landing page
screenshots
=> Make @jbrowse/react-linear-genome-view storybook docs more visible

plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
This fixes the filters on alignments track e.g. read name, which currently had jexl syntax errors which are displayed in 1.1.0 if filters attempt to be used
=> Fix alignments read filter jexl syntax

plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/alignments/src/PileupRenderer/configSchema.ts, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap
The "Color by" scheme for alignments currently has 'Fade mismatches by quality'
Instead of making this specifically a property of "Color by", I change this to a separate setting
Then I also make the fading less "strict" e.g. right now it is a scale on a 0-90 but I make it on 0-50 because at quality 40, you are 99.99% sure the base call is right (see https://learn.gencore.bio.nyu.edu/wp-content/uploads/2018/01/Screen-Shot-2018-01-07-at-1.36.09-PM-768x535.png) and so you really only need to worry at like 20 or less. Even though phred can go up to 90 it does not need to really be faded after 50 or so I think
=> Change "Fade mismatches by quality" setting to separate config param and make less strict

packages/core/rpc/coreRpcMethods.ts
This fixes a TypeScript error present in main currently. Looks like it was introduced because #1790 added a param to the Base RPC Method's `deserializeArguments`, but that didn't exist yet when #1853 was created.
=> Fix deserializeArguments in CoreGetMetadata

plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx, plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx, website/src/pages/demos.mdx
Currently, there are a couple of crashes in synteny workflows
1. Closing a linear synteny track produces an error on getContainingView of displayModel
2. Opening a dotplot or linear synteny view in the import form without a PAF file specified produces a crash
=> Fix some synteny workflow crashes

packages/core/util/layouts/GranularRectLayout.ts, plugins/linear-genome-view/src/BaseLinearDisplay/components/LinearBlocks.tsx, products/jbrowse-web/src/tests/Alignments.test.js
The code makes the assumption that findAllByTestId would return multiple canvases (2) automatically, but this adds a waitFor to ensure that this is true
Fixes #1876 
Also uses getTotalHeight, a method on the BaseLayout, instead of accessing a property called totalHeight which only exists on PrecomputedLayout, to fix an error 
```
[
'Warning: `NaN` is an invalid value for the `%s` css style property.%s',
'top',
'\n' +
'    in div (at LinearBlocks.tsx:57)\n' +
'    in div (at Block.tsx:49)\n' +
'    in wrappedComponent (at LinearBlocks.tsx:49)\n' +
'    in wrappedComponent (at LinearBlocks.tsx:107)\n' +
'    in div (at LinearBlocks.tsx:100)\n' +
'    in LinearBlocks (at BaseLinearDisplay.tsx:85)\n' +
'    in div (at BaseLinearDisplay.tsx:61)\n' +
'    in wrappedComponent (at …
```
=> Fix test error and warning by waiting for multiple canvases to be rendered

packages/core/util/index.ts
Currently opening a track on https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.1.0/index.html in midori browser and presumably, safari produces an error
```
TypeError: Object is not a function. (In 'Object(_.rIC)', 'Object' is an instance of Object)
```
This fixes the rIC ponyfill by making it actually check for the existence of window.requestIdleCallback before using it in the ponyfill
=> Fix rIC ponyfill for use on Safari

plugins/wiggle/src/index.ts
This adds the XYPlotRenderer and xyPlotRendererConfigSchema to the exports for the wiggle plugin. This was necessary in order to be able to import them when working on the quantseq external plugin.
=> Export XYPlotRenderer and configSchema

packages/core/BaseFeatureWidget/SequenceFeatureDetails.tsx
This adds a button that says "Copy" (as in copy to clipboard) button for the feature details sequence panel, and the sequence can then be pasted in word or google docs and retain the coloring, and be used for microsoft word based bioinformatics
The code had to be modified slightly to support this (span instead of div)
=> Add ability to copy the text produced by the feature details sequence panel to MS Word/Google Docs and preserve styling

packages/core/ui/DrawerWidget.js
This adds position="sticky" on the DrawerWidget AppBar to make it so you can scroll far down and the header is always visible
There may be other ways to achieve this but I think this is easy
This does not have support on ie11 but I believe this has already been omitted from our support
Currently it is position="static"
There is also position="fixed" but this makes it take up 100% of the screen widthy @li
Requested by @li153348734 if I understood correctly
=> Position sticky for drawer widget appbar

packages/core/ReExports/list.ts, packages/core/ReExports/modules.ts
@peterkxie is using the data-grid in the Apollo plugin, but it was proving hard to install in the plugin due to some conflicts with how we re-export Material UI for plugins. There are probably some improvements that could be made to make that easier, but as a first step, since the DataGrid is already in the peerDeps of core and is a useful component, I think we may as well re-export it so it's easy to use.
=> Add Material UI's DataGrid to re-exports

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/set-default-session.test.ts, products/jbrowse-cli/src/commands/set-default-session.ts, products/jbrowse-cli/test/data/sampleDefaultSession.json
This PR is a couple of small changes from when I was trying to figure out https://github.com/GMOD/jbrowse-components/discussions/1873.
* Fixes `jbrowse set-default-session --session session.json` so that it expects a session JSON file. It was previously expecting a config JSON file. Also added support for the session being in a top-level "session" attribute on the session JSON so that files created with `File -> Export session` can be used with `set-default-session`
* Adds a `--delete` option to `set-default-session` that removes the "defaultSession" from the config. Setting the default session to `null` or `{}` using `set-default-session --session file.json` caused errors, so this adds an easy way to clear the default session.
=> Add --delete to set-default-session, fix --session

scripts/release.sh, test_data/yeast_synteny/config.json, website/docs/faq.md, website/docs/introduction.md, website/docs/quickquickstart_web.md, website/docs/superquickstart_web.md, website/docusaurus.config.json, website/sidebars.json, website/src/pages/download.mdx
Proposes having a download page in the header bar for easy access to the latest release, for people that are too lazy to go through the blog post
Example screenshot
=> Add download page in website header and new super-quick-start guide

plugins/data-management/src/AssemblyManager/AssemblyTable.tsx
This is a tiny PR that revisits the styling and typography of the assembly manager screen. As I got started on the plugin store stuff, I felt like it looked a bit small and sad. Just adjusted spacing and typography a bit.
Before:
After:
=> Improve assembly manager styling and typography

plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.test.js, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, plugins/variants/src/VcfTabixAdapter/VcfFeature.ts
This renders the true ALT breakend strings. Using our "MatePosition/JoinDirection" json representation may not be familiar to people, while the breakend syntax can be learned to be read...it is also more succinct and faithful to the datafile
Also adds curlies to VcfFeature, makes some multiline things a single line a bit shorter using object destructuring, and changes the order of resolving data to prioritize this.data instead of this.variant in toJSON and get
=> Add true breakend ALT strings to the feature details panel

products/jbrowse-cli/src/commands/add-assembly.test.ts, products/jbrowse-cli/src/commands/add-assembly.ts
Fixes #1898
Also fixes issue trying to use --out on a symbolic link, use fstat instead of lstat
Currently on main using a symlink, if i am testing correctly, produces
```
mkdir ~/testing
ln -s testing
bin/run add-assembly --out testing volvox.fa --load copy
Error: ELOOP: too many symbolic links encountered, open 'testing'
Code: ELOOP
```
=> Make using --out for add-assembly create output directory if it does not exist

plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
Possible fix for #1897
The behavior of event.preventDefault made it so that when an autocomplete popup was open, it couldn't be closed by clicking in the track container
I couldn't necessarily find a reason why this line was needed...if there is one we might need a more advanced fix but this may help
=> Make clicking away from autocomplete popup on track container work

packages/core/util/Base1DViewModel.ts, plugins/linear-genome-view/src/LinearGenomeView/index.ts, products/jbrowse-web/src/tests/Alignments.test.js, test_data/yeast_synteny/config.json
Fixes #1895
Currently bpToPx overestimates the amount of times it needs to incorporate interRegionPaddingBlock to all the displayedRegions that are offscreen to the left of any particular view
It actually only needs to incorporate the interRegionPaddingBlock for any displayedRegion that is on the blocks, not ones that are off screen to the left.
A similar concept was incorporated in pxToBp (which was much needed when using show all regions in assembly) but needed to be applied to bpToPx here too.
=> Fix issue with synteny polygons displaying slightly offset

plugins/hic/package.json, plugins/hic/src/HicAdapter/HicAdapter.ts, plugins/hic/src/HicRenderer/HicRenderer.ts, plugins/hic/src/LinearHicDisplay/model.ts, products/jbrowse-web/src/tests/Alignments.test.js, yarn.lock
I had done this awhile ago but just wanted to rebase and put on master
Note that technically, and if interested we could do this, we could replace "coarser/finer" resolutions with a select box that chooses the true window size so it would instead be a dropdown with 5000,10000,25000,etc. that would probably be a custom RPC method that fetches that list of resolutions
Just an idea, though the coarser/finer seems to work pretty OK
=> Add coarser/finer resolution toggles to Hi-C tracks and bump version

products/jbrowse-web/src/Loader.tsx
This was found while testing React.StrictMode, which revealed that page refreshes did not keep the local session working.
StrictMode does a little "chaos testing" like double rendering components which can reveal weird things
In this case, I found sessionStorage from rootModel autorun outputs sessionStorage.setItem('current', JSON.stringify({session}))
The code here in loader was outputting sessionStorage.setItem('current', JSON.stringify(session)) instead
This fixes it so they both output {session}
It may be possible to not even update sessionStorage here and only rely on rootModel's autorun but I didn't look into this yet
=> Fix reloading of local sessions when using React.StrictMode

plugins/data-management/src/AssemblyManager/AssemblyManager.test.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.tsx, products/jbrowse-web/src/tests/BasicLinearGenomeView.test.js
This adds a X close icon to the top right of the assembly manager, and makes clicking outside the dialog close the dialog (as is the case with most of our dialogs, this behavior is made by having an onClose prop to the Dialog component)
Also renames the "Return" button to "Close"
=> Add close button to assembly manager dialog box

packages/core/util/types/index.ts, plugins/breakpoint-split-view/src/components/AlignmentConnections.tsx, plugins/breakpoint-split-view/src/components/Breakends.tsx, plugins/breakpoint-split-view/src/components/BreakpointSplitView.tsx, plugins/breakpoint-split-view/src/components/Translocations.tsx
Fixes #1902 
This makes sure to use canonical refname when searching.
There are possible alternatives to this PR
We could try to make all our adapters return features with a field called feature.get('originalRefName') that can be used for purposes like this (note that adapters do receive a parameter called region.originalRefName which is the canonical ref name for the assembly being views to their getFeatures function)
This could either
a) be the adapters responsibility to fill out this field or
b) be some sort of auto-added thing by some other aspect of our system (renderer/serialization/adapter/something else?)
Or we stick with this this type of solution, and wait until we find a good abstraction
=> Fix breakpoint split view visualizations for files that need ref renaming (e.g. chr1 vs 1)

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/ManageConnectionsDialog.tsx
Internally, it is still called ManageConnectionsDialog but usefully it only is used to delete connections. If needed I can change the internal name too.
=> Rename "Manage connections" to "Delete connections..."

plugins/data-management/package.json, plugins/linear-genome-view/package.json, yarn.lock
The react-vtree has a peerDependency on react-window
Currently there is a react-window dependency listed in linear-genome-view but that appears unused, so I just moved it over to the data-management plugin
=> Add react-window to the data-management plugin, remove from linear-genome-view

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
Noted by @nathanhaigh in gitter chat that for example a VCF with QUAL 0 was not displayed
=> Fix issue with some falsy values being hidden in feature details

package.json, packages/core/ui/FileSelector.tsx, packages/core/util/jexl.ts, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, plugins/data-management/src/AddTrackWidget/components/__snapshots__/AddTrackWidget.test.js.snap, plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.js, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/BedImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/LocString.js, products/jbrowse-web/src/tests/1.Spreadsheet.test.js, products/jbrowse-web/src/tests/Spreadsheet.test.js, yarn.lock
The syntax +item is not available in jexl so I converted to parseInt (with the radix param :))
Also, for example, the variable row.cells.ref.text was not actually existing, the previous code was
var [ref, start, end] = row.cells
ref.text
In jexl form, without destructuring, we use row.cells[0].text
Finally the navToLocString click on cell gave an error for "model width undefined" so I moved the view.initialized await above the view.setDisplayedRegions. There was some rearrangement of this code at some point so it works better to check for initialized before setting displayed regions
=> Fix import of BED and navToLocString from spreadsheet views

scripts/release.sh, website/docusaurus.config.json, website/src/pages/demos.mdx, website/src/pages/index.js
Xref previous lab talk where I noted that our S3 bucket doesn't have compression enabled...I went ahead and tried turning on a setting to turn on compression on cloudfront with these instructions
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-configuring
I tried a couple tests loading volvox cram files, etc and it seemed to work fine
This makes overall downloaded content 
Initial load of v1.1.0 is ~1MB total amount downloaded vs before which has 3.9MB downloaded, so the new bundle size is 25% of the size of the old bundle (or a 75% decrease)
Can see comparing
https://s3.amazonaws.com/jbrowse.org/code/jb2/v1.1.0/index.html
https://jbrowse.org/code/jb2/v1.1.0/index.html
So this PR updates demo links to use …
=> Update website to link to demos on cloudfront for better compression

plugins/linear-genome-view/src/LinearGenomeView/components/ExportSvgDialog.tsx
The Export SVG feature has to option to "rasterize layers" so that e.g. a very information dense wiggle or pileup visualization can just be an embedded PNG inside the SVG
This  doesn't work on Firefox and Safari where OffscreenCanvas based rasterizing doesn't exist, so we can try to avoid allowing that option to be used on these browsers
=> Disable rasterize layer option for browsers without offscreen canvas

packages/core/util/analytics.ts, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/jbrowseModel.js
closes #1927 
endpoints for analytics and sharing are now analytics.jbrowse.org and share.jbrowse.org
Used Route 53 to create the analytics and share subdomains of jbrowse.org
Both use alias redirects to Custom domain names in API Gateway under the same name
The custom domain names in API Gateway have API mappings to the existing endpoints that analytics and sharing sessions uses
=> Update Analytics and Share Endpoints For Clarity

products/jbrowse-react-linear-genome-view/package.json, products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx, yarn.lock
The storybook has an example of runtime-including a plugin but it is actually probably more common to use build-time plugins, so I added an example of that here
This adds a devDependency on jbrowse-plugin-ucsc to use as an example
=> Add example for using a build-time included plugin to storybook

products/jbrowse-desktop/public/electron.js
The PR for #336 resulted required a bugfix to fix loading of sessions, but currently now displays "Invalid Date" for session card timestamps
This fixes the loading of stats onto the sessions loaded in the electron IPC (and simplifies the logic a little bit)
=> Fix timestamp on session cards on desktop

website/src/pages/demos.mdx
This adds a demo for the 1000 genomes extended trio dataset reference paper (https://www.biorxiv.org/content/10.1101/2021.02.06.430068v1)
I had to do manual data munging to produce a tracklist from this data, and sometimes the NCBI servers where we fetch the data from are a little finicky and return status 200 for range requests, but it is mostly a good demo I think
=> Add demo for 1000 genomes extended trio dataset to website

packages/core/ui/AboutDialog.tsx, packages/core/ui/ViewContainer.tsx, packages/core/util/types/index.ts, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/ViewContainer.tsx, products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts, products/jbrowse-web/src/sessionModelFactory.ts, website/src/pages/plugin_store.js
The embedded component was not using the DialogComponent volatile option properly to do things like export svg and other features that use the results of session.setDialogComponent
This also makes the About track dialog use this setDialogComponent method instead of being a special case on the session model
For reference, this feature is pretty similar to widgets on the session, but is more explicitly a dialog box
=> Fix ability to use DialogComponent (used for svg export, pileup sort, etc) on embedded components

products/jbrowse-cli/src/commands/add-track.test.ts, products/jbrowse-cli/src/commands/add-track.ts, products/jbrowse-web/src/tests/Alignments.test.js, website/src/pages/plugin_store.js
Possible fix for #1958 
The main thing is that it needs to unlink the destination before trying to symlink it
It is somewhat of a coincidence that copy behavior is to overwrite by default. I changed it to actually use  COPYFILE_EXCL to avoid accidentally overwriting a destination file, and the user can go back and use --force to overwrite it, which matches the behavior of overwriting the symlink added in this PR
It uses a try catch because if the destination symlink doesn't exist it would otherwise throw
Adds some misc refactoring (could be split out) to  try to simplify or deduplicate some repetitive logic in the code and tests with the hope that simpler code==easier to see code paths
https://github.com/GMOD/jbrowse-components/compare/fix_symlink_add_track?expand=1#diff-7c20288c5391381db2 …
=> Fix ability to use add-track force on symlink tracks

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/ToggleConnectionsDialog.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js, products/jbrowse-desktop/package.json, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-web/package.json, products/jbrowse-web/src/sessionModelFactory.ts, yarn.lock
Three connections-related fixes:
* Add key to ToggleConnectionsDialog to fix React warning
* Show connections in ToggleConnectionsDialog and HierarchicalTrackSelector if the connection's "assemblyNames" config slot is an empty array. This preserves prior behavior described here: https://github.com/GMOD/jbrowse-components/pull/1660#issuecomment-816281981
* Open connections were not getting preserved on refresh. This PR fixes that by using `Array.isArray` instead of `isObject` to check if the `connectionInstances` should be discarded when loading a session.
=> Fix connection behavior

plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedBlockContent.tsx, products/jbrowse-web/src/tests/Hic.test.js
The hic tests were good and passing but have a little warning that is printed from, presumably, a setState after component teardown
```
● Console
console.error
Warning: An update to wrappedComponent inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at /home/cdiesh/src/jbrowse-components2/node_modules/mobx-react-lite/lib/observer.js:26:30
at div
at Repeater (/home/cdiesh/src/jbrowse-components2/plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedBlockContent.tsx:63:21)
at …
```
=> Fix warning on hic test

packages/core/BaseFeatureWidget/SequenceFeatureDetails.tsx
As title says, UTR prediction is not done if no exon subfeatures are available. Fixes #1983
=> Avoid error calculating UTR on features that have no exon subfeatures

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
The base feature details has heuristics and such to make sure sort of arbitrary "json type data" can get a reasonable display
If there is an array of json, it can display a datagrid or a list of elements but currently the list of elements dumps some raw json to the screen
This makes it so array values switch back to using the "attributes" if an object is encountered instead of dumping the stringified json to the screen
Note: screenshot is of the CIVIC cancer variants API
=> Better feature details when there are short arrays of json supplied as feature data

website/src/pages/demos.mdx
The cancer demo that takes people through the SV features gives grant reviewers a good overview of things without them having to do the work to click around, which I think is important right now.
=> reorganize the demo page to emphasize the cancer sv demo more

plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx, products/jbrowse-web/src/ConfigWarningDialog.tsx, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/SessionWarningDialog.tsx, products/jbrowse-web/src/tests/Loader.test.tsx
We currently have this behavior in jbrowse-web loader
a) trust plugins in a users config file if loading same-origin config
b) prompt against loading cross-origin configs
c) load plugins from sessions (without any checking)
I propose changing it so
a) same behavior, trust plugins in users config file if loading same-origin config
b) trust cross-origin configs if they have plugins that match our plugins.json file (e.g. matches urls from there), only prompt if not
c) trust session plugins if they have plugins that match our plugins.json file (e.g. matches urls from there), only prompt if not
The motivation here is that (c) is sort of a currently existing security hole, and that (b) is not really a security hole after checking whitelisted plugins and change to jexl, so does not need a prompt
=> Avoid warning dialog if plugin is in our plugins.json and popup confirmation dialog for unknown session plugins

plugins/alignments/package.json, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, plugins/linear-comparative-view/src/BreakpointSplitRenderer/components/BreakpointSplitRendering.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, yarn.lock
Currently, when you side scroll a block, the code makes a new request for a BAI file for example for BAM
Affects v1.1.0 and v1.2.0 and current main
Last working v1.0.4
This upgrades abortable-promise-cache which has a fix for this
It would be ideal if yarn automatically figured this one out, because this upgrade was allowed by semver to get an upgraded abortable-promise-cache
I ran `npx yarn-deduplicate` to achieve this result
I could have also released a new version of @gmod/cram and @gmod/bam specifying a minimum abortable-promise-cache of v1.4.0
This is especially bad for large index files that don't go in the browser cache, so are redownloaded in full
=> Fix issue with BAM index getting redownloaded after block scroll

packages/core/Plugin.ts, packages/core/PluginLoader.ts, packages/core/PluginManager.ts, packages/core/rpc/RpcManager.ts, packages/core/util/types/index.ts, plugins/data-management/src/PluginStoreWidget/components/InstalledPluginsList.tsx, plugins/menus/src/AboutWidget/components/AboutWidget.test.js, plugins/menus/src/AboutWidget/components/AboutWidget.tsx, plugins/menus/src/AboutWidget/components/__snapshots__/AboutWidget.test.js.snap, products/jbrowse-desktop/src/Loader.tsx, products/jbrowse-desktop/src/rootModel.ts, products/jbrowse-desktop/src/worker.ts, products/jbrowse-react-linear-genome-view/src/createModel/createModel.ts, products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/rootModel.ts, products/jbrowse-web/src/rpc.worker.ts
Currently there is a bug where the session plugins are not properly installed in the webworker
This is a little tricky to fix because we need to have a handle on the plugin definitions themselves, and the place where RpcManager is initialized in rootModel doesn't have session.sessionPlugins yet (the model is still initializing so session is undefined)
This takes the approach to store all plugin definitions as plugin metadata, and then adds a getter called PluginManager.pluginDefinitions and this can be used for the workerBootConfiguration
=> Make session plugins get transferred to the worker properly

plugins/alignments/src/BamAdapter/MismatchParser.ts, plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx, plugins/alignments/src/LinearPileupDisplay/components/ColorByModifications.tsx, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/alignments/src/shared.ts
This is a sort of tricky one where the SNPCoverage track, when colorBy modifications is turned on, draws with an uninitialized tag->color mapping
This could be a correctness issue as it could affect first-time rendering
Currently the Alignments track synchronizes the tag -> color mapping from the pileup to the snpcoverage display
One alternative would be to treat the snpcoverage track and pileup track is functionally independent, so they both do their own work to get the color mapping independently
This actually is extra work done, and could result in slowdown, as the getUniqueModifications RPC call is an extra pass through the data. We can count the number of passes through the data like this
So to draw a track, we get something like this
SNPCov - stats estimation
SNPCov - modification …
=> Make SNPCoverage independently generate the modifications tag-color mapping

packages/core/ui/FileSelector.tsx, plugins/data-management/src/AddTrackWidget/components/__snapshots__/AddTrackWidget.test.js.snap, products/jbrowse-web/src/tests/1.Spreadsheet.test.js, products/jbrowse-web/src/tests/2.SVInspector.test.js
This changes the default of the FileSelector component so that if it's not provided a location, it defaults to prompting for a URL instead of a local file. I think this is the more common use case, especially for JBrowse Web, and so would hopefully save users clicks (and possibly avoid some confusion).
=> Proposal: Make FileSelector default to URL instead of File

website/release_announcement_drafts/v1.3.0.md
Here is the changelog so far:
- Other
- [#2001](https://github.com/GMOD/jbrowse-components/pull/2001) Make tracks added using the add track widget a session track if not in adminMode ([@cmdcolin](https://github.com/cmdcolin))
- [#1980](https://github.com/GMOD/jbrowse-components/pull/1980) Add popup confirmation dialog for unknown session plugins, and use plugins.json as a whitelist ([@cmdcolin](https://github.com/cmdcolin))
- [#1977](https://github.com/GMOD/jbrowse-components/pull/1977) Upgrade @material-ui/data-grid ([@cmdcolin](https://github.com/cmdcolin))
- `core`
- [#1982](https://github.com/GMOD/jbrowse-components/pull/1982) Allow manually specifying adapter type if filename does not match expected pattern ([@cmdcolin](https://github.com/cmdcolin))
- …
=> Create v1.3.0.md, draft of release announcements

.github/workflows/jbrowse-web.yml, scripts/release.sh
A couple updates to help make future releases smoother.
- Use node 12 on the CI job that builds JBrowse Web, since our dependencies don't support node 10 anymore
- Make sure the user doesn't have any local file changes when running the release script
=> Post-v1.3.0 release updates

plugins/linear-genome-view/src/LinearGenomeView/index.tsx
The showTrack has a "initial snapshot" method that it can use to instantiate track specific state, but it is also useful to be able to initialize display specific state too (in the GDC plugin, we can use this to provide initial min and max scores for wiggle display for dynamically added tracks for example)
=> Pass initialDisplay snapshot via separate param to showTrack

products/jbrowse-react-linear-genome-view/package.json
Small contribution to try to fix warnings about peer dependencies from npm installing our @jbrowse/react-linear-genome-view
Uses greater than react 16.8.0  instead of just the 16 version range
=> Update peerDependencies for react-linear-genome-view to help npm install peer deps warnings

products/jbrowse-react-linear-genome-view/README.md, products/jbrowse-react-linear-genome-view/docs/example.md, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/JBrowseLinearGenomeView.tsx, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/createModel/createConfigModel.ts, products/jbrowse-react-linear-genome-view/src/createModel/createModel.ts, products/jbrowse-react-linear-genome-view/src/deprecations.tsx, products/jbrowse-react-linear-genome-view/src/index.ts, products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx, products/jbrowse-react-linear-genome-view/stories/NextJsUsage.stories.mdx, products/jbrowse-react-linear-genome-view/stories/NextstrainGenomeView.stories.tsx
I realized that #2014 would probably be a problem when thinking about #1996. This is because the theme has to be in the configuration so that it can be passed through in the RPC render, but the React LGV didn't have a slot for the theme in the configuration. The first commit in this PR adds that slot.
The problem then, though, is that users would have to put the theme both in the ThemeProvider and in the configuration for it to work. This PR proposes moving the ThemeProvider inside the ReactLGV, so that users no longer have to worry about it in their code. Theming will still be available, but via the configuration instead.
As an example:
Before
```js
const theme = {
palette: {
primary: { main: '#311b92' },
bases: { A: { main: '#98FB98' } },
},
}
function View() {
const state = …
```
=> Move ThemeProvider inside React JBrowseLinearGenomeView

plugins/menus/src/ImportSessionWidget/components/ImportSessionWidget.js
Fixes #2017 after updates to blob map
The reason for this was basically related to having raw usage of openLocation and passing in a blob, instead of using fileselector which automatically performs this
We could, potentially, make our file selector's use a dropzone to make things more consistent but this does fix the issue
=> Fix session import to use blob map for opening local files

products/jbrowse-desktop/src/JBrowse.js, products/jbrowse-desktop/src/rootModel.ts, products/jbrowse-web/src/rootModel.ts
Currently adding some plugins using the plugin store on desktop can run into an error of infinite looping. The CIVIC plugin is an example of this
I don't actually know what the reason was but I tried a couple small rearrangements to try to fix it, which appeared to work
a) making the pluginsUpdated a volatile
b) separate the code that does the window reload out into it's own little useeffect instead of getting debounced
=> Fix infinite loop in adding some plugins on desktop

packages/core/ui/App.js, products/jbrowse-web/src/jbrowseModel.js, test_data/test_custom_logo.svg, website/docs/config_guide.md
This is a small PR that adds a config slot to jbrowse-web for providing a custom logo. This should help with model organism communities who want to customize their app.
A quick way to test is to toss this config in `config.json`
```json
"configuration": {
"logoPath": {
"uri": "/test_data/jb-logo.svg"
}
}
```
=> Configurable app logo for web

packages/core/util/simpleFeature.ts, plugins/config/src/FromConfigAdapter/FromConfigAdapter.test.ts, test_data/volvox/fromconfig_integration_test.json
This PR started with trying out copying the data by default here https://github.com/GMOD/jbrowse-components/commit/b5810295e6633fae357509ee6184113e23ca67df
I realized this data copying could be reduced if we store the subfeatures array outside of this.data, thereby not mutating it
We could also consider methods to avoid the idMaker crash, or other possible approaches, but this solution seemed nice because it did not necessarily require a full object clone of the inputted simplefeature args (which i tried first here  https://github.com/GMOD/jbrowse-components/commit/b5810295e6633fae357509ee6184113e23ca67df before using this alternative solution https://github.com/GMOD/jbrowse-components/commit/3ac1218c353c0134ab5d0c604789b9b9619dcfd2)
=> Fix infinite recursion in FromConfigAdaptor by avoiding mutating the passed in data when using SimpleFeature

packages/core/ui/FileSelector.tsx, packages/core/util/io/index.ts, packages/core/util/types/mst.ts
this PR addresses two issues:
1. A CORS rejection when attempting to load the app while also running a plugin
2. The requirement for custom headers to be sent as part of openURL (not just Authorization)
A ternary check for optional headers is performed before attempting to openUrl(), if authHeader and authToken are not defined, then this field will be undefined and avoid the CORS error being thrown when running the app with plugins.
A new field is added to the `UriLocation` model, `authHeader` which needs to be the header required to execute the authorization, this is a string.
For example, if you are creating the 'location' of a request to be made, your object might now look like
```js
{
uri: metadata.downloadUrl,
authHeader: 'Authorization',
authToken: `Bearer …
```
=> [auth-for-plugin-adjustments] slight adjustments to openLocation changes for plugins

packages/core/ui/App.js, packages/core/ui/NewSessionCards.tsx, products/jbrowse-desktop/src/JBrowse.test.tsx, products/jbrowse-desktop/src/StartScreen.tsx, products/jbrowse-desktop/src/jbrowseModel.js, products/jbrowse-web/src/StartScreen.tsx, products/jbrowse-web/src/tests/StartScreen.test.js
Currently starting up jbrowse desktop crashes because it tries to access a nonexistant logoPath configslot on the desktop's jbrowseModel
This fixes that by adding the logoPath configslot to desktop, plus a couple of items that jbrowse-web has that desktop didn't have  (theme, featureDetails,and ...pluginConfigurationSchemas()) just for good measure
Also makes the Logo a component
=> Add logoPath on jbrowse-desktop to fix crash

products/jbrowse-cli/src/commands/add-track.ts
If --force was used but no track/file existed there to overwrite, then the script failed
This checks for the file existing
This code is a little tedious and it would be sorta nice if we could "operate at a slightly higher level of abstraction" than the raw fs module, but this does fix the issue :)
=> Fix issue with using --force error when no track was previously loaded

package.json, yarn.lock
"yarn is wanting to build node-sass since it can't find a prebuilt arch (which is bizarre in itself! - but possibly because node-sass is now deprecated under npm and no-one has maintained the build"
Mentioned in chat for jbrowse 2 https://gitter.im/GMOD/jbrowse2?at=60d0974fbcb3e8060ed7b70e
There is a particular version compatibility chart that is a little hard to follow, I think if we are not using sass though we can remove https://www.npmjs.com/package/node-sass
Note: This issue is also seen in some jbrowse 1 installs possibly too
=> Remove node-sass to avoid some issues installing dev setup with newer node versions

packages/core/assemblyManager/assembly.ts, plugins/circular-view/src/CircularView/components/CircularView.js, plugins/dotplot-view/src/DotplotView/model.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/SearchResultsDialog.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.test.ts, plugins/linear-genome-view/src/LinearGenomeView/index.tsx, plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.js
This is a possible proposal to help speed up large assemblies
This demo has 200,000 contigs
https://s3.amazonaws.com/jbrowse.org/code/jb2/main/index.html?config=test_data%2Fconfig_many_contigs.json
This can hang the page for as much as 10 seconds on a fast machine, production build
After this change the load time is about 3 seconds, with the code that does this coming from refNameAliases instead of assembly.regions now, so probably can be reduced more
This is an early proof of concept PR but note that types.frozens can also be typescripted 
Possible help for #1847
=> Improve performance with large numbers of reference sequences by using MST volatiles

packages/core/package.json, packages/core/util/index.ts, packages/core/util/offscreenCanvasPonyfill.js, yarn.lock
Two small changes here to help plugins. First, the `__webpack_require__` check was removed from offscreenCanvasPonyfill. Instead, it just checks for `OffscreenCanvas` without checking `__webpack_require__` first. To detect node, it uses [`detect-node`](https://www.npmjs.com/package/detect-node), a popular NPM library.
The second change was to export the offscreenCanvasPonyfill functions from `@jbrowse/core/util`. That way plugins can use them without them being built into the plugin (since offscreenCanvasPonyfill itself isn't in our re-exports). This change fixes https://github.com/GMOD/jbrowse-plugin-template/issues/15.
=> Export offscreenCanvasPonyfil from core/util

packages/core/util/io/index.ts
As noted in [this gitter thread](https://gitter.im/GMOD/jbrowse2?at=60d26b3bbef0c66d9d1b9e71), leaving an empty string in the "uri" of a "faiLocation" of an assembly adapter wouldn't trigger a 404 like it would if you put in the URI incorrectly, and you'd get some error about an invalid refName. This is because `fetch('')` is a valid fetch that gets the current page. This adds some error throwing to `openLocation` if the uri (or localPath) is an empty string, so the error message would be at least a bit more sensible.
=> Better error message if a file location has an empty string

plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.js, plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts
This fixes the ability to open local files in spreadsheet/sv inspector. This was a regression following the change of our FileSelector to return the objects with blobId instead of blob from #1975
=> Fix support for opening local files in spreadsheet/SV inspector

packages/core/TextSearch/TextSearchManager.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, products/jbrowse-react-linear-genome-view/package.json, products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx
In this pr
[Issue 2058 : Missing supercontig in the chromosome selector](https://github.com/GMOD/jbrowse-components/issues/2058)
* Removes jbrowse-legacy plugin dependency
* Removes storybook text searching example for now
* Adds message at the end of the dropdown to guide user to search when there are more than 100 refName options
* sets dropdown limit to 100 options
=> Dropdown warnings 2058

plugins/dotplot-view/src/index.ts, plugins/linear-comparative-view/src/index.tsx
The fix from #2024 caused a knock-on effect of the read-vs-ref displays to display inversions where none existed. Reason being was that the read vs ref code assumed it should provide the strand of the read, but even though the strand of a given BAM read might be given as -1, all the data is actually oriented in the forward direction (e.g. the SEQ field will be read left to right aka 5' to 3' even for negative strand features)
Example: Current main displays inversions on a "volvox SV" example which should not be inversions (it is just a deletion)
=> Reorient strands on read vs ref plots

products/jbrowse-web/src/rootModel.ts
This may have been vestigial or unneeded logic to do "setPluginsUpdated" anytime setSession was called.
Removing it, I can still see plugin install and remove work in the in-app plugin store
=> Fix issue with page reload after editing session title

packages/core/configuration/configurationSchema.ts, plugins/alignments/src/__snapshots__/index.test.ts.snap, plugins/bed/src/__snapshots__/index.test.js.snap, plugins/config/src/FromConfigAdapter/configSchema.ts, plugins/config/src/__snapshots__/index.test.js.snap, plugins/config/src/index.test.js, plugins/dotplot-view/src/DotplotDisplay/index.ts, plugins/filtering/src/__snapshots__/index.test.js.snap, plugins/legacy-jbrowse/src/__snapshots__/index.test.js.snap, plugins/linear-comparative-view/src/LinearComparativeDisplay/index.ts, plugins/rdf/src/__snapshots__/index.test.js.snap, plugins/sequence/src/__snapshots__/index.test.js.snap, plugins/variants/src/__snapshots__/index.test.js.snap, plugins/wiggle/src/__snapshots__/index.test.js.snap, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, products/jbrowse-web/src/__snapshots__/rootModel.test.js.snap, products/jbrowse-web/src/rootModel.test.js, test_data/config_synteny_grape_peach.json, test_data/volvox/config.json
During pairing @teresam856 and I were thinking about the "textSearchAdapter" in her branch. It's an "optional" config sub-schema, but the default value of the sub-schema was still showing up in config snapshots, which we thought might be confusing. This is an option we came up with that will omit the snapshot of a configuration schema if the snapshot matches the snapshot for the default value of that schema. We though this might be good as a separate PR.
This can be a bit odd if the whole config matches the default, since it makes the whole config snapshot be `undefined` instead of `{}`. We also had to change a couple places that used `getConf(self, 'renderer').type` to `getConf(self, ['renderer', 'type'])`.
It does have the advantage of removing unused things from our config snapshot, …
=> Omit configurationSchema snapshot when it matches the default

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx, packages/core/BaseFeatureWidget/__snapshots__/index.test.js.snap, plugins/alignments/src/AlignmentsFeatureDetail/AlignmentsFeatureDetail.tsx, plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap, plugins/dotplot-view/src/ServerSideRenderedBlockContent.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedBlockContent.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ReturnToImportFormDialog.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.js.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
In jbrowse/react-linear-genome-view, if there are bare "divs with text", then the font used might be something like "Times new roman" instead of a nice font
This tries to use typographies more thoroughly to make the font's a bit better
=> More usage of typography

products/jbrowse-react-linear-genome-view/src/corePlugins.ts
Removes one reference to the legacy JBrowse plugin from `@jbrowse/react-linear-genome-view`, which is causing the following error:
```
ERROR in ./node_modules/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.cjs.production.min.js
Module not found: Error: Can't resolve '@jbrowse/plugin-legacy-jbrowse' in './node_modules/@jbrowse/react-linear-genome-view/dist'
```
=> Fix "Can't resolve '@jbrowse/plugin-legacy-jbrowse'" in `@jbrowse/react-linear-genome-view`

plugins/circular-view/src/CircularView/models/CircularView.ts, plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.js, website/src/pages/demos.mdx
Fixes #2108 
Historical note:
There has been a tension in the history of the development regarding whether assemblies should be "waited on using promises" or "respond to observability" and this is a move towards "waited on using promises". This can interact with the mobx observability in weird ways e.g. anything after an await likely would not be picked up by the mobx autorun-observer-stuff but that should be ok here
=> Make sure to wait for assembly to load before downloading canonical refnames in SV inspector

package.json, products/jbrowse-cli/README.md, products/jbrowse-cli/package.json, yarn.lock
It looks like sometimes during the release process, the README for the CLI gets auto-generated, but the pre-commit hook doesn't make sure it gets properly formatted. This adds formatting to the step where the CLI gets auto-generated, so it'll get formatted even if the pre-commit hook doesn't work. It also makes the CLI's package.json more cross-platform by using [`npm-run-all`](https://www.npmjs.com/package/npm-run-all) instead of chained `&&`s and replacing `rm -rf` with [`rimraf`](https://www.npmjs.com/package/rimraf).
=> Ensure CLI's README is formatted whenever it's updated

plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
Fixes #2118 
Gets rid of useMemo statement. It could use assembly.regions as the parameter for useMemo but it is more straightforward i think to not useMemo here
=> Fix loading indicator on refnameautocomplete being stuck

plugins/data-management/src/PluginStoreWidget/components/InstalledPlugin.tsx, plugins/data-management/src/PluginStoreWidget/components/InstalledPluginsList.tsx, plugins/data-management/src/PluginStoreWidget/components/PluginCard.tsx, products/jbrowse-desktop/src/Loader.tsx, products/jbrowse-desktop/src/jbrowseModel.js, products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/jbrowseModel.js, products/jbrowse-web/src/sessionModelFactory.ts
This fixes https://github.com/GMOD/jbrowse-components/issues/2052 by not using the name at all when removing plugins and instead relying on the plugin URL to identify which plugin to remove.
=> Use URL instead of name to remove plugins

plugins/alignments/src/shared.ts, test_data/config_demo.json
Fixes #2125 
There is a subtle chain of behaviors where because the ref renaming didn't work, it created the invalid state seen in #2125 
It started with the assemblyName not being defined, so renameRegionsIfNeeded returned the regions back, so then the bamadapter just returned 0 features for requests to the wrong chromosome for getting the 'modification color map' preprocessing step, so then the colors were black
complicated chain of events...it could be interesting if it used the assemblyName on the region object perhaps but this fixes the issue in the current way that things work
=> Fix using Color by modifications on BAM/CRAM that need ref renaming

packages/core/util/tracks.ts, plugins/variants/src/VcfAdapter/VcfAdapter.ts, products/jbrowse-cli/src/commands/add-track.ts
This adds the VcfAdapter for a plain VCF to both CLI and add-track. It doesn't really try to warn against large VCFs but it should be fine for small VCF that are encountered in the wild. The VcfAdapter was created by @carolinebridge-oicr originally
We could think about also unifying the cli and core codebase, and making it more pluggable perhaps too...but maybe as follow ons :)
=> Add plain VCF adapter recognition to guessAdapter

packages/core/util/index.ts, plugins/alignments/src/shared.ts, plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
This uses the assemblyName defined on a region object to do the renameRegionsIfNeeded operation. It first prepares a map of assemblyName->refNameMap and uses those for the individual renameRegionIfNeeded calls as usual
=> Make renameRegionsIfNeeded use assemblyName defined on regions themselves

products/jbrowse-web/src/rpc.worker.ts
This is a minor thing but it sometimes confuses debugging when you pause the debugger and it is in the flushLog instead of another part of the code that you are interested in.
I am not sure if there was context behind the logging like this but it seems like reverting to a direct console log is fine
=> Remove flushLog in rpc.worker for easier debugging

plugins/alignments/src/PileupRenderer/components/PileupRendering.test.js, plugins/alignments/src/PileupRenderer/components/PileupRendering.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.test.js, plugins/svg/src/SvgFeatureRenderer/components/SvgOverlay.tsx
This is probably a fix for #2130 
SVG and pileup tracks have been updated
The blockLayoutFeatures concept is completely removed now
=> Fix missing mouseovers in some cases in pileup/svg tracks

plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts, products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/text-index.ts, products/jbrowse-web/package.json, yarn.lock
I found that removing the lzutf8 package stopped the hanging that was seen in #2116 
I propose removing the lzutf8 package as a result
I think it is probably ok to remove it and I don't believe we need a replacement for it
The current usage of having per-line or per-entry compression is probably not very efficient, it is better to compress larger blocks of text so you can exploit redundancy across lines/entries
It may be worth considering alternative encodings or compression if we see issues but I think removing is ok for now
It is unclear to me why removing lzutf8 fixed the hanging but it was very reproducible to me
This is a PR targetting the text_searching branch
=>  Remove the lzutf8 package from cli to fix process hang

package.json, packages/core/package.json, plugins/alignments/package.json, plugins/breakpoint-split-view/package.json, plugins/circular-view/package.json, plugins/config/package.json, plugins/data-management/package.json, plugins/dotplot-view/package.json, plugins/filtering/package.json, plugins/gff3/package.json, plugins/hic/package.json, plugins/linear-comparative-view/package.json, plugins/linear-genome-view/package.json, plugins/lollipop/package.json, plugins/menus/package.json, plugins/sequence/package.json, plugins/spreadsheet-view/package.json, plugins/sv-inspector/package.json, plugins/trackhub-registry/package.json, plugins/variants/package.json, plugins/wiggle/package.json, products/jbrowse-desktop/package.json, products/jbrowse-react-linear-genome-view/package.json, products/jbrowse-web/package.json, website/package.json, website/yarn.lock, yarn.lock
#2141 uses some features that are only in the latest releases of material-ui/core. This updates all our package.json dependency versions to use a higher minimum version where those features are available. This doesn't change anything for web or desktop, since the material-ui/core was already updated in the lockfile, but users of `@jbrowse/react-linear-genome-view` or plugins published to npm could end up with incompatible versions of material-ui/core if the package.json versions aren't updated.
=> Raise minimum material-ui/core version everywhere

plugins/alignments/src/BamAdapter/MismatchParser.test.ts, plugins/alignments/src/BamAdapter/MismatchParser.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.tsx, plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
There is a subtle part of the MM tag specification which says
"If SAM FLAG 0x10 is set, indicating that SEQ has been reverse complemented from the sequence observed by the sequencing machine, note that these base modification field values will be in the opposite orientation to SEQ and other derived SAM fields."
This means all the calculations have to be done backwards on the reverse complemented read sequence, and then flipped back forward
=> Fix rendering of negative strand alignment modifications/methylation

plugins/circular-view/src/BaseChordDisplay/components/RpcRenderedSvgGroup.js
=> Remove outline from clicking on SVG chord tracks

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts, test_data/volvox/config.json
Reduces duplicates of options displayed in the dropdown. Should simplify flow of selecting option and opening more searchResults dialog. Instead of adding an indicator for the different types of options which could be misleading or confusing to the user, this simplifies displaying more options in the search results dialog.
Before:
After:
before:
after:
TODO: need to adjust to not open dialog when there is only one result, check for trackID in index in order to open track
=> Remove duplicate options from LGV search dropdown and dialog

test_data/config_demo.json
This is an interesting tumor+normal paired dataset that I stumbled on here https://www.biorxiv.org/content/10.1101/2020.07.09.196527v1
The ENA has some BAM files for the data https://www.ebi.ac.uk/ena/browser/view/PRJEB27698
There is also a plain text "truth set" of breakends in a VCF source data file here https://github.com/UMCUGenetics/COLO829_somaticSV
=> Add example dataset for COLO829

plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
Fixes #2130 
This is a surprise where I thought the layout data structure was causing issues and resulted in some layout code restructuring (converting to rbush)
I still think converting to rbush was a good change, but the proximal issue for #2130 is that the code for getting the feature calls
```
getFeatureOverlapping(blockKey: string, x: number, y: number) {
+        console.log(self.blockState.get(blockKey), blockKey, [
+          ...self.blockState.keys(),
+        ])
return self.blockState.get(blockKey)?.layout?.getByCoord(x, y)
},
```
We could even consider this to be a little too low level for BaseLinearDisplay but when you console.log this the blockKey that is received has -reload appended, an earlier way we used to force a rerender, while the blockKeys in self.blockState.keys() …
=> Fix mouseover after force load

plugins/grid-bookmark/src/GridBookmarkWidget/components/ClearBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/DeleteBookmark.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/DownloadBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx
These are a couple proposals for the bookmark widget
1) Uses a method for "auto-calculating" the width of a particular column that is used in the base feature details
2) Makes it so DeleteBookmark is just a dialog and not also a button. If it is a Button with a Dialog state inside it, it will render that dialog many times, even if in a hidden state. I propose extracting the Dialog as such
3) Makes a compact mode. I personally prefer the look of compact data displays, but could understand if this is not what all users want. I add it as an option here
4) Adds a note that lets users know that they can edit the label field by double clicking
Main thing I wanted to do this PR is (1)
The reason is we presupply a pixel width for each column. DataGrid does not have a method to change column …
=> Updates to bookmark widget

packages/core/ui/FileSelector.tsx
Proposal for #2138 
This is a little hacky but it is fairly straightforward
Alternatively, we could try something like a react context, or passing an mst tree to the file selector so we get a handle on a flag that we can use to determine when to hide the option. Note that the adminMode flag on session is just true in desktop so might need to be alternative if that was considered
=> Hide local file option if the adminKey url param is in place

plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts
This PR makes the trix search adapter return more results by default. This has some implications with duplicated results, because sometimes a query can return many duplicates and then you don't get that many autocompletes. For example in the volvox example, there are many features named seg02, but there are features named from seg01-seg15. It would be nice to list many of them, but if you search "seg", the autocomplete only has seg01 and seg02 in the dropdown. With this change, we get more seg results
Before:
After:
=> Increase number of results returned by @gmod/trix by default

packages/core/rpc/BaseRpcDriver.ts
The current code for checking if a worker was killed would progressively create more watchers over time because the resolve was never called. I mistakenly thought that Promise.race might kill the watcher promise
This was found because I saw the code freeze, and clicking the pause tab in the source debugger always ended up at the worker=='killed' line which seemed odd, and console.logging around this line indicated that it could be called thousands of times a second
=> Fix handle leak for killed worker checker

plugins/alignments/src/AlignmentsFeatureDetail/AlignmentsFeatureDetail.tsx, plugins/dotplot-view/src/DotplotRenderer/DotplotRenderer.ts, plugins/dotplot-view/src/index.ts, plugins/linear-comparative-view/src/index.tsx, products/jbrowse-web/src/sessionModelFactory.ts, test_data/config_demo.json
In the past PR #2024 the strand got ignored in read vs ref because after drawing negative strand alignments was added to the renderer, it was realized that strand was not specified correctly at that time of loading the data for read vs ref visualizations
This change makes the read vs reference strand become relative to the "original strand" the feature was on.
Intuitively if a read is on the forward strand, switches to the reverse, and back to forward
```
----->   <------ ----->
```
And the left most is the "primary" alignment (the rest are supplementary/split read alignments) then the strands are 1 for primary, -1 and then 1 for supp
But also the data can come in like
```
<------ -------> <------
```
This is fundamentally equivalent but the data is just from a reverse strand template. …
=> Add better inversion visualization to read vs reference visualizations

plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
This is a small change to have "unmapped reads" included in the default set of flags hidden on alignments tracks
Unmapped reads can be weird in that they can exist at a given coordinate but be shown still
1540 can be seen here https://broadinstitute.github.io/picard/explain-flags.html
read unmapped
read fails platform/vendor quality checks
read is PCR or optical duplicate
This is true in jbrowse 1 and igv by default. Had run into this with a hand crafted sam file that had unmapped reads that displayed in jbrowse but not in igv by default.
=> Hide reads with unmapped flag by default in alignments tracks

plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
* restores filtering options ( creates custom filter that checks label for search query or checks if there was a matched object in the returned result)
* Returns the expected results by filtering based on name and or displaying search results returned by adapters (note: may need future refactoring to provide best label)
=> Create custom filter for autocomplete filtering options 

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js
The title of this PR somewhat underestimates the issue scope but it is what the end user experiences
The collapsed category state was not stored in the widget model properly, and it was causing the code to forget the collapsed categories after a track is toggled (which causes the tree to get rerendered)
Note: Technically it might be somewhat expensive/not the best way to do things for for the tree to get recalculated after things like a track toggle or category collapse, but it seems to work fine afaik
This change is also good because it is nice for the collapsed categories to also be remembered in state e.g. across page refreshes
Fixes #2207
=> Fix issue where collapsed categories were not remembered after toggling a track

packages/core/rpc/coreRpcMethods.ts, plugins/linear-genome-view/src/LinearGenomeView/components/SequenceDialog.tsx, plugins/sequence/package.json, plugins/sequence/src/BgzipFastaAdapter/BgzipFastaAdapter.ts, plugins/sequence/src/IndexedFastaAdapter/IndexedFastaAdapter.ts, yarn.lock
This PR that adds an AbortSignal options parameter to "CoreGetFeatures" rpcManager
This was just based on the observation that "SequenceDialog" if a large region is selected and then the dialog is closed, does not cancel the fetch of sequence
This does not yet actually add full aborting for that sequence fetch, because the sequence adapters such as indexedfasta-js et al would have to add abort support to make this really work, but it may be worth it to have the infrastructure added here anyways
=> Add aborting to CoreGetFeatures rpcManager call

products/jbrowse-web/src/Loader.tsx
Tries to help with #2171 
Based on the idea that a red error box for a 404 not found error might be overly scary, so it specifically detects this case and displays a green message instead of a red one
=> Add a helpful message if there is a 404 on config.json error

products/jbrowse-cli/src/commands/text-index.test.ts
This performs a text-index command on the volvox data directory itself, and then compares the results of running the text with what was already there
If it fails then there are multiple things that could be happening
1) volvox needs to be re-indexed
2) the format of meta json or trix indexes has changed, implying (1) in the case of a bugfix, or a unexpected bug resulting in mismatch
Pretty much a snapshot test but where we can use the results in the volvox instance
=> Text indexing check against volvox instance

packages/core/pluggableElementTypes/models/BaseDisplayModel.tsx, packages/core/pluggableElementTypes/models/BaseTrackModel.ts, packages/core/util/tracks.ts, plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/circular-view/src/BaseChordDisplay/components/RpcRenderedSvgGroup.js, plugins/circular-view/src/BaseChordDisplay/models/BaseChordDisplayModel.ts, plugins/circular-view/src/BaseChordDisplay/models/renderReaction.js, plugins/dotplot-view/src/DotplotDisplay/index.ts, plugins/dotplot-view/src/DotplotView/model.ts, plugins/filtering/src/LinearFilteringDisplay/model.js, plugins/hic/src/LinearHicDisplay/model.ts, plugins/linear-comparative-view/src/LinearComparativeDisplay/index.ts, plugins/linear-comparative-view/src/LinearComparativeView/model.ts, plugins/linear-comparative-view/src/LinearSyntenyDisplay/index.ts, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts, plugins/linear-genome-view/src/LinearBareDisplay/model.ts, plugins/linear-genome-view/src/LinearBasicDisplay/model.ts, plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.tsx, plugins/lollipop/src/LinearLollipopDisplay/model.ts, plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts, plugins/variants/src/ChordVariantDisplay/models/ChordVariantDisplay.js, plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts, products/jbrowse-web/src/sessionModelFactory.ts, website/docs/developer_guide.md
=> Use superRenderProps and superTrackMenuItems for better simulated inheritance model

plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts, products/jbrowse-web/src/tests/BasicLinearGenomeView.test.js
Mentioned in comment [here](https://github.com/GMOD/jbrowse-components/pull/1881#issuecomment-901524338)
* filters formatted results in trix text search adapter to return only those that exactly match the label when searchType is set to exact
* this resolves options reappearing on the dialog when a user has already chosen an option from the dropdown
Before:
https://user-images.githubusercontent.com/45598764/130001901-f782b32f-0a7e-43c7-9a63-5fbc29fd1e09.mov
After:
https://user-images.githubusercontent.com/45598764/130001618-8a58c0d2-fb4f-475c-969c-bce95f609dfa.mov
=> Resolves prefix matches found in search results dialog

packages/core/util/index.ts
May help with https://github.com/GMOD/jbrowse-plugin-template/issues/18
=> Export offscreenCanvasUtils

packages/core/ui/ViewContainer.tsx
The change to make menuItems into a function makes it somewhat challenging for previous plugins who used menuItems as a getter
This attempts to add a little backcompat
Minor cleanup of unused styles also
=> Fix some backcompat for view menuItems

products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.js, yarn.lock
I've been using this change to make working on desktop easier, so I thought I'd put it in as a separate PR.
This adds `electron-window-state`, which keeps track of the size and location of the window is in when it closes in JBrowse Desktop. When you re-open JBrowse Desktop, it restores the window to the same size and position.
=> Restore previous desktop window location when re-opening

plugins/bed/package.json, yarn.lock
The current @gmod/bed parser makes I think too  assumptions about what a BED file is if no info is specified e.g. as with BED tabix files. 
For example, currently the inversion BED tabix files in #2198 are displayed incorrectly (it thinks it is an intron because it thinks it's like a BED12 file)
This proposes using an "unassuming" BED parser that will use the strand/score fields if it makes sense to, otherwise it just stores the fieldnames, and only tries to use @gmod/bed if the code is actually a BED12 file or has autoSql attached
With this change added, the BED tabix files in #2198 display properly e.g. just as boxes indicating the region of the inversion, and some fields that don't have any description are called field5,field6,field7... in the feature details panel
=> Make the BED parser not interpret general tab delimited data as BED12

packages/core/babel.config.js, packages/core/package.json, yarn.lock
According to the [babel docs](https://babeljs.io/docs/en/babel-plugin-transform-runtime), if you use `@babel/plugin-transform-runtime`, you need to have `@babel/runtime` as a dependency for the package. This adds that missing dependency to our `@jbrowse/core` package. It also makes the "regenerator" option for that plugin be `true`, the default, because I was still seeing errors while troubleshooting #2244 unless I made that change.
=> Fix missing regenerator runtime dependency in core

plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts, plugins/alignments/src/index.ts, plugins/dotplot-view/src/index.ts, plugins/linear-comparative-view/src/index.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/components/BaseLinearDisplay.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, website/docs/developer_guide.md
Inspired by #2226, this makes it so that plugins that want to add context menu items to displays now do so using the `Core-extendPluggableElement` extension point. This removes the need for there to be an autorun that watches for new displays and adds "additionalContextMenuItems" to them. Instead, it extends the display state model itself so all instances of the display already have the additional context menu items.
=> Use extendPluggableElement for context menu items

packages/core/data_adapters/BaseAdapter.ts, packages/core/data_adapters/dataAdapterCache.ts, packages/core/util/idMaker.ts
This is a small proposal to use the "idMaker" concept from BaseAdapter for the dataAdapterCache key
The reason is that, potentially, the jsonStableStringify on a large FromConfigAdapter input would be large, and so automatically would take...just trying to estimate but I imagine the stringified version of a JSON object could be at least 2x but probably much more the size of the data (imagine 4byte ints vs 10char sequences...but also think of all the key values being stringified probably being stored more efficiently in memory)
=> Use idMaker for dataAdapterCache key for faster FromConfigAdapter performance

website/release_announcement_drafts/v1.3.4.md
Here's the current changelog. Note that the beta pre-release of desktop has split up the changelog, and you have to do a bit of extra work to get it to generate for two releases. I'll probably fix the changelog manually in this release, but we might want to consider that before we do the next desktop beta release.
```markdown
* Other
* [#2163](https://github.com/GMOD/jbrowse-components/pull/2163) Add new embeddable React Circular Genome View ([@garrettjstevens](https://github.com/garrettjstevens))
* [#2229](https://github.com/GMOD/jbrowse-components/pull/2229) Use extendPluggableElement for context menu items ([@garrettjstevens](https://github.com/garrettjstevens))
* [#2233](https://github.com/GMOD/jbrowse-components/pull/2233) Add optional chromSizes config slot to TwoBitAdapter to speed …
```
=> Add v1.3.4 release announcement draft

packages/core/ui/FileSelector.tsx
Fixes #2246
The key is that, onChange will produce a "null" change when its in exclusive mode, and you click a button that is already depressed expecting it to become undepressed. Our code switched it from url->file mode however.
=> Prevent the ToggleButton for the FileSelector toggling to local file when only URL should be available

plugins/grid-bookmark/src/GridBookmarkWidget/components/AssemblySelector.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/ClearBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/DeleteBookmark.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/DownloadBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.test.js, plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/ImportBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/model.ts, plugins/grid-bookmark/src/GridBookmarkWidget/utils.ts
I had a quick interest in getting a import bookmarks function implemented
This let's a user quickly import a BED formatted file. The name column 4 is stored in the "label" field
It also has a couple more add-ons
* replaces the NA default export with a . which is the standard not available data description for BED
* makes it so duplicates in bookmarks are allowed, as this may come from data files, and rather than filtering on import, it retains them (note that if this was not done, then strange errors would occur on editing fields)
* makes the hover style on links in the grid bookmark widget cursor:pointer
Some motivation to this includes my feeling that you can easily loose track of your session 
During development especially, I cycle through tons of sessions and I imagine a user may …
=> Import bookmarks functionality for grid bookmark widget

plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
When viewing on a small display, this particular autocomplete attribute would make the dropdown display differently
before
after
Kind of an unexpected effect but I think this helps
=> Fix autocomplete height on small displays

plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, test_data/large.chrom.sizes
Fixes #1899 
Before
After
One notable case is that when viewing all chromosomes e.g. "Show all regions in assembly" it makes a long ref string concatenating all strings. we could consider making a compact representation. Anyways, there is a maxWidth:500, minWidth:200 (uses custom width calculation instead of directly using minWidth/maxWidth  in css, didn't seem like it works in css to sensibly autoadjust by specifying those see https://codesandbox.io/s/material-demo-forked-j2c1b?file=/demo.js seems to expand to maxWidth by default)
=> Auto adjust box RefNameAutocomplete width based on refName length

scripts/release.sh
This attempts to force publish all packages on each release, despite if they have not changed
This could be considered overkill and a reaction to the v1.3.4 to v1.3.5 release thing but it seemed to have resulted in a fair bit of confusion. It may be best to publish all every time. The only downside may be taking up a bit more npmjs.com server space
https://lerna.js.org/#command-publish
=> Force publish all packages on release

products/jbrowse-react-circular-genome-view/README.md, products/jbrowse-react-linear-genome-view/README.md
Fixes https://github.com/GMOD/jbrowse-components/pull/1943
If we don't want to suggest legacy-peer-deps we might need https://github.com/GMOD/jbrowse-components/pull/1727 and maybe even other evaluations of our many dependencies and their peerDependencies...it's just quite a picky system sometimes
Also removes storybook note from circular view
@garrettjstevens is the circular view storybook published?
=> Add note about legacy-peer-deps to readme

plugins/variants/src/VcfTabixAdapter/VcfFeature.ts
This adds the feature.get('type') for some variant symbolic allele types
The VariantDetailWidget  actually needs (in some form, or it has to change itself) because it checks for feature.type==='breakend' and feature.type==='translocation' but the translocation one wasn't working
=> Fix ability for the variant detail panel to create breakpoint split view for <TRA> elements

plugins/trix/package.json, plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts, products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/__snapshots__/text-index.test.ts.snap, products/jbrowse-cli/src/types/gff3Adapter.ts, products/jbrowse-cli/src/types/gtfAdapter.ts, products/jbrowse-cli/src/types/vcfAdapter.ts, test_data/volvox/trix/volvox.ix, test_data/volvox/trix/volvox_meta.json, yarn.lock
This makes the trix index files about 25% smaller but also, more human readable
=> Use encodeURIComponent for trix encoding instead of base64

plugins/breakpoint-split-view/package.json, plugins/breakpoint-split-view/src/BreakpointSplitView.ts, plugins/breakpoint-split-view/src/components/AlignmentConnections.tsx, plugins/breakpoint-split-view/src/components/Breakends.tsx, plugins/breakpoint-split-view/src/components/Header.tsx, plugins/breakpoint-split-view/src/declare.d.ts, plugins/breakpoint-split-view/src/model.ts, plugins/config/src/FromConfigAdapter/FromConfigAdapter.ts, plugins/dotplot-view/src/DotplotRenderer/ComparativeRenderRpc.ts, plugins/dotplot-view/src/DotplotRenderer/DotplotRenderer.ts, plugins/dotplot-view/src/DotplotView/model.ts, plugins/dotplot-view/src/index.ts, plugins/linear-comparative-view/src/LinearComparativeView/model.ts, plugins/linear-comparative-view/src/index.tsx, plugins/spreadsheet-view/package.json, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/__snapshots__/VcfImport.test.ts.snap, plugins/variants/package.json, plugins/variants/src/StructuralVariantChordRenderer/ReactComponent.js, plugins/variants/src/StructuralVariantChordRenderer/index.js, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.js.snap, plugins/variants/src/VcfTabixAdapter/VcfFeature.ts, test_data/breakpoint/config.json, yarn.lock
This PR works in tandem with a major version bump to @gmod/vcf
https://github.com/GMOD/vcf-js/pull/69
The reason I found this is because there were breakends in the COLO829 dataset (on config_demo.json, hg19) that I wanted to check out. They are actually representing an SVTYPE=DEL using breakend representation, and it was not possible to do breakend split view on this example.
To fix, my strategy was to have basically "point-of-use" breakend parsing: most usages of the breakends should know when they need it parsed out, and can do so at that point by importing parseBreakend from @gmod/vcf
Also, some notable other things:
FromConfigAdapter does not need to have logic for parsing out mate/bnd/chr2, it does not respond to getFeatures requests with data about those mates, and ref renaming for …
=> Improve breakend parsing and don't rely on SVTYPE=BND for displaying breakend split view options

plugins/alignments/src/LinearSNPCoverageDisplay/components/Tooltip.tsx, plugins/linear-genome-view/package.json, plugins/linear-genome-view/src/BaseLinearDisplay/components/BaseLinearDisplay.tsx, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/wiggle/package.json, plugins/wiggle/src/LinearWiggleDisplay/components/Tooltip.tsx, plugins/wiggle/src/index.ts, yarn.lock
This uses react-popper library manually to create a tooltip
It is a second approach to  https://github.com/GMOD/jbrowse-components/pull/2284
This can now display it's tooltip outside the bounds of the track
See snpcoverage for example here, displaying over the track panel
The calculation of the width of the tooltip is done manually with getBoundingClientRect. It doesn't appear to perfectly track the coordinates of where you want to display it
I think that overcoming the limitations in #2284 will be good, and while it takes a fair amount more code to do it this way, it helps greatly with the users perceived speed on the page.
I think it is either this or we get rid of some tooltips by default
=> Faster tooltip method for feature tracks and wiggle tracks with react-popper

test_data/config_demo.json, website/src/pages/demos.mdx
Adds a SKBR3 demo (breakpoint split view + sv inspector) and a COLO829 demo (tumor vs normal coverage profile) to the demos page
=> Add cancer demos to the demos page on website

plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx, plugins/alignments/src/PileupRenderer/components/PileupRendering.tsx, plugins/breakpoint-split-view/src/BreakpointSplitView.test.tsx, plugins/breakpoint-split-view/src/model.test.tsx, plugins/breakpoint-split-view/src/model.ts, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx, plugins/svg/src/SvgFeatureRenderer/components/SvgOverlay.tsx
Fixes #2308
The code mistakenly looked across blocks for feature highlights, resulting in feature highlights appearing in the wrong block
Was a bug introduced around the time of the this layout related PR #2099 (introduced bug in v1.3.1)
=> Fix mouseover selection appearing across unrelated blocks

packages/core/ui/FileSelector.tsx, plugins/data-management/src/AddTrackWidget/model.ts
The add track model improperly "clears" the trackData and indexTrackData state and this makes it so that the second time you use the form, the inference doesn't work
This fixes that
It also trims whitespace from the filename which fixes when you copy and paste with a string that has a space at the end or similar
=> Fix issue where add track widget doesn't infer adapters the second time around

scripts/release.sh
The current blogpost url format got a little weird in https://github.com/GMOD/jbrowse-components/commit/41b9f3e460dddb9a292986736e71b3ffe8e196de#diff-1bba00e5aca52286a667c09eff92ba2ca8e3ca77e0d31b0599cc829ab0173389
This was unintentional, it was thought this would just be a datestamp in the blogpost itself
Now the filename is containing date only, blogpost can have datetime
=> Fix blogpost url formats

plugins/linear-genome-view/src/LinearBasicDisplay/model.ts, plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js, plugins/svg/src/SvgFeatureRenderer/configSchema.ts
There is currently a "Show labels" toggle box that hides both label and description
This adds a "Show description" toggle box that just hides the description part of the feature label
=> Add show descriptions toggle box to most feature tracks

plugins/variants/src/StructuralVariantChordRenderer/ReactComponent.js, products/jbrowse-react-circular-genome-view/src/createModel/createSessionModel.ts
- Handle feature.get('ALT') being undefined so that non-VCF features can be used
- Set stroke width back to 1 when chord is no longer being hovered over
- Make renderProps not a getter to match recent changes
=> Fix bugs preventing embedded circular genome view from rendering in some circumstances

website/docs/bcc2020_plugin_development.md, website/docs/developer_guide.md, website/docs/faq.md, website/docs/quickstart_cli.md, website/docs/quickstart_gui.md, website/docs/quickstart_web.md, website/docs/superquickstart_web.md, website/docs/user_guide.md, website/docusaurus.config.json, website/package.json, website/yarn.lock
Currently I found there are links that can end up broken if you click through the docs
Especially if you follow a link someone gives you e.g. https://jbrowse.org/jb2/docs/quickstart_cli#indexing-feature-names-for-searching
And then you go on to click the link to the CLI docs
This fails with a 404
There is a subtle behavior where the browser or server automatically adds a slash
So if you copy and paste https://jbrowse.org/jb2/docs/quickstart_cli into the browser, then it becomes
https://jbrowse.org/jb2/docs/quickstart_cli/
and then navigating to
./cli
is
https://jbrowse.org/jb2/docs/quickstart_cli/cli
when it should be
https://jbrowse.org/jb2/docs/cli
However it is subtle also because currently, clicking on
https://jbrowse.org/jb2/docs/
Then clicking quickstart_cli, gives you …
=> Use ../ for all doc links and use trailing slash to fix links

plugins/config/src/FromConfigAdapter/FromConfigSequenceAdapter.ts
A user using the FromConfigSequenceAdapter and the React Circular Genome View noted that it was unexpected that the regions around the circle were not in the same order specified in the adapter config. I agree that this seems unexpected and propose that we don't sort and instead keep the sequences in the same order they are specified.
=> Don't sort sequences in FromConfigSequenceAdapter

plugins/authentication/src/GoogleDriveOAuthModel/model.tsx, test_data/volvox/config.json
I was able to load a BigWig from Google Drive just fine, but CRAM didn't work. This ended up being because Google Drive doesn't expose the Content-Range header, so whenever the filehandle called `stat` (which it does on CRAM but not BigWig), it errored out.
This workaround provides a custom `openLocation` for Google Drive accounts that uses a custom filehandle that overrides the `stat` method. This `stat` gets the file size by getting the file metadata from the Google Drive API, since it can't get the size from the Content-Range header.
It also switches to using a different endpoint for the file contents so that v3 of the Google Drive API is used instead of v2. @peterkxie this will probably need to be fixed to restore `fetchFile` like you fixed my Dropbox code in …
=> Workaround for Google Drive not exposing Content-Range

package.json, packages/core/util/io/declare.d.ts, packages/core/util/io/index.ts, yarn.lock
Currently jb2export is broken on local files because a check for allowing local files, around the time electron was changed to use normal webworker instead of electron windowworkers (79e799fece)
This PR makes it so that LocalFile is allowed anytime the environment detects isNode===true, not just if it is electron (e.g. jb2export is a plain nodejs process)
=> Fix ability to use LocalFile on nodejs-based apps e.g. @jbrowse/img

products/jbrowse-web/src/rpc.worker.ts
I think in the current code, there is some unneeded ritual around the RPC calls that is probably unneeded. With this change, the only thing wrapForRpc does is initialize the statusCallback on the call properly
=> Remove unused wrapForRpc functionality

package.json, products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, products/jbrowse-desktop/src/Loader.tsx, products/jbrowse-desktop/src/StartScreen/data/preloadedConfigs.js, products/jbrowse-desktop/src/StartScreen/index.tsx, products/jbrowse-desktop/src/corePlugins.ts, products/jbrowse-desktop/src/index.js, products/jbrowse-desktop/src/jbrowseModel.js, products/jbrowse-desktop/src/rootModel.ts, yarn.lock
The code in #2247 fails to automatically reload the page to the right session after the user has exited
This adds code in the Loader of jbrowse-desktop that allows specifying a "query parameter" to the electron session that let's it restore a particular config
This query parameters on desktop could also be used for automating desktop via the CLI
Also adds text searching to desktop...random add on but just found it in the process
=> Fix install plugin workflow on desktop

packages/core/util/types/index.ts, plugins/menus/src/index.ts, products/jbrowse-web/package.json, products/jbrowse-web/src/__snapshots__/rootModel.test.js.snap, products/jbrowse-web/src/rootModel.ts
The menus plugin adds some menu items by default but it was recognized by @garrettjstevens that maybe the logic doesn't necessarily apply the same way for desktop now that a session on desktop is more like a full config
This removes the session options in the File menu on desktop, and for jbrowse-web, moves the code for adding those menu items to the products/jbrowse-web/ app
=> Remove session related menu items from jbrowse-desktop

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/admin-server.test.ts, products/jbrowse-cli/src/commands/admin-server.ts, products/jbrowse-web/src/JBrowse.js
Possible fix for #2139 
This would let the admin-server receive a config path from a client and write to it
Note that with the current admin-server, something like this is possible: you setup --out to a specific config.json, and then you navigate to that specific config using &config=
However, if you wanted e.g. to edit multiple configs in the same admin-server session, this PR would help
=> Update admin-server to accept a configPath

plugins/legacy-jbrowse/src/JBrowse1TextSeachAdapter/configSchema.ts, products/jbrowse-web/src/tests/TextSearching.test.js, test_data/volvox/volvox_jb1_text_config.json
Trix adapter was updated here. https://github.com/GMOD/jbrowse-components/pull/2298
Need to update the JB1 text search adapter. AssemblyNames field is used to filter the necessary adapters during a search based on the assemblies those adapters cover.
=> update assemblies to assemblyNames in JB1 text search adapter

plugins/authentication/src/HTTPBasicModel/model.tsx
This is a small change so that the HTTP Basic account dialog uses a `<form>`. This allows the user to be able to submit with the <kbd>Enter</kbd> key as well as enabling the browser's built-in form validations.
=> Make HTTPBasic dialog use a form

packages/core/declare.d.ts, packages/core/package.json, packages/core/pluggableElementTypes/models/InternetAccountModel.ts, packages/core/util/io/RemoteFileWithRangeCache.ts, packages/core/util/io/index.ts, plugins/authentication/src/DropboxOAuthModel/model.tsx, plugins/authentication/src/ExternalTokenModel/model.tsx, plugins/authentication/src/GoogleDriveOAuthModel/model.tsx, plugins/authentication/src/HTTPBasicModel/model.tsx, plugins/authentication/src/OAuthModel/model.tsx, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, products/jbrowse-web/src/tests/Reload.test.js, test_data/volvox/config.json, yarn.lock
This adds `http-range-fetcher` back due to concerns described in [this comment](https://github.com/GMOD/jbrowse-components/pull/2279#issuecomment-921322346).
To handle various authentication models needing to use their own `fetch`es with auth headers, etc., it adds it back in a different way. It extends `RemoteFile` to `RemoteFileWithRangeCache`, and anything that wants to use the global range cache can use that class instead of `RemoteFile`. This does not require any changes to `http-range-fetcher`
=> Add `http-range-fetcher` back

packages/core/pluggableElementTypes/models/InternetAccountModel.ts, packages/core/ui/FileSelector/FileSelector.tsx, packages/core/ui/FileSelector/LocalFileChooser.tsx, packages/core/ui/FileSelector/UrlChooser.tsx, packages/core/ui/FileSelector/index.ts, packages/core/util/types/index.ts, plugins/authentication/src/DropboxOAuthModel/model.tsx, plugins/authentication/src/GoogleDriveOAuthModel/model.tsx, plugins/data-management/src/AddTrackWidget/components/TrackSourceSelect.tsx, test_data/volvox/config.json
This is a proposal for more adjustments to the file selector UI. I wanted to make the UI easier for the most common cases. I think that the large majority of users will have either no internet accounts configured (default for web) or Google Drive and Dropbox configured (possible future default for desktop). There does need to be some way to handle many configured accounts in the UI, but since that's an uncommon case, in this branch that particular UI does not show up until three or more accounts are configured. By default with two accounts configured, the UI looks like this (all four possible states):
With more accounts, there is a "More" button, and selecting an account from that menu moves it to be the last displayed account.
In discussion earlier with @peterkxie and …
=> Make file chooser more configurable by internet accounts

plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.js, plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts
reason for change:
GDC does not support stat(). when putting a GDC resource through the spreadsheet view, stat() cannot retrieve the size of the file and then errors and aborts the operation ;; spreadsheet view is required to visualize BEDPE files.
additional changes enable authentication to go through the spreadsheet component
=> authenticate files through spreadsheet view ;; skips stat() if it fails

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js
When looking at https://github.com/GMOD/jbrowse-components/discussions/2367 and thinking about how people can differentiate their tracks, I realized there is no tooltip on the current track selector entries (there were on previous iterations of the track selector). This adds such a tooltip. I think this can be a useful way for people to keep information about their tracks easily accessible.
=> Add tooltip with track description to track selector

products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, products/jbrowse-desktop/src/StartScreen/PreloadedDatasetSelector.tsx, products/jbrowse-desktop/src/StartScreen/RecentSessionsPanel.tsx, products/jbrowse-desktop/src/StartScreen/data/preloadedConfigs.js, products/jbrowse-desktop/src/StartScreen/index.tsx, yarn.lock
This PR has several small changes I wanted to propose after working with the desktop app:
- Reduce size of saved session thumbnail image. Now saves at a width of 250 (the size of the preview image in the card) instead of full window width.
- Fix bug in mm10 preloaded config where it would not open by itself because it didn't have a defaultSession
- Fix bug where if you checked and then un-checked an assembly, it would still be in the session (also disable "Go" button while no assemblies are checked)
- Move tooltip on toggle button from the contents to the toggle button itself, so that the tooltip will show up even if hovering over the edges of the button.
- Rename "table view" to "list view" in start screen. Small survey (at least my OS's file explorer and Google Drive) shows this to be …
=> Desktop bug fixes and UI updates

.github/workflows/desktop_beta.yml, .github/workflows/desktop_build_linux.yml, .github/workflows/desktop_build_mac.yml, .github/workflows/desktop_build_win.yml, .github/workflows/jbrowse-web.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, .github/workflows/website.yml, CONTRIBUTING.md, README.md, package.json, products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, yarn.lock
This method will create a method for auto-updating on desktop. I tested this on a mac
Notes
- There are now many more release artifacts, the blockmap files, the latest-*.yml files are needed for auto-update
- The mac needs both a dmg and a zip because without the zip it gives an error to the auto-updater (https://github.com/electron-userland/electron-builder/issues/2199). Zip could also be used separate from dmg e.g. like a non-installer
- Bumps requirement for the monorepo to node 14 because electron-builder needs it. I could revert this particular change but it seems best to stay updated, and this just requires node 14 via the engines field
- Adds snap and appimage options for linux. AppImage was what previously was only available, but snap might help a subset of users
- The workflow …
=> Desktop auto update

plugins/data-management/src/SetDefaultSession/SetDefaultSession.test.tsx, plugins/data-management/src/SetDefaultSession/SetDefaultSession.tsx, products/jbrowse-web/src/AdminComponent.tsx
Small redesign proposal for the "Set default session" dialog
current
I think by making it clear that there are just a couple choices for the user, and having a little help text, it helps them make the right choice. It also removes the usage of displaying the saved sessions in the dialog
=> Set default session dialog redesign proposal

package.json
Not exactly sure if this will help but saw a test failure here was memory related. Try to increase memory allotment on test
https://github.com/GMOD/jbrowse-components/runs/4051597092?check_suite_focus=true
=> Increase memory allocation jest on CI

plugins/variants/src/VcfAdapter/VcfAdapter.ts, plugins/variants/src/VcfAdapter/__snapshots__/VcfAdapter.test.ts.snap
This fixes refName renaming for the VcfAdapter. Also adds the 512MB limit, and delays parsing into VcfFeatures until needed, which aided memory usage on large ClinVar VCF from ncbi e.g. https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_clinvar.vcf.gz
=> Fix refName renaming on VcfAdapter for files that don't have ##contig lines

products/jbrowse-desktop/public/electron.ts
Currently we "await fetch" the preconfigured sessions file before the app starts, but instead, we can fetch this and the app polls the disk for updates, so no need to wait. This prevents a failure starting the app when offline
=> Don't fail if offline on starting jbrowse-desktop

plugins/data-management/src/PluginStoreWidget/components/CustomPluginForm.tsx, plugins/data-management/src/PluginStoreWidget/components/InstalledPlugin.tsx, plugins/data-management/src/PluginStoreWidget/components/PluginCard.tsx, plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.test.js, plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx, plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.js.snap
Small refactoring of the "Add custom plugin" dialog box
- combined formInput state split into two variables
- small margin added around the plugin widget
- title added to add custom plugin dialog box
- small instructional text
- submit and cancel boxes added
=> "Add custom plugin" dialog improvements

plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeViewSvg.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, plugins/linear-genome-view/src/LinearGenomeView/index.tsx, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This makes it so that the chromosome name is displayed to the left of the cytoband/ideogram in the overview scale bar
Cytobands are only visible when one chromosome (displayedRegion) is used
Also changes one of the cytoband colors ("stalk") from brown to grey to match UCSC (brown also looked very much like centromere, the dark red)
This has to apply a "cytobandOffset" to move the display to the left in several different places but since we have control over all these pieces, it seems like the effect of this is contained, and also the benefit for the user I think is also good
Before
After
=> Use an X offset in overviewscalebar when cytobands are viewed

packages/core/TextSearch/TextSearchManager.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/util.ts, plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts
This is a proposed fix for #2429 
The problem shown in that issue is that: when the user is trying to type in a refName e.g. typing 10<ENTER>, the search results from trix may come in and clobber their attempt at navigating by refName (hitting ENTER would then navigate to whatever is in the trix results)
Try typing e.g. 10 here https://jbrowse.org/code/jb2/v1.5.0/?config=test_data%2Fconfig_demo.json&session=share-Uk4KG8ocZC&password=VXmsd
Functionally, the change on this branch is that if you type something that matches a refname, it will return the matching refnames first in the list (sliced to limit 10 results, arbitrary limit to just balance trix/refname result if they were trying to query trix) and after that in the list, any matching search results from trix.
Internally, we have …
=> Improve usability of the search result autocomplete when typing in via keyboard

plugins/breakpoint-split-view/src/BreakpointSplitView.ts, products/jbrowse-web/src/tests/Loader.test.tsx
Currently the code was crashing on parseBreakend(undefined) for a BEDPE row accessed with breakpoint split view
This only calls parseBreakend if the string is defined
Additional typescripting (e.g. on @gmod/vcf) or unit tests could possibly catch errors such as this
=> Fix ability to open breakpoint split view from a BEDPE row in SV inspector

plugins/sv-inspector/package.json, plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.js, plugins/sv-inspector/src/SvInspectorView/models/adhocFeatureUtils.js, plugins/sv-inspector/src/SvInspectorView/models/breakpointSplitViewFromTableRow.js
Small refactor of sv-inspector to have less usage of factory functions, which actually improves some of my text editor type checking and such
The git diff is very messy but I just removed the outer factory functions that jbrequire uses and used standard es6 requires
=> Less use of factory functions sv-inspector

products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/text-index.ts, yarn.lock
This adds a Object.fromEntries polyfill for use in text-index for the CLI
Our CLI currently says it is compatible with node 10.4+ which needs a Object.fromEntries polyfill
xref https://github.com/GMOD/jbrowse-components/discussions/2359
We could also bump min to node 12 but this isn't too bad for now
=> Add polyfill for text-index compatibility with node 10

website/src/pages/index.js
This adds cytobands, text searching, and makes the "Browse web demo link" on the website go straight to an LGV using a share link
Idea being that it is just nicer to drop them into something that looks interesting rather than the bare bones start screen and having them find it themselves
=> Update the "Browse web demo instance" link to go to an LGV

products/jbrowse-desktop/src/StartScreen/RecentSessionsPanel.tsx
This adds a tooltip to the "Session path" on the desktop start screen. This can help if the path is cut off so you can't see the end of it.
=> Add a tooltip to desktop session path so you can see the full path if it's cut off

products/jbrowse-cli/package.json, yarn.lock
If you're using Yarn 2 and install `@jbrowse/cli` as a devDependency, it fails when you try to use it because the code uses `@oclif/errors` and it's not listed as a dependency. It's still installed by way of being a dependency of a dependency, but Yarn 2 is more strict about those things.
=> Add missing dependency to CLI

products/jbrowse-cli/README.md, website/docs/introduction.md
There are a lot of things on the "docs intro page" e.g. the landing page when a user clicks docs in the header bar. I thought it might be good to organize it a bit into 
Before
After
also incorporates a suggestion from @scottcain to link to @jbrowse/img on cli
=> Improve organization on docs landing page

packages/core/pluggableElementTypes/renderers/index.ts
This adds another export that plugins might want to use (e.g. I might need it for Apollo).
=> Add RenderProps to core/pluggableElementTypes export

plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeViewSvg.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
=> Add a red background to the overview scale bar with cytobands

website/docs/embedded_components.md, website/docs/introduction.md, website/sidebars.json, website/src/pages/download.mdx, website/src/pages/index.js
Found during pairing with @rbuels 
After updating the website for desktop release,  the embedded components docs got buried and it can be hard to quickly find storybook links.
Clicking on links above does not direct you to the appropriate section in the downloads docs. It can be confusing to click on embedded components and see desktop as the first thing. The link to "other platforms" directs you to the latest github tag/release? Maybe this could be a link to the introduction page of the docs.
Could be worth making a small little page for embedded docs once we add [Circular View embedded docs](https://github.com/GMOD/jbrowse-components/issues/2462)
Related Issue [Make Embedded docs more visible](https://github.com/GMOD/jbrowse-components/issues/2507)
=> Update docs for embedded components

plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js
This is a simple fix for #2515 
If we need to have a regex based search, we could possibly enable it as an option but it is probably ok to use a more simple string.includes check instead
=> Fix ability to search for tracks with parentheses in tracklist

.github/workflows/push.yml, products/jbrowse-react-circular-genome-view/stories/GettingStarted.stories.mdx, products/jbrowse-react-circular-genome-view/stories/JBrowseCircularGenomeView.stories.tsx, products/jbrowse-react-linear-genome-view/stories/GettingStarted.stories.mdx, website/src/pages/download.mdx
Follow up to #2508 to add circular view + adds storybook
Fixes #2462
=> Add circular genome view storybook

packages/core/ui/App.tsx
Basically appears to be overridden by the zIndex. Adds an arbitrarily higher number for zIndex. Fixes #2532
=> Fix drawer widget minimized button when overlapping with a view

plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js, plugins/svg/src/SvgFeatureRenderer/components/util.ts
We have two requirements where extending the SVG feature renderer would be useful:
- Custom glyphs with our own logic controlling when to render them instead of the provided ones
- Custom logic around whether or not a feature should be rendered. In particular, we have a feature filtration system, which means we need more control over which features are rendered based on filtration logic on our end
In order to do this, in this PR we define two optional props on the `SvgFeatureRendering` component and some of its children:
The `extraGlyphs` prop contains a list of custom glyphs and an associated validator for each. Then, when choosing which glyph to render in `chooseGlyphComponent`, we iterate the list and check each validator. The first one that succeeds is the custom glyph that gets …
=> Implement prop interface for providing arbitrary user-defined glyphs

packages/development-tools/package.json, packages/development-tools/src/createRollupConfig.ts, yarn.lock
The original Rollup config this was based on used [`rollup-plugin-typescript2`](https://www.npmjs.com/package/rollup-plugin-typescript2) for TypeScript compilation instead of the official Rollup TypeScript plugin ([`@rollup/plugin-typescript`](https://www.npmjs.com/package/@rollup/plugin-typescript)) because the official plugin at the time didn't do any type-checking, only transpilation. The official plugin does do type-checking now, though, claims to be faster, and has the benefit of official Rollup support. This PR switches over to using the official Rollup TypeScript plugin.
=> Use official Rollup TypeScript plugin in development-tools

packages/core/rpc/RpcManager.ts, packages/core/rpc/WebWorkerRpcDriver.ts
This appears to fix #2547 
The summary of #2547 is that multiple rpc drivers were being created due to the async change of getDriver
This changes it back to not being an async call, but loses the storing of ipc call to userData with this
If it is needed to have userData for other purposes in the code, it could be obtained in another way?
Alternatively, we could modify this PR to try to avoid double-creation of the drivers e.g. with a promise-singleton type pattern seen elsewhere in the codebase
=> Fix broken feature layout due to async race condition on getRpcDriver

plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeViewSvg.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
Changes the border color for non-cytoband OverviewScaleBar back to blue (was red when cytoband was added) and lightens the fill alpha on the cytoband overview rect (0.3->0.1)
after
before
after
before
=> Change border on non-cytoband OverviewScaleBar visible region back to blue and cytoband OverviewScaleBar to a little lighter fill

plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js
This restores the case-insensitivity of the track selector filter that was lost when the filter was change to use `includes` instead of regexp in 7ee926ec06d53af4af138a57fcc028e4f0287c2f.
=> Restore track selector filter case-insensitivity

packages/core/util/index.ts, plugins/menus/src/AboutWidget/components/AboutWidget.test.js
This is a fix for `findParentThat`, which is used by `getContainingView`, `getContainingTrack`, etc. Previously, it would start searching at the given node, and not its parent, so `getContainingView(self)` called from a view would return itself, even if it was nested inside another view. With this change it start searching at the first parent instead.
=> Start looking for parents with parent, not self in findParentThat

packages/core/ReExports/list.ts, packages/core/ReExports/modules.ts, packages/core/util/layouts/index.ts
This adds the code in `packages/core/util/layouts` to the core re-exports so that external plugins can use it. All of the exports in that directory have been added to and index file, so the code should be imported from external plugins like:
```js
import { SceneGraph } from '@jbrowse/core/util/layouts'
```
=> Add layouts code to core re-exports

plugins/authentication/src/HTTPBasicModel/model.tsx
This is the one way @peterkxie and I were able to solve #2541 for bigwig files
We tried several alternative approaches
1) Making the "new BigWig" object get recreated inside the setup function instead of in BigWigAdapter constructor
2) Removing AbortablePromiseCache from getHeader in bbi.ts inside of @GMOD/bbi
3) lots of console.logging elsewhere in the code
None of these worked though
With this PR though, it does work. It does have the result of making many small range requests that are not saying they are read from disk cache in chrome, so could result in slowness, but would fix BigWig tracks for http basic
Note that we only saw issues with BigWig files. BAM tracks with SNPCoverage work for example, even with the LinearSNPCoverageDisplay only showing.
If needed we could do even deeper …
=> Fix ability to access BigWig tracks on http basic auth for some cases

packages/core/data_adapters/BaseAdapter.ts, packages/core/pluggableElementTypes/renderers/FeatureRendererType.ts, packages/core/util/types/index.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.tsx, plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.test.ts, plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts
The colorByMethylation currently fails on files that require ref renaming
Example: "Nanopolish modbam_test.reference 20:10000000" in config demo
This fixes that by querying the sequenceAdapter with originalRefName instead of refName
It also tries to formalize that the originalRefName is an attribute that flows through the system, even at the level of BaseAdapter
=> Fix ability to use "Color by methylation" on files that require refname renaming

packages/core/pluggableElementTypes/index.ts, packages/core/util/index.ts
I was looking at the GDC plugin to see how hard it would be to convert to the new plugin build system, and found a few things from core that it was using that weren't in our current exports. That means it must have been compiling those into the build, but with these it can use the runtime versions of them.
=> Add more exports that can be used by plugins

packages/core/ui/SnackbarModel.ts, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-react-circular-genome-view/src/createModel/createSessionModel.ts, products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts, products/jbrowse-web/src/sessionModelFactory.ts
This proposes refactoring the snackbar code into a reusable unit in @jbrowse/core that different products use. It is essentially identical across modules currently, so this avoids a bit of code duplication
It also fixes #2568 by auto dismissing info and success messages after 5 seconds
=> Make core snackbar notifications module with auto-dismissing info/success level notifications

plugins/linear-genome-view/src/LinearGenomeView/components/HelpDialog.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This tries to help with #2527 by changing the help text on the import form for the lgv, and also adding a "help button" inside the RefNameAutocomplete that pops up a dialog, which contains some help text inspired by the jbrowse 1 help menu
This also increases the width of the RefNameAutocomplete to support the added help text and help button (otherwise it wraps to two lines of help text and makes it look a bit messy)
screenshot of how it looks now
=> Add help text and help dialog for the RefNameAutocomplete

packages/development-tools/package.json, packages/development-tools/src/createRollupConfig.ts, packages/development-tools/src/util.ts
Sometimes when bundling certain dependencies, there would be leftover import/require statements in the generated bundle that looked something like:
```js
import 'react';
```
These would make it so the plugin couldn't load, since it expects everything to be bundled in and there to be no external imports. It turns out rollup was keeping those around since it thought they had side effects, but there is a `moduleSideEffects` setting in rollup that fixed it for our use case.
Leaving as draft while I run through some more packages and check that this works.
=> Fix leftover imports being in CJS and ESM bundles

packages/development-tools/package.json
Adds a `prepack` script so the build gets properly created on publish.
=> Fix broken published build of jbrowse/development-tools

babel.config.js, packages/core/PluginManager.ts, packages/core/TextSearch/TextSearchManager.ts, packages/core/data_adapters/BaseAdapter.ts, packages/core/pluggableElementTypes/RpcMethodType.ts, packages/core/rpc/BaseRpcDriver.ts, packages/core/rpc/RpcManager.ts, packages/core/rpc/WebWorkerRpcDriver.ts, packages/core/util/blockTypes.ts, packages/core/util/compositeMap.ts, packages/core/util/layouts/MultiLayout.ts, packages/core/util/layouts/SceneGraph.ts, packages/core/util/types/index.ts, plugins/alignments/src/BamAdapter/BamSlightlyLazyFeature.ts, plugins/alignments/src/CramAdapter/CramSlightlyLazyFeature.ts, plugins/circular-view/src/CircularView/models/slices.ts, plugins/dotplot-view/src/DotplotView/blockTypes.ts, plugins/hic/src/HicAdapter/HicAdapter.ts, plugins/legacy-jbrowse/src/NCListAdapter/NCListFeature.ts
I learned about Typescript's [parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) recently, and did a quick search in our code base to see if there was anywhere we could use them. This is a refactoring, so no functionality is changed. I think they are useful because they allow us to not have to declare types twice and make the code more concise. Basically how they work is that this:
```ts
class Person {
public name: string
constructor(name: string) {
this.name = name
}
}
```
can be written as this:
```ts
class Person {
constructor(public name: string) {}
}
```
`this.name` is assigned automatically, so the constructor can be empty.
The only odd thing was that the tests wouldn't run with this change, and to fix it I had to change the order …
=> Use TypeScript parameter properties

plugins/bed/src/BedTabixAdapter/BedTabixAdapter.ts, plugins/wiggle/src/LinearWiggleDisplay/components/Tooltip.tsx
It was seen in jbrowse-plugin-gwas that sometimes a stringified score can be passed to the tooltip https://github.com/cmdcolin/jbrowse-plugin-gwas/issues/4
This makes sure to convert to number first
=> Fix wiggle tooltip crash on non-numerical inputs

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx, packages/core/BaseFeatureWidget/__snapshots__/index.test.js.snap, plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap, plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.js.snap
It was pointed out in a demo that the alignment of the field labels in a BaseFeatureDetail window looks a little sloppy and makes the fields hard to read. This is because the styling was set to any length between 90 and 150px.
This PR uses measureText to determine the longest label in the field labels to be processed and uses that as the width of each field name. Any given label will be one of two values now: 90px at minimum, or the length of the longest string (or if that length exceeds 170px, 170px).
170px gives the labels a little more flexibility than 150px while still maintaining a maximum such that fields aren't going off the screen.
Before:
After:
=> Adjust label width on base feature detail to enforce better alignment

plugins/config/src/ConfigurationEditorWidget/components/ColorEditor.tsx
Before this fix, if you changed the color in the config editor GUI, it would update the color to something like `rgb(44,0,255,1)`, which isn't valid since you need to use `rgba` instead of `rgb` if you're specifying an alpha level. This resulted in wiggle density tracks having a solid color instead of a color range if you picked their color with the GUI. This fixes it by using `rgba` instead of `rgb` if `a` is defined.
=> Fix GUI color editor rgba string format

packages/core/util/jexl.ts, packages/core/util/simpleFeature.ts
This adds two options for inspecting the parent feature in jexl callbacks
1. parent(feature), using an added jexl function
2. get(feature,'parent'), using an extra check to the get method in SimpleFeature
Fixes #2630
=> Add ability to get parent feature in jexl syntax with either parent(feature) or get(feature,'parent')

website/release_announcement_drafts/v1.5.6.md
Our v1.5.5 has an issue with the babel config not compiling a new syntax that we used, which affected @jbrowse/core specifically, which makes usage of things like @jbrowse/react-linear-genome-view unusable
=> Release draft announcement v1.5.6

plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx, plugins/dotplot-view/src/DotplotView/model.ts
Can help with #2631 
This does not proportionally adjust the bpPerPx of the vertical view while increasing the height, it just adds more blank space at the top, but if needed could try to adjust the bpPerPx perhaps too. Note that similar things like closing the drawer do not proportionally adjust bpPerPx
=> Add vertical resize handle to dotplot view

babel.config.js
For some reason the default of `babel-preset-react-app` is to use [absolute paths for babel runtime stuff](https://github.com/facebook/create-react-app/tree/main/packages/babel-preset-react-app#absolute-runtime-paths), so when run on another machine from the one it was built on, it failed. That's why the errors say they can't find: `'/data/jbrowse-components2/node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js'`. With this change that will be `'@babel/runtime/helpers/esm/objectWithoutProperties.js'` instead.
We could also try using `@babel/preset-react` instead of `babel-preset-react-app` like `core` used before, but I'm not sure if that will change much.
=> Fix core by not using absolute runtime in babel

products/jbrowse-react-circular-genome-view/package.json, products/jbrowse-react-linear-genome-view/package.json
Fixes the name of the "module" build in the React linear and circular views. It looks like webpack might silently fall back to "main" if it doesn't find module, so that's probably why we've never noticed this before.
Noted in https://github.com/GMOD/jbrowse-components/issues/2617#issuecomment-1014374339
=> Fix "module" of embedded React views

website/docs/pag2022_synteny_visualization.md, website/sidebars.json, website/src/pages/demos.mdx
Links to the PAG2022 tutorial from our demos page and adds a page for PAG2022 in our "course archive" in the sidebar which links out to the gmod.org tutorial
=> Add link to PAG 2022 youtube tutorial on demos page and course archive

package.json, yarn.lock
after observing that hot reload wasn't working, I also noticed that it correlated with this error in the dev console for "process is not defined"
googling stackoverflow for this turned up
https://stackoverflow.com/questions/70357360/process-is-not-defined-on-hot-reload/70402397
adding this resoluton to the root package.json for react-error-overlay fixed it for me
fixes #2656
=> Fix hot reload using yarn resolution on react-error-overlay

plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
Before
After
This is especially nice for larger SVs, you can mentally get a little picture of the length of a deletion
Note it also labels this for smaller variants
before
after
can compare to IGV, which does not label it for smaller variants, but does for larger ones. they also use a different style where they draw a thin line where the deletions are, sort of similar to the splice notation
=> Draw deletion width

plugins/svg/src/SvgFeatureRenderer/components/util.ts
@cmdcolin This is related to #2509. The issue is that in the current code, extraGlyphs are only considered when the feature has subfeatures. I think that's incorrect, and we should be testing/applying the custom glyph only if the feature lacks subfeatures.
=> custom glyphs should be applied to features without subfeatures

products/jbrowse-web/src/Loader.tsx, products/jbrowse-web/src/SessionLoader.ts
This is an add-on to #2165 
Allows saying &sessionTracks=[...array of track configs here...]
example
http://localhost:3000/?config=test_data/volvox/config.json&loc=ctgA:6000-7000&assembly=volvox&tracks=gff3tabix_genes,volvox_filtered_vcf,volvox_microarray,volvox_cram,url_track&sessionTracks=[{"type":"FeatureTrack","trackId":"url_track","name":"Test","assemblyNames":["volvox"],"adapter":{"type":"FromConfigAdapter","features":[{"uniqueId":"one","refName":"ctgA","start":190,"end":191,"type":"foo","score":200,"name":"Boris","note":"note for boris"},{"uniqueId":"two","refName":"ctgA","start":191,"end":192,"type":"bar","score":20,"name":"Theresa","note":"note for theresa"},{"uniqueId":"three","refName":"ctgA","start":210,"end":211,"type":"baz","score":300,"name":"Nigel","note":"note for …
=> Add session tracks via url using session spec type URLs

website/docs/faq.md, website/docs/urlparams.md, website/sidebars.json
Fixes #2661
Adds a specialized page called "URL query params API" (does not really fit directly in dev, config, or user guide, so gave it it's own page)
This covers all the details of the query param API that is available right now
=> Add urlparams docs

plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx, plugins/dotplot-view/src/PAFAdapter/PAFAdapter.ts, plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx
This is a small fix that allows loading mashmap files. The mashmap paf are space separated rather than tab separated. I assume that if a file does not have any tabs, it is a mashmap paf
=> Add mashmap PAF support

plugins/wiggle/src/DensityRenderer/index.ts, plugins/wiggle/src/LinearWiggleDisplay/components/SetColorDialog.tsx, plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx, plugins/wiggle/src/util.ts
Add ability to set the "plus and minus colors"  in the wiggle dialog
Fixes #1818 
Also fixes #2621 (the renderProps override of the config colors passed e.g. posColor:undefined would override whatever setting was in the configBlog that is spread on the renderProps)
=> Fix ability to change colors on wiggle track using the config

products/jbrowse-desktop/src/OpenSequenceDialog.tsx
I found if I pasted an incomplete assembly in the "Open sequence" dialog (e.g. just the url, and no assembly name) then it would allow me to hit submit but the assembly would not be added. This adds an error if no assembly was added (confs array is empty)
=> Improve error handling on jbrowse desktop open sequence dialog

packages/core/util/index.ts, plugins/config/src/RefNameAliasAdapter/RefNameAliasAdapter.ts, plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx, plugins/linear-comparative-view/src/LinearComparativeDisplay/index.ts, plugins/linear-comparative-view/src/LinearComparativeView/components/Header.tsx, plugins/linear-comparative-view/src/LinearComparativeView/components/LinearComparativeView.tsx, plugins/linear-comparative-view/src/LinearComparativeView/model.ts, plugins/linear-comparative-view/src/LinearSyntenyDisplay/index.ts, plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx, plugins/linear-comparative-view/src/util.ts, products/jbrowse-desktop/src/OpenSequenceDialog.tsx
- Adds high resolution /retina rendering to the linear synteny view
- Adds resize handle to the linear synteny view
- Adds optimization to the linear synteny view similar to what was done for dotplot: bypass using the observables and operate on snapshot
- Avoid creating a syntenytrack from import form on dotplot/synteny view if none was specified
=> Optimizations and usability improvements to synteny view

products/jbrowse-cli/src/commands/add-assembly.ts, products/jbrowse-cli/src/commands/add-track.ts
This fixes https://github.com/GMOD/jbrowse-components/issues/2685
This always creates a resolved, absolute path for a symlink
This makes the change for both add-assembly and add-track
=> Use path.resolve to fix --load symlink in jbrowse CLI

website/release_announcement_drafts/v1.6.0.md
current yarn changelog
```
* `core`
* [#2679](https://github.com/GMOD/jbrowse-components/pull/2679) Optimizations and usability improvements to synteny view ([@cmdcolin](https://github.com/cmdcolin))
* [#2677](https://github.com/GMOD/jbrowse-components/pull/2677) Save user settings from LGV ([@cmdcolin](https://github.com/cmdcolin))
* [#2571](https://github.com/GMOD/jbrowse-components/pull/2571) Add stats estimation to JB2 ([@cmdcolin](https://github.com/cmdcolin))
* [#2666](https://github.com/GMOD/jbrowse-components/pull/2666) Add option to display curved lines and to square the dotplot and synteny views ([@cmdcolin](https://github.com/cmdcolin))
* [#2672](https://github.com/GMOD/jbrowse-components/pull/2672) Optimize dot plot rendering ([@cmdcolin](https://github.com/cmdcolin))
* Other …
```
=> v1.6.0 release announcement

packages/core/util/tracks.ts, plugins/alignments/src/index.ts, plugins/bed/src/index.ts, plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.tsx, plugins/gff3/src/index.ts, plugins/gtf/src/index.ts, plugins/hic/src/index.ts, plugins/sequence/src/index.ts, plugins/variants/src/index.ts, plugins/wiggle/src/index.ts
xref https://github.com/GMOD/jbrowse-plugin-apollo/issues/38
Makes the regex less specific, so that if adapterHint is GtfAdapter and it visits VcfAdapter's Core-guessAdapterType, the regex doesn't say that it is a VcfAdapter.
=> Fix adapterType dropdown in add track widget

packages/core/rpc/BaseRpcDriver.test.ts, plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, products/jbrowse-web/src/tests/Alignments.test.js
Currently the track menu can be disabled in embedded mode if there are no "items" but there should always be at least an "About track" dialog
=> Fix disabled state on the linear genome view track labels dropdown menu

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/admin-server.ts
By default `app.use(express.json())` enforces a limit of 100kb (see [here](https://expressjs.com/en/api.html#express.json)) on request body size. For reference, our config_demo.json human config is 132kb. This PR increases the limit to an (admittedly arbitrary) 25mb.
Problem with limit originally noted in https://github.com/GMOD/jbrowse-components/discussions/2703
=> Increase admin-server payload limit

packages/core/util/io/index.ts, plugins/authentication/src/OAuthModel/model.tsx
This fixes the ability to use authenticated files in an assembly. They differ from other files because the adapter is created on the main thread and not on the webworker, so they don't go through the RPC steps that handle authentication. Basically the logic now is that if there is a UriLocation that doesn't have any auth information, and it can find a root model, it checks if any of the configured internet accounts handle that URI.
Also fixes a small bug in the OAuth model I found while testing this change using a Dropbox file.
=> Fix ability to use authenticated assembly files

website/docs/faq.md, website/docs/quickstart_web.md, website/docs/superquickstart_web.md
I think an oclif update now recommend node 12. Can install under node 10 but it warns a lot
Example of use under node 10
```
❯❯ jbrowse admin-server
WARNING
WARNING Node version must be >=12.0.0 to use this CLI
WARNING Current node version: 10.24.1
WARNING
┌─────────────────────────────────────────────────────────────────────┐
│                                                                     │
│   Now serving JBrowse                                               │
│   Navigate to the below URL to configure                            │
│                                                                     │
│   - Local:            http://localhost:9090?adminKey=b9742c57bc     │
│   - On Your Network:  http://192.168.0.7:9090?adminKey=b9742c57bc   │
│ …
```
=> Update to node12 requirement for @jbrowse/cli

packages/core/data_adapters/BaseAdapter.ts, plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/2694
I am not able to reproduce this locally, but the condition seen in the code seems like it would only happen if an empty array was passed to the estimateRegionsStats 
I wait until there is a region from staticBlocks and also throw a hard error if empty
=> Avoid uninitialized state during stats estimation

products/jbrowse-cli/src/commands/add-track.ts
I'm not sure if this makes the message too long, but I thought I'd see what people think. This adds the ID to the output when running `add-track`, so that instead of
```
Added track "volvox.sort.gff3" to ./config.json
```
it would look like
```
Added track "volvox.sort.gff3" with ID "volvox.sort.gff3" to ./config.json
```
The hope is that this will reduce confusion in cases like https://github.com/GMOD/jbrowse-components/issues/2704
=> Add ID to add-track log message

products/jbrowse-desktop/public/electron.ts
May help with #2720 where if it fails to parse recent_sessions.json, it returns an empty array
=> Make jbrowse desktop more robust to errors when reading recent sessions file

products/jbrowse-img/package.json
This is required, unless we want to add a AbortController poly/ponyfill 
On node 12 and node 14 it produces this error
```
jb2export --bigwig src/jbrowse-components/test_data/volvox/volvox-sorted.bam.coverage.bw --loc ctgA:1000-2000 --fasta src/jbrowse-components/test_data/volvox/volvox.fa
(node:1965899) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
at _callee$ (/home/cdiesh/.nvm/versions/node/v12.22.7/lib/node_modules/@jbrowse/img/node_modules/@jbrowse/core/util/index.js:881:15)
at tryCatch (/home/cdiesh/.nvm/versions/node/v12.22.7/lib/node_modules/@jbrowse/img/node_modules/regenerator-runtime/runtime.js:63:40)
at Generator.invoke [as _invoke] (/home/cdiesh/.nvm/versions/node/v12.22.7/lib/node_modules/@jbrowse/img/node_modules/regenerator-runtime/runtime …
```
=> Add engines 16 to @jbrowse/img

products/jbrowse-cli/src/types/gff3Adapter.ts, products/jbrowse-cli/src/types/gtfAdapter.ts, products/jbrowse-cli/src/types/vcfAdapter.ts
Currently the code explicitly checks for .gz, but this helps allow .gz extensions. It could be more advanced and detect a gzip encoding regardless of file extension but this may help
Fixes #2718
=> Handle .bgz file extension for text-index

products/jbrowse-cli/package.json, products/jbrowse-cli/src/types/common.ts, products/jbrowse-cli/src/types/gff3Adapter.ts, products/jbrowse-cli/src/types/gtfAdapter.ts, products/jbrowse-cli/src/types/vcfAdapter.ts, products/jbrowse-cli/src/util.ts, products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, products/jbrowse-desktop/public/generateFastaIndex.ts, yarn.lock
This tries to simplify the codebase somewhat, removing the `follow-redirects` dependency
Motivation was that the latest patch update to `follow-redirects` produced weird typescript errors after a simple `yarn upgrade`
```
yarn tsc                                             main ⬆ ✭ ✱
yarn run v1.22.17
$ /home/cdiesh/src/jbrowse-components/node_modules/.bin/tsc
products/jbrowse-cli/src/types/common.ts:15:13 - error TS2349: This expression is not callable.
Each member of the union type '{ (options: string | URL | (RequestOptions & FollowOptions<RequestOptions>), callback?: ((res: IncomingMessage & FollowResponse) => void) | undefined): RedirectableRequest<...>; (url: string | URL, options: RequestOptions & FollowOptions<...>, callback?: ((res: IncomingMessage & FollowResponse) => void) | …
```
=> Use node fetch instead of follow-redirects in cli

plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
Fixes #2737 
The sashimi arc drawing was using feature.get('tags').XS as a fallback for CRAM (CRAM does not use feature.get('XS')), but it didn't take into account that this would be undefined in BAM files. The getTag helper function already helps with this
=> Add better catch for XS and TS tag detection from CRAM

plugins/dotplot-view/package.json, plugins/dotplot-view/src/DotplotDisplay/components/DotplotDisplay.tsx, plugins/dotplot-view/src/DotplotDisplay/index.ts, plugins/dotplot-view/src/DotplotReadVsRef.ts, plugins/dotplot-view/src/DotplotRenderer/index.ts, plugins/dotplot-view/src/DotplotView/components/Axes.tsx, plugins/dotplot-view/src/DotplotView/index.ts, plugins/dotplot-view/src/PAFAdapter/PAFAdapter.test.ts, plugins/dotplot-view/src/PAFAdapter/PAFAdapter.ts, plugins/dotplot-view/src/PAFAdapter/index.ts, plugins/dotplot-view/src/ServerSideRenderedBlockContent.tsx, plugins/dotplot-view/src/index.ts, plugins/dotplot-view/src/util.ts, products/jbrowse-predefined-sessions/sessions.json, products/jbrowse-web/src/tests/Dotplot.test.js, products/jbrowse-web/src/tests/Loader.test.tsx, test_data/config_demo.json
This is a small refactoring to the dotplot view that moves code out of plugins/dotplot/src/index.ts into other source files. The lengthy plugin registration can get bogged down with a lot of code so this splits it into multiple files (similar thing was done in plugins/alignments recently)
It also makes sure to display the error state in dotplot views and allows loading gzipped PAF files
=> Add better display of error state in dotplot view and load gzipped PAF files
