packages/jbrowse-web/src/RootModelFactory.js, packages/jbrowse-web/src/index.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/model.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/model.test.js, packages/jbrowse-web/src/util/io/localFile.js, packages/jbrowse-web/test/root.snap.1.json
I had to update the track model to be a map instead of an array so that the track selector can more easily interact with the tracks. I also added the ability to show and hide tracks. I still haven't added the actual track selector yet, but now that the track model is updated it will be a lot easier.
=> Change track model from array to map, add ability to show and hide tracks

packages/jbrowse-web/src/RootModelFactory.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.js, packages/jbrowse-web/src/plugins/LinearGenomeView/components/LinearGenomeView.test.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/model.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/model.test.js, packages/jbrowse-web/src/ui/App.js, packages/jbrowse-web/src/ui/App.test.js, packages/jbrowse-web/src/ui/DrawerResizeHandle.js, packages/jbrowse-web/src/ui/Theme.js, packages/jbrowse-web/src/ui/__snapshots__/App.test.js.snap, packages/jbrowse-web/test/root.snap.1.json
=> Manage drawer and track widths

packages/jbrowse-web/src/serviceWorker.js, packages/jbrowse-web/src/workerPolyfill.js
Pulled in latest service worker code from create-react-app. Also added "location" to the web worker polyfill.
Resolves #9
=> Fix service and web worker problems in production build

README.md
=> Add more dependency management info to README

packages/jbrowse-web/src/configuration/README.md, packages/jbrowse-web/src/configuration/__snapshots__/configurationLayer.test.js.snap, packages/jbrowse-web/src/configuration/configurationLayer.js, packages/jbrowse-web/src/configuration/configurationLayer.test.js, packages/jbrowse-web/src/configuration/configurationSchema.js, packages/jbrowse-web/src/configuration/configurationSlot.js, packages/jbrowse-web/src/configuration/index.js, packages/jbrowse-web/src/plugins/BamAdapter/__snapshots__/index.test.js.snap, packages/jbrowse-web/src/plugins/BamAdapter/index.test.js, packages/jbrowse-web/src/plugins/BigWigAdapter/index.test.js, packages/jbrowse-web/src/plugins/FromConfigAdapter/__snapshots__/index.test.js.snap, packages/jbrowse-web/src/plugins/FromConfigAdapter/index.test.js, packages/jbrowse-web/src/plugins/IndexedFastaAdapter/index.test.js, packages/jbrowse-web/src/plugins/TwoBitAdapter/index.test.js
=> 220 config layers

packages/core/package.json, packages/core/util/index.ts, packages/core/util/io/rangeFetcher.js, packages/jbrowse-web/package.json, packages/jbrowse-web/src/plugins/LinearGenomeView/models/baseTrack.js, packages/jbrowse-web/src/plugins/LinearGenomeView/models/serverSideRenderedBlock.js, yarn.lock
This is pending results of https://github.com/rbuels/http-range-fetcher/pull/4
=> Fix aborting code after http-range-fetcher merge

packages/jbrowse-web/src/ui/DrawerResizeHandle.js
This adds position: fixed and removes the left: from the resize handle. This appears to give good behavior for a fullscreen app.
=> Add position fixed for the resize handle.

packages/alignments/src/PileupRenderer/PileupRenderer.ts, packages/alignments/src/PileupRenderer/configSchema.js, packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/core/pluggableElementTypes/renderers/BoxRendererType.js, packages/core/rpc/RpcManager.js, packages/core/util/layouts/GranularRectLayout.js, packages/jbrowse-web/public/test_data/config_integration_test.json, packages/jbrowse-web/public/test_data/config_volvox.json, packages/jbrowse-web/src/JBrowse.test.js, packages/jbrowse-web/src/render.test.js, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.js, packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
This proposes having a maxHeightReached state that is is on the core BlockState
This allows a generic rendering of this message across different renderings
The message doesn't display correctly along the bottom of the rendered data currently, sort of because I can't figure out how to get things like the ssr-container display:block or something like this, but this is a template
=> Pileup max height

packages/config/src/ConfigurationEditorDrawerWidget/components/CallbackEditor.js, packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js
This proposes fixes for callback editing to address issue #393 
I made these changes
1) make the CallbackEditor use react hooks
2) only update the callback if it passes a baseline stringToFeature test
3) remove the try/catch from the SvgFeatureRendering loop
Together, this appears to address some basic callback concerns
=> Callback editor fixes

packages/core/util/index.ts, packages/linear-genome-view/src/BasicTrack/baseTrackModel.tsx, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, packages/linear-genome-view/src/LinearGenomeView/index.ts
This attempts to add some typescript to our state models which are made by factory functions
A reference for factory functions and MST https://spectrum.chat/mobx-state-tree/general/factory-pattern-with-mst~0496904e-d779-4096-9e88-a8ed642015e2
key idea is that I can just get `ReturnType<typeof stateModelFactory>` and that works pretty well :)
Using `this` vs `self` in the views/actions is to refer to things within that block https://github.com/mobxjs/mobx-state-tree#typing-self-in-actions-and-views
=> Typescriptify LinearGenomeView

packages/core/util/tracks.js, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/TrackEntry.js, packages/jbrowse1/src/JBrowse1Connection/jb1ToJb2.ts
As seen in demo with Shihab today
=> Fix unknown/unsupported tracks in JB1 connection

packages/linear-genome-view/src/BasicTrack/blockBasedTrackModel.js, packages/linear-genome-view/src/BasicTrack/components/Block.js, packages/linear-genome-view/src/BasicTrack/components/MarkerBlocks.js, packages/linear-genome-view/src/BasicTrack/components/TrackBlocks.js, packages/linear-genome-view/src/BasicTrack/util/blockTypes.js, packages/linear-genome-view/src/BasicTrack/util/calculateStaticBlocks.js, packages/linear-genome-view/src/LinearGenomeView/components/ScaleBar.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
=> use padding blocks instead of block borders in LGV

packages/jbrowse-web/package.json, packages/jbrowse-web/src/JBrowse.test.js, packages/jbrowse-web/src/__snapshots__/sessionModelFactory.test.js.snap, packages/jbrowse-web/src/sessionModelFactory.js, packages/jbrowse-web/src/sessionModelFactory.test.js, packages/jbrowse-web/src/ui/App.js, yarn.lock
Fixes #523 
Note that the jsdom doesn't appear to "support" this API well, so I use a larger default session width that corresponds to a normal window width and this allows tests to pass
=> Use react-measure instead of react-sizeme

packages/core/ui/App.js, packages/core/ui/DrawerWidget.js, packages/core/ui/StartScreen.js, packages/core/ui/StartScreen.tsx, packages/core/ui/index.ts, packages/core/ui/theme.js, packages/jbrowse-desktop/public/preload.js, packages/jbrowse-desktop/src/JBrowse.js, packages/jbrowse-web/src/JBrowse.js
This modularizes some components of the start screen. I think in general, if we see code like "DialogComponent= ..." it suggests that this should be a separate component
I suppose this is debateable refactoring but I just some think of these components with many conditions and sub functions as needing breaking up
=> Refactor start screen dialog components to be separate

packages/breakpoint-split-view/src/components/Header.tsx, packages/breakpoint-split-view/src/components/__snapshots__/BreakpointSplitView.test.js.snap, packages/circular-view/src/CircularView/components/CircularView.js, packages/config/src/ConfigurationEditorDrawerWidget/components/SlotEditor.js, packages/config/src/ConfigurationEditorDrawerWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, packages/core/ui/DevTools.js, packages/core/ui/DevTools/SessionMenu.js, packages/core/ui/DevTools/ViewMenu.js, packages/core/ui/StartScreen.js, packages/core/ui/theme.js, packages/data-management/src/AddConnectionDrawerWidget/components/ConnectionTypeSelect.tsx, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/HierarchicalTrackSelector.js, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/TrackEntry.js, packages/data-management/src/HierarchicalTrackSelectorDrawerWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap, packages/linear-genome-view/src/BasicTrack/components/TrackControls.js, packages/linear-genome-view/src/LinearGenomeView/components/BlockError.js, packages/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx, packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.js, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/menus/src/ImportConfigurationDrawerWidget/components/ImportConfigurationDrawerWidget.js, packages/menus/src/MainMenuBar/components/DropDownMenu.js, packages/menus/src/MainMenuBar/components/__snapshots__/DropDownMenu.test.js.snap, packages/menus/src/SessionManager/components/SessionManager.js, packages/menus/src/SessionManager/components/__snapshots__/SessionManager.test.js.snap, packages/spreadsheet-view/src/SpreadsheetView/components/Spreadsheet.js, packages/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetView.js, packages/sv-inspector/src/SvInspectorView/components/SvInspectorView.js, packages/trackhub-registry/src/trackhub-registry/HubDetails.js
Thanks @peterkxie for noticing that disabled IconButtons were not getting grayed out. This fixes that by moving the coloring from Icon to IconButton.
=> Fix IconButton not showing disabled coloring

packages/jbrowse-web/package.json, packages/jbrowse-web/src/corePlugins.js, packages/jbrowse-web/src/sessionModelFactory.ts, test_data/config.json, test_data/config_in_dev.json
also removes menu items in config.json files so it will use hardcoded ones.
fixes #732
=> enable sv inspector in jbweb

packages/core/ui/FactoryResetDialog.tsx, packages/core/ui/FatalErrorDialog.tsx, packages/core/ui/StartScreen.tsx, packages/jbrowse-desktop/src/JBrowse.js, packages/jbrowse-desktop/src/factoryReset.ts, packages/jbrowse-web/src/JBrowse.js
this refactors the fatal error dialog to remove the actual reset code from core, and adds reset code for jbweb
=> add jbweb factory reset

.travis.yml
This adds a continuous deployment to amazon s3 via travis-CI
=> Add continuous deploy to s3

packages/core/ui/PrerenderedCanvas.js, packages/core/util/offscreenCanvasPonyfill.js, packages/jbrowse-web/src/index.js
This is a template for an offscreen canvas ponyfill that can run in firefox
Renders the alignments track pretty ok right now :)
Maybe slightly WIP but feedback welcome
=> Add a ponyfill offscreen canvas

packages/config/src/ConfigurationEditorDrawerWidget/components/ConfigurationEditor.js, packages/config/src/ConfigurationEditorDrawerWidget/components/SlotEditor.js, packages/config/src/ConfigurationEditorDrawerWidget/model.js
This fixes #804 and shouldn't regress on #772
=> Fix config editor text entry focus

packages/linear-genome-view/src/BasicTrack/util/serverSideRenderedBlock.ts
=> Handle an unhandled promise from a freeResourcesInClient RPC call

.eslintrc.json, package.json, packages/alignments/src/BamAdapter/BamSlightlyLazyFeature.ts, packages/breakpoint-split-view/src/BreakpointSplitView.ts, packages/circular-view/src/CircularView/components/Ruler.js, packages/core/rpc/BaseRpcDriver.ts, packages/core/util/functionStrings.js, packages/core/util/index.ts, packages/core/util/layouts/GranularRectLayout.ts, packages/data-management/src/ucsc-trackhub/model.js, packages/data-management/src/ucsc-trackhub/ucscTrackHub.js, packages/jbrowse-desktop/src/assemblyConfigSchemas.js, packages/jbrowse-web/src/assemblyConfigSchemas.js, packages/jbrowse1/src/JBrowse1Connection/jb1ToJb2.ts, packages/jbrowse1/src/JBrowse1Connection/model.js, packages/linear-genome-view/src/LinearGenomeView/components/Ruler.tsx, packages/trackhub-registry/src/trackhub-registry/model.js, packages/variants/src/VcfTabixAdapter/VcfFeature.ts, packages/wiggle/src/XYPlotRenderer/XYPlotRenderer.js, yarn.lock
There is a default to say arrowParens: true in 2.0 and while interesting reasoning, I think it's better we keep it off
=> Use prettier 2.0 for code formatting

packages/core/ui/Drawer.js, packages/core/ui/theme.js
This fixes a problem where the drawer sometimes had a horizontal scroll when nothing was overflowing.
=> Fix drawer horizontal overflow

packages/alignments/src/AlignmentsTrack/components/AlignmentsTrack.tsx
Made on the road via GitHub UI...lol
=> Remove manually set css height, fixes #863

packages/breakpoint-split-view/src/components/__snapshots__/BreakpointSplitView.test.js.snap, packages/jbrowse-web/src/JBrowse.test.js, packages/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx, packages/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap, packages/linear-genome-view/src/LinearGenomeView/index.test.ts, packages/linear-genome-view/src/LinearGenomeView/index.ts
This aims to remove allowedBpPerPx
It also makes maxBpPerPx depend on the totalBp of the displayed regions
=> Remove allowedBpPerPx

packages/core/pluggableElementTypes/RpcMethodType.ts, packages/core/rpc/coreRpcMethods.ts, packages/wiggle/src/WiggleTrack/rpcMethods.ts
Adds refName renaming to WiggleGetMultiRegionStats
Fixes #952
=> WiggleGetMultiRegionStats refName renaming

packages/dotplot-view/src/DotplotView/components/DotplotView.tsx
This works by checking if there are going to be colliding labels, and if there are, it starts hiding labels of the smallest blocks first until there are no more collisions. This seems to successfully label "more important" (i.e. bigger) regions over smaller ones
Resolves #921
=> Improve dotplot label collision avoidance

packages/core/assemblyManager/assemblyManager.ts
This uses a reaction instead of an autorun to watch the assembly configs in the assembly manager. This should avoid it looping infinitely when you add an assembly config.
=> Avoid loop in loading assemblies

packages/jbrowse-desktop/src/jbrowseModel.js, packages/jbrowse-web/src/JBrowse.js, packages/jbrowse-web/src/JBrowse.test.js, packages/jbrowse-web/src/Loader.tsx, packages/jbrowse-web/src/jbrowseModel.js, test_data/breakpoint/config.json, test_data/config.json, test_data/config_chrom_sizes_test.json, test_data/config_dotplot.json, test_data/config_gdc_test.json, test_data/config_longread.json, test_data/config_longread_linear.json, test_data/config_synteny_grape_peach.json
This applies the "useLocalStorage" and "useUrlSession" to loading as well as persisting sessions, also renames "updateUrl" to "useUrlSession"
=> Check config for session loading

packages/jbrowse-web/src/JBrowse.js, packages/jbrowse-web/src/Loader.tsx
=> Update URL without useState

packages/jbrowse-web/src/JBrowse.js
@cmdcolin mentioned that while the throttle on the URL update made it so there was sometimes some scroll jank if you were continuously scrolling, and I started noticing it as well. This makes it so the URL update is debounced, so e.g. it will only update when you are done scrolling.
There was similar behavior to this before #976, but it had to be removed since useDebounce was causing errors. This adds a debounce function that is not a hook, since updating the URL is not a stateful update.
=> Make URL update debounce instead of throttle

packages/linear-genome-view/src/BasicTrack/components/ServerSideRenderedBlockContent.tsx
This is a low CPU loading modification
Could look at actual spinners too but this seems like it is not too bad
Note the removal of textAlign center because the text changing length causes the center to move so it is simply left aligned now
=> Low CPU usage loading animation

packages/alignments/src/PileupRenderer/PileupRenderer.ts
=> Add fix for softclipping glyph expansion

packages/svg/src/SvgFeatureRenderer/components/Box.js, packages/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js, packages/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.js.snap
proposed fix for minimum width warnings, what do you think about this @cmdcolin 
enforces minimum 1px width on all rects.
=> enforce a 1px minimum width on svg boxes

packages/circular-view/src/ChordTrack/components/Loading.js, packages/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
=> Restore scss loading to fix sequence track

packages/jbrowse-cli/package.json, packages/jbrowse-cli/src/commands/create.ts, packages/jbrowse-cli/src/commands/upgrade.ts, packages/jbrowse-cli/tsconfig.json, yarn.lock
This is a proposal to use extract-zip to download the jbrowse zip
https://github.com/maxogden/extract-zip/blob/master/index.js
=> Simplify command unzip

packages/core/util/tracks.ts, packages/jbrowse-cli/README.md, packages/jbrowse-cli/src/commands/add-assembly.ts, packages/jbrowse-cli/src/commands/add-track.ts
This fixes some bugs and adds some features to the CLI. If we could get this published tonight it would help the embedding classes tomorrow a lot.
=> Fixes for CLI

.travis.yml
This uploads a built zip file to each branch to s3
Also fixes multiple provider deploy yaml syntax
=> Upload built versions zip file to s3

packages/jbrowse-cli/src/commands/create.test.ts, packages/jbrowse-cli/src/commands/create.ts, packages/jbrowse-cli/src/commands/upgrade.ts, packages/jbrowse-cli/src/testUtil.ts
Appears to fix error #1083
Not sure precisely why but the logic is a standard unzip. If we require custom unzipping logic and this is invalid let me know
=> Fix EISDIR error running upgrade

packages/core/util/types/index.ts, packages/jbrowse-desktop/src/Loader.tsx, packages/jbrowse-desktop/src/rootModel.ts, packages/jbrowse-desktop/src/sessionModelFactory.ts, packages/jbrowse-web/src/Loader.tsx, packages/jbrowse-web/src/rootModel.ts, packages/jbrowse-web/src/sessionModelFactory.ts, packages/menus/src/AboutDrawerWidget/components/AboutDrawerWidget.tsx, packages/menus/src/AboutDrawerWidget/components/__snapshots__/AboutDrawerWidget.test.js.snap, packages/menus/src/HelpDrawerWidget/components/HelpDrawerWidget.tsx, packages/menus/src/HelpDrawerWidget/components/__snapshots__/HelpDrawerWidget.test.js.snap
=> Add package version number to drawers

.eslintrc.json, .travis.yml, package.json, packages/jbrowse-cli/src/commands/add-assembly.test.ts
I think that failing the build on a prettier style failure is maybe too drastic, and something that will be cleaned up by future people that see warnings, etc.
This proposes having less total build failures from style checks
=> Don't fail the build on minor style issues

packages/core/rpc/BaseRpcDriver.test.ts, packages/core/rpc/BaseRpcDriver.ts
This involves a bit of mocking but tries to test some basic BaseRpcDriver functionality
However, this actually reveals an 
```
(node:3482423) UnhandledPromiseRejectionWarning: Error: operation timed out, worker process stopped responding
at emitUnhandledRejectionWarning (internal/process/promises.js:170:15)
at processPromiseRejections (internal/process/promises.js:247:11)
at processTicksAndRejections (internal/process/task_queues.js:94:32)
```
Not exactly sure why
=> Unit test BaseRpcDriver functionality

packages/alignments/src/AlignmentsTrack/model.ts, packages/alignments/src/PileupTrack/model.ts, packages/alignments/src/SNPCoverageTrack/model.ts, packages/breakpoint-split-view/src/model.ts, packages/core/BaseViewModel.ts, packages/core/ui/DropDownMenu.tsx, packages/core/ui/Menu.tsx, packages/core/ui/ViewContainer.tsx, packages/core/util/types/index.ts, packages/dotplot-view/src/DotplotView/components/DotplotView.tsx, packages/dotplot-view/src/DotplotView/model.ts, packages/jbrowse-desktop/src/rootModel.ts, packages/jbrowse-web/src/rootModel.ts, packages/linear-comparative-view/src/LinearComparativeView/model.ts, packages/linear-genome-view/src/BasicTrack/baseTrackModel.tsx, packages/linear-genome-view/src/BasicTrack/blockBasedTrackModel.ts, packages/linear-genome-view/src/BasicTrack/components/BlockBasedTrack.tsx, packages/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx, packages/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, packages/linear-genome-view/src/LinearGenomeView/index.ts, packages/spreadsheet-view/src/SpreadsheetView/components/ColumnMenu.js, packages/spreadsheet-view/src/SpreadsheetView/components/RowMenu.tsx, packages/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.ts, packages/sv-inspector/src/SvInspectorView/models/SvInspectorView.js
As requested [here](https://github.com/GMOD/jbrowse-components/pull/1129#issuecomment-673712510). Seems like probably a more intuitive name.
=> Rename menuOptions to menuItems

packages/linear-genome-view/package.json, packages/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx, packages/linear-genome-view/src/LinearGenomeView/declare.d.ts, yarn.lock
This is an initial result in trying to add zooming with the mouse wheel while holding the ctrl key
I think having this hidden behind the ctrl key modifier keeps vertical scrolling feeling normal, although that does reduce discoverability
Nevertheless, hopefully this could be useful to power users? Feedback welcome
#990
=> Add ctrl+zoom for speedily navigating zoom levels

packages/jbrowse-cli/src/commands/add-connection.test.ts
These tests fail on my local machine unless I add these nocks.
=> Add a couple nocks for tests

packages/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/Text.js
Fixes #1140 
Added a does not equal for good measure
=> Add a equals and does not equal to spreadsheet view

plugins/spreadsheet-view/src/SpreadsheetView/models/ImportWizard.ts
Potentially fixes #1215 
Not the most super generic way to do things but also pretty simple here
=> Parses a star fusion filename

.github/workflows/website.yml, products/website/docs/Makefile, products/website/package.json
This autodeploys the website with a github workflow when a commit uses the phrase "update docs"
Could also just be "^docs" if we use conventional commits
=> Autodeploy website

packages/core/util/types/index.ts, packages/core/util/types/mst.ts, plugins/alignments/src/__snapshots__/index.test.ts.snap, plugins/bed/src/__snapshots__/index.test.js.snap, plugins/filtering/src/__snapshots__/index.test.js.snap, plugins/legacy-jbrowse/src/JBrowse1Connection/types.ts, plugins/legacy-jbrowse/src/__snapshots__/index.test.js.snap, plugins/rdf/src/__snapshots__/index.test.js.snap, plugins/sequence/src/__snapshots__/index.test.js.snap, plugins/variants/src/__snapshots__/index.test.js.snap, plugins/wiggle/src/__snapshots__/index.test.js.snap, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, products/jbrowse-web/src/__snapshots__/rootModel.test.js.snap, products/jbrowse-web/src/jbrowseModel.js
Merge changes for keeping snapshots unmodified
=> 1147 relative urls snapshot processor

packages/core/ui/ViewContainer.tsx, packages/core/util/io/ElectronRemoteFile.ts, packages/core/util/io/index.ts, packages/core/util/tracks.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap, plugins/data-management/src/HierarchicalTrackSelectorWidget/model.js, plugins/legacy-jbrowse/src/JBrowse1Connection/jb1ToJb2.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, products/jbrowse-desktop/src/JBrowse.js, products/jbrowse-desktop/src/jbrowseModel.js, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-web/src/jbrowseModel.js, products/jbrowse-web/src/sessionModelFactory.ts, products/jbrowse-web/src/tests/BasicLinearGenomeView.test.js, products/jbrowse-web/src/tests/CopyAndDelete.test.js, products/jbrowse-web/src/tests/JBrowse.test.js, test_data/breakpoint/config.json, test_data/config_chrom_sizes_test.json, test_data/volvox/connection_test.json
This uses ideas from the session tracks to give desktop the ability to delete and copy tracks
Also addresses #1295 
Note that somehow maybe this PR exaggerated #1295 and then fixed it e.g. before this commit a291322 this branch was painfully slow. Desktop LGV scrolling was actually ok on master...
=> Desktop and adminMode delete and copy track functions

plugins/hic/package.json, plugins/hic/src/HicRenderer/HicRenderer.ts, plugins/hic/src/HicRenderer/configSchema.ts, yarn.lock
This proposes having a baseColor and a colorcallback which uses baseColor by default
It does not obtain a normal simplefeature
The before and after color default color scheme are identical with this change
CC @keiranmraine
=> Better hic coloring

plugins/legacy-jbrowse/src/NCListAdapter/NCListAdapter.ts
=> Create relative url with the URL constructor for nclist

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx, plugins/linear-genome-view/src/LinearGenomeView/index.ts
This tried to speed up the scrolling animation by making the headerbar text e.g. in the search box update less frequently
This is a trick that exists in jbrowse 1 also
=> Coarser update frequency for lgv headerbar

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
This is a bit of refactoring
It removes some internal state of RefNameAutocomplete which gives it a little more predictable behavior, and basically makes it more like a controlled component.
=> Add back the RefNameAutocomplete loading state

plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.js, plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.js
=> Fix add track

plugins/alignments/src/LinearAlignmentsDisplay/models/configSchema.ts, plugins/alignments/src/LinearPileupDisplay/configSchema.ts
=> Add a maxDisplayedBpPerPx for pileup

products/jbrowse-desktop/src/corePlugins.ts
=> Fix the use of filtering display on desktop

products/jbrowse-react-linear-genome-view/README.md, products/jbrowse-react-linear-genome-view/package.json
=> Add missing dep to react-linear-genome-view

plugins/hic/package.json, yarn.lock
=> Update hic-straw to fix error for hic files with many scaffolds

plugins/data-management/src/AssemblyManager/AssemblyAddForm.tsx, plugins/data-management/src/AssemblyManager/AssemblyManager.tsx
Some minor changes to spacing and formatting for the assembly manager GUI. Noticed when working on adding some docs that the default scrollbar made things a bit funky.
=> Admin server GUI enhancements

plugins/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx
=> Take into account offsetX of the rubberband on scalebar zooming

plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
=> Fix overview scale polygon not appearing properly in some cases

scripts/release.sh
Adds checks when running the release script to make sure user is in master branch and user is logged into npm so script can upload packages
=> Add extra checks for release script

packages/core/rpc/BaseRpcDriver.ts, products/jbrowse-web/src/rpc.worker.ts, test_data/config_demo.json
=> Add error reporting on a worker failure

website/docs/developer_guide.md
https://jbrowse.org/jb2/docs/developer_guide/#adding-a-top-level-menu
=> typo in developer guide docs

plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx
=> Fix LGV navigation after a display region change

products/jbrowse-desktop/src/rootModel.ts, products/jbrowse-desktop/src/sessionModelFactory.ts
=> Add sessionAssemblies to jbrowse-desktop for use in linear read-vs-ref comparisons

website/blog/2021-02-22-JBrowseR-release.md, website/src/pages/index.js
This PR:
- Adds a blog post introducing JBrowseR
- Adds a link to JBrowseR from the embedded links list of our site
=> JBrowseR release

products/jbrowse-web/src/Loader.tsx
=> Add warning for JSON session if it contains callbacks

packages/core/pluggableElementTypes/models/BaseTrackModel.ts
=> Adjust rpcSessionId to use the config ID instead of instance ID

plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
This is a quick fix for #1776 
Restores the try {} catch that existed previously in renderBlockData
=> Quick fix for block error

packages/core/assemblyManager/assembly.ts, packages/core/data_adapters/BaseAdapter.ts, packages/core/pluggableElementTypes/models/BaseConnectionModelFactory.js, packages/core/util/index.ts
These are just a few bugfixes I've run into that didn't really fit in any particular PR
=> A few bugfixes

.github/workflows/push.yml, .github/workflows/website.yml, website/package.json, website/yarn.lock
Just to try to stay on top of fast moving docusaurus releases. Requires node 12 now so it is built separately from our main codebase which keeps testing node 10 for now
=> Bump docusaurus version

products/jbrowse-desktop/package.json, products/jbrowse-desktop/src/sessionModelFactory.ts, products/jbrowse-web/package.json, products/jbrowse-web/src/sessionModelFactory.ts, test_data/yeast_synteny/config.json, yarn.lock
=> Snapshot preprocessor to filter out old connectionInstances

packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
The data grid for large lists of data was currently in some nested logic but looked a bit better to separate out into it's own component here
=> Small refactor to make data grid in feature details it's own component

website/src/css/pluginStyles.module.css, website/src/pages/plugin_store.js
This closes #1937 .
Seems like a weird issue with using JSS in docusaurus. I moved the CSS into a module following the docs [here](https://docusaurus.io/docs/styling-layout#css-modules).
=> Fix layout issues for website plugin store

packages/core/data_adapters/BaseAdapter.ts, products/jbrowse-web/src/tests/2.SVInspector.test.js
=> Fix SV inspector circular view not displaying

plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
After methylation tag merger, there was a somewhat weird code that tries to download the region sequence using the sequence adapter. This uses the internals of Bam/Cram adapter to do this
I change it here to make PileupRenderer responsible for calling getAdapter on adapterConfig.sequenceAdapter
=> Fix duplicate requests for BAM file and avoid internal behavior of the data adapters

plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx
=> Make tracks added using the add track widget a session track if not in adminMode

website/src/pages/index.js
This proposes adding @jbrowse/img to the homepage, helps add some awareness perhaps
It adds a new section called CLI since I'm not sure it fits in the "Embedded" section
=> Add @jbrowse/img to homepage

website/release_announcement_drafts/v1.3.1.md
Here is a draft for the next release, tentatively labeled v1.3.1
```
yarn run v1.22.10
* `core`
* [#2094](https://github.com/GMOD/jbrowse-components/pull/2094) More usage of typography to improve consistent text styling ([@cmdcolin](https://github.com/cmdcolin))
* [#2068](https://github.com/GMOD/jbrowse-components/pull/2068) Add non-indexed and plaintext VCF Adapter to variants plugin ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#2067](https://github.com/GMOD/jbrowse-components/pull/2067) Better error message if a file location has an empty string ([@garrettjstevens](https://github.com/garrettjstevens))
* [#2060](https://github.com/GMOD/jbrowse-components/pull/2060) Improve performance with large numbers of reference sequences by using MST …
```
=> Add draft release notes for v1.3.1

products/jbrowse-web/src/Loader.tsx
This is a basic fix that could help address #2136 
A proper fix may be a bit more advanced
=> Catch localStorage setItem fail

website/release_announcement_drafts/v1.3.3.md
```
* `core`
* [#2141](https://github.com/GMOD/jbrowse-components/pull/2141) Update to @material-ui/core@4.12.2 ([@cmdcolin](https://github.com/cmdcolin))
* [#2126](https://github.com/GMOD/jbrowse-components/pull/2126) Add plain VCF adapter recognition to guessAdapter ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#2157](https://github.com/GMOD/jbrowse-components/pull/2157) Fix rendering of negative strand alignment modifications/methylation ([@cmdcolin](https://github.com/cmdcolin))
* [#2131](https://github.com/GMOD/jbrowse-components/pull/2131) Fix missing mouseovers in some cases in pileup/svg tracks ([@cmdcolin](https://github.com/cmdcolin))
* [#2128](https://github.com/GMOD/jbrowse-components/pull/2128) Fix using the "Color by modifications" setting on files …
```
=> Create draft for v1.3.3

products/jbrowse-desktop/src/rootModel.ts
=> Add rootModel setError on jbrowse-desktop

packages/core/package.json, plugins/grid-bookmark/package.json, plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx, plugins/variants/package.json, products/jbrowse-desktop/package.json, products/jbrowse-web/package.json, yarn.lock
=> Fix bookmark widget crashing on clicking away from cell

plugins/trix/package.json, products/jbrowse-react-linear-genome-view/package.json
Would probably want to re-release as v1.4.1
=> Publish @jbrowse/plugin-trix and add as dependency to @jbrowse/react-linear-genome-view

packages/core/TextSearch/BaseResults.test.ts, packages/core/TextSearch/BaseResults.ts, plugins/linear-genome-view/src/LinearGenomeView/components/Header.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
Fixes #2370 
As @teresam856 notes, this particular conditional in handleSelectedRegion is similar to what existed in earlier text search branch results
=> Check if user input is a refName before querying the text search manager

products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, products/jbrowse-desktop/public/generateFastaIndex.ts, yarn.lock
Seemed prudent to add a little testing of the code and so the logic is moved to a tiny npm package here https://github.com/GMOD/faidx-js
=> Move fasta indexing logic to @gmod/faidx

plugins/linear-comparative-view/src/index.tsx
=> Fix [object Window] issue in alignment read vs reference dialog

plugins/alignments/src/BamAdapter/MismatchParser.test.ts, plugins/alignments/src/BamAdapter/MismatchParser.ts
=> Add fix regarding hts-specs update to Mm tag regarding status skipped bases

products/jbrowse-cli/package.json, products/jbrowse-cli/src/commands/__snapshots__/text-index.test.ts.snap, products/jbrowse-cli/src/commands/add-assembly.test.ts, products/jbrowse-cli/src/commands/add-assembly.ts, products/jbrowse-cli/src/commands/add-connection.test.ts, products/jbrowse-cli/src/commands/admin-server.test.ts, products/jbrowse-cli/src/commands/create.test.ts, products/jbrowse-cli/src/commands/set-default-session.test.ts, products/jbrowse-cli/src/commands/text-index.test.ts, products/jbrowse-cli/src/commands/upgrade.test.ts, yarn.lock
Fixes #2588 
I worked with author of external-sorting package to help resolve this https://github.com/ldubos/external-sorting/issues/10
I am hammering the test suite (running 1000's of times) to try to reproduce any failure but I think the update fixed it
=> Fix occasional failures observed from running text-index command

plugins/trix/package.json, plugins/trix/src/TrixTextSearchAdapter/TrixTextSearchAdapter.ts, yarn.lock
This will incorporate a refactoring to @gmod/trix to fix an infinite loop bug, and there are a couple refactorings added in the process
Fixes #2592 
Fixes #2317 (by just only querying first word)
Planning on major version bump to @gmod/trix to have slightly new return value format
=> Update @gmod/trix to fix infinite loop bug while searching certain strings

website/release_announcement_drafts/v1.5.2.md
Here is a little draft post for v1.5.2
It's been about a month since to last release, and there are some good features coming along
Changelog
```
* Other
* [#2579](https://github.com/GMOD/jbrowse-components/pull/2579) Add help text and help dialog for the RefNameAutocomplete ([@cmdcolin](https://github.com/cmdcolin))
* [#2553](https://github.com/GMOD/jbrowse-components/pull/2553) Add sashimi-style arcs for RNA-seq type skips on SNPCoverage display ([@cmdcolin](https://github.com/cmdcolin))
* [#2552](https://github.com/GMOD/jbrowse-components/pull/2552) Change border on non-cytoband OverviewScaleBar visible region back to blue and cytoband OverviewScaleBar to a little lighter fill ([@cmdcolin](https://github.com/cmdcolin))
* [#2509](https://github.com/GMOD/jbrowse-components/pull/2509) …
```
=> Release announcement draft v1.5.2

website/release_announcement_drafts/v1.5.4.md
This proposes a draft for v1.5.4
it adds the layout fix for embedded users and a couple other small improvements
```
* Other
* [#2601](https://github.com/GMOD/jbrowse-components/pull/2601) Allow opening multiple sequences from the desktop start screen ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#2623](https://github.com/GMOD/jbrowse-components/pull/2623) Adjust label width on base feature detail to enforce better alignment ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* Other
* [#2612](https://github.com/GMOD/jbrowse-components/pull/2612) Fix ability to remove plugins ([@cmdcolin](https://github.com/cmdcolin))
* [#2622](https://github.com/GMOD/jbrowse-components/pull/2622) Fix GUI color editor rgba string format …
```
=> Release announcement draft v1.5.4

products/jbrowse-react-circular-genome-view/stories/GettingStarted.stories.mdx
* small updates to storybook CGV getting started docs
=> Fix small typo in CGV docs

packages/core/pluggableElementTypes/RpcMethodType.ts, packages/core/pluggableElementTypes/renderers/BoxRendererType.ts, packages/core/pluggableElementTypes/renderers/ServerSideRendererType.tsx, packages/core/util/index.ts, packages/core/util/types/index.ts, plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx, products/jbrowse-web/src/tests/Alignments.test.js
=> Avoid console.warns in tests due to writing to MST nodes that are not alive

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/admin-server.ts
Helps with a comment made in https://github.com/GMOD/jbrowse-components/issues/2708
=> Change --target to --root for jbrowse CLI admin-server

plugins/variants/src/index.ts
=> Use VariantTrack for plaintext VCF type

website/release_announcement_drafts/v1.6.5.md
Would be good to get this published sometime soon I suppose :) good bugfixes especially for the CLI
Changelog
```
yarn run v1.18.0
* [#2736](https://github.com/GMOD/jbrowse-components/pull/2736) Add better display of error state in dotplot view and load gzipped PAF files ([@cmdcolin](https://github.com/cmdcolin))
* [#2705](https://github.com/GMOD/jbrowse-components/pull/2705) Increase admin-server payload limit ([@garrettjstevens](https://github.com/garrettjstevens))
* Other
* [#2738](https://github.com/GMOD/jbrowse-components/pull/2738) Add better catch for XS and TS tag detection from CRAM ([@cmdcolin](https://github.com/cmdcolin))
* [#2733](https://github.com/GMOD/jbrowse-components/pull/2733) Use sparse array for alignments coverage to fix bug viewing large sparse …
```
=> v1.6.5 release announcement

plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts, plugins/wiggle/src/LinearWiggleDisplay/components/Tooltip.tsx
=> Fix the drawing of SNP height when the SNPCoverage track is using log scale

package.json, products/jbrowse-desktop/package.json, yarn.lock
=> Update electron 16->17

website/release_announcement_drafts/v1.6.8.md
```
* Other
* [#2847](https://github.com/GMOD/jbrowse-components/pull/2847) Add option to color all the letters on all the reads to the pileup renderer ([@cmdcolin](https://github.com/cmdcolin))
* [#2849](https://github.com/GMOD/jbrowse-components/pull/2849) Avoid drawing intron subfeatures for gene glyphs ([@cmdcolin](https://github.com/cmdcolin))
* [#2835](https://github.com/GMOD/jbrowse-components/pull/2835) Hide add track and connection menu items when using embedded component ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#2836](https://github.com/GMOD/jbrowse-components/pull/2836) Display low-quality modifications in SNPCoverage renderer for MM tag ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* …
```
=> v1.6.8 release announcement

website/docusaurus.config.json, website/src/pages/download.mdx, website/src/pages/index.js
tweaks wordings on homepage and downloads page, adds the Python stuff to the downloads page
=> tweak wording on homepage and downloads page

plugins/bed/package.json, plugins/trix/package.json, plugins/wiggle/package.json, yarn.lock
=> Bump @gmod/trix to fix prefix size calculation and searching first word in index

demos/jbrowse-react-circular-genome-view-vanillajs/README.md, demos/jbrowse-react-linear-genome-view-vanillajs/README.md, products/jbrowse-img/EXAMPLES.md, products/jbrowse-img/README.md, products/jbrowse-react-circular-genome-view/README.md, products/jbrowse-react-linear-genome-view/README.md, website/package.json, website/yarn.lock
- Adds readme's to the vanillsjs demos
- Updates component npm pages with links to demos
- Small updates to @jbrowse/img readme
- Bump docusaurus version
=> Small doc updates

.github/workflows/push.yml, packages/core/ui/SanitizedHTML.tsx, website/package.json, website/yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/discussions/2982
=> Set target=_blank by default in user HTML links

plugins/config/src/ConfigurationEditorWidget/components/SlotEditor.js, plugins/config/src/ConfigurationEditorWidget/components/StringArrayEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap, plugins/config/src/ConfigurationEditorWidget/index.js, plugins/data-management/src/AddConnectionWidget/components/AddConnectionWidget.test.js
Fixes #2973 
Uses a "Add item" button to add new array elements, and also has "OK" and "Cancel" buttons to confirm adding the element to the array
=> Add string array configuration slot UI improvements

plugins/authentication/src/OAuthModel/model.tsx
I encountered an issue when setting up the oAuth config using [PingFederate](https://www.pingidentity.com/en/pingone/pingfederate.html), but I'm sure other systems behave in a similar fashion.
When the oAuth configuration is invalid (eg. invalid scope) it will return an error as a query parameter when redirecting back to the redirect URI.
The problem with the current code is that if that error is any different then `access_denied` app will swallow it and no error will be displayed anywhere since the oAuth window is automatically closed after the redirect and nothing happens in main window.
I looked for other similar issues, but only found this one: https://github.com/GMOD/jbrowse-components/issues/2742 which might be connected - not sure if [cmdcolin](https://github.com/cmdcolin) was …
=> Add error handling in case of invalid oAuth2 configuration used.

plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
if you are viewing a genome with cytobands, but navigate to a contig/chromosome with no cytobands available, this PR makes it drop back to displaying coordinates (currently displays just an empty box in the place of the cytobands)
=> Display coordinates when no cytoband available

website/release_announcement_drafts/v1.7.11.md
Yarn changelog
```
* `core`
* [#3044](https://github.com/GMOD/jbrowse-components/pull/3044) Remove node-canvas from @jbrowse/core dependencies ([@cmdcolin](https://github.com/cmdcolin))
* [#3041](https://github.com/GMOD/jbrowse-components/pull/3041) Fix ability to search and load data files using lower case refName aliases ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3042](https://github.com/GMOD/jbrowse-components/pull/3042) Add fetch with proxy support to jbrowse CLI ([@cmdcolin](https://github.com/cmdcolin))
* [#3038](https://github.com/GMOD/jbrowse-components/pull/3038) Display coordinates in overview scalebar when no cytoband available ([@cmdcolin](https://github.com/cmdcolin))
* [#3015](https://github.com/GMOD/jbrowse-components/pull/3015) Add plaintext bed support with …
```
=> Add v1.7.11 release announcement

plugins/dotplot-view/src/DotplotView/model.ts
=> Fix crash opening synteny track selector launched from dotplot view

website/docs/api_guide.md, website/docs/developer_guide.md, website/release_announcement_drafts/v2.1.0.md
```
* `core`
* [#3111](https://github.com/GMOD/jbrowse-components/pull/3111) Create undo manager in jbrowse-web and jbrowse-desktop ([@cmdcolin](https://github.com/cmdcolin))
* [#3115](https://github.com/GMOD/jbrowse-components/pull/3115) Add warning when dotplot renders outside of it's boundaries, and create click-and-drag panning of dotplot view ([@cmdcolin](https://github.com/cmdcolin))
* [#3102](https://github.com/GMOD/jbrowse-components/pull/3102) Allow creating alternative "add track workflows" from within the "Add track" widget ([@cmdcolin](https://github.com/cmdcolin))
* [#3043](https://github.com/GMOD/jbrowse-components/pull/3043) Create MultiWiggle track type, adapter, and renderers ([@cmdcolin](https://github.com/cmdcolin))
* Other
* …
```
=> Add 2.1.0 release announcement

packages/core/pluggableElementTypes/models/BaseTrackModel.ts
Fixes issue noted here https://sourceforge.net/p/gmod/mailman/message/37688532/
There were cosmetic refactorings that broke the code in this case in v2.0.0
=> Fix menu items for changing display type from track menu

plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx
Fixes #3123
removes some proptypes too
=> Fix ability to click and drag overview scale bar dragging right to left

website/release_announcement_drafts/v2.1.1.md
```
* `core`
* [#3132](https://github.com/GMOD/jbrowse-components/pull/3132) Extend theme with module augmentation ([@garrettjstevens](https://github.com/garrettjstevens))
* Other
* [#3137](https://github.com/GMOD/jbrowse-components/pull/3137) Make ideogram menu item similar to others ([@garrettjstevens](https://github.com/garrettjstevens))
* Other
* [#3157](https://github.com/GMOD/jbrowse-components/pull/3157) Support the "name" field on multi-wiggle adapter subadapters instead of source ([@cmdcolin](https://github.com/cmdcolin))
* [#3154](https://github.com/GMOD/jbrowse-components/pull/3154) Use the union of all the subadapter refNames for the MultiWiggleAdapter getRefNames ([@cmdcolin](https://github.com/cmdcolin))
* [#3156](https://github.com/GMOD/jbrowse-components/pull/3156) Fix for …
```
=> Add v2.1.1 release announce

plugins/authentication/src/OAuthModel/model.tsx, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, plugins/variants/src/VariantFeatureWidget/VariantSampleGrid.tsx
=> Add mouseover tooltip descriptions to the header of the VariantFeatureDetails sample/genotype table

plugins/wiggle/src/MultiLinearWiggleDisplay/components/WiggleDisplayComponent.tsx
=> Fix legend being cutoff on multiwiggle tracks with wide window

test_data/ce_aliases.txt
annoying people who don't use standard names.
=> adding aliases to the worm alias file

plugins/alignments/package.json, plugins/alignments/src/CramAdapter/CramAdapter.ts, plugins/alignments/src/CramAdapter/CramSlightlyLazyFeature.ts, plugins/alignments/src/declare.d.ts, yarn.lock
=> Use typescript version of @gmod/cram

plugins/alignments/src/CramAdapter/CramSlightlyLazyFeature.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3288
Before
After
=> Fix CRAM plotting for data files that encode insertions in uncommon way

website/release_announcement_drafts/v2.2.1.md
```
* Other
* [#3277](https://github.com/GMOD/jbrowse-components/pull/3277) Create new "Add track workflow" that allows pasting JSON track configs ([@cmdcolin](https://github.com/cmdcolin))
* [#3328](https://github.com/GMOD/jbrowse-components/pull/3328) Add GC content display type to the reference sequence track ([@cmdcolin](https://github.com/cmdcolin))
* [#3316](https://github.com/GMOD/jbrowse-components/pull/3316) Add LGV typescripting to @jbrowse/react-linear-genome-view ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3298](https://github.com/GMOD/jbrowse-components/pull/3298) Add authentication plugin to embedded components ([@garrettjstevens](https://github.com/garrettjstevens))
* [#3329](https://github.com/GMOD/jbrowse-components/pull/3329) Add ability to minimize/collapse …
```
=> Add v2.2.1 release announcement

website/release_announcement_drafts/v2.2.2.md
```
yarn run v1.22.19
* Other
* [#3350](https://github.com/GMOD/jbrowse-components/pull/3350) Retain feature labels in compact display mode for SVG features, and allow turning off keeping feature description without feature label ([@cmdcolin](https://github.com/cmdcolin))
* [#3357](https://github.com/GMOD/jbrowse-components/pull/3357) Allow holding shift key to create rubberband selection on LGV ([@cmdcolin](https://github.com/cmdcolin))
* [#3363](https://github.com/GMOD/jbrowse-components/pull/3363) Create remove-track CLI command ([@cmdcolin](https://github.com/cmdcolin))
* [#3341](https://github.com/GMOD/jbrowse-components/pull/3341) Add BEDPE adapter type ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* …
```
=> v2.2.2 release announcement

website/release_announcement_drafts/v2.3.0.md
adds the read cloud/read arcs and such :)
```
* `core`
* [#3391](https://github.com/GMOD/jbrowse-components/pull/3391) Allow arc display to connect to "unpaired" positions using RNEXT/PNEXT or SA tag ([@cmdcolin](https://github.com/cmdcolin))
* [#3387](https://github.com/GMOD/jbrowse-components/pull/3387) Small UI tweaks for add track workflow ([@cmdcolin](https://github.com/cmdcolin))
* [#3358](https://github.com/GMOD/jbrowse-components/pull/3358) Create new "arc" display type to show long range connections between paired-end and split-reads ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3381](https://github.com/GMOD/jbrowse-components/pull/3381) Add method for cache busting requests to the config file in jbrowse-web ([@cmdcolin](https://github.com/cmdcolin))
* …
```
=> v2.3.0 release announcement

website/blog/2022-12-16-yearendroundup.md
This was an idea bandied around in the gitter chat, just a little review of the fun stuff we did
=> Year end roundup blog post

packages/core/BaseFeatureWidget/__snapshots__/index.test.tsx.snap, packages/core/ui/ResizeBar.tsx, packages/core/ui/SanitizedHTML.tsx, packages/core/util/index.ts, plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.tsx.snap, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/util.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabel.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap, plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, test_data/volvox/config.json
=> Render HTML in faceted track selector for track data/metadata

website/release_announcement_drafts/v2.3.4.md
changelog
* Other
* [#3475](https://github.com/GMOD/jbrowse-components/pull/3475) Bypass plugins.json download if unneeded during app startup ([@cmdcolin](https://github.com/cmdcolin))
* [#3458](https://github.com/GMOD/jbrowse-components/pull/3458) Improve auto-update of sequence track height when toggling forward/reverse/translation settings ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3470](https://github.com/GMOD/jbrowse-components/pull/3470) Variant sample grid auto-size columns and resizer ([@cmdcolin](https://github.com/cmdcolin))
* [#3457](https://github.com/GMOD/jbrowse-components/pull/3457) Fix synteny view not drawing after horizontal flip in v2.3.3 ([@cmdcolin](https://github.com/cmdcolin))
* [#3459](https://github.com/GMOD/jbrowse-components/pull/3459) Booleanize …
=> v2.3.4 release announcement

website/release_announcement_drafts/v2.4.0.md
Changelog
* `core`
* [#3513](https://github.com/GMOD/jbrowse-components/pull/3513) Add ability to open refNameAliases+cytobands in "Open sequence" start screen on desktop ([@cmdcolin](https://github.com/cmdcolin))
* [#3512](https://github.com/GMOD/jbrowse-components/pull/3512) SVG export of linear synteny view, dotplot, and circular views ([@cmdcolin](https://github.com/cmdcolin))
* [#3467](https://github.com/GMOD/jbrowse-components/pull/3467) Create dark theme and allow user to toggle different themes from preferences dialog ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3510](https://github.com/GMOD/jbrowse-components/pull/3510) Allow configuring default display height ([@cmdcolin](https://github.com/cmdcolin))
* [#3524](https://github.com/GMOD/jbrowse-components/pull/3524) Fix …
=> v2.4.0 release announcement

plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap, plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.tsx.snap, plugins/linear-comparative-view/src/LinearComparativeDisplay/stateModelFactory.ts, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, yarn.lock
Fixes #3553
Now just has a blank screen, which is not super helpful either, but it is more correct than saying that we are loading the data
=> Fix infinite loading state when no synteny features are visible in synteny view

plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyDisplay/drawSynteny.ts, plugins/linear-comparative-view/src/LinearSyntenyDisplay/model.ts, plugins/menus/src/AboutWidget/components/__snapshots__/AboutWidget.test.tsx.snap, plugins/menus/src/HelpWidget/components/__snapshots__/HelpWidget.test.js.snap, yarn.lock
This fixes the issue by storing the actual feature IDs on the model instead of the on-the-fly computed 'color ids' used in the click map
Fixes https://github.com/GMOD/jbrowse-components/issues/3497
=> Fix selected synteny feature getting unselected after scroll

website/release_announcement_drafts/v2.4.1.md
changelog
* `core`
* [#3534](https://github.com/GMOD/jbrowse-components/pull/3534) Improve visibility of SNPs on alignments track ([@cmdcolin](https://github.com/cmdcolin))
* [#3561](https://github.com/GMOD/jbrowse-components/pull/3561) Add scroll zoom, d-pad, and more click+drag options to dotplot ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3574](https://github.com/GMOD/jbrowse-components/pull/3574) Add ability to load all built-in synteny data sources from @jbrowse/cli ([@cmdcolin](https://github.com/cmdcolin))
* [#3564](https://github.com/GMOD/jbrowse-components/pull/3564) Use double-click to zoom in on particular offset in LGV, and make ctrl+scroll also zoom in on particular offset ([@cmdcolin](https://github.com/cmdcolin))
* …
=> v2.4.1 release announcement

packages/core/BaseFeatureWidget/SequenceFeatureDetails.tsx, plugins/arc/src/LinearArcDisplay/index.ts, plugins/linear-genome-view/src/LinearBareDisplay/index.ts, plugins/linear-genome-view/src/LinearBasicDisplay/components/SetMaxHeight.tsx, plugins/linear-genome-view/src/LinearBasicDisplay/index.ts, plugins/linear-genome-view/src/LinearBasicDisplay/model.ts
Fixes issue reported by @scottcain from chat
=> Fix gene without subfeatures not being displayed in sequence feature details

plugins/alignments/src/MismatchParser/index.ts, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/hic/src/HicRenderer/components/HicRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/Component.tsx, plugins/linear-comparative-view/src/LinearSyntenyView/model.ts, plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedBlockContent.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx, plugins/lollipop/src/LollipopRenderer/components/LollipopRendering.js, plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts, plugins/svg/src/SvgFeatureRenderer/components/SvgOverlay.tsx, plugins/variants/src/LinearVariantDisplay/model.ts, products/jbrowse-web/src/SessionLoader.ts, products/jbrowse-web/src/tests/util.tsx
Splits out irrelevant refactors from https://github.com/GMOD/jbrowse-components/pull/3595 into a separate PR
=> Minor refactors

website/release_announcement_drafts/v2.4.2.md
* `core`
* [#3604](https://github.com/GMOD/jbrowse-components/pull/3604) Alignments tags description in feature details on mouseover ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3586](https://github.com/GMOD/jbrowse-components/pull/3586) Add authorization(internetAccount) support for Trix index files ([@andrzejgrzelak](https://github.com/andrzejgrzelak))
* Other
* [#3610](https://github.com/GMOD/jbrowse-components/pull/3610) Avoid cutting off import form of spreadsheet view, fix overflowed text in table header ([@cmdcolin](https://github.com/cmdcolin))
* [#3600](https://github.com/GMOD/jbrowse-components/pull/3600) Fix using the force load button after a stats timeout ([@cmdcolin](https://github.com/cmdcolin))
* …
=> v2.4.2 release announcement

website/release_announcement_drafts/v2.5.0.md
* Other
* [#3675](https://github.com/GMOD/jbrowse-components/pull/3675) Use react-popper for tooltips in DotplotView ([@cmdcolin](https://github.com/cmdcolin))
* [#3637](https://github.com/GMOD/jbrowse-components/pull/3637) Fix renderDelay not being applied to dynamicBlocks ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3677](https://github.com/GMOD/jbrowse-components/pull/3677) Smaller fontSize in global theme by default ([@cmdcolin](https://github.com/cmdcolin))
* [#3660](https://github.com/GMOD/jbrowse-components/pull/3660) Bump x-data-grid dependency, refactors for BaseFeatureDetails, add GridToolbar ([@cmdcolin](https://github.com/cmdcolin))
* [#3626](https://github.com/GMOD/jbrowse-components/pull/3626) Update to mui x-data-grid 6 …
=> v2.5.0 release announcement

packages/core/pluggableElementTypes/models/components/gff3.ts
I think this is all that's needed to address https://github.com/GMOD/jbrowse-components/issues/3678
=> attempt at fixing strand for gff3 dumping

plugins/alignments/src/BamAdapter/BamAdapter.ts, plugins/alignments/src/CramAdapter/CramAdapter.ts
=> Fix ability to filter certain fields in BAM/CRAM files

packages/core/BaseFeatureWidget/BaseFeatureDetail/index.tsx, plugins/variants/src/VariantFeatureWidget/AnnotGrid.tsx, plugins/variants/src/VariantFeatureWidget/VariantAnnotationTable.tsx, plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.tsx, plugins/variants/src/VariantFeatureWidget/VariantSampleGrid.tsx
Helps resize potentially large columns in the CSQ
Split out from https://github.com/GMOD/jbrowse-components/pull/3697
also reduces some use of type any, refactor, etc
=> Add column resizers to the variant ANN/CSQ panels

plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
Commit 5cf7cabca080358acce9e7763b416aa9f7bbc700 introduced some odd warnings during tests
I don't know exactly why, but I reverted some of the misc refactoring and that seemed to fix it
=> Fix some test warnings

plugins/hic/src/HicRenderer/HicRenderer.tsx
This commit intends to add functionality to the "Horizontally Flip" Feature in the Hamburger Menu. Detailed discussion can be found in issue #3460 (https://github.com/GMOD/jbrowse-components/issues/3460)
=> Horizontal Flip Functionality for Hi-C Display

plugins/alignments/src/LinearPileupDisplay/components/ColorByTag.tsx, plugins/alignments/src/LinearPileupDisplay/components/LinearPileupDisplayBlurb.tsx, plugins/alignments/src/LinearPileupDisplay/model.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3718
=> Fix hanging when changing sort by tag

packages/core/pluggableElementTypes/renderers/BoxRendererType.ts, packages/core/rpc/BaseRpcDriver.ts, packages/core/util/io/index.ts, packages/core/util/mst-reflection.ts, packages/product-core/src/Session/DrawerWidgets.ts, packages/text-indexing/src/util.ts, plugins/alignments/src/LinearPileupDisplay/model.ts, plugins/alignments/src/PileupRenderer/sortUtil.ts, plugins/bed/src/util.ts, plugins/breakpoint-split-view/src/BreakpointSplitView/BreakpointSplitView.ts, plugins/breakpoint-split-view/src/BreakpointSplitView/components/util.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.tsx, plugins/grid-bookmark/src/index.ts, plugins/legacy-jbrowse/src/NCListAdapter/NCListFeature.ts, plugins/sv-inspector/src/SvInspectorView/components/SvInspectorView.tsx, plugins/svg/src/SvgFeatureRenderer/components/util.ts, products/jbrowse-desktop/src/indexJobsModel.ts
This was the result of running the "sonarjs" eslint fixes rule set over the codebase. It gives many warnings, maybe too many to realistically take care of (many about cyclomatic complexity, repeated variables that should be extracted to a constant, etc) but this applies a couple auto-fixed results
Added 
"plugin:sonarjs/recommended",
And
"eslint-plugin-sonarjs": "^0.19.0",
for fixes and then removed
=> Sonarjs eslint fixes

plugins/alignments/package.json, plugins/alignments/src/BamAdapter/BamAdapter.ts, plugins/alignments/src/CramAdapter/CramAdapter.ts, yarn.lock
This is a pretty minor-major version release, but was done in caution (otherwise semver for existing versions of e.g. @jbrowse/react-linear-genome-view could have gotten semver updates that could have caused devtool complaints, etc)
=> Upgrade to @gmod/bam v2.0.0

plugins/variants/src/VcfFeature/index.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3797
=> Fix VCF feature starting at 1-based 1

products/jbrowse-react-app/src/rootModel/index.ts, yarn.lock
=> Fix version missing from about menu in @jbrowse/react-app

plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx
- updates deprecated option for accessing editable mui data grid fields
- resolves https://github.com/GMOD/jbrowse-components/issues/3805
=> Fix a bug on the BookmarkWidget mui data grid where labels were not saving

packages/core/util/types/index.ts
I found myself needing these type guards during some apollo development
=> type guards for LocalPathLocation and BlobLocation

jest.config.js, plugins/linear-genome-view/src/LinearGenomeView/model.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3878
=> Only keyboard shortcut zoom if the current zoom is done

plugins/grid-bookmark/src/GridBookmarkWidget/components/AssemblySelector.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/DeleteBookmarks.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/model.ts, plugins/grid-bookmark/src/index.ts, products/jbrowse-web/src/tests/BookmarkWidget.test.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/3935
Fixes https://github.com/GMOD/jbrowse-components/issues/3934
demo: https://s3.amazonaws.com/jbrowse.org/code/jb2/fixing-bookmarks-bugs/index.html
=> Fixes crash upon deleting bookmarks and inability to filter by assembly

plugins/alignments/src/PileupRenderer/renderSoftClipping.ts, website/blog/2022-06-22-v1.7.11-release.md
Matches the "heightLimit" used in mismatch rendering for softclip rendering
=> Stop drawing the letters of soft clipping bases in collapsed drawing mode

products/jbrowse-desktop/package.json, products/jbrowse-desktop/public/electron.ts, yarn.lock
Partially addresses #3944
screenshot of a syntax error in the JSON
before
after
=> Report JSON parse error when failing to load JSON file on desktop

website/release_announcement_drafts/v2.6.4.md, website/release_announcement_drafts/v2.7.0.md
* Other
* [#3951](https://github.com/GMOD/jbrowse-components/pull/3951) Add jobs widget to jbrowse-web ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#3900](https://github.com/GMOD/jbrowse-components/pull/3900) Make bookmarks persistent across sessions with local storage ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#3896](https://github.com/GMOD/jbrowse-components/pull/3896) Upgrade oclif to v3 to avoid deprecation warnings ([@garrettjstevens](https://github.com/garrettjstevens))
* [#3907](https://github.com/GMOD/jbrowse-components/pull/3907) Change the config.json missing screen to an "It worked!" message ([@cmdcolin](https://github.com/cmdcolin))
* [#3913](https://github.com/GMOD/jbrowse-components/pull/3913) Add color scheme …
=> v2.7.0 release announcement

plugin-development-tools/yarn.lock, plugins/gccontent/src/GCContentAdapter/GCContentAdapter.ts, plugins/gccontent/src/GCContentAdapter/configSchema.ts, plugins/gccontent/src/LinearGCContentDisplay/components/EditGCContentParams.tsx, plugins/gccontent/src/LinearGCContentDisplay/config.ts, plugins/gccontent/src/LinearGCContentDisplay/stateModel.ts, products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap, test_data/volvox/config.json, website/yarn.lock, yarn.lock
Helps with https://github.com/GMOD/jbrowse-components/discussions/3985
Adds slots to the LinearGCContentDisplay and renderer, and a dialog to edit it. Adds a default change to the volvox config to ensure it can be configured
=> Allow editing step size and window size of GC content adapter

website/release_announcement_drafts/v2.7.2.md
* `core`, `product-core`
* [#4013](https://github.com/GMOD/jbrowse-components/pull/4013) Create concept of global hovered state ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3999](https://github.com/GMOD/jbrowse-components/pull/3999) Example of using customElement + ShadowDOM for @jbrowse/react-linear-genome-view ([@AcaDemIQ](https://github.com/AcaDemIQ))
* [#4015](https://github.com/GMOD/jbrowse-components/pull/4015) Create MacOS universal build of jbrowse-desktop to help M1 macs ([@cmdcolin](https://github.com/cmdcolin))
* `app-core`, `core`
* [#3994](https://github.com/GMOD/jbrowse-components/pull/3994) Refactors for app-core view container ([@cmdcolin](https://github.com/cmdcolin))
* [#4016](https://github.com/GMOD/jbrowse-components/pull/4016) Fix mouseover …
=> v2.7.2 release announcement

plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx, test_data/volvox/config.json
More minimal change compared to #4094
Fixes #4092
=> Fix faceted metadata header names colliding with non-metadata header names

packages/app-core/src/ui/App/ViewMenu.tsx, packages/embedded-core/src/ui/ViewMenu.tsx, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap, products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, products/jbrowse-web/src/tests/BasicLinearGenomeView.test.tsx, yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/4115
i am not sure why this fixes the issue, which isn't great, but it does fix it. see discussion in the issue thread for more info
=> Fix view menu checkboxes not responding in some cases

packages/core/ui/FileSelector/FileSelector.tsx, plugins/authentication/src/HTTPBasicModel/HTTPBasicLoginForm.tsx
=> Fix internet accounts not being shown in FileSelector on page refresh

packages/app-core/package.json, packages/core/package.json, plugins/data-management/package.json, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/SyntenyContextMenu.tsx, plugins/linear-genome-view/package.json
add on to previous functionality to wheel/touchpad side scroll the synteny view
=> Add ability to click and drag synteny area of LinearSyntenyView to side scroll

website/release_announcement_drafts/v2.10.0.md
* Other
* [#4003](https://github.com/GMOD/jbrowse-components/pull/4003) Adds the ability to highlight regions using the bookmarks widget ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#4123](https://github.com/GMOD/jbrowse-components/pull/4123) Remove session.notify after using the Add track workflow ([@cmdcolin](https://github.com/cmdcolin))
* [#3859](https://github.com/GMOD/jbrowse-components/pull/3859) Add new pairwise indexed PAF adapter format with CLI creation workflow ([@cmdcolin](https://github.com/cmdcolin))
* [#4109](https://github.com/GMOD/jbrowse-components/pull/4109) Allow right clicking synteny features ([@cmdcolin](https://github.com/cmdcolin))
* [#4110](https://github.com/GMOD/jbrowse-components/pull/4110) Scroll both panels of the linear synteny view …
=> v2.10.0 release announce

website/release_announcement_drafts/v2.10.1.md
$ lerna-changelog --silent
* `core`
* [#4155](https://github.com/GMOD/jbrowse-components/pull/4155) Remove react-svg-tooltip library ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4152](https://github.com/GMOD/jbrowse-components/pull/4152) Add directional feet to breakends in linear arc display ([@cmdcolin](https://github.com/cmdcolin))
* [#4143](https://github.com/GMOD/jbrowse-components/pull/4143) Add webpack build for @jbrowse/react-app ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4158](https://github.com/GMOD/jbrowse-components/pull/4158) Fix subfeature refNames on BED and BEDTabix parsers ([@cmdcolin](https://github.com/cmdcolin))
* [#4154](https://github.com/GMOD/jbrowse-components/pull/4154) Fix metadata facet filters being blank …
=> v2.10.1 announcement

website/blog/2023-12-26-yearinreview.md
=> Year in review blog post

.eslintrc.js, products/jbrowse-img/package.json, products/jbrowse-img/src/index.test.ts, products/jbrowse-img/src/index.ts, products/jbrowse-img/src/setupEnv.ts, yarn.lock
=> Fix @jbrowse/img tests to run under node environment

website/docs/tutorials/embed_linear_genome_view/03_assemblies.md
A small documentation amendment to get started contributing.
=> Rephrase suggestion to use JBrowse CLI

yarn.lock
=> Fix for jbrowse desktop on-the-fly faidx indexing

plugins/linear-genome-view/src/LinearGenomeView/components/MiniControls.tsx
This uses a less strong purple color for the minicontrols focus
=> Subtler minicontrols focus

packages/core/ui/theme.ts, packages/core/util/index.ts, packages/web-core/src/BaseWebSession/index.ts, plugins/linear-genome-view/src/LinearGenomeView/model.ts, plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.test.tsx, plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx, plugins/sequence/src/DivSequenceRenderer/components/__snapshots__/DivSequenceRendering.test.tsx.snap, plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts, plugins/svg/src/SvgFeatureRenderer/components/Box.tsx, plugins/svg/src/SvgFeatureRenderer/components/FeatureGlyph.tsx, plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.test.tsx, plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx, plugins/svg/src/SvgFeatureRenderer/components/util.ts, products/jbrowse-desktop/src/sessionModel/index.ts, products/jbrowse-react-circular-genome-view/src/createModel/createSessionModel.ts, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts
builds off of #4185 
screenshot
=> Allow toggling color by CDS frames using linear genome view menu

.github/workflows/push.yml, .github/workflows/website.yml
Fixes warnings outputted like these in screenshot below
=> Fix deprecation warnings on some github action workflows

package.json, packages/core/ReExports/modules.tsx, packages/core/package.json, plugins/data-management/package.json, plugins/dotplot-view/package.json, plugins/grid-bookmark/package.json, plugins/variants/package.json, plugins/wiggle/package.json, products/jbrowse-desktop/package.json, products/jbrowse-react-app/package.json, products/jbrowse-web/package.json, products/jbrowse-web/src/tests/BookmarkWidget.test.tsx, yarn.lock
removes re-export of GridPreferencesPanel, following https://github.com/mui/mui-x/issues/1855
=> Update @mui/x-data-grid 6->7

packages/core/ui/ErrorMessageStackTraceDialog.tsx
jbrowse2dev@gmail.com -> jbrowse2@berkeley.edu
=> Change email on error message dialog

plugins/hic/src/LinearHicDisplay/model.ts
=> Force specific jexl callback when using new pre-defined hi-c color schemes

packages/app-core/src/ui/App/ViewContainer.tsx, plugins/linear-genome-view/src/LinearGenomeView/svgcomponents/SVGLinearGenomeView.tsx
edit:outdated original comment
=> Use overflow:clip on viewcontainer for pinned tracks branch

plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/OverviewHighlight.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/OverviewHighlight.tsx, yarn.lock
=> Fix bookmark showing up on wrong assembly

website/release_announcement_drafts/v2.11.1.md, yarn.lock
* `core`
* [#4354](https://github.com/GMOD/jbrowse-components/pull/4354) Allow capitalizing CDS sequences and lowercasing introns in sequence feature panel ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4351](https://github.com/GMOD/jbrowse-components/pull/4351) Store and retrieve user track selector settings in local storage ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4381](https://github.com/GMOD/jbrowse-components/pull/4381) Replace all rgba(...) color strings with rgb(...) in SVG exports to fix usage in illustrator/inkscape ([@cmdcolin](https://github.com/cmdcolin))
* [#4364](https://github.com/GMOD/jbrowse-components/pull/4364) Fix tooltips creating a scrollbar when overflowing off the screen in Chrome ([@cmdcolin](https://github.com/cmdcolin))
* …
=> v2.11.1 release announcement

plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Adds a context menu option that zooms to a feature
resolves https://github.com/GMOD/jbrowse-components/issues/4174
demo: https://s3.amazonaws.com/jbrowse.org/code/jb2/simple-zoom-to-feat/index.html?session=share-zkoO31SfHQ&password=4SnIY
right click on a feature > zoom to feature
cmd + z or equivalent is good for getting back to where you were too
=> Adds a context menu option to zoom to a feature

plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx, plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/util.ts
this code is very similar to wheel handler in a single LGV, but applies it to both top and bottom LGV's
=> Add ctrl+wheel scroll to zoom both top and bottom of synteny view

plugins/linear-comparative-view/src/LGVSyntenyDisplay/components/util.ts, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, yarn.lock
=> Fix "Open synteny view at this position" when file contains CIGAR X/= operators

plugins/wiggle/src/MultiWiggleAddTrackWorkflow/AddTrackWorkflow.tsx
=> Filter blank lines in multi-wiggle addtrack workflow

packages/core/BaseFeatureWidget/BaseFeatureDetail/DataGridDetails.tsx, yarn.lock
This particularly affects MultiQuantitativeTrack about dialog's because they use a data grid in their About track panel
A screen recording demonstrates the issue
https://github.com/GMOD/jbrowse-components/assets/6511937/b358a18e-e630-4639-a8b7-635985c97a95
The width:100% that was there is likely vestigial from when older versions of x-data-grid needed a container to size into. That is not done automatically
=> Fix unstable dialog width in "About track" dialog for multi-quantitative tracks

products/jbrowse-cli/README.md, products/jbrowse-cli/src/commands/__snapshots__/set-default-session.test.ts.snap, products/jbrowse-cli/src/commands/set-default-session.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/4434
=> Update docs for set-default-session, and make session arg required

packages/core/configuration/configurationSchema.ts, plugins/bed/src/BedpeAdapter/BedpeAdapter.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HierarchicalTree.tsx, plugins/wiggle/src/MultiWiggleAdapter/MultiWiggleAdapter.ts, yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/4461
bumps @gmod/indexedfasta (and typescript bumped to 5.5 as a rider)
=> Fix @gmod/indexedfasta Buffer not defined error

packages/core/package.json, packages/core/util/io/RemoteFileWithRangeCache.ts, yarn.lock
Follow up to https://github.com/GMOD/jbrowse-components/pull/4462
=> Convert http-range-fetcher to @gmod/http-range-fetcher for buffer fix

website/release_announcement_drafts/v2.12.3.md, yarn.lock
Fixes bug noted during meeting yesterday where desktop would fail to start with error about createAutosave file https://github.com/GMOD/jbrowse-components/pull/4469
=> v2.12.3 release announce

plugins/config/src/ConfigurationEditorWidget/components/ColorEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
Fixes https://github.com/GMOD/jbrowse-react-app-vite-demo/issues/1
=> Fix config editor crash in vite usage of embedded components in dev mode

website/docs/faq.md
As briefly discussed on Gitter. A small explanation on how to enable gzip compression of the config.json.
=> Update faq.md with compression explanation

website/release_announcement_drafts/v2.13.0.md
currently changelog
* [#4494](https://github.com/GMOD/jbrowse-components/pull/4494) Add assembly name to scalebar in synteny views ([@cmdcolin](https://github.com/cmdcolin))
* [#4480](https://github.com/GMOD/jbrowse-components/pull/4480) Changes default height for SVG rendering to maxHeight to fix blank track effect on slow CPU ([@carolinebridge](https://github.com/carolinebridge))
* [#4478](https://github.com/GMOD/jbrowse-components/pull/4478) Add ability to use CSI indexes in @jbrowse/img ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4483](https://github.com/GMOD/jbrowse-components/pull/4483) Fix configuration settings for track sorting in the track selector ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4476](https://github.com/GMOD/jbrowse-components/pull/4476) Fix …
=> v2.13.0 release announcement

website/release_announcement_drafts/v2.13.1.md
* [#4497](https://github.com/GMOD/jbrowse-components/pull/4497) Add ability to toggle  "Show track outlines" ([@cmdcolin](https://github.com/cmdcolin))
* [#4501](https://github.com/GMOD/jbrowse-components/pull/4501) Fix opening track selector causing crash in v2.13.0 ([@cmdcolin](https://github.com/cmdcolin))
* [#4495](https://github.com/GMOD/jbrowse-components/pull/4495) Fix log scale for some types of signal tracks ([@cmdcolin](https://github.com/cmdcolin))
- Colin Diesh ([@cmdcolin](https://github.com/cmdcolin))
Done in 0.78s.
=> v2.13.1 release announcement

website/release_announcement_drafts/v2.14.0.md
* `core`
* [#4532](https://github.com/GMOD/jbrowse-components/pull/4532) De-duplicate snackbar messages ([@cmdcolin](https://github.com/cmdcolin))
* [#4516](https://github.com/GMOD/jbrowse-components/pull/4516) Add NCBI sequence_report.tsv alias adapter, with ability to recode NCBI fasta files to use UCSC style names ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4533](https://github.com/GMOD/jbrowse-components/pull/4533) Allow setting sequenceType='pep' in ReferenceSequenceTrack configuration ([@cmdcolin](https://github.com/cmdcolin))
* [#4528](https://github.com/GMOD/jbrowse-components/pull/4528) Add description config slot to reference sequence track ([@cmdcolin](https://github.com/cmdcolin))
* `app-core`, `core`
* [#4523](https://github.com/GMOD/jbrowse-components/pull/4523) …
=> v2.14.0 release announcement

packages/core/BaseFeatureWidget/__snapshots__/index.test.tsx.snap, plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.tsx.snap, plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap, plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.tsx.snap, plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap, plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap, plugins/menus/src/AboutWidget/components/__snapshots__/AboutWidget.test.tsx.snap, plugins/menus/src/HelpWidget/components/__snapshots__/HelpWidget.test.tsx.snap, plugins/menus/src/SessionManager/components/__snapshots__/SessionManager.test.tsx.snap, plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.tsx.snap, products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap, products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap, yarn.lock
In v2.14.0 the bigbed string decoding had a bug due to https://github.com/GMOD/bbi-js/pull/66/files
This updates @gmod/bbi to fix it
=> Fix BigBed decoding of strings in v2.14.0

plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/model.ts
Adds the ability to 'open bookmark widget' and 'remove bookmark'
=> Add dropdown menu from bookmark label clicks

plugins/variants/src/StructuralVariantChordRenderer/ReactComponent.tsx, yarn.lock
accidental bugs in refactoring during #4518 led to the circular chords not being colored correctly, with essentially a typo causing this (comparison to a display "id" that was in scope was compared against instead of feature.id())
=> Fix coloring on circular chord renderings

eslint.config.mjs, package.json, packages/web-core/src/BaseWebSession/index.ts, plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx, products/jbrowse-desktop/package.json, website/release_announcement_drafts/v2.15.1.md, yarn.lock
* `core`, `sv-core`
* [#4561](https://github.com/GMOD/jbrowse-components/pull/4561) Create notion of launching a single-row breakpoint split view ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4556](https://github.com/GMOD/jbrowse-components/pull/4556) Add dropdown menu from bookmark label clicks ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4554](https://github.com/GMOD/jbrowse-components/pull/4554) Fix the ability to sort menu items by priority for CascadingMenu ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4560](https://github.com/GMOD/jbrowse-components/pull/4560) Fix coloring on circular chord renderings ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4553](https://github.com/GMOD/jbrowse-components/pull/4553) Fix performance regression since …
=> v2.15.1 release announcement

yarn.lock
incorporates ixixx-js version bump https://github.com/GMOD/ixixx-js/pull/20
big credit to @carolinebridge for tracking down this bug!
=> Fix text indexing on Windows 

test_data/config_demo.json
=> Add tiberius sample dataset and updated gencode and ncbi GFF gene sets

website/release_announcement_drafts/v2.16.0.md, yarn.lock
* `app-core`, `core`
* [#4430](https://github.com/GMOD/jbrowse-components/pull/4430) Multi-level synteny rendering ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4612](https://github.com/GMOD/jbrowse-components/pull/4612) Fix error with tooltips in embedded components in vite dev mode ([@cmdcolin](https://github.com/cmdcolin))
* [#4602](https://github.com/GMOD/jbrowse-components/pull/4602) Fix decoding of CRAM ML tag ([@cmdcolin](https://github.com/cmdcolin))
* [#4594](https://github.com/GMOD/jbrowse-components/pull/4594) Fix highlight button causing issues clicking underlying track features ([@cmdcolin](https://github.com/cmdcolin))
* [#4586](https://github.com/GMOD/jbrowse-components/pull/4586) Update electron-builder to fix broken desktop builds …
=> v2.16.0 release announcement

plugins/alignments/src/MismatchParser/index.ts
=> Fix MM tag modifications from particular BAM file failing to render on the negative strand

plugins/hic/src/HicAdapter/HicAdapter.ts, plugins/hic/src/HicAdapter/HicFilehandle.ts, plugins/hic/src/HicAdapter/configSchema.ts, plugins/hic/src/HicRenderer/HicRenderer.tsx, plugins/hic/src/LinearHicDisplay/model.ts, plugins/wiggle/src/BigWigAdapter/configSchema.ts, test_data/config_demo.json
fixes https://github.com/GMOD/jbrowse-components/issues/4611
=> Allow configuring Hi-C normalization and default resolution multiplier

website/release_announcement_drafts/v2.16.1.md
* `app-core`, `core`, `product-core`, `text-indexing`
* [#4624](https://github.com/GMOD/jbrowse-components/pull/4624) Add utility links to synteny feature details to allow centering a view on a feature ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4628](https://github.com/GMOD/jbrowse-components/pull/4628) Allow configuring Hi-C normalization and default resolution multiplier ([@cmdcolin](https://github.com/cmdcolin))
* [#4619](https://github.com/GMOD/jbrowse-components/pull/4619) Add resolutionMultiplier config slot to BigWigAdapter ([@cmdcolin](https://github.com/cmdcolin))
* [#4634](https://github.com/GMOD/jbrowse-components/pull/4634) Fix opening local files in the multi-wiggle add track selector ([@cmdcolin](https://github.com/cmdcolin))
* …
=> v2.16.1 release announcement

packages/core/ui/AssemblySelector.tsx, packages/core/ui/FileSelector/UrlChooser.tsx, plugins/alignments/src/LinearPileupDisplay/components/ColorByTagDialog.tsx, plugins/alignments/src/LinearPileupDisplay/components/GroupByDialog.tsx, plugins/alignments/src/LinearPileupDisplay/components/SortByTagDialog.tsx, plugins/alignments/src/shared/FilterByTagDialog.tsx, plugins/authentication/src/ExternalTokenModel/ExternalTokenEntryForm.tsx, plugins/authentication/src/HTTPBasicModel/HTTPBasicLoginForm.tsx, plugins/config/src/ConfigurationEditorWidget/components/CallbackEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/ConfigurationTextField.tsx, plugins/config/src/ConfigurationEditorWidget/components/JsonEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/NumberMapEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/StringArrayEditor.tsx, plugins/config/src/ConfigurationEditorWidget/components/StringArrayMapEditor.tsx, plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.tsx, plugins/data-management/src/AddTrackWidget/components/TextIndexingConfig.tsx, plugins/data-management/src/AddTrackWidget/components/TrackAdapterSelector.tsx, plugins/data-management/src/AddTrackWidget/components/TrackTypeSelector.tsx, plugins/data-management/src/AssemblyManager/AssemblyAddForm.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedHeader.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HierarchicalHeader.tsx, plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx, plugins/grid-bookmark/src/GridBookmarkWidget/components/dialogs/EditBookmarkLabelDialog.tsx, plugins/linear-genome-view/src/LinearBasicDisplay/components/AddFiltersDialog.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/GetSequenceDialog.tsx, plugins/spreadsheet-view/src/SpreadsheetView/components/GlobalFilterControls.tsx, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/LocString.tsx, plugins/spreadsheet-view/src/SpreadsheetView/models/ColumnDataTypes/Text.tsx, plugins/wiggle/src/MultiWiggleAddTrackWorkflow/AddTrackWorkflow.tsx, products/jbrowse-web/src/components/ShareDialog.tsx
I ran "npx @mui/codemod@latest deprecations/accordion-summary-classes" in packages,plugins,and products folders
=> Run codemod fix for some MUI deprecated props

plugins/bed/src/BedpeAdapter/configSchema.ts, plugins/spreadsheet-view/src/SpreadsheetView/ImportWizard.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/BedImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/BedpeImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/STARFusionImport.ts, plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/VcfImport.ts
=> Allow opening bedpe files from users tracks in SV inspector

plugins/linear-comparative-view/src/LinearComparativeView/model.ts, plugins/linear-comparative-view/src/LinearSyntenyView/model.ts
Requested by RGD
#4759
Had been removed in #4428
=> Restore concept of linking synteny views

packages/core/BaseFeatureWidget/SequenceFeatureDetails/model.ts, packages/core/util/index.ts, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedDataGrid.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx, plugins/data-management/src/HierarchicalTrackSelectorWidget/facetedModel.ts, plugins/linear-genome-view/src/LinearGenomeView/model.ts, products/jbrowse-web/src/components/ShareButton.tsx, products/jbrowse-web/src/components/ShareDialog.tsx, products/jbrowse-web/src/components/ShareDialogLinkField.tsx, products/jbrowse-web/src/components/ShareInfoDialog.tsx
- Clearer variable names for the facet filtering stage
- Moves the data grid to separate component
- More use of the localStorageGetX (number, boolean) functions
=> Refactors for faceted track selector

.github/workflows/push.yml, .github/workflows/release.yml, .github/workflows/update-docs.yml, docs/generateConfigDocs.ts, docs/generateStateModelDocs.ts, docs/tsconfig.json, plugins/data-management/src/UCSCTrackHub/ucscTrackHub.ts, tsconfig.json, website/docs/config/BigBedAdapter.md, website/docs/config/VcfAdapter.md, website/docs/config/VcfTabixAdapter.md, website/docs/models/AddTrackModel.md, website/docs/models/DotplotView.md, website/docs/models/FacetedModel.md, website/docs/models/LinearComparativeView.md, website/docs/models/LinearGenomeView.md, website/docs/models/LinearSyntenyView.md, website/docs/models/LinearVariantMatrixDisplay.md, website/docs/models/MultiLinearVariantDisplay.md
fixes issue with rmsk (repeatmasker) track showing as unsupportd
=> Make any bigType track open as BigBedAdapter in ucsc connections

plugins/variants/package.json, yarn.lock
this bumps our @gmod/vcf patch version in package.json to make sure npm library users gets the needed @gmod/vcf version bump
this PR in response to user bug report via email
=> VCF ensure latest

packages/core/PluginLoader.ts, plugins/alignments/src/LinearSNPCoverageDisplay/model.ts, plugins/wiggle/src/LinearWiggleDisplay/components/WiggleDisplayComponent.tsx, plugins/wiggle/src/LinearWiggleDisplay/model.ts, plugins/wiggle/src/LinearWiggleDisplay/renderSvg.tsx, plugins/wiggle/src/MultiLinearWiggleDisplay/components/ColorLegend.tsx, plugins/wiggle/src/MultiLinearWiggleDisplay/components/LegendItem.tsx, plugins/wiggle/src/MultiLinearWiggleDisplay/model.ts, products/jbrowse-web/src/components/ConfigWarningDialog.tsx, products/jbrowse-web/src/components/SessionWarningDialog.tsx, yarn.lock
When a session or config is loading cross-origin plugin javascript...potential XSS...we warn the user
This improves the warning to show the URL of the plugin being loaded, and adds a "Why am I seeing this" button
=> Improvements to the sesson/config warning dialogs

packages/app-core/src/ui/App/ViewContainerTitle.tsx, packages/core/assemblyManager/assembly.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/4815
=> Use assembly "displayName" field on View titles

plugins/bed/src/BigBedAdapter/BigBedAdapter.ts, plugins/data-management/src/UCSCTrackHub/doConnect.ts, plugins/data-management/src/UCSCTrackHub/ucscTrackHub.ts, plugins/gtf/src/GtfAdapter/GtfAdapter.ts, plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts, products/jbrowse-web/src/loadHubSpec.ts
- Automatically navigates to defaultLocation on opening a single file hub
- Puts species name in session name
- Adds displayName for the assembly
=> Additional ?hubURL compat

website/release_announcement_drafts/v3.0.4.md
* Other
* [#4856](https://github.com/GMOD/jbrowse-components/pull/4856) Add status callback while parsing .delta (MUMmer), .chain (liftover) and PIF files ([@cmdcolin](https://github.com/cmdcolin))
* [#4855](https://github.com/GMOD/jbrowse-components/pull/4855) Handle case insensitive UTR ([@cmdcolin](https://github.com/cmdcolin))
* [#4853](https://github.com/GMOD/jbrowse-components/pull/4853) Split VCF adapter ([@cmdcolin](https://github.com/cmdcolin))
* [#4848](https://github.com/GMOD/jbrowse-components/pull/4848) Allow clicking feature even if there is a slight mouse drag ([@cmdcolin](https://github.com/cmdcolin))
* [#4847](https://github.com/GMOD/jbrowse-components/pull/4847) Add mouseover color and resize handle to variant matrix view ([@cmdcolin](https://github.com/cmdcolin))
* …
=> v3.0.4 release announcement

package.json, plugins/trix/package.json, yarn.lock
Includes fix from @gmod/trix https://github.com/GMOD/trix-js/pull/20
Fixes https://github.com/GMOD/jbrowse-components/issues/4863
=> Bump trix to fix bug fetching some search results

test_data/config_demo.json, test_data/volvox/config.json, yarn.lock
Pulls in https://github.com/GMOD/bam-js/pull/109
=> Bump @gmod/bam for CSI index fix

plugins/variants/src/shared/components/ClusterDialog.tsx, plugins/wiggle/src/MultiLinearWiggleDisplay/components/ClusterDialog.tsx, plugins/wiggle/src/WiggleBaseRenderer.tsx, plugins/wiggle/src/WiggleRPC/MultiWiggleGetScoreMatrix.ts
The code on main can occasionally produce irregular matrixes (different number of columns)
This fixes it so that the code consistently produces a square matrix
=> Fix clustering for certain sets of bigwig files

packages/core/data_adapters/BaseAdapter/BaseOptions.ts, packages/core/data_adapters/BaseAdapter/types.ts, packages/core/pluggableElementTypes/RpcMethodTypeWithFiltersAndRenameRegions.ts, plugins/bed/src/BigBedAdapter/BigBedAdapter.ts, plugins/variants/src/VariantRPC/MultiVariantClusterGenotypeMatrix.ts, plugins/variants/src/VariantRPC/MultiVariantGetGenotypeMatrix.ts, plugins/variants/src/VariantRPC/MultiVariantGetSimplifiedFeatures.ts, plugins/variants/src/VariantRPC/cluster.ts, plugins/variants/src/VariantRPC/getGenotypeMatrix.ts, plugins/variants/src/VariantRPC/types.ts, plugins/variants/src/index.ts, plugins/variants/src/shared/MultiVariantBaseModel.tsx, plugins/variants/src/shared/components/ClusterDialog.tsx, plugins/variants/src/shared/components/ClusterDialogAuto.tsx, plugins/variants/src/shared/components/ClusterDialogManual.tsx, plugins/wiggle/src/WiggleRPC/MultiWiggleGetScoreMatrix.ts, yarn.lock
Uses @greenelab/hclust code (but vendored/copied into codebase)
Could be wasm-ified potentially
Easy one click instead of having user download
=> Add in-browser clustering method for genotype matrix

plugins/linear-comparative-view/src/LinearSyntenyView/model.ts, plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts, plugins/linear-genome-view/src/LinearGenomeView/model.ts, plugins/linear-genome-view/src/LinearGenomeView/types.ts, test_data/volvox/config.json
Example
We can make a simplified snapshot like this
```json
{
"defaultSession": {
"name": "Integration test example",
"views": [
{
"id": "integration_test",
"type": "LinearGenomeView",
"init": {
"loc": "ctgA:5,000-6,000",
"assembly": "volvox",
"tracks": ["volvox_cram_alignments_ctga"]
}
}
]
}
}
```
without
```json
{
"session": {
"drawerPosition": "right",
"drawerWidth": 384,
"widgets": {
"hierarchicalTrackSelector": {
"id": "hierarchicalTrackSelector",
"type": "HierarchicalTrackSelectorWidget",
"view": "integration_test",
"faceted": {
"filterText": "",
"showSparse": false,
"showFilters": true,
"showOptions": false,
"panelWidth": 400
}
},
"GridBookmark": {
"id": "GridBookmark",
"type": "GridBookmarkWidget"
}
},
"activeWidgets": {
"hierarchicalTrackSelector": "hierarchicalTrackSelector"
}, …
```
=> Create simplified defaultSession snapshot API for navigating a LGV to a particular position

plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
Fix for #4912 
Adds a 500kb window when doing parent aggregation
There are still potentially some very long genes that could cause issues with this, but hopefully this should fix most usages
One alternative to more generally fix this would be to allow a glyph to be reconstructed if it detects it hit a new subfeature in another block, but we assume that features are static and shared across blocks.
Another alternative would be to use something like dynamic blocks (as opposed to static blocks) for gene tracks. This would make it less needed for there to be exact shared feature across blocks as there would be a single block for a single refseq for most cases...less information sharing
=> Fix parent aggregation in BigBed files using larger request window

packages/core/ui/theme.ts
Regression between v3.0.5 and v3.1.0
=> Fix dark stock theme

plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
Double-follow-up to https://github.com/GMOD/jbrowse-components/issues/4912
The initial fix in v3.2.0 dc6bba07b6 had a ts-expect-error that covered up the fact that it was not performing the right check. It is now fixed, more clear with no ts-expect-error
=> Fix broken bigbed features when there is gene level aggregation

.github/workflows/release.yml
Adds this to the release pipelines specifically via github action
Fixes #4801
=> Upload last release build to https://jbrowse.org/code/jb2/latest

plugins/linear-genome-view/src/LinearBasicDisplay/components/AddFiltersDialog.tsx, plugins/linear-genome-view/src/LinearBasicDisplay/model.ts, plugins/variants/src/MultiLinearVariantRenderer/components/MultiLinearVariantRendering.tsx, plugins/variants/src/VcfFeature/util.ts, plugins/variants/src/shared/MultiVariantBaseModel.tsx, plugins/variants/src/shared/components/AddFiltersDialog.tsx, yarn.lock
This helps with a particular example that i saw: filter out super large >10Mbp events as they crowd out smaller events
=> Add ability to use jexl filters on multi-sample variant displays

plugins/linear-genome-view/src/LinearGenomeView/components/useWheelScroll.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/4964
Apparently touchpad pinch-to-zoom can trigger zoom
I have seen two different users use pinch-to-zoom (undergrad in Ian's class, and a office hours user) use the pinch-to-zoom, which I was unaware existed
It is a funny thing where pinch-to-zoom just happens to trigger the ctrl+wheel scroll
However, the pinch zoom has very small scroll deltaY values
To accommodate, we can dynamically toggle the 'wheel normalization'. When the deltaY values are small (pinch-to-zoom-like), then we can use one normalization value, and when they are large (more true-wheel-scroll-like) we can use another
Example pinchzoom values
```
Object { averageDeltaY: 0.09999847412109375, normalizer: 25 }
Object { averageDeltaY: 0.6359367370605469, normalizer: 25 …
```
=> Dynamically toggle wheel-scroll normalization to accomodate pinch-to-zoom

plugins/wiggle/src/drawDensity.ts, plugins/wiggle/src/drawLine.ts, plugins/wiggle/src/drawXY.ts
=> Fix mouseover for some variable width bigwig features

packages/core/TextSearch/TextSearchManager.ts, packages/core/package.json, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/index.tsx, plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/util.ts, plugins/linear-genome-view/src/LinearGenomeView/model.ts, yarn.lock
Possible helper for https://github.com/GMOD/jbrowse-components/issues/4655
Fixes https://github.com/GMOD/jbrowse-components/issues/2334
=> Add uFuzzy to prioritize text search results e.g. gene name search

packages/core/pluggableElementTypes/renderers/FeatureRendererType.ts, packages/core/util/offscreenCanvasUtils.tsx, plugins/alignments/src/PileupRenderer/PileupRenderer.ts, plugins/linear-comparative-view/src/LinearSyntenyView/svgcomponents/SVGLinearSyntenyView.tsx, plugins/variants/src/MultiLinearVariantMatrixRenderer/MultiLinearVariantMatrixRenderer.ts, plugins/variants/src/MultiLinearVariantRenderer/MultiVariantRenderer.ts, plugins/wiggle/src/DensityRenderer/__snapshots__/DensityRenderer.test.ts.snap, plugins/wiggle/src/WiggleBaseRenderer.tsx, plugins/wiggle/src/XYPlotRenderer/__snapshots__/XYPlotRenderer.test.ts.snap
Revert of https://github.com/GMOD/jbrowse-components/pull/5000
This PR introduced a number of sort of complex issues, so this reverts
=> Fix typescript on renderToAbstractCanvas

website/release_announcement_drafts/v3.3.1.md, website/release_announcement_drafts/v3.4.0.md
* `core`
* [#5010](https://github.com/GMOD/jbrowse-components/pull/5010) Add mouseover metadata for fields in the base feature widget ([@cmdcolin](https://github.com/cmdcolin))
* [#4998](https://github.com/GMOD/jbrowse-components/pull/4998) Add padding to the genomic window of search result hits ([@cmdcolin](https://github.com/cmdcolin))
* [#4995](https://github.com/GMOD/jbrowse-components/pull/4995) Add uFuzzy to improve gene name search ([@cmdcolin](https://github.com/cmdcolin))
* [#4983](https://github.com/GMOD/jbrowse-components/pull/4983) Update some data parser packages for ESM compat ([@cmdcolin](https://github.com/cmdcolin))
* [#4980](https://github.com/GMOD/jbrowse-components/pull/4980) Synthesize displayId if none provided in display config …
=> v3.4.0 release announcement

yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/5031
=> Bump @gmod/bbi to fix loading bigwig files from bigtools

products/jbrowse-img/src/bin.js
=> No-op CSS import for @jbrowse/img

plugins/linear-genome-view/src/LinearGenomeView/components/SearchResultsTable.tsx
fixes https://github.com/GMOD/jbrowse-components/issues/4960
renames e.g. NC_000001.10:1-100 to  chr1:1-100 in search results if a NCBI GFF was indexed
=> Canonicalize refNames in search results

plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/VariantSampleGrid.tsx, plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/getSampleGridRows.ts
=> Toggle button for selecting sample data grid columns

plugins/linear-comparative-view/src/LinearComparativeView/components/Rubberband.tsx, plugins/linear-comparative-view/src/LinearComparativeView/components/RubberbandSpan.tsx, plugins/linear-comparative-view/src/LinearComparativeView/components/RubberbandTooltip.tsx, plugins/linear-comparative-view/src/LinearComparativeView/components/useRangeSelect.ts, plugins/linear-comparative-view/src/LinearComparativeView/components/util.ts, plugins/linear-genome-view/src/LinearGenomeView/components/RubberbandTooltip.tsx
similar to work done for normal linear-genome-view in #5085
=> Migrate the linear-comparative-view rubberband tooltip to default MUI tooltip

website/release_announcement_drafts/v3.6.0.md
Current changelog:
* Other
* [#5102](https://github.com/GMOD/jbrowse-components/pull/5102) Refactor CLI to use built-in nodejs parseArgs ([@cmdcolin](https://github.com/cmdcolin))
* [#5090](https://github.com/GMOD/jbrowse-components/pull/5090) Optimize some modifications code for performance and readability ([@cmdcolin](https://github.com/cmdcolin))
* [#5087](https://github.com/GMOD/jbrowse-components/pull/5087) Better usage of dark mode on sequence track ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#5095](https://github.com/GMOD/jbrowse-components/pull/5095) Fix alpha rendering of SVG renderer box stroke/fill ([@cmdcolin](https://github.com/cmdcolin))
* [#5086](https://github.com/GMOD/jbrowse-components/pull/5086) Add status message reporting for synteny view loading …
=> v3.6.0 release announcement

website/release_announcement_drafts/v3.6.4.md
* Other
* [#5116](https://github.com/GMOD/jbrowse-components/pull/5116) Add padding if selecting search result from table ([@garrettjstevens](https://github.com/garrettjstevens))
* `product-core`
* [#5114](https://github.com/GMOD/jbrowse-components/pull/5114) Add locstrings to synteny mouseovers ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#5120](https://github.com/GMOD/jbrowse-components/pull/5120) Generalize parse line by line function to fix bed, gff3, and other types of files with no trailing newline ([@cmdcolin](https://github.com/cmdcolin))
* [#5111](https://github.com/GMOD/jbrowse-components/pull/5111) Fix issue where multiple cascading submenus could be opened at once ([@cmdcolin](https://github.com/cmdcolin))
* Other
* …
=> v3.6.4 release announcement

plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabelMenu.tsx, plugins/linear-genome-view/src/LinearGenomeView/model.ts, products/jbrowse-web/src/tests/TrackMenu.test.tsx, website/docs/models/LinearGenomeView.md
Fixes #5132 
Git bisected to https://github.com/GMOD/jbrowse-components/pull/5024/ introducing the bug
Probably should add an integration test for pin track functionality
=> Fix pin track function being missing from track menu
