- plugins/svg/src/SvgFeatureRenderer/components/ProcessedTranscript.js
- plugins/svg/src/SvgFeatureRenderer/components/Subfeatures.js
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.js
- plugins/svg/src/SvgFeatureRenderer/components/util.ts
This is related to our [original PR](https://github.com/GMOD/jbrowse-components/pull/2509) for providing arbitrary user-defined glyphs, which modifies the `chooseGlyphComponent` function in order to allow the additional glyphs to be rendered. 
There are several locations in the SVG module where `chooseGlyphComponent` is called without access to the `extraGlyphs` prop, which causes the custom glyphs to be skipped in several cases where they should be rendered. This PR passes `extraGlyphs` to every call of `chooseGlyphComponent` by propagating it into the relevant `layOut` calls and adding it to `FeatureLayOutArgs` and `SubfeatureLayOutArgs`.
> Pass extraGlyphs prop to all calls of chooseGlyphComponent

- packages/core/package.json
- plugins/alignments/package.json
- plugins/dotplot-view/package.json
- plugins/hic/package.json
- plugins/legacy-jbrowse/package.json
- plugins/linear-comparative-view/package.json
- plugins/sequence/package.json
- plugins/wiggle/package.json
- yarn.lock
Small bundle size savings, better typescript on the .get() method of abortable-promise-cache
> Bump abortable-promise-cache, http-range-fetcher, @gmod/nclist for esm versions

- packages/core/util/offscreenCanvasPonyfill.js
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- yarn.lock
Fixes mailing list issue noted here https://sourceforge.net/p/gmod/mailman/message/37611106/
> Add bezierCurveTo to offscreen canvas ponyfill to fix sashimi arcs rendering in alignments track in webkit and firefox

- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Adds a fix that was missed in https://github.com/GMOD/jbrowse-components/pull/2719/files to check for empty regions in the autorun
> Add a check for empty content blocks to fix rare empty stats estimation

- plugins/config/src/RefNameAliasAdapter/RefNameAliasAdapter.ts
- plugins/config/src/RefNameAliasAdapter/configSchema.ts
Fixes #1775
Makes a configuration slot for saying which column from the ref name alias file is being configured
> Make a configurable refNameColumn in RefNameAliasAdapter

- package.json
- products/jbrowse-cli/README.md
- products/jbrowse-cli/package.json
- products/jbrowse-cli/src/base.ts
- products/jbrowse-cli/src/commands/upgrade.ts
- yarn.lock
Adds a --clean argument to `jbrowse upgrade `
Uses rimraf to clean the static directory
Fixes #2337 
We could also consider making this the default behavior and not using --clean as an extra argument but it's maybe the 'safest' option since it would ensure that we don't delete anything unless a user confirms they want to delete stuff
> Add a --clean argument to `jbrowse upgrade` to clean up old files

- plugins/wiggle/src/WiggleRPC/rpcMethods.ts
Currently the wiggle track fails to use get global stats with the error
```
TypeError: Cannot read properties of undefined (reading 'includes')
at WiggleGetGlobalStats.execute (070fac713102893201a0.worker.js:253449:36)
```
This uses an older adapter capabilities concept. The code already checks for the adapter capabilities (using the adapterCapabilities attribute on the pluggable element) inside of linearwiggledisplay model correctly already so this check is unneeded
> Fix using global stats autoscale on wiggle tracks

- products/jbrowse-cli/src/commands/add-track.ts
This unconditionally performs an fs.unlink when using force so that it doesn't run into the issue with broken symlinks, mentioned in https://github.com/GMOD/jbrowse-components/issues/2768#issuecomment-1053703952
> Fix overwriting broken symlink with --force in add-track CLI

- packages/core/data_adapters/BaseAdapter.ts
- packages/core/ui/ErrorMessage.tsx
- packages/core/ui/ReturnToImportFormDialog.tsx
- packages/core/ui/index.ts
- packages/core/util/Base1DViewModel.ts
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
- plugins/dotplot-view/src/DotplotView/components/Header.tsx
- plugins/dotplot-view/src/DotplotView/model.ts
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/src/corePlugins.ts
This adds a blurb in the header bar, that tells you in text form 
(a) the current totalBp of the width and current totalBp of the height
(b) if a click and drag is occuring, the totalBp of the width and height of the click and drag selection
Also adds a method to return to the import form via the view menu
We could also consider adding RefNameAutocomplete style components to the dotplot header also to facilitate navigation
> Display the total bp viewed in the header of the dotplot view

- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
Currently the little "caps" on the ends of the cytobands are in the wrong orientation if the view is horizontally flipped
This fixes that
Note that we could also consider making a better indication of horizontally flipped status when cytobands are visible. The <<< chevrons from when the cytoband is not present are not used when the cytoband is present
> Fix display of cytobands when horizontally flipped

- products/jbrowse-img/package.json
- products/jbrowse-img/src/index.js
- yarn.lock
this approach at polyfilling specifically targets the jbrowse/img package instead of trying to make it part of core
> Add abortcontroller polyfill to jbrowse-img to allow it to run under node 14

- packages/core/rpc/BaseRpcDriver.test.ts
- packages/core/rpc/BaseRpcDriver.ts
- packages/core/rpc/MainThreadRpcDriver.ts
- packages/core/rpc/WebWorkerRpcDriver.ts
- products/jbrowse-desktop/src/rpc.worker.ts
- products/jbrowse-web/src/rpc.worker.ts
I first noticed a problem when I tried using an ESM plugin, and it seemed to make the web worker get stuck. It turned out that the little bit of additional time to load the plugin made it so that the RPC driver tried to call the first RPC method before the RPC client on the worker was ready. I also noticed when testing that sometimes the worker tried to get the message that had the worker boot configuration after it had already been sent, resulting in the RPC setup getting stuck.
The first step to fixing this was to make `makeWorker` on the RPC drivers be asynchronous. This required changing other functions in the drivers to be async as well, but it's not part of the code that is accessible to plugins, so I don't think it will break anything.
After making `makeWorker` async, I was able to …
> Fix bug where web worker would sometimes be called before it was ready

- products/jbrowse-img/src/index.js
- yarn.lock
Currently running jb2export will finish quickly and print out "Finished rendering 1.24s" for example, but the process will stay running. This may be due to an autorun or something keeping nodejs alive.
We could try to dig into why it is kept alive, but doing a process.exit after the image is generated seems reasonable also
This would fix an older issue open at https://github.com/GMOD/jb2export/issues/6
> Exit process after rendering to speed up jb2export

- plugins/alignments/package.json
- yarn.lock
There was an update in @gmod/bam v1.1.13 for optimizing BAM but it had a slightly inaccurate calculation for sequence apparently. The @gmod/bam v1.1.13 was updated in this repo in #2767 but  wasn't released in a jbrowse-web/desktop release yet.
Example link
works v1.6.5
https://jbrowse.org/code/jb2/v1.6.5/?config=test_data%2Fconfig_demo.json&session=share-RrN9QmtRAN&password=k97Zv
fails main
https://jbrowse.org/code/jb2/main/?config=test_data%2Fconfig_demo.json&session=share-RrN9QmtRAN&password=k97Zv
works this branch
https://jbrowse.org/code/jb2/bam_fix/?config=test_data%2Fconfig_demo.json&session=share-RrN9QmtRAN&password=k97Zv
> Fix for BAM file sequence calculation

- config/jest/crypto.js
- jest.config.js
fixes #2794 
The polyfills `window.crypto.getRandomValues` in the tests since it isn't implemented in JSDOM.
> Polyfill window.crypto.getRandomValues in tests

- packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
- packages/core/ui/theme.test.ts
- packages/core/ui/theme.ts
- plugins/config/src/ConfigurationEditorWidget/components/CallbackEditor.js
- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.js
- plugins/config/src/ConfigurationEditorWidget/components/SlotEditor.js
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.js.snap
This is a possible helper for #1402
Adds collapsible sections to the config editor. All sections are expanded by default, but they can be collapsed. The animation on collapsing is disabled so it happens quickly.
I wasn't able to make the configuration editor for the long callback strings get smaller (be contained in the width of the drawer) but you can sidescroll now (overflow:none is removed)
live link
https://jbrowse.org/code/jb2/accordion_config_editor/?config=test_data%2Fvolvox%2Fconfig.json&session=share-BfuDrTSD5P&password=LFGyt
> Collapsible accordion sections in configuration editor

- plugins/authentication/src/OAuthModel/model.tsx
Prompted by [this comment](https://github.com/GMOD/jbrowse-components/pull/2808#issuecomment-1067390189), this makes it so the `codeVerifierPKCE` is created only if an OAuth flow is started, where before it created it any time an OAuth account model was created (which is any time an OAuth account exists in the config).
> Create codeVerifierPKCE only when needed

- README.md
This adds some helper instructions to the README for installing additional pre-requisites for the canvas package when pre-built binaries are not available.
> Add note about additional pre-requisites to README

- website/docs/config_guide.md
- website/release_announcement_drafts/v1.6.6.md
about two weeks since last release, includes a fix for @bbimber and other misc stuff
```
* Other
* [#2799](https://github.com/GMOD/jbrowse-components/pull/2799) Exit process after rendering to speed up jb2export ([@cmdcolin](https://github.com/cmdcolin))
* [#2793](https://github.com/GMOD/jbrowse-components/pull/2793) Add abortcontroller polyfill to jbrowse-img to allow it to run under node 14 ([@cmdcolin](https://github.com/cmdcolin))
* [#2761](https://github.com/GMOD/jbrowse-components/pull/2761) Add a --clean argument to `jbrowse upgrade` to clean up old files ([@cmdcolin](https://github.com/cmdcolin))
* [#2760](https://github.com/GMOD/jbrowse-components/pull/2760) Make a configurable refNameColumn in RefNameAliasAdapter ([@cmdcolin](https://github.com/cmdcolin))
* …
```
> v1.6.6 release announcement

- products/jbrowse-desktop/src/rpc.worker.ts
Fixes #2818 
This copies `rpc.worker.ts` from web to desktop. They had diverged a bit in form, but were still doing the same thing, so this hopefully makes them easier to maintain. #2818 was caused by #2798 incorrectly applying the the same change to both these files.
> Fix bug in desktop where first track gets stuck loading

- plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx
- plugins/comparative-adapters/package.json
- plugins/dotplot-view/package.json
- plugins/gff3/package.json
- plugins/gtf/package.json
- plugins/spreadsheet-view/package.json
- plugins/variants/package.json
- yarn.lock
Bumps @gmod/bgzf-filehandle for fix in https://github.com/GMOD/bgzf-filehandle/pull/57
Was found to have a 5.5x performance improvement in a particular short read example with high coverage reads
> Add optimization for BAM and unzip operations

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
- plugins/wiggle/src/LinePlotRenderer/LinePlotRenderer.js
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This PR #2678 produced a bad layout on wiggle type tracks
xref
https://jbrowse.org/code/jb2/v1.6.6/?config=test_data%2Fvolvox%2Fconfig.json&session=share-pQCVXdXf9X&password=fdako
prev version
https://jbrowse.org/code/jb2/v1.6.5/?config=test_data%2Fvolvox%2Fconfig.json&session=share-pQCVXdXf9X&password=fdako
we don't want a scrollbar
this PR reverts the TrackContainer part of #2678
> Fixup scroll on wiggle tracks with trackLabels->offset

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
There is a UI bug where selecting the tracklabels "offset" option doesn't update the UI in 1.6.7, a knock on effect of fixing a bug from 1.6.6
> Fix tracklabels positioning not updating in UI after user selection

- packages/core/rpc/BaseRpcDriver.test.ts
- packages/core/rpc/BaseRpcDriver.ts
- packages/core/rpc/RpcManager.ts
- packages/core/rpc/configSchema.ts
- products/jbrowse-web/src/Loader.tsx
As discovered with @cmdcolin yesterday, there was a `workerCount` property in `BaseRpcDriver` that was set to 0 and had no way to change it, meaning the worker count was always auto-calculated. We also realized that the config for the worker was not getting passed to the worker driver. This fixes that by passing the worker configs to the drivers and then reading `workerCount` out of the config. You can specify a certain number of workers like this:
```json
{
"configuration": {
"rpc": {
"drivers": {
"WebWorkerRpcDriver": {
"type": "WebWorkerRpcDriver",
"workerCount": 2
}
}
}
}
}
```
This also contains a bug fix related to #2798. As a consequence of that change, if you had a lot of tracks open when the page loaded, it would sometimes create some unused workers, but this PR fixes that.
> Allow user to specify number of workers

- packages/core/rpc/BaseRpcDriver.ts
Currently the formula for getting number of web workers is a bit odd. (#cores -2) /3. probably an ad-hoc formula
On my machine it produces 5 workers (16 cores-2/3 = 4.666 Math.ceil to 5)
I think 5 on my machine with many cores is reasonable, if it used a lot more it would probably go too crazy (its a laptop...fans would take off)
But, on a 4 core AWS instance doing profiling tests, it is only getting 1 worker thread. I think maxing out hardware cores -1 for jbrowse, with a cap on 5 cpu's, could be a reasonable change to the formula
> Change calculation for number of webworkers for web/desktop

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap
Removes the ability to attempt to add a track or connection when using an embedded component. The UI is hidden based on the existence of the session.addTrackConf property.
resolves https://github.com/GMOD/jbrowse-components/issues/1634 and part of https://github.com/GMOD/jbrowse-components/issues/2516
> Hide add track and connection menu items when using embedded component

- packages/core/util/index.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
- plugins/alignments/src/util.ts
Fixes #2832 
The sparse CRAM may be relevant in some cases but I found that for totally empty chromosomes, our color-by-methylation/modifications was trying to fetch the large sequence regions
This only fetches if features are found to draw and the methylation/modifications mode is used
> Fix alignments tracks loading excessive data on chromosomes where no features exist

- plugins/svg/src/SvgFeatureRenderer/components/FeatureGlyph.tsx
- plugins/svg/src/SvgFeatureRenderer/components/util.ts
Before, can see feature is overlapping another (arrow in middle of feature)
After, no overlapping features
Fixes #1204
> Fix layout of small features without labels for SvgFeatureRenderer

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.js
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap
Currently the tests and the live webapp have warnings in dev mode saying
`Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.`
This changes the booleans (which I think eventually puts a raw session.addTrackConf as a react child) into ternaries (article with similar recommendation :) https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx )
> Fix warnings in React for rendering functions as children

- plugins/svg/src/SvgFeatureRenderer/components/Box.tsx
Fixes #2735 
Uses a heuristic that doesn't draw introns only if the feature is a subfeature
> Avoid drawing intron subfeatures for gene glyphs

- plugins/alignments/src/LinearPileupDisplay/components/ColorByModifications.tsx
- plugins/alignments/src/LinearPileupDisplay/components/ColorByTag.tsx
- plugins/alignments/src/LinearPileupDisplay/components/FilterByTag.tsx
- plugins/alignments/src/LinearPileupDisplay/components/SetFeatureHeight.tsx
- plugins/alignments/src/LinearPileupDisplay/components/SetMaxHeight.tsx
- plugins/alignments/src/LinearPileupDisplay/components/SortByTag.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/linear-genome-view/src/LinearBasicDisplay/components/SetMaxHeight.tsx
Draw all bases in the pileup with a setting called "Per-base lettering" (alongside the "Per-base quality")
It is a nice sanity check for alignments viewing
> Add option to color all the letters on all the reads to the pileup renderer

- packages/core/package.json
- packages/core/util/layouts/BaseLayout.ts
- packages/core/util/layouts/GranularRectLayout.ts
- packages/core/util/layouts/PrecomputedLayout.ts
- packages/core/util/offscreenCanvas/ponyfill.ts
- packages/core/util/offscreenCanvas/types.ts
- plugins/wiggle/src/WiggleBaseRenderer.tsx
- products/jbrowse-desktop/package.json
- products/jbrowse-web/package.json
- yarn.lock
Marks serialized layouts, wiggle-type render results, and shimmed offscreen canvas serializations as containing no transferables.
Gets a good performance boost, but I haven't measured exactly how much.
depends on https://github.com/cmdcolin/librpc-web/pull/1 being merged and released as 1.2.0
> Limit peekTransferables

- plugins/svg/src/SvgFeatureRenderer/components/Arrow.tsx
- plugins/svg/src/SvgFeatureRenderer/components/ProcessedTranscript.tsx
- plugins/svg/src/SvgFeatureRenderer/components/Segments.tsx
After the new glyph style (#2775) the arrows pointed the wrong way in horizontally flipped mode, this fixes it
> Fix strand on arrows in reverse mode

- packages/core/ui/AssemblySelector.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/2745
Uses a "local storage" hook. It also uses a useEffect to update the parent component onChange, becuase the component acts like a controlled component (https://reactjs.org/docs/forms.html#controlled-components) so needs to immediately (onLoad) update the parent component with a new value with the useEffect if the AssemblySelector finds a value in the localStorage entry. The alternative to this is propagating useLocalStorage to all usages of AssemblySelector but this doesn't seem like a bad approach here
> Make assembly selector remember your last selected assembly

- plugins/linear-comparative-view/src/LinearComparativeView/components/LinearComparativeView.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/components/RubberBand.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx
Fixes #2658 
I don't know if there is a good way to style it but I found it is maybe good not to be too visually intrusive, so in this example, it is invisible. But, if you mouse over it, a clearly visible vertical guide that goes over the full height of both views appears
And then after clicking and dragging
> Multi-level synteny rubberband

- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.js
Without this PR, the color editor popup can get cutoff by the page
This PR adds some padding
Similar thing exists in the ViewContainer/App to add padding to the bottom of the stack of views
before
after
> Add padding at the bottom of the configuration editor to help color editing popup being cutoff

- plugins/alignments/src/BamAdapter/BamAdapter.ts
- plugins/alignments/src/CramAdapter/CramAdapter.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
- plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
Fixes #2886
Directly passes the filterBy object to the adapter, which performs filtering
This is in contrast to passing jexl filtering expressions that are evaluated by the renderer code https://github.com/GMOD/jbrowse-components/blob/4be115ed00adb0bda3f951141e840ede90d8d2a0/packages/core/pluggableElementTypes/renderers/FeatureRendererType.ts#L185-L200
> Optimize filtering on alignments tracks

- packages/core/package.json
- packages/core/tsconfig.json
This goes back to using babel for the core build since tsc that was there was outputting ESM which could have trouble with e.g. jbrowse-img
Need better testing on that, and possibly it would be good to have a "dual package" with both ESM/CJS (similar to many of our parsers) but might have to be careful with the ESM in particular since PluginLoader has the import from variablename which bundlers hate
> Back to babel for core build

- packages/core/util/io/index.ts
- products/jbrowse-desktop/craco.config.js
- products/jbrowse-web/craco.config.js
Fixes #2898 
Uses the "electron-renderer" target from webpack, and also requires loading the alternative localFile util class instead of generic-filehandle's because it is possible the "browser" package.json field is too strict in this case
> Fix electron localfile

- packages/core/ui/AssemblySelector.tsx
- plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx
The import form for e.g. linearsyntenyview had an infinite loop with the new AssemblySelector feature that remembers your last selection.
This fixes by only calling a callback if it is different from what you passed in. It also improves ergonomics of the AssemblySelector's remember feature by associating the last selection with specific URL paths and config files
> Remember assembly selector selections based on hostname/config and avoid infinite loop

- products/jbrowse-desktop/src/rootModel.ts
Currently the "Open assembly..." menu item in jbrowse-desktop did nothing
This makes sure to add the assemblies in response to the Open sequence dialog's onclose callback, which provides us with configurations
> Fix the 'Open assembly' menu item in jbrowse desktop

- packages/core/PluginLoader.ts
- packages/core/PluginManager.ts
- products/jbrowse-desktop/src/StartScreen/util.tsx
- products/jbrowse-desktop/src/rpc.worker.ts
- products/jbrowse-react-circular-genome-view/src/loadPlugins.ts
- products/jbrowse-react-linear-genome-view/src/loadPlugins.ts
- products/jbrowse-web/src/Loader.tsx
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/rpc.worker.ts
This is a concept that can help import ESM using a callback, which avoids bundler specific behavior of `/*webpackIgnore:true */` being embedded in core (helps avoid embedded users getting the Critical dependency of an expression also, and embedded users could pass their own fetchESM callback if they want)
Possible fix for https://github.com/GMOD/jbrowse-components/issues/2638
> Callback to import ESM from PluginLoader

- package.json
- packages/__mocks__/react-use-measure.ts
- packages/core/package.json
- packages/core/ui/App.tsx
- packages/core/ui/ViewContainer.tsx
- plugins/breakpoint-split-view/package.json
- plugins/linear-comparative-view/package.json
- plugins/linear-genome-view/package.json
- products/jbrowse-react-circular-genome-view/package.json
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/ViewContainer.tsx
- products/jbrowse-react-circular-genome-view/src/declare.d.ts
- products/jbrowse-react-linear-genome-view/package.json
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/ViewContainer.tsx
- products/jbrowse-react-linear-genome-view/src/declare.d.ts
- yarn.lock
Changes embedded components to use react-measure instead of react-use-dimensions
We at one point had react-sizeme, react-measure, and react-use-dimensions
After this PR, just react-measure :)
Even react-measure could be considered old with the HOC pattern (use-dimensions is nice as a hook) but it does not use ResizeObserver which means it could miss some resize too e.g. if elements shift around on the page (only listens to window.resize for changes)
> Use react-use-measure instead of react-use-dimensions

- packages/core/PluginLoader.ts
- packages/core/package.json
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/src/StartScreen/util.tsx
This PR is similar to https://github.com/GMOD/jbrowse-components/pull/2891 but for jbrowse-desktop, which can import CJS modules
Without this PR, a 'http' module polyfill (stream-http) is bundled in jbrowse-web
screenshots with `npx source-map-explorer build/static/js/*.js` in jbrowse-web
before (see stream-http)
after (stream-http removed)
Also uses `window.require` instead of `__non_webpack_require__` which sort of ensures that the electron require machinery is used instead of bundled
> Use a user-supplied fetchCJS callback to import CJS plugins

- products/jbrowse-react-circular-genome-view/src/createModel/createSessionModel.ts
- products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts
This avoids using the lazy import for AboutDialog for the embedded components.
This is a particular issue that affected vite only. xref https://github.com/GMOD/jbrowse-components/issues/2896
The issue does not affect our webpack configs
Possibly an esm build of core could help avoid this workaround, but this might be challenging with the flat/import-from-subdirectory style. Would maybe need to use exports:{} in package.json to explicitly allow legal core import paths
> Fix AboutDialog under vite for embedded components

- website/release_announcement_drafts/v1.7.0.md
Placeholder for new release :) 
```
* Other
* [#2887](https://github.com/GMOD/jbrowse-components/pull/2887) Optimize filtering on alignments tracks ([@cmdcolin](https://github.com/cmdcolin))
* [#2879](https://github.com/GMOD/jbrowse-components/pull/2879) Multi-level synteny rubberband ([@cmdcolin](https://github.com/cmdcolin))
* [#2874](https://github.com/GMOD/jbrowse-components/pull/2874) Optimizations for rendering long syntenic alignments e.g. CHM13 vs GRCh38 ([@cmdcolin](https://github.com/cmdcolin))
* [#2872](https://github.com/GMOD/jbrowse-components/pull/2872) Better connection between paired-end alignments in breakpoint split view and optimizations ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#2781](https://github.com/GMOD/jbrowse-components/pull/2781) Add floating …
```
> Add v1.7.0 release announcement

- products/jbrowse-img/package.json
- products/jbrowse-img/src/index.js
Currently @jbrowse/img fails in 1.7.0 because RemoteFileWithRangeCache uses Headers/Response objects, which are not defined in node since  we stopped using cross-fetch as a polyfill inside of http-range-fetcher
That basically means we were sort of "cryptically dependent" on http-range-fetcher polyfilling these variables
This more explicitly polyfills fetch in @jbrowse/img. Soon node will have fetch built in by default but until then...
> Manually polyfill fetch in @jbrowse/img

- website/src/pages/download.mdx
This PR adds a new button to the download page for JBrowse Web. It also removes the screenshot (to get more info on the screen at once), and changes a little wording.
The changes are motivated by watching users browse for jbrowse-web during a zoom call. It seemed like having a more directly accessible button would help to guide them to the JBrowse Web install.
> Add download link for jbrowse web on downloads page

- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Since #2571, if a track doesn't have an adapter, it throws an error. This adds a check in `estimateRegionStats` that allows a track to work without an adapter.
The context for this change is Apollo, which doesn't get its track data from a typical adapter.
> Allow track to not have adapter

- packages/text-indexing/package.json
- packages/text-indexing/tsconfig.build.json
- plugins/jobs-management/package.json
- plugins/jobs-management/tsconfig.build.json
- plugins/text-indexing/package.json
- plugins/text-indexing/tsconfig.build.json
The release of webpack 5 uses typescript project references in a file called tsconfig.build.json to correctly generate types
This PR propagates those changes to the newly landed text-indexing/jobs related packages (this change will be most useful if and when the packages are published to npm, so that they include .d.ts files)
> Add tsc types compilation/project references to text-indexing commands

- plugins/gtf/src/GtfAdapter/GtfAdapter.ts
Possible fix for https://github.com/GMOD/jbrowse-components/issues/2681
loading a random location on chr1 for a 19MB gtf.gz file from UCSC
This branch, ~10s
Main branch, ~48s
approx tracing differences
this branch
main branch
> Optimize gtf by only parsing lazily per-refName

- plugins/svg/src/SvgFeatureRenderer/components/Box.tsx
- plugins/svg/src/SvgFeatureRenderer/components/util.ts
Possible fix for #1887
before
after
this feature has CDS subfeature so triggers "hasSubSub" in the util
There are a number of weird workarounds here, but it does solve the proximate problem
Sort of unrelated but I think it may be worth making the layout part of a pre-processing routine. The way the code makes the layout as a side product of rendering might not be ideal
> Render gene with CDS subfeatures properly

- plugins/linear-comparative-view/src/ReadVsRef.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/sequence/src/referenceSeqTrackConfig.ts
Adds a config slot called "name" to the Reference sequence track config, which is optional, and is otherwise filled in by "Reference Sequence (assembly name)" like it is currently on master
> Use the name "Read Sequence" for the read vs ref view

- website/release_announcement_drafts/v1.7.5.md
```
* `core`
* [#2885](https://github.com/GMOD/jbrowse-components/pull/2885) Reduce serialization overhead on alignments tracks and access feature details asynchronously ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#2935](https://github.com/GMOD/jbrowse-components/pull/2935) Use the name "Read Sequence" for the read vs ref view ([@cmdcolin](https://github.com/cmdcolin))
* [#2916](https://github.com/GMOD/jbrowse-components/pull/2916) Add vite setup to our embedded component demos ([@cmdcolin](https://github.com/cmdcolin))
* [#2927](https://github.com/GMOD/jbrowse-components/pull/2927) Optimize gtf by only parsing lazily per-refName ([@cmdcolin](https://github.com/cmdcolin))
* [#2928](https://github.com/GMOD/jbrowse-components/pull/2928) Add vanillajs/script tag loading embedded …
```
> Add v1.7.5 release announcement

- products/jbrowse-desktop/craco.config.js
Without this change to craco.config.js, on jbrowse-desktop, we get an error with usage of anything that uses CRAM, TwoBit, etc (which have a particularly strict Buffer.isBuffer from @gmod/binary-parser)
https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined
The error is "argument buffer is not a Buffer object"
> Fix loading CRAM, TwoBit, and other modules that use @gmod/binary-parser on jbrowse desktop

- packages/core/assemblyManager/assemblyManager.ts
If no assemblyName is passed to ref name renaming, we avoid performing an infinite wait
> Avoid stalling on undefined assemblyName during ref name renaming

- packages/core/util/index.ts
- plugins/alignments/package.json
- plugins/alignments/src/CramAdapter/CramSlightlyLazyFeature.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/components/Tooltip.tsx
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
- yarn.lock
This can save about ~1second in generateCoverageBins calls on a 20kb region
Allocates less nested objects
On 200x coverage shortreads from jb2profile
Time spent in generateCoverageBins specifically:
This branch 2.82s
Main branch 3.6s
Possibly we could also bin multiple bp into a single bin (jb1 does this) and or use skips_and_dels (another jb1-ism) to optimize further, but we would need to be careful about binning multiple bp into a single bin with snps/modifications as those should probably not be aggregated
> Optimization for SNPCoverageAdapter and CRAM parsing

- component_test/craco.config.js
- demos/jbrowse-react-circular-genome-view-cra5/craco.config.js
- demos/jbrowse-react-linear-genome-view-cra5/craco.config.js
- package.json
- products/jbrowse-desktop/craco.config.js
- products/jbrowse-react-linear-genome-view/.storybook/main.js
- products/jbrowse-web/craco.config.js
- yarn.lock
Various MUI elements and react-error-boundary have issues with @types/react v18
I have subscribed to an react-error-boundary issue so if it gets fixed, can revisit. The MUI ones may remain tricky though. For now we can pin to @types/react v17
xref https://twitter.com/reactjs/status/1512453230504124420
> Pin to @types/react v17 to fix typescript issues with v18

- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
Small detail, but we are able to capture a clip indicator when it goes "past the feature end" (the soft clips are technically not stored interbase, so to get them, we need to go past the feature end)
demo
main
https://jbrowse.org/code/jb2/main/?config=test_data%2Fvolvox%2Fconfig.json&session=share-fBa97hv8H8&password=YL7ng
this branch
https://jbrowse.org/code/jb2/clip_indicator_cliff/?config=test_data%2Fvolvox%2Fconfig.json&session=share-fBa97hv8H8&password=YL7ng
> Allow getting clip indicator after feature end

- .eslintrc.json
This PR re-enables the `"prettier/prettier"` lint rule as a warning. This allows us to run `eslint --fix` to fix prettier formatting warnings.
> Re-enable eslint autofix for prettier rules

- plugins/legacy-jbrowse/src/JBrowse1Connection/jb1ToJb2.ts
We now have in-memory GFF3 and GTF adapters, so this PR makes it so that JB1 connections that use the `JBrowse/Store/SeqFeature/GFF3` or `JBrowse/Store/SeqFeature/GTF` store classes use those adapters instead of displaying an "unsupported" message.
> Support in-memory GFF3 and GTF in JBrowse 1 connection

- plugins/alignments/package.json
- plugins/linear-comparative-view/src/ReadVsRef.tsx
- yarn.lock
Currently, there is a routine to get the primary read if you start with a supplementary read for linear ReadVsRef visualization. It requests reads overlapping a single base pair where the start of the primary read is. One issue though is there is likely an off-by-one error in specifically CRAM feature fetching where if I request reads overlapping ctgA:0-1, it does not return anything. Making it request ctgA:0-2 is a workaround, but fixing the off by one would be worthwhile
Also, fixes error handling on the read vs ref dialog (previously, the error wasn't displayed)
> Fix read vs ref on certain CRAM files

- plugins/alignments/src/BamAdapter/BamAdapter.ts
- plugins/alignments/src/CramAdapter/CramAdapter.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
- plugins/alignments/src/PileupRenderer/PileupLayoutSession.ts
The optimization for filterBy caused the filter reads function to break in the pileup track. This restores functionality by
1) Using readName instead of name in the filter by read name function
2) Recreating the layout after a filterBy is applied
3) Serializing a clone of the filterBy object to make sure it gets recognized by observability systems when it is updated
> Fix filter functionality on pileup tracks

- plugins/alignments/src/BamAdapter/MismatchParser.test.ts
- plugins/alignments/src/BamAdapter/MismatchParser.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
- plugins/alignments/src/util.ts
Found a crash displaying modifications, example share link
https://jbrowse.org/code/jb2/v1.7.0/?config=test_data%2Fconfig_demo.json&session=share-Jfg7Adjvai&password=ZCjW1
This is probably due to displaying a modifications that was called on a soft clipped area of a read (e.g. a part of the read that did not properly map to the reference genome)
Instead of trying to display these (and currently, causing a crash) this PR proposes to filter them out
> Fix crash displaying modifications called on softclipped regions of reads

- plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/SearchBox.tsx
Possible shortcut for refnameautocomplete
If the user input looks like a locstring then we can shortcircuit and not perform a text search
This shortcut already exists for a locstring that matches exactly a chromosome name in the assembly's refname list (or alias)
So, this just expands the shortcut to detect if it matches the a locstring with a colon, splitting on the colon and assuming the start of that is a locstring
That wouldn't perfectly apply for assembly based locstrings but the majority use case would be non-assembly-including locstrings probably
> Avoid performing a text index search if input looks like a locstring

- plugins/dotplot-view/src/DotplotRenderer/DotplotRenderer.ts
- test_data/yeast_synteny/config.json
The CIGAR rendering on dotplot was not working after refactoring made awhile back, this restores it though!
It uses a path with multiple lineTo inside the loop, and a single stroke for all the segments of the line
> Fix link on yeast synteny demo and fix CIGAR rendering on dotplot

- products/jbrowse-react-linear-genome-view/package.json
- products/jbrowse-react-linear-genome-view/src/corePlugins.ts
Prompted by @scottcain's use of the embedded LGV, this PR proposes adding the legacy JBrowse plugin (which has the NCList adapter) to the embedded LGV and React component. I'm not sure if this is a good idea or not, but I thought it would be good to have a place to discuss it. Here is the size difference of the UMD builds:
```
$ du -k without_legacy_plugin/*
14088   dist/react-linear-genome-view.umd.development.js
12908   dist/react-linear-genome-view.umd.development.js.map
2704    dist/react-linear-genome-view.umd.production.min.js
$ du -k with_legacy_plugin/*
14260   with_legacy_plugin/react-linear-genome-view.umd.development.js
13064   with_legacy_plugin/react-linear-genome-view.umd.development.js.map
2748    with_legacy_plugin/react-linear-genome-view.umd.production.min.js
```
So …
> Add plugin-legacy-jbrowse to React LGV core plugins

- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
Currently SNPs and indels are not drawn in modifications mode, including in SNPcoverage where indels can affect coverage
This restores drawing indels, SNPs are still hidden
Before
After
> Draw indels in modifications/methylation mode

- website/release_announcement_drafts/v1.7.8.md
```
* [#2960](https://github.com/GMOD/jbrowse-components/pull/2960) Avoid performing a text index search if input looks like a locstring ([@cmdcolin](https://github.com/cmdcolin))
* [#2954](https://github.com/GMOD/jbrowse-components/pull/2954) Support in-memory GFF3 and GTF in JBrowse 1 connection ([@garrettjstevens](https://github.com/garrettjstevens))
* [#2964](https://github.com/GMOD/jbrowse-components/pull/2964) Fix crash displaying modifications called on softclipped regions of reads ([@cmdcolin](https://github.com/cmdcolin))
* [#2965](https://github.com/GMOD/jbrowse-components/pull/2965) Fix filter functionality on pileup tracks ([@cmdcolin](https://github.com/cmdcolin))
* [#2953](https://github.com/GMOD/jbrowse-components/pull/2953) Fix "Open" button on LGV ImportForm …
```
> Add v1.7.8 announcement

- plugins/data-management/src/AddTrackWidget/model.ts
* fixes https://github.com/GMOD/jbrowse-components/issues/2972
* sets textIndexTrack to true
> Index track by default on add track widget

- jest.config.js
- products/jbrowse-web/src/tests/Authentication.test.js
This ignores .d.ts and the specific makeWorkerInstance file (since it uses a new Worker syntax, which jest has trouble with, and indeed, we mock this module out when doing our actual tests)
> Remove errors related to test coverage in CI

- packages/core/util/offscreenCanvas/Canvas2DContextShim/context.ts
- packages/core/util/offscreenCanvas/Canvas2DContextShim/types.ts
Was a regression after refactoring the offscreen canvas ponyfill. 
Xref https://sourceforge.net/p/gmod/mailman/message/37661575/
With the buggy ponyfill, it prevents RNA-seq SNPcoverage from being viewed on safari/firefox
> Fix bezierCurveTo ponyfill on firefox

- plugins/linear-genome-view/src/LinearGenomeView/components/ExportSvgDialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
Simple modification to the Export SVG dialog box to allow user specified filename for the SVG export
> Allow choosing filename svg export

- website/release_announcement_drafts/v1.7.9.md
```
* `core`
* [#2483](https://github.com/GMOD/jbrowse-components/pull/2483) Add setting to color by query score per alignment for dotplot, support HTML in config slot descriptions ([@cmdcolin](https://github.com/cmdcolin))
* [#2983](https://github.com/GMOD/jbrowse-components/pull/2983) Set target=_blank by default in user HTML links ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#2989](https://github.com/GMOD/jbrowse-components/pull/2989) Fix bezierCurveTo ponyfill on firefox ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#2977](https://github.com/GMOD/jbrowse-components/pull/2977) Respect --indexFile option when adding VCF and BED tracks ([@heavywatal](https://github.com/heavywatal))
* [#2974](https://github.com/GMOD/jbrowse-components/pull/2974) Fix track indexing being …
```
> Add v1.7.9 announcement

- plugins/alignments/src/BamAdapter/MismatchParser.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/components/Tooltip.tsx
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
Adds the reference letter, e.g. "REF (T)", to tooltip in the SNPCoverageDisplay if you are mouse-overed on a mismatch. This is a follow up from some suggestions @gringer  made recently in #2833 
Also includes a better calculation of percents when including indels (previously used a "total" score that is subtracted against when encountering a deletion, now counts the deletion against a new variable called "all" that is not subtracted against when encountering a deletion)
Before
After
> Add reference base and correct percentage calculations to tooltip on SNPCoverage display

- packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
- yarn.lock
Automatically generates clickable links to files in about track panels or anywhere else where contents look like links in the BaseFeatureDetails attribute panel
Also creates a custom element for UriLocation objects, and resolves relative paths relative to the baseUri, so that files that aren't absolute URLs can get included. This makes it easier for the user to easily download the data because resolving such a file path manually is not straightforward without this
> Generate clickable links to track data in about track dialog

- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
The !== comparison to [] is not a valid operation as it would always be false
e.g. it is referential equality, whether it refers to the exact same array, so with this even []!==[] is true
Just a small fix. This may or may not actually improve search results, haven't tested
> Small fix to rankSearchResults logic

- plugins/linear-genome-view/src/LinearGenomeView/components/HelpDialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.test.ts
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
Fixes #2978
Allows you to enter e.g. ctgA 1 100 to navigate to ctgA:1-100. Can be any type of whitespace separated
The code first tries to interpret this as a sequence of locstrings first, to handle our usage of e.g. ctgA ctgB to navigate to multiple chromosomes, but if one of the inputted sequences is not a locstring it throws an exception which we catch and then retry using whitespace separated refName,start,end
> Allow whitespace separated refname,start,end type locstring

- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/linear-genome-view/src/BaseLinearDisplay/components/BaseLinearDisplay.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/Tooltip.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Fixes #2996
Customizes the onMouseOver renderProp for the pileup display model to fetch the moused over feature from the remote (similar to a click) and then runs the mouseover callback on it
This could be considered possibly a slow step as it may run many rpc calls quickly while doing this, but in testing it out, it seemed quite fast
> Fix mouseover display of read name to alignments track

- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/text-index.ts
Fixes #2959 
Let's you run a command like
```
jbrowse text-index --file t1.vcf.gz --fileId t1
```
By default, without `--fileId`, then the output assumes the trackId will be t1.vcf.gz  (equal to the filename) but is overridden by `--fileId`
> Allow choosing trackId when using text-index with --file with --fileId

- packages/core/util/types/index.ts
- plugins/linear-comparative-view/src/LaunchLinearSyntenyView.ts
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-genome-view/src/index.ts
- plugins/spreadsheet-view/src/index.ts
- plugins/sv-inspector/src/index.ts
- products/jbrowse-web/src/tests/Loader.test.tsx
- test_data/volvox/config_main_thread.json
- yarn.lock
Adds ability to automatically load a spreadsheet from the spec URL
http://localhost:3000/?config=test_data/volvox/config.json&session=spec-{%22views%22:[{%22type%22:%22SpreadsheetView%22,%20%22uri%22:%22test_data/volvox/volvox.filtered.vcf.gz%22,%22assembly%22:%22volvox%22}]}
prettier output for url
```
{
views: [
{
type: "SpreadsheetView",
uri: "test_data/volvox/volvox.filtered.vcf.gz",
assembly: "volvox",
},
],
};
```
> Add spreadsheet spec

- plugins/dotplot-view/src/DotplotView/model.ts
- plugins/dotplot-view/src/LaunchDotplotView.ts
- plugins/dotplot-view/src/index.ts
- plugins/linear-comparative-view/src/LaunchLinearSyntenyView.ts
- products/jbrowse-web/src/tests/Loader.test.tsx
Example
http://localhost:3000/?config=test_data/volvox/config_main_thread.json&session=spec-{"views":[{"type":"DotplotView","views":[{"assembly":"volvox"},{"assembly":"volvox"}],"tracks":["volvox_fake_synteny"]}]}
Expanded
```
{
views: [
{
type: "DotplotView",
views: [{ assembly: "volvox" }, { assembly: "volvox" }],
tracks: ["volvox_fake_synteny"],
},
],
};
```
> Add dotplot session spec

- website/docs/developer_guide.md
Fixes #2602
Doesn't use a biological example, but demonstrating how to access nodejs system libraries I think is quite valuable, and this change would be an easy fix :)
> Add desktop specific plugin example

- website/docs/quickstart_cli.md
- website/docs/superquickstart_web.md
Uses GNU sort, following @scottcain's report that the genometools sort can be buggy
Command using gnu sort originally from https://www.biostars.org/p/92074/
> Update commands for sorting GFF3 for tabix

- plugins/arc/src/ArcRenderer/configSchema.tsx
I think it is intended for all the linear arc renderer slots to be able to become callbacks, but it is not displayed this way in the user interface since they lack the "contextVariable"
> Fix ability to use callbacks for the linear arc renderer

- package.json
- packages/core/package.json
- packages/core/util/offscreenCanvasPonyfill.tsx
- plugins/wiggle/src/DensityRenderer/DensityRenderer.test.js
- plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.test.js
- products/jbrowse-img/package.json
- products/jbrowse-img/src/index.js
- products/jbrowse-img/src/index.testmod.js
- products/jbrowse-web/src/tests/Loader.test.tsx
- products/jbrowse-web/src/tests/util.js
- yarn.lock
If we detect `isNode` is true, then we use global variables `nodeCreateCanvas` and `nodeImage` to perform canvas operations. These are global variables that apps that know that they run under node can set (namely, @jbrowse/img which runs under node and our integration tests which perform canvas snapshots)
We do not try to use the global variables until client code calls `new Image` or `createCanvas`, which allows us an opportunity to set `nodeCreateCanvas` and `nodeImage` after initialization e.g. doesn't depend on the order that dependencies are included (if we tried to statically detect whether e.g. `nodeCreateCanvas` exists then it would depend on whatever sets global.nodeCreateCanvas to be included first for example, and it is tricky to guarantee order of initialization)
Would maybe …
> Remove node-canvas from @jbrowse/core dependencies

- packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
In deeply nested data in a data grid on base feature details, it may display [object Object] because we call String(object). This changes it to use JSON.stringify, so it will display a bit of json inside the table but it is generally human-readable-enough (was seen in deeply nested data from myvariant.info, now usable on https://github.com/cmdcolin/jbrowse-plugin-biothings-api)
> Avoid displaying [object Object] on deeply nested data in base feature details

- plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.ts
Fixes #3046
Need to make sure to stringify the result. The HTML5 canvas API presumably automatically stringifies the fillStyle object, but canvas2svg needs to do this manually.
It is perhaps a bit surprising that typescript does not catch the Color object as not being a string in our custom fillRect helper function, but this PR should help avoid crash
> Fix export SVG crash on some BigWig tracks

- packages/core/ReExports/modules.tsx
I found that with the MUI upgrades, editing some data grid cells wasn't working in Apollo. I needed `useGridApiContext` to fix it, which wasn't exported before. @cmdcolin, let me know if there's a better way to export these with the recent changes.
> Add more mui/x-data-grid exports

- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
Instead of drawing colorful SNPs, in the modifications view, this proposes that the SNPs be drawn in a simpler black on white
Would be curious if you had any feedback on this design @gringer xref https://twitter.com/gringene_bio/status/1527797881234931712
Example screenshot with this branch
The resulting SNPs look pretty similar to deletion boxes but not exactly the same
> Draw SNPs in modifications/methylation views

- plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx
Was seen because the mouseover, worked on in #3071 does not incorporate CIGARs, just using feature.start and feature.end but it did not match up with what the CIGAR renderings were showing. Flipping the orientation of insertions and deletions fixes the issue
> Fix the display of deletions vs insertions being backwards in synteny view with CIGAR strings

- plugins/alignments/src/BamAdapter/MismatchParser.ts
- plugins/comparative-adapters/src/PAFAdapter/PAFAdapter.ts
- plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx
Inspection of the DNA bases found that what was being rendered as the CIGAR (e.g. yellow and blue insertions/deletions) did not match up properly, so this fixes the issue
> Fix negative strand CIGAR renderings on linear synteny view

- plugins/linear-genome-view/src/LinearGenomeView/index.test.ts
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
Fixes #3083 
This is a one-liner fix in the LGV model with a couple of fixed tests
Intuitively using the app gives reasonable values for rubberband selections (which are the primary user of the moveTo function that we fix here) even with many displayed regions visible (which commonly occurs with show all regions and synteny views)
https://jbrowse.org/code/jb2/fix_zoomto/?config=test_data%2Fconfig_dotplot.json&session=share-qZrNF9OGYz&password=MMo0X can be tested and appear to work ok
> Fix zoom to behavior being inaccurate with many displayed regions visible

- plugins/svg/src/SvgFeatureRenderer/components/FeatureGlyph.tsx
- plugins/svg/src/SvgFeatureRenderer/components/FeatureLabel.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
Currently, there can be a mismatch between the server and the client when hydrating feature labels since they are floated to the right position on the client side, and this can result in the labels being cut off sometimes
The server tries to float the feature labels in the right place,  but a mismatch can still occur because if the user scrolls for example during the time the request is sent to when it is hydrated, it can mismatch.
To help with this, this PR proposes using a useEffect to render the feature only on the main thread (e.g. the useEffect would only be used once hydrated)
There is a caveat for exportSVG which does use the server side to render the features labels in the requested position, there is no main thread "hydration" of the ssr component from the svg export so the …
> Fix labels being cut-off in SVG features by rendering feature labels on main thread

- packages/core/pluggableElementTypes/renderers/FeatureRendererType.ts
- packages/core/rpc/coreRpcMethods.ts
This uses some similar checks to #3084 to show a different error message when a reference sequence track that uses a ChromSizesAdapter or FromConfigRegionsAdapter is opened (mentioned [here](https://github.com/GMOD/jbrowse-components/pull/3084#issuecomment-1182147172)).
Before it said `Error: Data adapter not found`, now it says `Error: Adapter does not support retrieving features`.
> Clarify error message when adapter has no features

- demos/jbrowse-react-linear-genome-view-vite/package.json
- demos/jbrowse-react-linear-genome-view-vite/yarn.lock
- packages/core/package.json
- packages/core/pluggableElementTypes/renderers/FeatureRendererType.ts
- packages/core/tsconfig.build.json
- packages/core/tsconfig.json
Fixes #3091 
Uses tsc instead of babel to compile @jbrowse/core
Outputs module type "commonjs" since it is used under node, and it is difficult to create dual esm/commonjs builds for core (becuase of the "flat" module structure/importing from subpaths)
Simple local testing showed it fixed the vite 3.0.0 build
> Fix use of embedded components with vite 3.0 using tsc to compile @jbrowse/core

- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
- plugins/wiggle/src/MultiLineRenderer/configSchema.ts
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/WiggleDisplayComponent.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/models/model.tsx
- plugins/wiggle/src/MultiRowLineRenderer/configSchema.ts
- plugins/wiggle/src/MultiRowXYPlotRenderer/configSchema.ts
- plugins/wiggle/src/MultiXYPlotRenderer/configSchema.ts
- plugins/wiggle/src/XYPlotRenderer/configSchema.ts
- plugins/wiggle/src/drawxy.ts
- products/jbrowse-web/src/tests/BasicLinearGenomeView.test.tsx
Currently we have the "no fill" mode on XYPlotRenderer type tracks
This helps draw a scatterplot style rendering
It can be useful to emphasize those scatterplot points, so this PR adds an "emphasis" setting that is toggleable
current main: all the no-fill points are quite tiny
this branch: emphasis mode makes points 2px in size
> Add "emphasis" mode for no fill/scatterplot mode in XYPlot type renderings

- plugin-development-tools/src/createRollupConfig.ts
In yarn 2+ workspaces, packages that are shared in the workspace don't show up under `node_modules`, they show up under a `__virtual__ ` folder. This adds handling of that to the plugin rollup config, so that shared workspace packages are processed by rollup correctly.
> Add __virtual__ to rollup files to process

- plugins/svg/src/SvgFeatureRenderer/components/FeatureGlyph.tsx
- plugins/svg/src/SvgFeatureRenderer/components/FeatureLabel.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.test.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgOverlay.tsx
- plugins/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.tsx.snap
Currently, clicking a feature on the SVG track produces a re-rendering of all the features which can produce noticeable lag
This PR avoids this, and adds a test to make sure it stays that way. Incidentlally, that fix is a one liner and a regression, we just need to not dynamically create function props from within the render. This is the line https://github.com/GMOD/jbrowse-components/compare/test_rerender_svg?expand=1#diff-064ed32393d9637238ee6b5daa2f1ebe67829b1a3b719dc01cbd510ff45f6176R227
Also typescriptifies the SVG rendering unit tests to help ensure the right "API" is used
> Improve SVG performance by avoiding re-render when feature is clicked

- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.tsx
The "level arrow" in the ConfigurationEditor is currently "🡒" (Rightwards Sans-Serif Arrow U+1F852), which does not render on my computer, so it looks like this:
Since I recently re-installed my OS, I'm guessing there are other systems that have trouble with that arrow character as well. This PR changes it to "➔" (Heavy Wide-Headed Rightwards Arrow U+2794), which I think is more common. It looks like this for me:
If someone with a Mac (@rbuels or @carolinebridge-oicr?) could double-check for me that it looks fine on there, that would be great. Session link: https://s3.amazonaws.com/jbrowse.org/code/jb2/config_editor_level_arrow/index.html?session=share-uNPMnDdnXA&password=QunGJ
> Change arrow in ConfigurationEditor

- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
This standardizes the ideogram LGV menu item so that it is more like the others.
**Before:**
**After:**
It also changes "Show gridlines" to "Show guidelines". Since there are no horizontal lines, only vertical ones, that are hidden/shown, it isn't a grid, so I think "guidelines" is more clear. It could also be "Show vertical guidelines" to be more explicit, or something else entirely if anyone has suggestions.
> Make ideogram menu item similar to others

- products/jbrowse-desktop/src/rootModel.ts
- products/jbrowse-web/src/rootModel.ts
- website/docs/user_guide.md
<kbd><kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd></kbd> for redo wasn't working for me, since it was using the `event.key` attribute being "z", and my system detects "Z" (upper case) for that case. This changes it to use `event.code` being "KeyZ" instead, which should work on any system.
It also updates the description of the shortcuts in the docs to use `<kbd>` and `<samp>` elements as suggested in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd. For example, instead of "ctrl+z", use <kbd><kbd>Ctrl</kbd>+<kbd>Z</kbd></kbd>.
> Use "code" instead of "key" for undo/redo keyboard event

- plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
> In LGV import, update sequence when assembly is changed

- packages/core/ui/theme.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.tsx
- plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts
- plugins/circular-view/src/BaseChordDisplay/components/Loading.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.test.js
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/Node.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.js.snap
- plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.test.js
- plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.js.snap
- plugins/jobs-management/src/JobsListWidget/components/JobsListWidget.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/components/RubberBand.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberBand.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/RubberBand.tsx
This uses [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) to add the tertiary, quaternary, and base colors to our theme in TypeScript. This way, we can get rid of the `@ts-ignore`s that are used whenever the tertiary, quaternary, or base colors are referenced.
> Extend theme with module augmentation

- plugins/wiggle/src/WiggleBaseRenderer.tsx
Fixes #3155 
This makes sure to transform reducedFeatures returned by wiggle adapters to a Map (was returning an array, which worked in some cases e.g. arrays have a .values() function but not in others with the .has() on composite map)
> Fix for mouseover/mouse click on wiggle/multi-wiggle causing errors in embedded mode

- plugins/wiggle/src/MultiWiggleAdapter/MultiWiggleAdapter.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3153
> Use the union of all the subadapter refNames for the MultiWiggleAdapter getRefNames

- plugins/wiggle/src/MultiWiggleAdapter/MultiWiggleAdapter.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- test_data/volvox/config.json
- website/docs/config_guide.md
Fixes #3122
"name" may be a fairly intuitive key to specify on the subadapter, so if "name" is specified without a "source" field, it is used. If both "source" and "name" are specified, "source" is given priority
> Support the "name" field on multi-wiggle adapter subadapters instead of source

- products/jbrowse-desktop/public/electron.ts
This message could help for the issue seen by @carolinebridge-oicr where it takes a minute or so to install after you close, and could otherwise be confusing if the user relaunches immediately after closing the app and not seeing the update
> Note for user to wait before re-launching app on desktop update

- plugin-development-tools/src/createRollupConfig.ts
This removes some customization from the rollup plugins in the plugin-development-tools package. The customizations were originally brought in from the TSDX template we used to create the rolllup config. In my testing in Apollo, the defaults actually end up having more consistent and reliable behavior than these customizations.
> Use more defaults in rollup plugins

- products/jbrowse-cli/src/commands/add-track.ts
- products/jbrowse-cli/src/types/common.ts
This just adds a small adapter to recognize BED files to the CLI, using BedAdapter
> Adds ability for CLI to recognize plaintext BED files

- packages/core/util/io/index.ts
`getFetcher` is supposed to be an alternative to `openLocation` for things like adapters that need to e.g. call a REST API instead of reading a file. This makes the `pluginManager` param for `getFetcher` optional so that its function signature and logic matches `openLocation`.
I found this while trying to use `getFetcher` in an adapter that retrieves sequences from the new Apollo server.
> Make pluginManager param to getFetcher optional

- packages/core/util/calculateDynamicBlocks.ts
- packages/core/util/calculateStaticBlocks.ts
I found a relatively reproducible procedure to create the dead state tree node error, and a probable fix for this particular case
- Go to LGV import form
- Enter EDEN
- Select EDEN from the dropdown
- Hit open
A good portion of the time, this produces the error in #3181 
I found that the "parentRegion" attribute in the static/dynamic blocks were not snapshots and were instead proxies for the state tree node, creating this error
Note that this change could mildly slow down the block calculations. Note also that parentRegion is not even used anywhere in our codebase, but have some hypothetical use cases
Fixes #3181
> Fix "dead state tree node" error by creating snapshots of parent region for block calculations

- products/jbrowse-desktop/src/sessionModelFactory.ts
- products/jbrowse-web/src/sessionModelFactory.ts
This adds an extension point to web and desktop that allows the session to be extended. You can use this to add more—or override exisiting—state, views, or actions to the session. I can be used from plugins like this:
```ts
pluginManager.addToExtensionPoint(
'Core-extendSession',
(sessionModel: IAnyModelType) =>
sessionModel
.props({
// additional model state here
})
.views((self) => ({
// additional views here
}))
.actions((self) => ({
// additional actions here
})),
)
```
> Add extendSession extension point to web and desktop

- plugins/authentication/package.json
- plugins/authentication/src/OAuthModel/model.tsx
OAuthModel is supporting refresh tokens, but because of how [getToken()](https://github.com/GMOD/jbrowse-components/blob/7ed81c2b1e1554279c0b70767ef8fcb46a68df9d/packages/core/pluggableElementTypes/models/InternetAccountModel.ts#L135) is implemented it exchanges refresh token only once and does not pull new one when currently used one expires.
This change adds a validator that checks the currently used auth token for expiration and tries to use refresh token to get a new one. If that fails it removes refresh token to force full re-authorization.
There still might be a problem if a user will re-start a previous (authorized) session exactly on the assembly selection page because assemblies do not use the same data loading flow and thus do not use …
> Add OAuthModel InternetAccount token refresh

- packages/core/assemblyManager/assembly.ts
- packages/core/assemblyManager/assemblyManager.ts
- packages/core/ui/AboutDialog.tsx
- packages/core/util/when.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeViewSvg.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- products/jbrowse-web/src/sessionModelFactory.ts
This has a few different changes related to assemblies:
- In the session view `assemblyNames`, this now includes the session assemblies' names as well. This has the effect of being able to choose session assemblies from the assembly selector in e.g. the LGV setup screen.
- Uses the assembly's `displayName` instead of `name` in more user-facing places.
- Improves `waitForAssembly` on the assembly manager. Before, if you added an assembly and then immediately called `waitForAssembly`, it wouldn't work because the reaction that adds the new assembly hadn't fired yet. Now, if it can't find the assembly it waits for a second and tries again to give the reaction time to run.
- (minor) returns the assembly config when it's added via the session action
> Allow selecting session assemblies, improve session adding

- products/jbrowse-desktop/craco.config.js
- products/jbrowse-desktop/src/StartScreen/RecentSessionsPanel.tsx
fixes https://github.com/GMOD/jbrowse-components/issues/3185
Also uses a MUI grid to vertically center the button, checkbox, etc. (which is a technique I hadn't known before, could apply to other places in app potentially where that is relevant)
> Add 'Open saved session' button to start screen on desktop

- website/release_announcement_drafts/v2.1.3.md
current changelog 
```
* Other
* [#3188](https://github.com/GMOD/jbrowse-components/pull/3188) Add 'Open saved session' button to start screen on desktop ([@cmdcolin](https://github.com/cmdcolin))
* [#3187](https://github.com/GMOD/jbrowse-components/pull/3187) Add mouseover tooltip descriptions to the header of the VariantFeatureDetails sample/genotype table ([@cmdcolin](https://github.com/cmdcolin))
* [#3179](https://github.com/GMOD/jbrowse-components/pull/3179) Add extendSession extension point to web and desktop ([@garrettjstevens](https://github.com/garrettjstevens))
* [#3178](https://github.com/GMOD/jbrowse-components/pull/3178) Allow X/Y assemblies of dotplot or top/bottom selection of synteny views to be either query or target ([@cmdcolin](https://github.com/cmdcolin))
* …
```
> v2.1.3 release announcement

- products/jbrowse-web/src/RecentSessionCard.js
- products/jbrowse-web/src/RecentSessionCard.tsx
- products/jbrowse-web/src/StartScreen.tsx
- removes deprecated prop ("raised") on listItem to fix a console error
- sets a message for the user instead of throwing an error on the front end that was causing a crash if the user attempted to open a "Recent session" that cannot be loaded
> Better error reporting on jbrowse-web start screen when user attempts to open a broken recent session

- products/jbrowse-desktop/src/rootModel.ts
This passes a "configuration" object instead of a "config" object. I am actually a bit confused on how the internet account code worked without this fix, but this PR would fix https://github.com/GMOD/jbrowse-components/issues/3201
> Fix configuration initialization on the internet accounts models

- packages/core/assemblyManager/assemblyManager.ts
- plugins/dotplot-view/src/DotplotReadVsRef.ts
- plugins/dotplot-view/src/DotplotView/model.ts
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-comparative-view/src/LinearReadVsRef.tsx
- plugins/linear-comparative-view/src/index.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
- products/jbrowse-desktop/src/sessionModelFactory.ts
- products/jbrowse-web/src/__snapshots__/sessionModelFactory.test.js.snap
- products/jbrowse-web/src/sessionModelFactory.ts
- products/jbrowse-web/src/tests/dotplot_inverted_flipaxes.json
- products/jbrowse-web/src/tests/dotplot_inverted_test.json
- test_data/yeast_synteny/config.json
This restores the ability to view session assemblies in the session selector https://github.com/GMOD/jbrowse-components/pull/3180
It stores the "read assemblies" in a new field called "temporaryAssemblies" on the sessionmodel
I considered also using the "view assembly" (store the assembly itself on the view model) but this is tricky to make work right because 
a) it has to bypass using the assembly manager, or otherwise makee the assembly manager track assemblies on the view models
b) has to make the view receive the assembly config, which it currently does not (was using a frozen for 'view assemblies'). as a frozen, it will not properly hydrate the displays such as the LinearReferenceDisplay (which is used to display the sequence track on the read assembly in the synteny view), it must …
> Use "temporaryAssemblies" to store read vs ref assemblies, and allow selecting "sessionAssemblies" in dropdown

- plugins/trackhub-registry/package.json
- plugins/trackhub-registry/src/trackhub-registry/SelectBox.js
- plugins/trackhub-registry/src/trackhub-registry/TrackHubRegistrySelect.js
Fixes #3208 
Missed the conversion to MUI5 due to being in js instead of TS! conversion to ts is a somewhat longer process, this is a quick fix
> Fix trackhub registry failing to load in 2.x.y versions of jbrowse

- packages/core/ui/App.tsx
- packages/core/ui/DrawerWidget.tsx
- plugins/linear-genome-view/package.json
- plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
Example with the trackhub registry error
> Add error boundary on view, track, and drawer widget

- packages/core/PluginManager.ts
- packages/core/util/types/index.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/Header.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
- plugins/wiggle/src/CreateMultiWiggleExtension/index.ts
- plugins/wiggle/src/index.ts
- products/jbrowse-react-linear-genome-view/src/createModel/createModel.ts
- products/jbrowse-react-linear-genome-view/src/createModel/createSessionModel.ts
- products/jbrowse-react-linear-genome-view/src/createViewState.ts
- products/jbrowse-react-linear-genome-view/stories/GettingStarted.stories.mdx
- products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx
I made it so the embedded react LGV component has the ability to add session tracks, along with a flag "disableAddTracks" to optionally disable it. "disableAddTracks" is off by default.
I also made it so that extension points can be evaluated with a second "props" argument. This allows passing the session model to the extension point, and it does not have to participate in the "accumulator" pipeline (before this, the only way to pass information to extension points is via the accumulator param which is subsequently returned by each extension point). This allows e.g. checking that the TrackSelect-multiTrackMenuItems extension point should add a multi-wiggle add track widget by checking the new extra session prop
Fixes https://github.com/GMOD/jbrowse-components/issues/3205 (The sequence …
> Allow adding session tracks to embedded react component along with disableAddTracks option if unwanted

- packages/core/util/types/index.ts
- plugins/alignments/src/LinearPileupDisplay/components/SetFeatureHeight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/ExportSvgDialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/SequenceSearchDialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
- plugins/wiggle/src/CreateMultiWiggleExtension/index.ts
- plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SetColorDialog.tsx
This makes it so the `queueDialog` method type on the AbstractSessionModel checks that the props passed to it match the component passed to it, instead of being `any`. The other changes in this PR fix the type errors revealed by this change.
> Improve TypeScript for queueDialog

- packages/core/ui/theme.test.ts
- packages/core/ui/theme.ts
This PR:
- updates theme.ts to get rid of an `any` and a `@ts-ignore`
- passes the provided theme to the overrides in `createJBrowseTheme` so that things that are styled by the overrides (e.g. the accordion summary) get the correct theme color
Accordion not being the right color noted by @scottcain here: https://gitter.im/GMOD/jbrowse2?at=6335cacc3a42316d331451a9
> Use provided theme in overrides, update TS types

- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.tsx
- plugins/data-management/src/AddConnectionWidget/components/AddConnectionWidget.tsx
- plugins/data-management/src/AddConnectionWidget/components/ConfigureConnection.tsx
- plugins/trackhub-registry/src/trackhub-registry/TrackHubRegistrySelect.tsx
This allows a user to select a local assembly name to add their tracks from the trackhub registry to
It might be the case that the name of the user's local assembly does not match the remote name provided by the trackhub, so this allows the user to select the local assembly to add the trackhub tracks to.
> Allow user to select local assembly to add tracks to for trackhub registry

- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/ViewContainer.tsx
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap
The addition of the version number in a little dialog box in 2.1.3 made circular view fail to load
Can be seen to fail currently here https://jbrowse.org/demos/cgv and elsewhere
The reason was a oversight keeping the "ViewContainer" between the linear and circular embedded components synced up. Adding app-core, and maybe a simple embedded test for circular, could help avoid future issues
> Fix circular embedded view failing to load in v2.1.3 and v2.1.4

- plugins/svg/src/SvgFeatureRenderer/components/FeatureLabel.tsx
Fixes #3236
Makes sure that the floating label being drawn is within an "appropriate closeness" to the left side of the screen. Can elaborate more with a teardown if there is interest (the logic for floating labels is a bit tricky) but this appeared to fix the issue seen in #3236 
Compare
https://jbrowse.org/code/jb2/main/?config=test_data%2Fvolvox%2Fconfig.json&session=share-j4NQOSjQXJ&password=QyIov
https://jbrowse.org/code/jb2/fix_block_label2/?config=test_data%2Fvolvox%2Fconfig.json&session=share-j4NQOSjQXJ&password=QyIov
> Fix floating feature label showing fragments of itself with smaller blocks

- plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/package.json
- plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.js.snap
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.js.snap
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.js.snap
- plugins/trackhub-registry/package.json
- plugins/trackhub-registry/src/trackhub-registry/declare.d.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/src/SessionLoader.ts
- yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/3240
> Fix local session failing to load copying between tabs in some cases

- website/release_announcement_drafts/v2.1.5.md
```
* Other
* [#3229](https://github.com/GMOD/jbrowse-components/pull/3229) Allow user to select local assembly to add tracks to for trackhub registry ([@cmdcolin](https://github.com/cmdcolin))
* [#3220](https://github.com/GMOD/jbrowse-components/pull/3220) Better error display on SV inspector/spreadsheet view on import form ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3223](https://github.com/GMOD/jbrowse-components/pull/3223) Allow adding session tracks to embedded react component along with disableAddTracks option if unwanted ([@cmdcolin](https://github.com/cmdcolin))
* [#3227](https://github.com/GMOD/jbrowse-components/pull/3227) Add infrastructure for creating linear-genome-view sub-classes ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* …
```
> Release announcement v2.1.5

- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScaleBar.tsx
Currently, the tick labels on the overview scalebar can change depending on the zoom level of the zoomed in view
This changes it so that it only uses the "overview's zoom level", so the overview labels don't change depending on your zoom level
Not visible on genomes like human that have cytobands, since it doesn't show overview coords
before: can see overview scale bar labels change depending on your zoom level
> Use tick labels that correspond to the overview's larger zoom level

- packages/core/ui/FatalErrorDialog.tsx
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/src/declare.d.ts
- products/jbrowse-desktop/src/index.tsx
- products/jbrowse-web/package.json
- products/jbrowse-web/src/JBrowse.tsx
- products/jbrowse-web/src/Loader.tsx
- products/jbrowse-web/src/rootModel.ts
- products/jbrowse-web/src/tests/Loader.test.tsx
- products/jbrowse-web/src/tests/util.tsx
- yarn.lock
Updates the use-query-params dependency to 2.0.0, which is more lightweight (uses native URLSearchParams instead of query-string). Also includes a couple small refactors ported over from  https://github.com/GMOD/jbrowse-components/pull/3192 e.g. onSnapshot in jbrowse-web is properly disposed of in the useEffect
> Update use-query-params to 2.0.0

- packages/core/rpc/WebWorkerRpcDriver.ts
- packages/core/ui/FatalErrorDialog.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
- plugins/bed/package.json
- plugins/variants/src/VcfTabixAdapter/VcfTabixAdapter.ts
- plugins/wiggle/package.json
- yarn.lock
I found that safari/webkitgtk, tracks can hang in  https://github.com/GMOD/jbrowse-components/issues/3245
This seems to be a safari/webkitgtk only bug
I found an odd workaround where if I console.log the value returned by makeWorkerHandle (which is a "new Worker" https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker instance) then it removes the issue with tracks hanging. This seems odd, perhaps indicative of a race condition, but I did not see issue after doing this change.
Fixes https://github.com/GMOD/jbrowse-components/issues/3245
Also found two instances where tracks (pileup and snpcoverage) were using view.staticBlocks before view.initialized was completed, which throws a hard error, so that was also fixed. These errors were not seen in other browsers but i did see it …
> Fix tracks hanging in safari

- plugins/breakpoint-split-view/src/model.ts
Adds a check for view.initialized before performing operations with view.staticBlocks
Also catches async errors during fetching and runs `session.notify` if any errors occur
Seen in firefox, similar to recent issue caught with view.staticBlocks  here https://github.com/GMOD/jbrowse-components/pull/3256/files
> Fix issue with breakpoint split view using view before initialized

- packages/core/BaseFeatureWidget/SequenceFeatureDetails.test.tsx
- packages/core/data_adapters/CytobandAdapter.ts
- plugins/alignments/src/CramAdapter/CramTestAdapters.ts
- plugins/bed/src/BedAdapter/BedAdapter.ts
- plugins/bed/src/BedTabixAdapter/BedTabixAdapter.ts
- plugins/comparative-adapters/src/ChainAdapter/ChainAdapter.ts
- plugins/comparative-adapters/src/DeltaAdapter/DeltaAdapter.ts
- plugins/comparative-adapters/src/MCScanAnchorsAdapter/MCScanAnchorsAdapter.ts
- plugins/comparative-adapters/src/MCScanSimpleAnchorsAdapter/MCScanSimpleAnchorsAdapter.ts
- plugins/comparative-adapters/src/MashMapAdapter/MashMapAdapter.ts
- plugins/comparative-adapters/src/PAFAdapter/PAFAdapter.ts
- plugins/comparative-adapters/src/util.ts
- plugins/config/src/RefNameAliasAdapter/RefNameAliasAdapter.ts
- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
- plugins/grid-bookmark/src/GridBookmarkWidget/components/ImportBookmarks.tsx
- plugins/gtf/src/GtfAdapter/GtfAdapter.ts
- plugins/legacy-jbrowse/src/JBrowse1Connection/jb1ConfigParse.ts
- plugins/sequence/src/ChromSizesAdapter/ChromSizesAdapter.ts
- plugins/sequence/src/TwoBitAdapter/TwoBitAdapter.ts
- plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/VcfImport.ts
- plugins/variants/src/VcfAdapter/VcfAdapter.ts
- plugins/wiggle/src/MultiWiggleAddTrackWidget/AddTrackWorkflow.tsx
- scripts/changelog.js
This does a global find-and-replace of `.split('\n')` with `.split(/\n|\r\n|\r/)`. This should handle unix (`\n`), dos (`\r\n`) and old-style mac (`\r`) line-endings. Hopefully it helps avoid issues especially with users creating files on Windows, like [this](https://github.com/GMOD/jbrowse-components/discussions/3249#discussioncomment-3791863).
> Handle alternate line endings

- packages/core/assemblyManager/assembly.ts
- products/jbrowse-web/src/tests/ErrorConditions.test.tsx
- test_data/wrong_assembly.json
Possible fix for #3260
This fix creates a small minimal config for testing the wrong assembly error
A possible alternative to this approach would be checking that the LGV is initialized before finishing test, but I think the minimal config would not try to load any refnamealiases and thus would not cause any error
> Fix for flaky test

- website/docs/config_guide.md
- website/docs/faq.md
Makes a note about how a custom function for jexl color callbacks is a little different from the jexl function for feature details, and adds a link to FAQ
Also makes the indentation a little less on FAQ, so the sidebar/TOC works better
> Add more docs about color callbacks

- packages/core/ui/App.tsx
Fixes #3268
Missed wrapping "AppToolbar" component in an observer during refactor in 2.1.5
> Fix ability to rename session in web/desktop

- component_tests/lgv/src/tracks.ts
- demos/jbrowse-react-linear-genome-view-cra5/src/tracks.ts
- demos/jbrowse-react-linear-genome-view/src/tracks.ts
- demos/jbrowse-react-linear-genome-view/yarn.lock
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.tsx.snap
- yarn.lock
In https://github.com/GMOD/bbi-js/pull/50 I found that bbi can receive plain Uint8Array objects, and then we would not want to use the Buffer::toString on them (Buffer is a subclass of Uint8Array with a special toString to transform e.g. to utf8, but plain Uint8Array does not have a toString method that does this, have to use TextDecoder)
bbi already got this fix and this PR just adds some more demo tracks to various projects, and updates the yarn.lock to get the bbi update
> Update bbi-js for bugfix on webpack 4

- packages/core/BaseFeatureWidget/SequenceFeatureDetails.tsx
- packages/core/BaseFeatureWidget/SequenceHelpDialog.tsx
- packages/core/BaseFeatureWidget/__snapshots__/index.test.js.snap
- plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.js.snap
- plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.js.snap
Adds a small help icon next to "Show feature sequence"
describes the drop down options and  may be helpful now that the sequence panel is displayed everywhere
> Add help dialog for sequence panel

- products/jbrowse-react-linear-genome-view/stories/UsingWebWorker.stories.mdx
- website/release_announcement_drafts/v2.1.6.md
```
yarn run v1.22.18
* `core`
* [#3250](https://github.com/GMOD/jbrowse-components/pull/3250) Handle alternate line endings ([@garrettjstevens](https://github.com/garrettjstevens))
* [#3252](https://github.com/GMOD/jbrowse-components/pull/3252) Fix gene sequence fetching in embedded, and allow fetching genomic sequence for other feature types ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3254](https://github.com/GMOD/jbrowse-components/pull/3254) Use tick labels that correspond to the overview's larger zoom level ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3269](https://github.com/GMOD/jbrowse-components/pull/3269) Fix ability to rename session in web/desktop ([@cmdcolin](https://github.com/cmdcolin))
* …
```
> v2.1.6 release announcement

- packages/core/util/io/RemoteFileWithRangeCache.ts
- plugins/authentication/package.json
- plugins/authentication/src/DropboxOAuthModel/model.tsx
- plugins/authentication/src/ExternalTokenModel/model.tsx
- plugins/authentication/src/GoogleDriveOAuthModel/model.tsx
- plugins/authentication/src/HTTPBasicModel/model.tsx
- plugins/authentication/src/OAuthModel/model.tsx
- plugins/authentication/src/index.ts
- products/jbrowse-web/src/rootModel.ts
This exports some things from the authentication plugin and makes the package public. The motivation is to be able to use the OAuth plugin in Apollo. A few classes and interfaces had to have `export` added to them (including one in core) so that TypeScript could make public types for the newly exported files.
Also updates the internetAccount models to use a simpler MST named/props pattern instead of using compose.
> Update and publish authentication plugin

- packages/core/util/Base1DUtils.ts
- products/jbrowse-web/src/tests/Alignments.test.tsx
Currently, rubberbanding selection+zoom in across ellided regions results in a inaccurate zoom
The reason comes down to assuming every region has an interRegionPaddingBlock but ellided regions do not
Can test on these links: rubberband zoom across the many ellided regions
main branch
https://jbrowse.org/code/jb2/main/?session=share-9S4NOE2u-q&password=Y1Uhn
this branch
https://jbrowse.org/code/jb2/improve_rubberband_ellided/?session=share-9S4NOE2u-q&password=Y1Uhn
Even this branch is not perfect, it seems to underestimate slightly, while main branch does overestimation
> Improve rubberband zooming across ellided regions

- packages/core/ui/App.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/HierarchicalTrackSelector.tsx
- plugins/dotplot-view/src/DotplotView/components/Grid.tsx
- plugins/dotplot-view/src/DotplotView/components/Header.tsx
- plugins/dotplot-view/src/DotplotView/components/ImportCustomTrack.tsx
- plugins/dotplot-view/src/DotplotView/components/ImportForm.tsx
- plugins/dotplot-view/src/DotplotView/components/ImportSyntenyTrackSelector.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/components/Header.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportCustomTrack.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportSyntenyTrackSelector.tsx
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- products/jbrowse-web/src/tests/Dotplot.test.tsx
- test_data/volvox/config.json
Possible fix for https://github.com/GMOD/jbrowse-components/issues/3079
Creates a rudimentary "tracklist" that shows session tracks and config tracks (not connection yet) at the synteny import form, helping users to more easily launch a synteny view
Will look for track types that contain the word 'Synteny' (in case another synteny track type is developed), and check that the track's assemblyNames matches **both** of the user selected assemblies
Makes it easier for the user to see that "opening their own track" is an optional step too
> Add ability to open a synteny track directly from the dotplot/linear synteny view import forms

- packages/core/ui/AssemblySelector.tsx
- plugins/dotplot-view/src/DotplotView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
Fix the refnameautocomplete displaying a stale value for refname in some cases e.g. could see this visiting config_dotplot.json and then launching a lineargenomeview on the import form: it displayed peach in the assembly selector but with grape chromosome names
Affected released versions of jb2 e.g. v2.1.7, v2.1.0, and probably further back
The cause boils down to the "useState" being sticky when we want it to reset it's state when assembly changes
> Fix the RefNameAutocomplete displaying a stale value for chromosome names

- plugins/authentication/src/OAuthModel/configSchema.ts
- plugins/authentication/src/OAuthModel/model.tsx
This adds to the option to use the [state](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.1) parameter in an OAuth authorization. By default it is read from the config, but if dynamic state is needed, the `get state` getter can be overridden in an extending model.
Motivation is to use this in Apollo to keep track of some state across the OAuth flow.
> Add option to use OAuth "state" param

- website/release_announcement_drafts/v2.2.0.md
```
* Other
* [#3296](https://github.com/GMOD/jbrowse-components/pull/3296) Add option to use OAuth "state" param in internet accounts ([@garrettjstevens](https://github.com/garrettjstevens))
* [#3285](https://github.com/GMOD/jbrowse-components/pull/3285) Use typescript version of @gmod/cram ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3299](https://github.com/GMOD/jbrowse-components/pull/3299) Add ability to open a synteny track directly from the dotplot/linear synteny view import forms ([@cmdcolin](https://github.com/cmdcolin))
* [#3287](https://github.com/GMOD/jbrowse-components/pull/3287) Lazy-load assemblies on demand instead of all at app startup ([@cmdcolin](https://github.com/cmdcolin))
* [#3279](https://github.com/GMOD/jbrowse-components/pull/3279) …
```
> v2.2.0 release announce

- README.md
- package.json
- products/jbrowse-desktop/craco.config.js
- products/jbrowse-web/craco.config.js
- yarn.lock
Tested on a windows vm with plain cmd.exe
Uses a code snippet found in https://github.com/viewstools/yarn-workspaces-cra-crna/issues/28 which manually runs `yarn` via a spawned process, which replaces the 'get-yarn-workspaces' dependency, which assumed forward slashes
> Fix ability to run development environment on windows

- packages/core/ui/App.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
Currently if a track has something that hits the track level error boundary, then the track label is not displayed so the track is more difficult to close (have to use tracklist maybe)
Note: It is a little uncommon to even have this ErrorBoundary show up as there are other error handling mechanisms related to data fetching and whatnot, but this ErrorBoundary can be useful catching unexpected hard crashes in the component code and avoiding the whole session, or in this case, the whole view, from being crashed.
> Move ErrorBoundary so that tracks/views that have crashed can be closed more easily

- packages/core/pluggableElementTypes/models/BaseTrackModel.ts
- packages/core/pluggableElementTypes/models/BaseViewModel.ts
- packages/core/ui/App.tsx
- packages/core/ui/EditableTypography.tsx
- packages/core/ui/ViewContainer.tsx
- packages/core/util/types/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/index.tsx
- products/jbrowse-desktop/src/sessionModelFactory.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- products/jbrowse-web/src/__snapshots__/rootModel.test.js.snap
- products/jbrowse-web/src/sessionModelFactory.ts
- website/docs/config/BamAdapter.md
- website/docs/config/CramAdapter.md
- website/docs/config/LinearGCContentDisplay.md
- website/docs/config/OAuthInternetAccount.md
- website/docs/config/SNPCoverageAdapter.md
- website/docs/models/Base1DView.md
- website/docs/models/BaseTrackModel.md
- website/docs/models/BaseViewModel.md
- website/docs/models/DotplotView.md
- website/docs/models/JBrowseWebSessionModel.md
- website/docs/models/LGVSyntenyDisplay.md
- website/docs/models/LinearComparativeDisplay.md
- website/docs/models/LinearComparativeView.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/LinearPileupDisplay.md
- website/docs/models/LinearSyntenyDisplay.md
This adds the ability to toggle a "minimize" a track. The track is then not visible. This can be useful because closing a track or view loses it's state entirely, while minimizing will keep it the track state available
The text "(minimized)" is appended to track labels when this state is enabled
Fixes https://github.com/GMOD/jbrowse-components/issues/2531
Fixes https://github.com/GMOD/jbrowse-components/issues/2107
Fixes #535
> Add ability to minimize/collapse tracks and views and move views up/down in view stack

- plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx
- plugins/data-management/src/AddTrackWidget/components/PasteConfigWorkflow.tsx
- plugins/data-management/src/AddTrackWidget/model.ts
This is a very simple component that let's users paste a config in plain JSON format
This would be an escape hatch for expert users or perhaps users getting instruction. sometimes I imagine it being helpful in a workshop for users to paste a particular thing rather than click and edit the GUI a bunch after adding the basic instance of a track
sort of the GUI version of the add-track-json CLI
> Add track workflow that allows pasting JSON config

- plugins/breakpoint-split-view/package.json
- plugins/spreadsheet-view/package.json
- plugins/variants/package.json
- yarn.lock
v2.2.1 included an update to @gmod/vcf that failed to parse breakends properly (https://github.com/GMOD/vcf-js/pull/95). This was fixed in https://github.com/GMOD/vcf-js/pull/97 and included here
> Fix for breakpoint split view and circular view issues with `<TRA>` type entries in v2.2.1

- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.tsx.snap
Example, with our "Gencode" gene track:
by default the gene "label" is it's ENCODE ID, and the description is it's "gene symbol". if I was an end user and it was configured this way, it would be difficult on current main to make it so that it just displays the gene symbol. Also, displaying in a compact mode, with the gene labels still displayed, I think is useful. This PR accomplishes both changes
Example screenshot, which is fairly easy to setup after this change
> Retain feature labels in compact display mode for SVG features, and allow turning off keeping feature description without feature label

- plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
- plugins/alignments/src/SNPCoverageAdapter/SNPCoverageAdapter.ts
- plugins/alignments/src/SNPCoverageAdapter/generateCoverageBins.ts
Fixes two issues
1) The "modification" mode for SNPCoverage could get stuck if it was turned on for a track or region that had no modifications, as the "ready" condition assumed that it would get at least one modification
2) The adapter type was changed to a 'frozen' for SNPCoverage, but fetching subconfigs doesn't work on this type
> Fix error with SNPCoverage not rendering MM tag modifications in some cases

- .github/workflows/push.yml
> Fix `jbrowse upgrade` CLI command overwriting config.json with --branch or --nightly options

- plugins/alignments/src/LinearPileupDisplay/components/SetFeatureHeight.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
Allows more easily toggling "normal" and "compact" settings for the pileup. Previously, we only had the "Set feature height" dialog, where the user would manually enter e.g. height:1 in a text box. The "compact" setting here is equal to setting height:2 and has "Remove y-spacing between features" to true
> Add method to more easily create compact view of alignments

- products/jbrowse-web/src/SessionLoader.ts
- website/docs/config_guides/avoiding_stale_config.md
We need to look at e.g. a global variable to check this, as there is no configuration file otherwise available to get this from
xref https://github.com/GMOD/jbrowse-components/issues/3045
> Add method for cache busting requests to the config file in jbrowse-web

- packages/core/ui/Snackbar.tsx
I found that if you trigger the same snackbar error e.g. two times, then close the snackbar, then trigger it again a third time, the snackbar will not show up.
Found debugging #3388 
This fixes the issue by always showing the last message on the snackbar stack. It avoids tricky React state+mobx-state-tree state conflicts by removing all react hooks from method
> Fix issue where snackbar would not show up when same error message is triggered multiple times

- packages/core/rpc/BaseRpcDriver.ts
Possible code simplification for the watchWorker RPC
Currently if this fails, it can produce a large stack trace due to the recursion. It's not very obscured by doing so, but seemed sort of awkward so I changed it into a while loop and the code seemed simpler anyways
> Simplify RPC watchWorker

- packages/core/util/stats.ts
- plugins/wiggle/src/BigWigAdapter/__snapshots__/BigWigAdapter.test.ts.snap
- plugins/wiggle/src/LinearWiggleDisplay/components/WiggleDisplayComponent.tsx
- plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/WiggleDisplayComponent.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/models/model.tsx
allows stats to exist in an undefined state, avoids the display of 5e-234 after blank region is viewed and [0-50] when loading https://github.com/GMOD/jbrowse-components/issues/3399
fixes https://github.com/GMOD/jbrowse-components/issues/3399
> Remove y-scalebar rendering placeholder values in blank and loading states

- packages/core/pluggableElementTypes/renderers/ComparativeServerSideRendererType.ts
- packages/core/util/dedupe.ts
- plugins/linear-comparative-view/src/LinearSyntenyRenderer/components/LinearSyntenyRendering.tsx
Fixes  #1794
The 'comparative renderer' getFeatures fetches features from all staticBlocks, and features can overlap multiple static blocks (they could overlap multiple dynamic blocks too, just less common)
xref https://github.com/GMOD/jbrowse-components/blob/fix_double_render/plugins/linear-comparative-view/src/LinearSyntenyRenderer/LinearSyntenyRenderer.ts
therefore, we uniquify by feature id before returning results
> Fix double-render of some synteny features

- plugins/gccontent/src/GCContentAdapter/configSchema.ts
Possible fix for issue noted here https://github.com/GMOD/Apollo3/issues/174#issuecomment-1350924715
Referring to e.g. adapter pluggable elements from within an adapter is problematic, as it likely is just the adapters registered up until that point. Since Apollo is added after GCContent, this makes it fail validation
Similar things came up in
- The creation of "sub-displays" with the alignments display recently. It is somewhat problematic to do this generically
- Using sequenceAdapter in BAM/CRAM, these were converted to types.frozens. types.late did not work when applied to both BAM and CRAM xref https://github.com/GMOD/jbrowse-components/issues/1165
> Fix ability to use GC content display on sequence track in Apollo

- plugins/linear-genome-view/src/LinearGenomeView/components/GetSequenceDialog.tsx
Adds the ability to reverse and complement the sequence in the get sequence dialog (allowing reverse complement if both are checked)
> Add ability to revcomp sequence in the "Get sequence" dialog

- packages/core/util/index.ts
- plugins/gccontent/src/LinearGCContentDisplay/config.ts
- plugins/gccontent/src/LinearGCContentDisplay/stateModel.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- website/docs/config/LinearGCContentDisplay.md
- website/docs/config/LinearReadArcsDisplay.md
- website/docs/models/CircularView.md
- website/docs/models/LinearGCContentDisplay.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/LinearReadArcsDisplay.md
- website/docs/models/LinearReferenceSequenceDisplay.md
When you e.g. turn off the "show translation" on the reference sequence track, it automatically makes the height smaller. This can reduce click and drag. 
Aside: I considered making show forward/reverse/translation settings "sticky" e.g. storing in localstorage, but thought that it could be confusing if it got stuck to "show reverse" and you were expecting show forward.
> Auto-adjust height of reference sequence track to current settings

- website/release_announcement_drafts/2.3.2.md
The fixes to the synteny rendering are pretty substantial and probably warrant a quick fix release. Details below
* [#3421](https://github.com/GMOD/jbrowse-components/pull/3421) Add ability to revcomp sequence in the "Get sequence" dialog ([@cmdcolin](https://github.com/cmdcolin))
* [#3413](https://github.com/GMOD/jbrowse-components/pull/3413) Add a "base" set of tracks and assemblies for the embedded demos ([@cmdcolin](https://github.com/cmdcolin))
* [#3419](https://github.com/GMOD/jbrowse-components/pull/3419) Fix rendering base-level alignments on synteny visualizations, especially in inverted regions ([@cmdcolin](https://github.com/cmdcolin))
* [#3416](https://github.com/GMOD/jbrowse-components/pull/3416) Fix rendering alignment arcs on files that need refname renaming and add jitter …
> v2.3.2 release announcement

- plugins/linear-genome-view/src/LinearGenomeView/model.ts
Fixes bug found by @carolinebridge-oicr when loading LGV with the localstorage populated with older "0"/"1" for settings instead of "true"/"false"
Git blame traces to here https://github.com/GMOD/jbrowse-components/commit/d509556f8d05f62e67b77a31d746a2cc799dba9a#diff-16ff04395edd82556eb8f6df4a771c9d56a968b512fba86976d5ace75344d2cbL212
Error message @carolinebridge-oicr reported
```
react-dom.production.min.js:101 Uncaught Error: [mobx-state-tree] Error while converting `0` to `boolean`:
value `0` is not assignable to type: `boolean` (Value is not a boolean).
at pt (mobx-state-tree.module.js:3847:12)
at Ge (mobx-state-tree.module.js:3440:15)
at Ze (mobx-state-tree.module.js:3426:9)
at t.value (mobx-state-tree.module.js:7105:17)
at t.value (mobx-state-tree.module.js:7078:54)
at …
```
> Booleanize localstorage settings from older versions of LGV to avoid crash

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/stateModelFactory.ts
There was a bug caused by use of the 'reaction' type for the new synteny rendering in v2.3.3
I thought that displayedRegions would be somewhat deeply observed, or at least shallowly observed so that if displayedRegions is assigned to, it would produce a rerendering, but the reaction data function needs to deeply access the variables to truly observe them. So, this PR JSON.stringifies the displayedRegions to fix
Fixes #3456
> Fix synteny view after horizontal flip

- packages/core/ui/ResizeBar.tsx
- packages/core/ui/ResizeHandle.tsx
- packages/core/util/index.ts
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid.tsx
Ports the resizer concept from the the faceted PR and also now auto-sizes the columns using the measureGridWidth method that is used in several other data-grid usages in the codebase
> Variant sample grid auto-size columns and resizer

- products/jbrowse-web/src/SessionLoader.ts
Currently, the app downloads the plugins.json file at app startup to see if any 'sessionPlugins' are used that may be dangerous, or if cross-domain configs are being used that use plugins also
But, even if sessionPlugins is empty and config is not cross-domain, plugins.json is still downloaded, so this skips the plugins.json DL if uneeded
> Bypass plugins.json download if unneeded during app startup

- packages/core/PluginLoader.ts
- products/jbrowse-react-circular-genome-view/src/loadPlugins.ts
- products/jbrowse-react-linear-genome-view/src/loadPlugins.ts
- products/jbrowse-react-linear-genome-view/stories/JBrowseLinearGenomeView.stories.tsx
Since version v2.1.6 https://jbrowse.org/jb2/blog/2022/10/19/v2.1.6-release/ the 'loading external plugins in embedded lgv' demo has been broken. This is due to changes in the PluginLoader to support loading relative paths (relative to a window.location.href or baseUrl) in jbrowse-web
This came from a confusion in my case that new URL(someUrl,baseUrl='') would just ignore the baseUrl, but it actually throws an exception when baseUrl is an empty string. This updates the code to use undefined instead of empty string, and then wires the code so undefineds flow through the pluginLoader instead of empty string
> Fix loading external plugins in embedded linear-genome-view demo

- packages/core/ui/Menu.tsx
Changes the positioning of the popover to be to the lower right of the ...
before
after (you can see the ... that we clicked)
> Add anchorOrigin/transformOrigin to default menu component

- plugins/data-management/src/AddTrackWidget/components/DefaultAddTrackWorkflow.tsx
- plugins/data-management/src/AddTrackWidget/components/TrackSourceSelect.tsx
> Larger margins to add track workflow to visually clarify next button behavior

- component_tests/cgv/cypress/integration/basic.spec.ts
- component_tests/cgv/package.json
- component_tests/cgv/public/test_data
- component_tests/cgv/src/App.tsx
- component_tests/cgv/src/assembly.ts
- component_tests/cgv/src/tracks.ts
The circular embedded test I believe was loading a largish pacbio VCF, and had a 30s timeout but was seen to fail here on CI https://github.com/GMOD/jbrowse-components/actions/runs/4058747404/jobs/6986041056
This is related to https://github.com/GMOD/jbrowse-components/issues/3492 where it was actually going to our s3 bucket for the file also, which should be fast, but also, could be a source of flakyness (more likely, it was due to rendering a pretty large file in this case)
This changes the code to test a small volvox file in the embedded cgv test suite
> Fix possible flaky issue with embedded cgv test

- packages/core/ui/DropDownMenu.tsx
- packages/core/ui/Menu.tsx
- packages/core/ui/theme.ts
Currently, there is a single transitionDuration 0 on the @jbrowse/core/ui/Menu component which makes it popup fast without animation. This PR goes a bit further and applies it to all popovers and menus via defaultProps in the theme. I noticed this because the CascadingMenu (a special type of menu only used on trackMenus right now) had the slowish animation, so I made it faster here.
> Use transitionDuration 0 as defaultProp in theme for both popovers and menus

- test_data/config_demo.json
The jbrowse-plugin-biothings-api plugin was changed to use the package 'string-template' https://www.npmjs.com/package/string-template in recent versions (circa june 2022) so the "dollar signs" need to be removed to make the demo work
> Fix mygene.info demo track

- plugins/alignments/src/LinearAlignmentsDisplay/models/configSchema.ts
- plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/models/configSchema.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- test_data/volvox/config.json
Fixes https://github.com/GMOD/jbrowse-components/issues/3030
Makes "height" into a getter on track displays, and uses a preProcessSnapshot to put any existing snapshots e.g. from session shares, into a state model attribute called heightPreConfig
> Config display height

- website/docs/faq.md
- website/docs/tutorials/simple_plugin.md
- website/docusaurus.config.json
- website/src/pages/contact.md
When the old `gitter.im` shuts down and we have to use the new `app.gitter.im` element app, this link should work for the JBrowse 2 room.
> Change gitter link to use new element gitter app

- products/jbrowse-aws-lambda-functions/saved-sessions/read-session-jbrowse.js
- products/jbrowse-web/src/sessionSharing.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3520
Works
https://share.jbrowse.org/api/v1/load?sessionId=Xc-hrJg1O%2B
Fails
https://share.jbrowse.org/api/v1/load?sessionId=Xc-hrJg1O+
Seems like it should be the same, could fix on the server side perhaps, but this is a client side fix
> Fix loading session shares that have a plus sign in the sessionId

- embedded_demos/jbrowse-react-linear-genome-view-vite/package.json
- embedded_demos/jbrowse-react-linear-genome-view-vite/src/main.tsx
- embedded_demos/jbrowse-react-linear-genome-view-vite/vite.config.ts
- embedded_demos/jbrowse-react-linear-genome-view-vite/yarn.lock
was giving some odd errors with the buffer polyfill. vite is a little funny because at dev time, it uses esbuild, but rollup at production build. this was a dev only esbuild error
Example error from the esbuild globals plugin
The injected path "/home/cdiesh/src/jbrowse-components/embedded_demos/jbrowse-react-linear-genome-view-vite/node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js" cannot be marked as external
I switched in this PR to polyfill buffer in the entry point (src/main.tsx) rather than in the vite config. buffer and stream are the two main things we  still need polyfills for afaik, as well as setting the "global" variable which may be related to the stream polyfill
> Fix issue with vite dev mode

- products/jbrowse-desktop/src/sessionModelFactory.ts
- products/jbrowse-web/src/__snapshots__/sessionModelFactory.test.js.snap
- products/jbrowse-web/src/sessionModelFactory.ts
Currently, the theme name is stored in the session snapshot. This makes the themes somewhat "viral" and would be applied when someone shared their session with someone else. The person receiving the snapshot, could, in a bad case, think there is a bug suddenly being thrown into a dark theme.
This PR makes it so we load the users current theme from local storage only
> Don't load theme from session snapshot, only from local storage

- plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/SearchBox.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This addresses a regression introduced in v2.2.0, related to #3306
The bug that is seen is if you clear the text in the searchbox in the linear genome view import form, an infinite loading spinner replaces the search box suddenly, and you can then no longer alter the search unless you change assemblies
The fix applied here is instead of showing a loading state depending on the "value" of the box being empty, show loading state if regions.length is empty which implies the assembly is loading (could try to do undefined also if it is of interest but we have a assembly?.regions||[])
Some small refactorings added also, but the main issue fixed by the above description
> Fix issue where clearing search box on LGV import form turns search box into loading bar

- plugins/legacy-jbrowse/src/JBrowse1TextSearchAdapter/JBrowse1TextSearchAdapter.test.ts
- plugins/legacy-jbrowse/src/JBrowse1TextSearchAdapter/JBrowse1TextSearchAdapter.ts
> Fix upper case querying of jbrowse 1 text search store

- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberband.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/RubberbandSpan.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
Clicking and dragging the overview scale bar and going from right to left produced the wrong visual selection (the accurate zoom would be produced though)
This was introduced in v2.2.2 with #3357
> Fix visual effect from using the overview scalebar click and dragging backwards

- packages/core/util/Base1DViewModel.ts
- plugins/dotplot-view/src/DotplotView/1dview.ts
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
- plugins/dotplot-view/src/DotplotView/components/DotplotWarnings.tsx
- plugins/dotplot-view/src/DotplotView/components/Header.tsx
- plugins/dotplot-view/src/DotplotView/components/PanButtons.tsx
- plugins/dotplot-view/src/DotplotView/components/WarningDialog.tsx
- plugins/dotplot-view/src/DotplotView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
1) Adds a d-pad pan buttons
2) Makes wheel scroll perform a zoom instead of a pan (user can change if they want, but wheel scroll to zoom is a more common UI interaction: think google map)
3) Reduces the action of wheel scroll by dividing by a reduction factor, this makes movements less dramatic
4) Adds holding ctrl+click-and-drag to pan view. Can also switch around so pan view is the default click-and-drag, and holding control performs region select. The latter is almost more user intuitive, but it reduces discoverability of "Open in linear synteny view" and the precise zooms, so the default is still click-and-drag to select region
5) Stricter zoom and scroll boundaries for the dotplot, to avoid scrolling out of view
Fixes #3554
> Dotplot UI improvements

- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/components/hooks.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- yarn.lock
> Double click zoom

- plugins/linear-genome-view/src/LinearGenomeView/index.test.ts
- plugins/sv-inspector/src/SvInspectorView/index.ts
- plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.ts
- plugins/sv-inspector/src/SvInspectorView/models/breakpointSplitViewFromTableRow.js
- website/docs/models/Base1DView.md
- website/docs/models/BaseLinearDisplay.md
- website/docs/models/Dotplot1DView.md
- website/docs/models/DotplotView.md
- website/docs/models/JBrowseDesktopSessionModel.md
- website/docs/models/JBrowseReactCGVSessionModel.md
- website/docs/models/JBrowseReactLGVSessionModel.md
- website/docs/models/JBrowseWebSessionModel.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/SvInspectorView.md
Changes featuresRefNamesP (which asynchronously initializes a FromConfigAdapter) to a simpler function that looks at the set of feature refNames and combines it with feature.INFO?.CHR2. 
also fixes a couple other small things including
- moving a jexl addFunction to plugin installation
- add javadoc style contents
this bug was I think noted by a user at PAG2023
> Fix use of "show all regions with data" feature in SV inspector with TRA entries (fetch CHR2 from INFO)

- .github/workflows/desktop_build_linux.yml
- .github/workflows/desktop_build_mac.yml
- .github/workflows/desktop_build_win.yml
- .github/workflows/jbrowse-web.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .github/workflows/website.yml
Attempting to fix warnings
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2, aws-actions/configure-aws-credentials@v1
```
xref https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
note that our create-release may be unmaintained https://github.com/actions/create-release
> Update github actions workflows to newer versions

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/model.ts
v2.4.1 introduced a small regression after #3578 was landed where the mouseout doesn't work properly on the synteny mouseover shading
Was basically a type confusion after converting the "-1" for undefined features to true undefined
> Fix shading on synteny features after mouseout

- plugins/spreadsheet-view/src/SpreadsheetView/components/ColumnMenu.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/DataRow.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/DataTable.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/DataTableHeader.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/GlobalFilterControls.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/NumberEditor.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetView.tsx
When you were zoomed in on the spreadsheet view, the import form's "Submit" button could be hidden because of the combination of the ViewContainer's overflow:hidden and the SpreadsheetView's strict usage of model.height
This changes the code to allow the SpreadsheetView to autosize it's contents better and does not strictly apply model.height when viewing the "ImportForm"
> Avoid cutting off import form of spreadsheet view, fix overflowed text in table header

- packages/core/ReExports/modules.tsx
- plugins/alignments/src/LinearPileupDisplay/components/SetMaxHeight.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.ts
- plugins/alignments/src/SNPCoverageAdapter/generateCoverageBins.ts
- plugins/linear-comparative-view/src/LinearReadVsRef/LinearReadVsRef.tsx
- plugins/wiggle/src/LinearWiggleDisplay/models/model.tsx
- yarn.lock
SEQ is often left empty on secondary alignments, and this causes at least one error in our code (per-base coloring on alignments tracks)
This adds typescript notes that feature.get('SEQ') returns string|undefined and fixes related issues
> Fix potential crashes where alignment SEQ field may be empty

- packages/core/ReExports/list.ts
- packages/core/ReExports/modules.tsx
- plugin-development-tools/package.json
- plugin-development-tools/src/createRollupConfig.ts
- plugin-development-tools/yarn.lock
This replaces [`rollup-plugin-node-builtins`](https://www.npmjs.com/package/rollup-plugin-node-builtins) and [`rollup-plugin-node-globals`](https://www.npmjs.com/package/rollup-plugin-node-globals) with [`rollup-plugin-polyfill-node`](https://www.npmjs.com/package/rollup-plugin-polyfill-node). It's a drop-in replacement, and plugin authors won't have to change anything in their code.
The reason for this update is that the prior packages were not maintained, and when trying to bundle code into a plugin that used newer JS syntax, (such as [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)), the prior packages could not handle it.
I tried to also see if there was a way to limit which node polyfills were scanned for and bundled, …
> Update plugin rollup polyfill package

- package.json
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
- plugins/dotplot-view/src/DotplotView/model.ts
- yarn.lock
The non-default mode to toggle click-and-drag to pan had a bug when you use the ctrl+click-and-drag where it wouldn't detect mouse up properly and would pan around even after you mouse up
This fixes that issue, and then also saves that setting to local storage
> Fix mouse click-and-drag behavior in the alternative "cursor mode" for the dotplot view

- package.json
- packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
- packages/core/package.json
- plugins/data-management/package.json
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx
- plugins/dotplot-view/package.json
- plugins/dotplot-view/src/DotplotView/components/WarningDialog.tsx
- plugins/grid-bookmark/package.json
- plugins/grid-bookmark/src/GridBookmarkWidget/components/GridBookmarkWidget.tsx
- plugins/variants/package.json
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid.tsx
- plugins/wiggle/package.json
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SetColorDialog.tsx
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/src/StartScreen/RecentSessionList.tsx
- products/jbrowse-web/package.json
- yarn.lock
Since the react 18 branch stalled and included some code for the @mui/x-data-grid 6 update, this just splits it out from there #3502 
some APIs are renamed, including the things like selectionModel->rowSelectionModel. Hopefully not too impactful on plugins though
> Update to mui x-data-grid 6

- plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
This is a more minimal PR to address same issue as https://github.com/GMOD/jbrowse-components/pull/3595 
That PR tried to introduce many refactorings to the block based system including how we hydrate content from our web worker, but I ran into many odd errors with this. 
This PR just adds a delay before creating the makeAbortableReaction on the serverSideRenderedBlock afterAttach
Fixes #887
> Fix renderDelay not being applied to dynamicBlocks

- packages/core/BaseFeatureWidget/BaseFeatureDetail.tsx
- packages/core/BaseFeatureWidget/index.ts
- plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
- products/jbrowse-web/src/tests/util.tsx
- yarn.lock
This discussion (https://github.com/GMOD/jbrowse-components/discussions/3640) showed me that the feature detail panel can present with a blank panel if an error occurs in a user's jexl callbacks for example. This PR adds a try/catch that now presents the user with an error if the jexl callback fails
> Fix error handling of feature detail formatter jexl callbacks

- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
This adds an extension point `'LinearGenomeView-TracksContainerComponent'` which can be used by plugins to implement, in my interest, their own e.g. "highlight" component. 
It may be able to do things beyond that also, but this small PR seemed like it could be useful in case the the 'general concept of highlighting' in #3648 is stalled...it is difficult to deliver a highlighting functionality that is sound, however, just allowing a plugin to add their own type of component at the TracksContainer level allows it to create it's own highlight functionality.
This is useful for the protein viewer
> Add extension point to allow plugins to render arbitrary e.g. highlighting components in TracksContainer

- plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx
- products/jbrowse-desktop/src/jbrowseConfig.ts
- products/jbrowse-web/src/jbrowseConfig.ts
- website/blog/2021-11-04-v1.5.1-release.md
- website/docs/config/JBrowseDesktopConfiguration.md
- website/docs/config/JBrowseWebConfiguration.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/LinearWiggleDisplay.md
- website/package.json
- website/yarn.lock
Currently there is a bug in docusaurus that prevents browsers that set 'prefers-reduced-motion' from accessing sub-categories on the sidebar
https://github.com/facebook/docusaurus/pull/8906
This uses the canary branch to fix this until a proper fix is released
Also clarifies the PluginDefinition docs in the autogen docs
> Fix website documentation sidebar on browsers with prefers-reduced-motion

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
I noticed along with @carolinebridge-oicr that double clicking a feature toggles a zoom in. This only zooms in if the featureIdUnderMouse is undefined. Only particular display types may use the 'featureIdUnderMouse' concept, but this does help double click on feature not performing a zoom in
> Only double-click zoom if not clicking on feature

- packages/core/ui/theme.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/src/tests/ReloadCram.test.tsx
- yarn.lock
We use 'fontSize:12' but in many places MUI bumps this up, so the effective font size for most elements is 13.8px (track list items, refnameautocomplete, etc).
I propose making the global theme use fontSize:11, which makes the effective font size for most elements 12.5px, which (I think) improves UI  information density without compromising readability.  
Extra Motivation: the RefNameAutocomplete was actually cutting off the text for even small refnames e.g. which was actually a regression between v2.4.0 and v2.4.1
Current v2.4.2 (lack of padding results in ellipses of the text prematurely on RefNameAutocomplete, uses fontSize:12 in the theme globally, which results in effective font size 13.7px for most elements)
This branch (adds extra padding to RefNameAutocomplete and makes theme …
> Smaller fontSize in global theme by default

- plugins/dotplot-view/package.json
- plugins/dotplot-view/src/DotplotView/components/DotplotTooltip.tsx
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
This updates the dotplot view tooltips to use react-popper instead of an absolute-positioned div with text
The absolute-positioned div can run into text-formatting issues near the margins, but the popper tries to lay out the text more nicely
Comparison
after
before
> Use react-popper for tooltips in DotplotView

- packages/core/rpc/methods/CoreGetFeatureDetails.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
> Guard against undefined in CoreGetFeatureDetails

- website/src/pages/index.tsx
This removes the abbreviated author list from our front page citation.
We did not have an abbreviated author list when it showed the biorxiv preprint, so this PR removes it again, just having the paper title and journal. People can use their own citation manager to get their formatted citation, rather than try to get a formatted copy and pasteable citation on our webpage
> Update webpage citation

- package.json
- products/jbrowse-cli/package.json
- products/jbrowse-cli/src/commands/create.ts
- products/jbrowse-cli/src/commands/upgrade.ts
- yarn.lock
Some people are reporting corrupt files from node-unzipper both to our project and in issues on their repo e.g. https://github.com/ZJONSSON/node-unzipper/issues/271
In the absence of this getting fixed upstream, this PR proposes using an alternative library, yauzl (yet another un-zip library) with a front end provided by npm package 'decompress' (see https://github.com/kevva/decompress-unzip/blob/master/package.json#L31) since yauzl is a bit tricky to use by itself
The firebase project maybe ran into same issue and created their own unzipper based on native nodejs zlib which seemed nice but it's not published on npm and I couldn't get it to work https://github.com/firebase/firebase-tools/pull/5714
> Fix CLI unzipping having intermittent failure

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabelContainer.tsx
There was a regression in v2.5.0 related to the double-click change #3670 which relocated the 'ref' that is used to calculate these positions
This restores the right calculation
Interestingly this did not cause a snapshot error which is surprising to me (xref https://github.com/GMOD/jbrowse-components/pull/3670/files, no snapshot changes)
> Fix breakpoint split view alignment connections not pointing at right position in v2.5.0

- plugins/alignments/src/LinearReadArcsDisplay/components/ReactComponent.tsx
- plugins/alignments/src/LinearReadArcsDisplay/drawFeats.ts
- plugins/alignments/src/LinearReadArcsDisplay/model.tsx
- plugins/alignments/src/LinearReadCloudDisplay/drawFeats.ts
- plugins/alignments/src/LinearReadCloudDisplay/model.tsx
- plugins/alignments/src/shared/BaseDisplayComponent.tsx
- plugins/alignments/src/shared/dynamicTrackAfterAttach.tsx
- plugins/alignments/src/shared/renderSvg.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-web/src/tests/AlignmentArcs.test.tsx
- yarn.lock
https://github.com/GMOD/jbrowse-components/pull/3697 reintroduced the render delay for the non block based arc tracks, which only renders after a certain timeout instead of on every frame, but this PR adds code to instantly render after a zoom level change, instead of after a render delay, which helps avoid "blanking" (a new vocab word) of the screen
> Render alignment track arcs instantly after bpPerPx change

- plugins/alignments/src/CramAdapter/CramAdapter.ts
When filtering by tag name and value in a CRAM file's alignments track, no features are rendered.
before filtering by tag:
after filtering by tag:
I fixed it by changing `const val = record[tagFilter.tag]` into `const val = record.tags[tagFilter.tag]`.
> Fix rendering error in alignments tracks when filtering by tag in CRAM file

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
Additional follow up to https://github.com/GMOD/jbrowse-components/pull/3691
Restores the modularization that was reverted in that PR, and fixes an issue where vertical scrolling wasn't working
>  Fix breakpoint split view alignment connections not pointing at right position (pt 2)

- packages/core/data_adapters/BaseAdapter/index.ts
- products/jbrowse-desktop/package.json
May help with https://github.com/GMOD/jbrowse-components/issues/3683
I am unable to build the electron-builder binaries locally (could be a separate issue, it is just confusing for my build environment) so difficult to test this
> Add removable-media to jbrowse desktop snap

- packages/product-core/src/Session/SessionTracks.ts
- products/jbrowse-web/src/tests/CopyAndDelete.test.tsx
Currently the CopyAndDelete gives a warning that the 'configuration' object is stale. This warning was introduced by splitting TrackContainer into TrackContainer and TrackRenderingContainer
I think this refactor is valid, but unfortunately causes the warning. I propose to silence the warning during test. Many stale warnings are hard to properly fix. The alternative to silencing it is to use getConf in both TrackContainer and TrackRenderingContainer, which appears to make it not go stale. Not sure why that is, but rather than implement this odd workaround, this silences the warning
> Silence console warn in CopyAndDelete test

- plugins/bed/src/BedpeAdapter/BedpeAdapter.ts
- plugins/bed/src/index.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HamburgerMenu.tsx
- adds a track type guess to the bedpe filetype (variant track) such that if you pop it into circular view, it will work
- follows through with track population if a certain field from the bedpe file is null
- disables the add track hamburger menu item from the sidebar such that if a user has disabled addtrack it will not give them the option
> Adds miscellaneous fixes to Add Track workflow

- packages/core/pluggableElementTypes/models/baseTrackConfig.ts
- website/docs/developer_guides/extension_points.md
This could possibly be a method for plugins to set 'default' values in track configs xref https://github.com/GMOD/jbrowse-components/issues/3609
The extension point is named `Core-preProcessTrackSnapshot` and plugins could `addToExtensionPoint('Core-preProcessTrackSnapshot',snap=>/*manipulate snap;return snap*/)`
I considered adding this to other config snapshot pre-processors but not all of them have a pluginManager available (e.g. the display one does not)
Could adjust to make that available, or accept that only track level is available?
> Evaluate extension point on track config pre-process snapshot

- products/jbrowse-web/src/components/ShareButton.tsx
- products/jbrowse-web/src/components/ShareDialog.tsx
- products/jbrowse-web/src/components/ShareInfoDialog.tsx
- products/jbrowse-web/src/components/ShareSettingsDialog.tsx
This adds a link to the "ShareDialog" that suggests to right-click to bookmark. This is useful because it can otherwise be hard to generate a bookmark from link in the text field
> Add button to bookmark in jbrowse-web share dialog

- plugins/comparative-adapters/src/ChainAdapter/ChainAdapter.ts
- plugins/comparative-adapters/src/ChainAdapter/util.ts
- plugins/comparative-adapters/src/DeltaAdapter/DeltaAdapter.ts
- plugins/comparative-adapters/src/DeltaAdapter/util.ts
- plugins/comparative-adapters/src/MashMapAdapter/MashMapAdapter.ts
- plugins/comparative-adapters/src/PAFAdapter/PAFAdapter.ts
- plugins/comparative-adapters/src/PAFAdapter/util.ts
- plugins/comparative-adapters/src/util.ts
This changes from string based parsing (which has a max string length of ~512Mb on chrome) to buffer based parsing (which can be up to maybe 2Gb or larger perhaps https://stackoverflow.com/a/8974841/2129219)
It may be that we need to improve performance in ways beyond just this PR to truly handle the larger files, but this would be a step towards enabling it
Fixes https://github.com/GMOD/jbrowse-components/issues/3664
> Allow synteny data adapters to open files larger than 512Mb

- packages/app-core/src/ui/ViewContainer.tsx
- plugins/breakpoint-split-view/src/BreakpointSplitView/BreakpointSplitView.ts
- plugins/spreadsheet-view/src/SpreadsheetView/components/ImportWizard.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/RowCountMessage.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetView.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/StatusBar.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/models/SpreadsheetView.ts
- plugins/sv-inspector/src/SvInspectorView/components/CircularViewOptions.tsx
- plugins/sv-inspector/src/SvInspectorView/components/SvInspectorView.tsx
- plugins/sv-inspector/src/SvInspectorView/models/SvInspectorView.ts
- products/jbrowse-web/src/tests/SVInspector.test.tsx
- yarn.lock
v2.4.2 introduced a regression where the SV inspector import form layout was not centered
This fixes that, and provides a couple of CSS style refactors
current main
this branch
also fixes an issue with "Open split view" not properly showing a disabled state when the features are not TRA/BND events
> Fix centering of the ImportForm on SV inspector

- packages/app-core/src/ui/App.tsx
- packages/app-core/src/ui/AppFab.tsx
- packages/app-core/src/ui/DialogQueue.tsx
- packages/embedded-core/src/ui/ViewTitle.tsx
- packages/product-core/package.json
- plugins/breakpoint-split-view/src/BreakpointSplitView/model.ts
- plugins/circular-view/src/CircularView/models/CircularView.ts
- plugins/dotplot-view/src/DotplotView/model.ts
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- yarn.lock
There is an approx 350kb bundle size regression between v2.5.0 and current main
It is likely due to x-data-grid being packaged by default so this PR doesn't address it head on but may help
> Fix lazy loading regression after app-core/embedded-core PR

- codecov.yml
Many of our main branch commits 'fail' the codecov patch or project 'coverage requirements'. We can adjust the thresholds to help, or just turn them off entirely. I think turning them off is probably the best thing for us
I looked at https://community.codecov.com/t/cannot-disable-codecov-patch-check/682 to try to help solve this
> Turn off the github checks for codecov patch/project

- .github/workflows/push.yml
- component_tests/react-app/package.json
- plugins/jobs-management/package.json
- plugins/menus/package.json
- plugins/rdf/package.json
- plugins/text-indexing/package.json
- products/jbrowse-react-app/package.json
- products/jbrowse-react-app/stories/examples/BasicExample.tsx
- yarn.lock
Fixes #3721 
greatly aided by pairing with @garrettjstevens
We discovered that you cannot use "yarn resolutions" to resolve things that are explicitly listed in the package.json "dependencies" and not on npm yet. it works for implicit dependencies (e.g. dependencies of dependencies) but not explicit ones (it tries to fetch from npmjs.org and fails with a 404)
This therefore changes what is explicitly listed in the dependencies to refer to the packed file
> Component test for the @jbrowse/react-app

- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/add-connection.test.ts
- products/jbrowse-cli/src/commands/add-connection.ts
Renames --assemblyName to --assemblyNames in the add-connection CLI, and makes clear that it is optional and is a comma separated list of multiple assembly names
Also makes some miscellaneous code simplifications
> Fix specifying the assemblyNames config slot on add-connection CLI

- packages/product-core/src/Session/Connections.ts
- packages/web-core/src/BaseWebSession/index.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/dialogs/ToggleConnectionsDialog.tsx
- plugins/data-management/src/ucsc-trackhub/model.ts
- plugins/legacy-jbrowse/src/JBrowse1Connection/model.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/base.ts
- products/jbrowse-cli/src/commands/add-connection.test.ts
- products/jbrowse-cli/src/commands/add-connection.ts
Also fixes session->connections getter in jbrowse-web to return sessionConnections and some other misc refactoring
Fixes #3737
> Don't throw on UCSC connection containing assemblies not matching connection->assemblyNames config

- packages/core/util/types/index.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/dialogs/CloseConnectionDialog.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HamburgerMenu.tsx
This formalizes some code that checks for 'session.makeConnection' (which embedded has) to be a SessionWithConnections and then 'session.addConnectionConf' to be SessionWithConnectionEditing (which embedded may not have)
Also cleans up the typescript a little (less use of Function)
> Distinguish between SessionWithConnections and SessionWithConnectionEditing

- plugins/authentication/src/HTTPBasicModel/HTTPBasicLoginForm.tsx
- plugins/authentication/src/OAuthModel/model.tsx
One tiny bugfix in this (was missing a "$" in a template literal substitution). Feel free to cherry-pick that commit out if the other commit requires more discussion.
Side note, it seems like there should be some sort of eslint rule that warns about `{` instead of `${` in template literals, but the closest thing I could find was disallowing backticks unless they contain a substitution or a newline:
```json
{
"quotes":  ["warn", "single", { "avoidEscape": true }]
}
```
The other commit is something where when I was reviewing #3742 I kept feeling like I'd tried to do something similar before, and I finally remembered what it was. It's possible to use `validateToken` to accomplish what I think is the same thing using `getPreAuthorizationInformation` does, which is basically making sure the …
> Use validateToken to exchange refresh token in OAuth getFetcher

- package.json
- packages/core/pluggableElementTypes/models/InternetAccountModel.ts
- plugins/authentication/src/DropboxOAuthModel/configSchema.ts
- plugins/authentication/src/DropboxOAuthModel/model.tsx
- plugins/authentication/src/HTTPBasicModel/HTTPBasicLoginForm.tsx
- plugins/authentication/src/OAuthModel/configSchema.ts
- plugins/authentication/src/OAuthModel/model.tsx
- plugins/authentication/src/OAuthModel/util.ts
- products/jbrowse-desktop/package.json
- yarn.lock
Follow up to the oauth PR
Also does a couple refactors
a) disables the need to have any config slot for "hasRefreshToken". it is just there or not in the responses, and eagerly attempted to use
b) misc immutable js syntax sugar
c) adds more console.error logs where before they were silent, which may make the log noisier but may improve debugging
> Avoid re-prompting a user login when refresh token is processed

- .ignore
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- products/jbrowse-react-linear-genome-view/stories/DefaultSessions.mdx
- website/release_announcement_drafts/v2.6.0.md
changelog thus far. we can do some testing to see that the rootmodel and related refactors are stable and then move for a new release :)
* Other
* [#3743](https://github.com/GMOD/jbrowse-components/pull/3743) Create mixin for shared code between LinearWiggleDisplay and MultiWiggleLinearDisplay ([@cmdcolin](https://github.com/cmdcolin))
* [#3711](https://github.com/GMOD/jbrowse-components/pull/3711) Allow synteny data adapters to open files larger than 512Mb ([@cmdcolin](https://github.com/cmdcolin))
* [#3639](https://github.com/GMOD/jbrowse-components/pull/3639) Add button to bookmark in jbrowse-web share dialog ([@cmdcolin](https://github.com/cmdcolin))
* [#3631](https://github.com/GMOD/jbrowse-components/pull/3631) Add BEDPE add track workflow, avoid showing "Add …
> v2.6.0 release announcement

- packages/core/TextSearch/TextSearchManager.ts
This uses `tracks` on the session instead of from the JBrowse config when checking for track-level text search adapters. This way session tracks get checked for text search adapters as well as tracks in the config.
Credit to @shashankbrgowda for figuring out that the text search manager was missing the session tracks: https://github.com/GMOD/Apollo3/pull/231#issuecomment-1610034986.
> Check session tracks for text search adapters

- plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx
- plugins/breakpoint-split-view/src/BreakpointSplitView/model.ts
Issue found by @carolinebridge-oicr 
Created when toggling the display type on an alignments track to e.g. arc display
> Fix potential issue with display searchFeatureByID being undefined

- plugins/alignments/src/LinearAlignmentsDisplay/components/AlignmentsDisplay.tsx
- plugins/alignments/src/LinearAlignmentsDisplay/models/model.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
User experience when opening 2+ AlignmentsTracks one after another using jbrowse-react-linear-genome-view: application would crash on some undefined properties (SNPCoverageDisplay.height, self.PileupDisplay.type, and .priority of menu items)
Might be something weird with next.js rendering / race conditions / not sure what; adding these checks resolves the issue.
Tested on the JBrowse 2 app and everything working the same as before.
> Adds safety checks on AlignmentsDisplay properties to avoid undefined rendering

- .github/workflows/desktop_build_mac.yml
- .github/workflows/desktop_build_win.yml
- .github/workflows/jbrowse-web.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .github/workflows/website.yml
- package.json
- products/jbrowse-desktop/scripts/notarize.js
- yarn.lock
Switches from 'legacy' (default) in @electron/notarize to 'notarytool' because the legacy says it'll be deprecated late 2023
Also suggests that the newer 'notarytool' is up to 10x faster https://github.com/electron/notarize
possibly will need to add 'teamId' also? see the readme https://github.com/electron/notarize (`teamId String - The team ID you want to notarize under.`, which is not in the legacy one)
> Use notarytool for macOS desktop signing

- products/jbrowse-desktop/package.json
Removes from slot, keeping it only in plugs
Xref https://github.com/GMOD/jbrowse-components/pull/3708
> Fix linux snap package removable_media error in v2.6.1

- plugins/linear-comparative-view/src/LinearComparativeView/components/Header.tsx
This makes it easier to access the track selector of the individual views. Was mentioned in discussions with @carolinebridge-oicr
> Add ability for track selector button in synteny view to select individual views

- packages/core/util/index.ts
- plugins/linear-comparative-view/src/LinearComparativeView/components/Rubberband.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/components/VerticalGuide.tsx
If the synteny view is showing volvox vs volvox at the exact same positions (which can happen if you open a synteny view and select the default choice of volvox vs volvox for example)
This is a picture of the bug, which is due to colliding React keys on the tooltips
This additionally modifies the tooltips to make it more clear what the text represents by specifying the assembly name and "row number"
> Fix synteny rubberband tooltips when views are exactly the same

- products/jbrowse-desktop/src/rpcWorker.ts
- products/jbrowse-desktop/src/util.tsx
Fixes #3785 
Worked on this with @cmdcolin during our pairing yesterday, and since then I've created a CJS plugin to test with that does node-native module import on the worker.
Because our electron version now uses node 18, we can use `fetch` natively. Also because webpack 5 doesn't do any polyfilling, we can avoid a bunch of `window.require`s that were a workaround to avoid the polyfilling.
> Allow workers to load CJS plugins

- products/jbrowse-react-circular-genome-view/package.json
The @jbrowse/react-circular-genome-view requires the @jbrowse/plugin-linear-genome-view 
The error message prints 
Import trace for requested module:
./node_modules/@jbrowse/plugin-sequence/esm/index.js
./node_modules/@jbrowse/react-circular-genome-view/esm/corePlugins.js
./node_modules/@jbrowse/react-circular-genome-view/esm/createModel/createModel.js
./node_modules/@jbrowse/react-circular-genome-view/esm/createModel/index.js
./node_modules/@jbrowse/react-circular-genome-view/esm/index.js
maybe then accesses plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts or plugins/sequence/src/LinearReferenceSequenceDisplay/index.ts
> Add missing @jbrowse/plugin-linear-genome-view dependency to @jbrowse/react-circular-genome-view

- packages/core/ui/CascadingMenuButton.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackCategory.tsx
Similar to a feature used in jbrowse 1 plugin (https://github.com/bhofmei/jbplugin-hierarchicalcheckbox)
> Add ability to show/hide all tracks in category

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.tsx
- plugins/wiggle/src/LinearWiggleDisplay/components/WiggleDisplayComponent.tsx
> Add suspense fallback to track container for lazy loaded display components

- packages/app-core/src/HistoryManagement/index.ts
I found that there is a field called document.activeElement. We can check it for html tag type INPUT to avoid undo'ing in this case
This helps us preserve the browser behavior of undo in a text field while keeping the browser-native ctrl+z hotkey
Fixes https://github.com/GMOD/jbrowse-components/issues/3638
> Add check for document.activeElement == INPUT before undo/redo

- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/menus/src/AboutWidget/components/__snapshots__/AboutWidget.test.tsx.snap
- plugins/menus/src/HelpWidget/components/__snapshots__/HelpWidget.test.js.snap
- plugins/wiggle/src/MultiDensityRenderer/MultiDensityRenderer.ts
- plugins/wiggle/src/MultiRowLineRenderer/MultiRowLineRenderer.ts
- plugins/wiggle/src/MultiRowXYPlotRenderer/MultiRowXYPlotRenderer.ts
- yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/3838
The key is that I assumed that all subtracks would return some feature for splitting into groups and getting a reliable number of "groups" but instead we can use the "sources" variable that is passed as a prop
(Sources is something that the display passes to the renderer, and the display itself requests the "sources" of the multiquantitative track as a separate RPC call. just for interest, the number of subtracks could change regionally in this way)
> Fix bug where multi-quantitative tracks plotted incorrectly for some bigwigs with empty regions

- .eslintignore
- package.json
- packages/app-core/package.json
- packages/core/package.json
- packages/core/rpc/WebWorkerRpcDriver.ts
- packages/core/util/nanoid.d.ts
- packages/core/util/nanoid.js
- packages/core/util/types/mst.ts
- packages/embedded-core/package.json
- packages/product-core/package.json
- packages/product-core/src/Session/BaseSession.ts
- packages/web-core/package.json
- products/jbrowse-react-app/package.json
- products/jbrowse-web/package.json
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/ConfigWarningDialog.tsx
- products/jbrowse-web/src/components/SessionWarningDialog.tsx
- yarn.lock
Shortid warns that it is deprecated on install https://www.npmjs.com/package/shortid
This PR switches shortid to nanoid
In order to do so, the codebase of nanoid is vendored (copied) into @jbrowse/core/util/nanoid because installing it from NPM gives tricky to solve issues with pure-ESM especially with jest
These could be worked around in jest probably but vendoring solves 'automatically' for us
xref https://github.com/ai/nanoid/issues/439
> Replace shortid with vendored nanoid

- packages/core/ui/EditableTypography.tsx
This PR fixes a bug observed by @scottcain  in chat where the "view title" could sometimes have incorrect width. There was a bad assumption in the code that the "clientWidth" was essentially observable, but this is not the case (it is a static html prop, not part of react, etc). 
This PR updates the view title to use our proper ResizeObserver based useMeasure hook to get the width
> Fix calculation of width of "view container title"

- plugins/authentication/src/DropboxOAuthModel/model.tsx
- plugins/authentication/src/OAuthModel/model.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/Cytobands.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/Gridlines.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/Scalebar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/util.ts
- products/jbrowse-web/src/tests/BreakpointSplitView.test.tsx
- products/jbrowse-web/src/tests/ExportSvgBreakpointSplitView.test.tsx
- website/docs/developer_guides/extension_points.md
- yarn.lock
- Remove some `type any` from Cytobands component
- Modularizes some of the block handling code into smaller components
> Minor refactors and typescripting improvements

- .eslintignore
- .eslintrc.js
I noticed that my eslint plugin wasn't working in VS Code, and also that eslint could only run from the top directory of the monorepo, not from subdirectories.
I found a solution [here](https://github.com/typescript-eslint/typescript-eslint/issues/251#issuecomment-567365174), but it requires using a JS file instead of a JSON file for the eslint config. It ends up still being a small change, though.
Basically the reason this is needed is that eslint looks for "tsconfig.json" in the closest parent that looks like a package, such as where there's a package.json. Since a lot of our tsconfigs are named like "tsconfig.build.esm.json," it can't find them. This change tells eslint to only look at the root-level tsconfig.
> Use eslinrc.js instead of eslintrc.json for better linter support

- packages/core/util/index.ts
- packages/text-indexing/src/TextIndexing.ts
- packages/text-indexing/src/types/common.test.ts
- packages/text-indexing/src/util.ts
- plugins/data-management/src/AddTrackWidget/components/ConfirmTrack.tsx
- plugins/data-management/src/AddTrackWidget/components/DefaultAddTrackWorkflow.tsx
- products/jbrowse-desktop/src/sessionModel/TrackMenu.ts
This PR started when the JBrowse Desktop `TrackMenu` threw errors because there was no adapter on the track (which is normal for Apollo). This makes the adapter optional in that file, and also refactors a bit to deduplicate a function and rename it to something a bit more intuitive.
> Make adapter optional when checking indexing

- packages/core/ReExports/modules.tsx
I noticed I was getting console errors and strange behavior when using the MUI `Tooltip` on another MUI component. Specifically I was using `Tooltip` to wrap `IconButton`, but the tooltip wouldn't appear until after the button had been clicked on. Eventually I found this docs page: https://mui.com/material-ui/guides/composition/#caveat-with-refs
What I eventually figured out is that basically, when we wrap lazy components in `Suspsense`, we have to use `React.forwardRef` to pass any refs on to the wrapped component. This allows things like `Tooltip` to work as usual.
I also had to add some display names after adding `forwardRef` to satisfy the "react/display-name" lint rule.
> Add forwardRef to wrapped re-exported lazy components

- plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/__snapshots__/VcfImport.test.ts.snap
- plugins/variants/src/VcfFeature/util.ts
The HG002 SV benchmark VCF has a particular way of describing insertions and deletions where it exactly specifies the deletion and insertion sequence in REF and ALT fields, even when these are quite long.
The resulting description strings generated on the VCF track are kind of unreadable as a result. This PR makes it so that insertions and deletions longer than 5bp are turned into just a string saying e.g. "10bp DEL" or "10bp INS"
current main
this branch
> Use shortened VCF feature description for some types of insertions and deletions

- package.json
- test_data/volvox/trix/volvox-rev-del_meta.json
- test_data/volvox/trix/volvox_meta.json
- webpack/scripts/build.js
- yarn.lock
Updates ixixx to fix a flaky test observed in e.g. https://github.com/GMOD/jbrowse-components/actions/runs/6112448642/job/16589925102
The updated ixixx uses a new pipe strategy to ensure that the contents are fully written to stdout before resolving the promise
> Bump deps to fix flaky test in ixixx

- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
Current main branch has a bug where applying e.g. "Color by"->"Tag" (select HP) or similarly "Sort by"->"Tag" (select HP) twice results in it hanging the second time
This is because it sets "sortReady:false", but the autorun does not detect that the "sortedBy" structure has changed since it is the same, so it doesn't change. This makes the autorun also listen for !sortReady (an analogous setting+autorun for colorBy)
> Fix alignments track infinite loading when applying same "Color by" or "Sort by" setting twice

- plugins/svg/src/SvgFeatureRenderer/components/FeatureLabel.tsx
- test_data/volvox/config_main_thread.json
Commonly embedded configurations use main thread RPC, so this helps SVG exports for many embedded users
Fixes https://github.com/GMOD/jbrowse-components/issues/3909
> Fix feature label offsets in SVG exports with main thread RPC

- test_data/config_demo.json
I thought this was a nice (minor) addition to the clinvar tracks
> this color scheme for ClinVar seems pretty common

- packages/core/assemblyManager/assembly.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3911
The issue #3911 mentions the issue this bisects to, which may be somewhat of a red herring or at least is a bit odd. The ideal solution to me seems to be properly checking that the getConf config entry is defined
> Avoid undefined getConf on assembly.configuration safeReference

- packages/app-core/package.json
- packages/app-core/src/ui/App/DrawerHeader.tsx
- packages/app-core/src/ui/App/ViewContainer.tsx
This is a more subtle change compared to the current theme.secondary.light, but it matches the color thats used for all previous versions and I think is still reasonably noticeable
> Use theme.secondary.main instead of theme.secondary.light on focusedView

- packages/core/util/blockTypes.ts
- plugins/dotplot-view/src/DotplotView/blockTypes.ts
There is a function called renameReference on the blocks, but this code is unused and a bit hairy, I think it is probably ok to just remove. also converts the Array.prototype.reduce into plain for loop based "sum" helper
> Remove some unused "renameReference" code in static blocks/dynamic blocks

- config/jest/console.js
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgOverlay.tsx
There are hydration warnings that come from rendering the 'overlay' on the server side 'webworker'. at one point in time, the RPC tried to serialize a partial copy of the displayModel so the server side could look up some aspect of the mouseover/selected feature, but this probably was changed and is not even sufficient to really fix this issue, as mouseovers for example change rapidly, and we don't want that to trigger new rpc renders
This PR proposes only rendering the SVG overlay if we are client side rendering
Caveat: in the future if we want SVG export to include the selected feature, would need additional work, but that isn't even in the current version of the SVG export either
> Fix hydration warning by only rendering the SvgFeature "selected feature" and "mouseover" client side

- package.json
- products/jbrowse-web/src/components/NoConfigMessage.tsx
- products/jbrowse-web/src/components/StartScreenErrorMessage.tsx
- yarn.lock
> Update config.json missing screen with "It worked!" message

- packages/core/ui/ResizeBar.tsx
- packages/core/ui/ResizeHandle.tsx
The current method of using the resize handle is to continuously provide a "distance" value to an onDrag callback, and normally in response to that, the UI continuously aggregates those small distance values to update the UI with a total distance travelled by the drag, however these often get out of sync with the true mouse position.
This PR changes it so it keeps track of total distance travelled from the mouseDown to the current drag position, and provides that as a second argument to the onDrag callback
> Fix mouse getting out of sync while dragging resize handle

- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebar.tsx
error message, observed only in chrome devmode in lgv header
Cannot update a component (`Unknown`) while rendering a different component (`Unknown`)
spotted by @garrettjstevens 
the fix is to avoid calling actions on the dynamically created MST object during render time
> Fix setState error from one component updating while another is rendering

- plugins/grid-bookmark/src/GridBookmarkWidget/components/AssemblySelector.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/EditBookmarkLabelDialog.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/ShareBookmarksDialog.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/model.ts
- plugins/grid-bookmark/src/index.ts
- products/jbrowse-web/src/tests/BookmarkWidget.test.tsx
- yarn.lock
This adds some further changes to try to simplify some of the grid bookmark code
Some notable changes
- Reverts multi-select textfield to a multi-select "formcontrol+select". This avoids some ts-ignores, which I think is valuable just for typescript purposes
- Removes bookmarkedRegions in postProcessSnapshot so that bookmarkedRegions is ONLY loaded from localstorage. Unless we want to try to mix the paradigm of bookmarks sometimes being in session, and sometimes being in localstorage, I think this is clearer for user expectations.
- Changes up the code of the assemblyselector to try to simplify it as it has some tricky statefulness logic
- Uses observable getters in a couple places instead of manual "update actions" to re-set various model state fields
> Add code improvements to GridBookmarkWidget pt 2

- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
Fixes https://github.com/GMOD/jbrowse-components/issues/3943
Removes "else if" logic to allow multiple settings to be specified
> Fix setting multiple hierarchical defaultCollapsed config options at initialization

- plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/model.ts
- plugins/grid-bookmark/src/index.ts
- products/jbrowse-web/src/tests/BookmarkWidget.test.tsx
This is in line with the decision to only load bookmark data from localStorage. there is a small loss of functionality not loading older bookmarks from the session data itself, but i think the localstorage only decision is ok going forward
> Rename bookmarkedRegions model slot to avoid loading bookmarks from older jbrowse sessions

- packages/core/BaseFeatureWidget/BaseFeatureDetail/DataGridDetails.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SetColorDialog.tsx
- products/jbrowse-desktop/src/components/StartScreen/RecentSessionList.tsx
uses our 'grid sizing' to measure grid widths and add column resizing instead of relying on the grid 'flex'
before
after
> Add column resizing for jbrowse-desktop start screen recent sessions panel

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilter.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedHeader.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx
This mirrors more closely the jbrowse 1 behavior of the faceted track selector where:
1) You select a specific facet filter
2) The other facet filters update in response to this
The behavior is a little tricky because each facet "progressively" filters so e.g. if you select all "BamAdapter" from e.g. the adapter facet, you don't want that to result in the adapter facet only showing BamAdapter.
Therefore, it stages it so that all the other facets are filtered on that BamAdapter selection.
> Make faceted track selector facet filters responsive to adjacent filter selections

- plugins/grid-bookmark/src/GridBookmarkWidget/components/AssemblySelector.tsx
Currently the UI component only lets you click on the checkbox and clicking the "Select all" text does nothing in contrast to the other menu items. This fixes it
> Fix ability to click on the text of the 'Select all' in the bookmark assembly selector

- packages/app-core/src/AppFocus/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/MiniControls.tsx
I think that the session.focusedView getter might be unneeded, and indeed, can even have cases where it doesn't fit well. Properly, I think it should resolveIdentifier instead of looping through views, but resolveIdentifier can be tricky because it requires a type argument. Instead of trying to fix the session.focusedView getter, I think it may be valid to just remove it and rely on checking only session.focusedViewId in client code
> Remove session.focusedView, only use session.focusedViewId

- packages/core/util/index.ts
- plugins/wiggle/src/DensityRenderer/DensityRenderer.ts
- plugins/wiggle/src/LinePlotRenderer/LinePlotRenderer.ts
- plugins/wiggle/src/MultiDensityRenderer/MultiDensityRenderer.ts
- plugins/wiggle/src/MultiLineRenderer/MultiLineRenderer.ts
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SetColorDialog.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SourcesGrid.tsx
- plugins/wiggle/src/MultiRowLineRenderer/MultiRowLineRenderer.ts
- plugins/wiggle/src/MultiRowXYPlotRenderer/MultiRowXYPlotRenderer.ts
- plugins/wiggle/src/MultiXYPlotRenderer/MultiXYPlotRenderer.ts
- plugins/wiggle/src/WiggleRendering.test.tsx
- plugins/wiggle/src/XYPlotRenderer/XYPlotRenderer.ts
- plugins/wiggle/src/__snapshots__/WiggleRendering.test.tsx.snap
- plugins/wiggle/src/drawDensity.ts
- plugins/wiggle/src/drawLine.ts
- plugins/wiggle/src/drawXY.ts
- plugins/wiggle/src/util.ts
The code to render multi-quantiative tracks iteratively goes to the 'next row', and requires calling a ctx.translate(0,height) to move down to the next row on each round of the loop, but the code was short circuiting the loop and not hitting that translate if the features in a particular row was empty
This fixes the issue
> Fix rendering multi-quantitative tracks when blank data is present

- package.json
- plugins/data-management/src/HierarchicalTrackSelectorWidget/generateHierarchy.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/public/electron.ts
- yarn.lock
- Removes ts-expect-error from electron.ts menu generation
- Downgrades electron 26 to 25, following some reports of issues with 26 #3979
> Downgrade electron 26->25 to fix screen blanking

- website/release_announcement_drafts/v2.7.1.md
```
* `core`
* [#3982](https://github.com/GMOD/jbrowse-components/pull/3982) Allow rendering semi-circles in the arc renderer + SVG rendering of arcs ([@cmdcolin](https://github.com/cmdcolin))
* `__mocks__`, `core`
* [#3981](https://github.com/GMOD/jbrowse-components/pull/3981) Auto-create HTML links for URLs, and strip HTML tags where they can't be rendered ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#3980](https://github.com/GMOD/jbrowse-components/pull/3980) Downgrade electron 26->25 to fix screen blanking ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#3971](https://github.com/GMOD/jbrowse-components/pull/3971) Fix rendering multi-quantitative tracks when blank data is present ([@cmdcolin](https://github.com/cmdcolin))
- Colin Diesh …
```
> v2.7.1 release announcement

- yarn.lock
Tested on an actual bzip2 track found in the hts-specs repo
> Update cram-js for bzip2 fix

- packages/core/PluginLoader.ts
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/ConfigWarningDialog.tsx
- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/components/SessionWarningDialog.tsx
- products/jbrowse-web/src/createPluginManager.ts
- products/jbrowse-web/src/tests/AssemblySelectorImportForm.test.tsx
- products/jbrowse-web/src/tests/Loader.test.tsx
- products/jbrowse-web/src/util.ts
I was investigating this issue https://github.com/GMOD/jbrowse-components/issues/3996 and found a possible solution, but in the process made some miscellaneous typescript and code organization refactors
> Refactors and typescript improvements for jbrowse-web loader

- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
> Fix mouseover tooltip getting stuck after selection action in dotplot

- package.json
- products/jbrowse-desktop/package.json
- yarn.lock
fixes https://github.com/GMOD/jbrowse-components/issues/4011
draft since untested
> Create MacOS universal build of jbrowse-desktop to help M1 macs

- packages/core/util/types/index.ts
- packages/product-core/src/Session/BaseSession.ts
- packages/web-core/src/BaseWebSession/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- plugins/svg/src/SvgFeatureRenderer/configSchema.ts
This creates an object session.hovered, similar to session.selected
The hovered state is rapidly updated by all onMouseMove events from LinearGenomeView, and includes hoveredPosition (result of pxToBp of the current mouseover x coordinate) and hoveredFeature which is the result of searching through `view.tracks.find(t=>t.displays[0].featureUnderMouse)` 
- This hover state is updated in a single place, which reduces the need to wire the code through many track types.
-  The "downside" is that it is always performing that views.tracks.find call instead of some more targeted session.setHovered right at the point-of-setting the `featureUnderMouse` but that seems like a hypothetical concern in terms of performance
- Any track type that wishes to opt in should make the top level display have …
> Create concept of global hovered state

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabelContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/linear-genome-view/src/index.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- products/jbrowse-web/src/util.ts
- test_data/volvox/config.json
- website/docs/config/LinearGenomeViewConfigSchema.md
This creates a configuration setting that allows admins to specify a preferred track label setting for their instance
It uses a 'rarely used' configuration setup where the LinearGenomeView plugin class has a configurationSchema property that provides some 'global config slots'
Therefore we have
configuration.LinearGenomeViewPlugin.trackLabels being a config types.enum('offset','overlapping','hidden')
this is accessible by calling
getConf(session,['LinearGenomeViewPlugin','trackLabels'])
there is a complex interplay between current session state, configuration, and user preference with this setting
one problem that actually currently exists is that visiting share link with e.g. trackLabels hidden would cause your current localStorage preference for lgv-trackLabels to automatically become …
> Allow configuring LGV trackLabels setting via config

- packages/core/rpc/BaseRpcDriver.ts
I'll explain the reasoning behind this extension point, and I'm certainly open to other ideas of ways to solve it if needed.
In Apollo, data about assemblies, features, sequences, etc. are stored in the session, and the Apollo display doesn't use web workers since it directly observes that store. For things like the regular JBrowse sequence track, though, it does use a web worker, and so can't read from the Apollo store in the session. We've gotten around this by creating a "FromConfigSequenceAdapter" when opening local GFF3s, but that duplicates a lot of data.
This extension point allows us to extend workers, which I've then used in Apollo to add an extra event listener in the worker. This allows the worker to query the main thread for data, which goes outside the normal RPC …
> Proposal: Add "extendWorker" extension point

- package.json
- products/jbrowse-cli/README.md
- products/jbrowse-cli/package.json
- products/jbrowse-cli/src/commands/sort-gff.ts
- yarn.lock
This helps automate the sorting of a gff, which can require tedious typing
This could be used in the Current Protocols paper also as a way to reduce steps
Assumes a unix-y type system with sh, sort, grep
> Add `jbrowse sort-gff` subcommand

- packages/core/BaseFeatureWidget/BaseFeatureDetail/index.tsx
- plugins/linear-comparative-view/src/LGVSyntenyDisplay/components/LaunchSyntenyViewDialog.tsx
- plugins/linear-comparative-view/src/LGVSyntenyDisplay/components/util.ts
- plugins/linear-comparative-view/src/LGVSyntenyDisplay/model.ts
- products/jbrowse-web/src/tests/BookmarkWidget.test.tsx
- products/jbrowse-web/src/tests/Spreadsheet.test.tsx
The text description of this text box is a little lengthy, but I think it helps clarify the behavior. Currently, it automatically horizontally flips the lower panel if an inverted feature is used to launch the linear synteny view, but this instead prompts the user for this behavior. The checkbox is not shown at all if the feature is not inverted, but the window size is still prompted (which kind of is just a small thing to justify showing a dialog box)
inverted feature
non inverted feature
> Prompt to horizontally flip view when launching linear synteny view on inverted feature

- packages/product-core/src/ui/AboutDialogContents.tsx
Fixes #3884
this is the same technique the entire 'jbrowse' object uses at a high level, but just added for this particular location for copying the track config
> Strip baseUri in 'About track' copy config

- plugins/linear-genome-view/src/LinearGenomeView/components/SearchBox.tsx
If you enter e.g. "chr1" in the search box, it skips lookup in e.g. the trix store, because it just knows it is a refname and then quickly navigates to it.
If you try the same with a "multi-region" style navigation like "chr1 chr2" to open up chr1 and chr2 side by side, it will not do this short cut, but this PR fixes that (first space separates the search query, then applies check for shortcut on each element of array)
> Speed up "multi-region" navigation in search box

- plugins/menus/src/SessionManager/components/AutosavedSessionsList.tsx
- plugins/menus/src/SessionManager/components/DeleteSavedSessionDialog.tsx
- plugins/menus/src/SessionManager/components/RegularSavedSessionsList.tsx
- plugins/menus/src/SessionManager/components/SessionListItem.tsx
- plugins/menus/src/SessionManager/components/SessionManager.tsx
- plugins/menus/src/SessionManager/components/util.ts
- plugins/variants/src/StructuralVariantChordRenderer/Chord.tsx
- plugins/variants/src/StructuralVariantChordRenderer/ReactComponent.tsx
- products/jbrowse-web/src/components/SessionWarningDialog.tsx
- website/src/pages/contact.mdx
some view types, e.g. MsaView, do not have any tracks, and this caused the Open session widget to crash (it tries to calculate sum of all view.tracks)
> Fix crash in "Open session" widget for sessions that have 'track-less views'

- products/jbrowse-web/src/SessionLoader.ts
fixes https://github.com/GMOD/jbrowse-components/issues/4012
True programmability for config loading probably is best to use @jbrowse/react-app but this may help some use cases
> Allow specifying alternative config.json path via global variable

- products/jbrowse-web/src/components/JBrowse.tsx
- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/components/ShareDialog.tsx
- products/jbrowse-web/src/tests/BreakpointSplitView.test.tsx
The URL manipulations we do in jbrowse-web are based on URL query params, but the default of the query param manipulation effectively used "pushState" (https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) instead of "replaceState" (https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState)
this was managed by the library we used (use-query-params), but this PR changes it to use replace instead now. This allows the browser back button to work more intuitively I think now
Fixes https://github.com/GMOD/jbrowse-components/issues/1128
> Fix browser back button behavior in jbrowse-web

- plugins/bed/src/BedpeAdapter/BedpeAdapter.ts
- website/docs/quickstart_web.md
- website/release_announcement_drafts/v2.7.3.md
- website/release_announcement_drafts/v2.8.0.md
* Other
* [#4046](https://github.com/GMOD/jbrowse-components/pull/4046) Show last autosave on jbrowse-web start screen ([@cmdcolin](https://github.com/cmdcolin))
* [#4044](https://github.com/GMOD/jbrowse-components/pull/4044) Speed up "multi-region" navigation in search box ([@cmdcolin](https://github.com/cmdcolin))
* [#4032](https://github.com/GMOD/jbrowse-components/pull/4032) Add `jbrowse sort-gff` subcommand ([@cmdcolin](https://github.com/cmdcolin))
* `product-core`
* [#4040](https://github.com/GMOD/jbrowse-components/pull/4040) Strip baseUri in 'About track' copy config ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4035](https://github.com/GMOD/jbrowse-components/pull/4035) Prompt to horizontally flip view when launching linear synteny view on inverted …
> v2.8.0 release announcement

- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
> Fix duplicate key error in hierarchical track selector

- packages/core/ui/CascadingMenu.tsx
Noticed that cascading menus were missing icons even when they were supplied to the list of MenuItems.
Not sure if the code changes align with the original intent of the component (e.g. I couldn't figure out why 'inset' was being used and the icon wasn't instead?), but this PR adds the provided icons to a cascading menu back to the left side of the menu text.
> Fixes missing icons on cascading menus

- products/jbrowse-react-linear-genome-view/package.json
- products/jbrowse-react-linear-genome-view/src/corePlugins.ts
Currently the lgv storybook actually crashes because the volvox config added a sample track that is a LinearPairedArcDisplay, which is supplied by plugin-arc, which works in jbrowse-web but not in the @jbrowse/react-linear-genome-view because plugin-arc is not added to the react-linear-genome-view
We could filter this out but IMO its probably just better to add this arc plugin to the lgv. It has useful variant viewing  characteristics for SVs which embedded can use
> Add arc plugin to lgv product

- notes/package.json.explainer.md
- package.json
- products/jbrowse-react-app/.storybook/main.js
- products/jbrowse-react-circular-genome-view/.storybook/main.js
- products/jbrowse-react-linear-genome-view/.storybook/main.js
- yarn.lock
One more dependency removed. The notes/package.json.explainer is removed also since it only mentions the ts-loader though it could be restored: there are some things that are worth annotating probably
> Remove ts-loader dependency used in storybooks

- products/jbrowse-desktop/package.json
It was observed on chat that the auto-update was not working on mac
This is due to the 'zip' files being unavailable for mac in the release in v2.7.2 forward which was a change that was unintentionally introduced by #4011 
This restores the zip file build
we could "potentially" restore the zip file builds on both v2.7.2 and v2.8.0 but it might be tricky to create proper app signing for them, so it might just be worth cutting a new release with the restored zip file and then the auto-updater will just look for the latest release
> Fix zip build for mac auto-update

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/ShoppingCart.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/__snapshots__/HierarchicalTrackSelector.test.tsx.snap
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HamburgerMenu.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/HierarchicalTree.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackCategory.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabel.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabelMenu.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/util.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/generateHierarchy.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
1) Fixes "Add to selection" highlighting of tracks
2) Passes trackId instead of full config objects for functions that manipulate recently used/favorites arrays, simplifies some logic (also uses set operations in some cases)
3) Renames some localStorage keys, makes more clear which are related to the option of showing
4) Changes the TreeNode to a tagged union of TreeCategoryNode and TreeTrackNode, simplifies some typescript
> Small refactoring for hierarchical track selector

- plugins/dotplot-view/src/DotplotView/components/ImportForm/index.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm/index.tsx
fixes #3941 
Changed the default "import form" for synteny views to show existing synteny tracks to launch rather than the "None" option by default.
If there are no synteny tracks available, it shows a red error, which isn't great, but the alternatives are some code that dynamically changes to new track or none if no synteny tracks are available. Not sure what the user expectation would be
> Make the default setting for the dotplot/synteny views use 'Existing tracks' by default

- packages/core/BaseFeatureWidget/BaseFeatureDetail/util.ts
- packages/core/PluginLoader.ts
- packages/core/configuration/types.ts
- packages/core/ui/react-colorful.js
- packages/core/util/simpleFeature.ts
- plugins/dotplot-view/src/DotplotRenderer/DotplotRenderer.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebar.tsx
- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/Arrow.tsx
- plugins/wiggle/src/drawXY.ts
- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/add-track.ts
- yarn.lock
There is code that will forcibly remove the file at the destination before doing the copy/move/symlink
This is due to a older bug https://github.com/GMOD/jbrowse-components/issues/2768
Unfortunately it has a weird side effect where --load inPlace and --force in combination, if the file path is a valid one (inPlace does not always require valid file paths), it will then remove that file
this is bad behavior, and so this PR fixes it to not forcibly remove the file when load inPlace is used.  It could probably additionally narrow it beyond this to only remove when load symlink is used, as copy and move may not be affected by the need to fs.unlink as #2768 brought up
> Fix issue where --load inPlace and --force can sometimes remove file unexpectedly

- packages/core/ui/CascadingMenu.tsx
- packages/core/ui/SanitizedHTML.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilter.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedHeader.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabel.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabelMenu.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/facetedModel.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- products/jbrowse-web/src/tests/JBrowse.test.tsx
- yarn.lock
The current faceted track selector uses mostly react hooks (and quite a few of them, useMemo, useReducer, useState, useEffect, prop drilling the useReducer/useState callbacks to multiple components, etc.) to try to synchronize relatively complex state. This changes it to mobx-state-tree which has a number of simplifying effects IMO
> Refactor faceted track selector to use more MST state

- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/SearchBox.tsx
- plugins/linear-genome-view/src/index.ts
- plugins/linear-genome-view/src/searchUtils.ts
This adds the ability to search by gene name from the &loc= in the URL bar for launching a linear genome view.
This would not yet work for synteny view because the synteny view still uses just navToLocString which assumes a locstring
Examples
```
localhost:3000/?config=test_data/volvox/config.json&loc=EDEN&assembly=volvox
localhost:3000/?config=test_data/volvox/config.json&loc=seg08&assembly=volvox
```
note that this may be just a larger issue of search box behavior, but I believe that it might popup if e.g. there are two gene tracks (e.g. ensembl and ncbi) with the same gene name even if they have "the same location"...it's not that bad but it may be undesirable for the URL bar to popup the selection box too much, its better to just jump right into the genome view if possible
this PR is …
> Allow searching the text-index by gene name from the URL bar

- packages/core/BaseFeatureWidget/BaseFeatureDetail/index.tsx
- packages/core/BaseFeatureWidget/index.ts
- packages/core/pluggableElementTypes/models/baseTrackConfig.ts
- packages/product-core/src/RootModel/FormatDetails.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- test_data/volvox/config.json
from question asked here https://github.com/GMOD/jbrowse-components/discussions/4084
the current feature detail formatter was not able to handle this (can't set e.g. formatDetails->subfeatures to undefined because it is maintained in a separate __jbrowsefmt object that isnt iterated over)
> Allow hiding subfeatures in the feature details panel

- plugins/linear-comparative-view/src/LaunchLinearSyntenyView.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/ImportForm.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/ImportFormRefNameAutocomplete.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/linear-genome-view/src/searchUtils.ts
- products/jbrowse-web/src/tests/JBrowse.test.tsx
Extends https://github.com/GMOD/jbrowse-components/pull/4068 for searching by gene name for a linear synteny view
Fixes https://github.com/GMOD/jbrowse-components/issues/3149
> Allow searching by gene name using linear synteny view

- package.json
- website/release_announcement_drafts/v2.9.0.md
* Other
* [#4070](https://github.com/GMOD/jbrowse-components/pull/4070) Add support for single file hubs ([@cmdcolin](https://github.com/cmdcolin))
* [#4096](https://github.com/GMOD/jbrowse-components/pull/4096) Allow searching by gene name using linear synteny view ([@cmdcolin](https://github.com/cmdcolin))
* [#4068](https://github.com/GMOD/jbrowse-components/pull/4068) Allow searching the text-index by gene name from the URL bar ([@cmdcolin](https://github.com/cmdcolin))
* [#3948](https://github.com/GMOD/jbrowse-components/pull/3948) Make the default setting for the dotplot/synteny views use 'Existing tracks' by default ([@cmdcolin](https://github.com/cmdcolin))
* [#4039](https://github.com/GMOD/jbrowse-components/pull/4039) Adds "Favorites" and "Recently used" track categories to the …
> v2.9.0 release announcement

- plugins/alignments/src/PileupRenderer/PileupRenderer.ts
- plugins/jobs-management/src/JobsListWidget/index.ts
- plugins/jobs-management/src/JobsListWidget/jobModel.ts
- plugins/jobs-management/src/JobsListWidget/model.ts
- plugins/jobs-management/src/index.ts
- plugins/linear-comparative-view/src/LinearReadVsRef/index.ts
- plugins/lollipop/src/LinearLollipopDisplay/configSchema.ts
- plugins/lollipop/src/LinearLollipopDisplay/index.ts
- plugins/lollipop/src/LinearLollipopDisplay/model.ts
- plugins/lollipop/src/LollipopRenderer/index.ts
- plugins/lollipop/src/index.ts
- plugins/wiggle/src/LinearWiggleDisplay/models/model.ts
- plugins/wiggle/src/MultiLinearWiggleDisplay/models/model.ts
- plugins/wiggle/src/MultiWiggleAddTrackWidget/index.ts
Fairly small misc PR
- bundle size improvements
- adds more autogen docs for e.g. joblistwidget, lollipop display
> Refactors and bundle size improvements

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx
Split out from https://github.com/GMOD/jbrowse-components/pull/4109 as it's pretty separate
This just is a small usability improvement for side-wheel scrolling the side panel. Potentially it could include a click and drag also, it would just have to be smart enough to avoid behavior of clicking on a feature
> Scroll both panels of the linear synteny view when side scrolling the middle panel

- plugins/data-management/src/AddTrackWidget/components/DefaultAddTrackWorkflow.tsx
Currently, after any usage of the Add track workflow, and an "info" level alert snackbar says
>> "Open a new view, or use the track selector in an existing view, to view this track"
However the "Add track" workflow automatically shows the track in the "current view", so I think this message may be unneeded. I would suggest removing, but it could also be re-phrased to tell the user that it was added to the current view and it is available in the track selector
> Remove session.notify after using the Add track workflow

- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
Fixes #4098 
Fixes #4111 
It also fixes the order in the recently used panel. The order shipped in v2.9.0 is not in any particular order, now the latest is at the bottom. This was a somewhat subtle bug because the order was actually the order basically from the config.json
Note that this would lose the recently used entries that anyone accumulated through using v2.9.0 but hopefully not too bad to have that happen...
> Split recently used local storage keys by view.assemblyNames

- package.json
- packages/core/assemblyManager/assembly.ts
- packages/core/assemblyManager/assemblyManager.ts
- packages/core/data_adapters/dataAdapterCache.ts
- packages/core/package.json
- packages/core/util/index.ts
- plugins/config/src/FromConfigAdapter/FromConfigAdapter.ts
- plugins/config/src/FromConfigRegionsAdapter/FromConfigRegionsAdapter.ts
- yarn.lock
Large FromConfigAdapter may be used for things like data frame tracks in jbrowse jupyter
Future usages of jbrowse-jupyter may create e.g. a custom adapter type, but this may help in the interim
> Speed up large FromConfigAdapter usages with alternative adapter id calculation

- plugins/arc/src/LinearPairedArcDisplay/components/Arcs.tsx
- website/docs/user_guides/bookmark_widget.md
The little feet can improve breakend interpretation
fixes https://github.com/GMOD/jbrowse-components/issues/4051
> Add directional feet to breakends in linear arc display

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilter.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedSelector.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/util.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/facetedModel.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
Reported by @scottcain 
Bottom right is empty
> Fix metadata facet filters being blank

- plugins/bed/src/BedAdapter/__snapshots__/BedAdapter.test.ts.snap
- plugins/bed/src/BedTabixAdapter/__snapshots__/BedTabixAdapter.test.ts.snap
- plugins/bed/src/BigBedAdapter/__snapshots__/BigBedAdapter.test.ts.snap
- plugins/bed/src/util.ts
Adds a refName field to all subfeatures.
Fixes #4157 
An alternative could potentially be done so that the subfeatures always look at their parent feature for the refName but this is interim or easy fix
> Fix subfeature refNames on BED and BEDTabix parsers

- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/set-default-session.test.ts
- products/jbrowse-cli/src/commands/set-default-session.ts
These options were created very early on but they have not worked for awhile and generated incomplete state snapshots of the session which could not be loaded
the alternative to removing this would be to either (a) make the CLI make a more complete snapshot or (b) make our code allow incomplete state snapshots to load
fixes https://github.com/GMOD/jbrowse-components/issues/2708
> Remove --tracks and --view options from set-default-session CLI

- packages/core/package.json
- packages/core/ui/ErrorMessage.tsx
- packages/core/ui/ErrorMessageStackTraceDialog.tsx
- packages/core/ui/RedErrorMessageBox.tsx
- packages/core/ui/Snackbar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- yarn.lock
This allows users to get the stack trace for various error messages in the user interface without having to go to their browser devtools
Tested in Safari-alike (GNOME Web), Firefox, and Chrome in both dev mode and production build
example screenshot
inspired by code here https://stackoverflow.com/questions/75400967/get-stack-trace-as-a-string-when-using-source-map
> Add ability to get stack trace for error messages in the UI

- component_tests/cgv/cypress/tsconfig.json
- component_tests/cgv/tsconfig.json
- component_tests/lgv/cypress/tsconfig.json
- component_tests/lgv/tsconfig.json
- component_tests/react-app/cypress/tsconfig.json
- component_tests/react-app/tsconfig.json
- docs/tsconfig.json
- packages/core/tsconfig.json
- plugin-development-tools/tsconfig.json
- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
- plugins/sequence/src/DivSequenceRenderer/components/__snapshots__/DivSequenceRendering.test.tsx.snap
- products/jbrowse-cli/tsconfig.json
- products/jbrowse-desktop/tsconfig.json
- products/jbrowse-img/tsconfig.json
- products/jbrowse-react-app/tsconfig.json
- products/jbrowse-react-circular-genome-view/tsconfig.json
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/tsconfig.json
- products/jbrowse-web/src/tests/OAuthServer/index.ts
- products/jbrowse-web/tsconfig.json
- tsconfig.json
- website/tsconfig.json
- yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/4175
> Remove text selection on sequence track with user-select: none

- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/index.test.ts
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/createPluginManager.ts
- website/docs/urlparams.md
- yarn.lock
> Allow adding &tracklist=true to URL bar to open the track selector, &nav=false to hide linear genome view header

- plugins/alignments/src/BamAdapter/BamAdapter.ts
- plugins/alignments/src/CramAdapter/CramAdapter.ts
- yarn.lock
Was doing an incorrect comparison to the tags value being * instead of the tag filter's value being *
Fixes https://github.com/GMOD/jbrowse-components/issues/4204
> Fix issue with tagFilter * in alignments track

- website/release_announcement_drafts/v2.10.2.md
Adds the new "Show stack trace" button to error messages, may help get better error reports from users without trying to instruct use of devtools (which doesn't even work in desktop also, i don't believe we have devtools enabled on our desktop build)
> v2.10.2 release announcement

- plugins/alignments/src/CramAdapter/CramAdapter.ts
- website/blog/2024-02-19-v2.10.2-release.md
- website/release_announcement_drafts/v2.10.2.md
- yarn.lock
This just bumps the @gmod/bam parser version which contains a fix for this xref https://github.com/GMOD/bam-js/pull/103
> Fix parsing of BAM refNames that contain a colon

- packages/core/pluggableElementTypes/renderers/ServerSideRenderedContent.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.test.tsx
- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
- plugins/sequence/src/DivSequenceRenderer/components/__snapshots__/DivSequenceRendering.test.tsx.snap
- plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/__snapshots__/SvgFeatureRendering.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
I wanted to see if I could get rid of the scrollbar on the default sequence display:
I started by passing the height for the display model to the renderer and using that as the SVG height. The height was previously hardcoded to 200px, and this change made the scrollable amount smaller, but the scrollbar was still there:
Inspecting the document, I saw that the `div` wrapping the SVG was a few pixels bigger that the SVG height, but it didn't have any padding, and the SVG inside didn't have a margin, so I wasn't sure what was making the height taller.
I also wasn't sure where that `div` was at first, but figured out that it's the `div` that the SSR content get hydrated into. I figured the extra spacing must be some built-in browser behavior related to block spacing. I tried setting `margin`, …
> Get rid of scrollbar on default sequence display

- website/docs/faq.md
Small FAQ section about the faceted track selector. This information was missing for me in the docs. Not sure if it's complete, or the right spot.
> Add FAQ section about faceted track selector

- plugins/breakpoint-split-view/src/BreakpointSplitView/components/Translocations.tsx
- products/jbrowse-web/src/tests/JBrowse.test.tsx
this fix will not have the "directional feet" that the strands tag helps with, but it at least does not crash :)
fixes usage with some DELLY VCF, potentially (as a follow on) can use a different tag from DELLY called "CT" which says "5to3" and "5to5" as an equivalent to STRAND
Fixes https://github.com/GMOD/jbrowse-components/issues/4188
Fix follows from office hours meeting
> Fix for missing INFO.STRANDS tag for TRA features in breakpoint split view

- plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx
- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/Highlight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewHighlight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/Loader.tsx
- website/docs/faq.md
Responds to comments on https://github.com/GMOD/jbrowse-components/issues/2316 and https://github.com/GMOD/jbrowse-components/issues/599 requesting a highlight feature similar to what existed in JB1.
Allows a user to specify a highlight region in the URL with the pattern &highlight=REF:START..END
> Adds URL query param for highlight on LGV

- packages/core/util/types/index.ts
- packages/product-core/src/RootModel/BaseRootModel.ts
- products/jbrowse-desktop/src/components/JBrowse.tsx
- products/jbrowse-desktop/src/rootModel/Menus.ts
Instead of custom MST state management about whether the assembly manager is open, use the 'standard' queueDialog API to open the "assembly manager"
> Queue dialog for assemblymanager

- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
can compare the viewport when visiting these links
https://jbrowse.org/code/jb2/order_of_operations/?loc=BRCA1&assembly=hg19&tracklist=true
https://jbrowse.org/code/jb2/main/?loc=BRCA1&assembly=hg19&tracklist=true
this PR branch includes the gene full width in the view
the main branch has the gene partially hidden
i'm not sure if this is 100% reliable as this code doesn't "wait for the viewport width to include that tracklist" but it could help
the source of this problem is that the state of the view is driven primarily by a combination of variables (bpPerPx and offsetPx and displayedRegions) instead of the desired loc string
This has some odd consequences including the fact that a share link from a screen that is e.g. 800px does not get stretched when shared with a screen that has width …
> Fix the viewport calculations for when URL params includes &tracklist=true

- packages/core/util/tracks.ts
- packages/text-indexing/package.json
- packages/text-indexing/src/util.ts
- products/jbrowse-desktop/src/indexJobsModel.ts
this combination of methods fixes text indexing on windows. some code was assuming forward slashes for filename separators essentially
> Fix text indexing on jbrowse desktop with MS Windows

- packages/core/ui/ErrorMessageStackTraceDialog.tsx
- packages/product-core/src/ui/FileInfoPanel.tsx
- plugins/alignments/src/shared/BaseDisplayComponent.tsx
- plugins/arc/src/LinearPairedArcDisplay/components/BaseDisplayComponent.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/dialogs/ManageConnectionsDialog.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/BlockMsg.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/LinearBlocks.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/ServerSideRenderedBlockContent.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/TooLargeMessage.tsx
The track errors do not use the "ErrorMessage" component with the built-in stack trace button so PR adds a the stack trace button to track errors
it works for web worker errors
I replaced the "API" of the BlockMsg component to make "action" a React.ReactNode instead of just a function, therefore any amount of stuff can be placed, and I just use IconButton instead of the "Reload" text
> Allow getting stack trace from track errors

- website/release_announcement_drafts/v2.10.3.md
* [#4234](https://github.com/GMOD/jbrowse-components/pull/4234) Adds URL query param for highlight on LGV ([@carolinebridge-oicr](https://github.com/carolinebridge-oicr))
* [#4232](https://github.com/GMOD/jbrowse-components/pull/4232) Fix for missing INFO.STRANDS tag for TRA features in breakpoint split view ([@cmdcolin](https://github.com/cmdcolin))
* [#4224](https://github.com/GMOD/jbrowse-components/pull/4224) Fix parsing of BAM and CRAM refNames that contain a colon ([@cmdcolin](https://github.com/cmdcolin))
* [#4240](https://github.com/GMOD/jbrowse-components/pull/4240) Small fixes to embedding tutorial docs ([@kwentine](https://github.com/kwentine))
* [#4223](https://github.com/GMOD/jbrowse-components/pull/4223) Add FAQ section about faceted track selector …
> v2.10.3 release announcement

- packages/text-indexing/src/types/gff3Adapter.ts
- packages/text-indexing/src/types/vcfAdapter.ts
- packages/text-indexing/src/util.ts
- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/types/gff3Adapter.ts
- products/jbrowse-cli/src/types/vcfAdapter.ts
- products/jbrowse-cli/src/util.ts
Some files are badly encoded (not following e.g. GFF3 spec) and cause decodeURIComponent to throw. This is not a good user experience. This PR just proposes passing the string along
addresses https://github.com/GMOD/jbrowse-components/discussions/4268
> Use a "no throw" version of decodeURIComponent for text indexing

- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/Highlight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewHighlight.tsx
Fixes #4261 
works
https://s3.amazonaws.com/jbrowse.org/code/jb2/fix-ref-name-highlight/index.html?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=1:2,000,000-2,100,000&tracks=repeats_hg19
works
https://s3.amazonaws.com/jbrowse.org/code/jb2/fix-ref-name-highlight/index.html?config=test_data%2Fconfig_demo.json&assembly=hg19&loc=1:1,937,214..2,081,004&highlight=chr1:2,000,000-2,100,000&tracks=repeats_hg19
> Fixes bug on URL highlight param in which refName aliases were not working

- packages/core/ui/ErrorMessage.tsx
- packages/core/ui/ErrorMessageStackTraceDialog.tsx
- plugins/svg/src/SvgFeatureRenderer/components/ProcessedTranscript.tsx
- products/jbrowse-web/src/components/ShareDialog.tsx
- yarn.lock
example screenshot of new error box with the refresh icon
changes the text "Show stack trace" to the "Report" icon, and optionally displays a refresh icon if a "onReset" callback is passed to ErrorMessage
fixes https://github.com/GMOD/jbrowse-components/issues/4274
> Add retry method to share link dialog in case of error

- packages/core/util/jexl.ts
- test_data/volvox/volvox.sort.gff3
This adds a JSON.parse utility to the jexl functions. It is a little specialized but this can enable a sort of (office hours) use case where a table of data can be stored in a GFF3 attribute as a json "array of objects". A volvox track showing this use case is added in this PR too
The alternative is that this isn't a built in utility but doesn't seem too bad to add it
> Add JSON.parse utility to the "jexl function library"

- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/add-connection.ts
> Fix usage of --assemblyNames in `jbrowse add-connection`

- plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/OverviewHighlight.tsx
> Add key to overview highlights to fix test warning

- package.json
- products/jbrowse-desktop/package.json
- yarn.lock
This takes influence from how the mac "multiple targets" config is defined (as an array of objects with "target" key within an array of targets within the OS specific grouping)
this was made from studying https://www.electron.build/configuration/linux
it is allowed for there to be a top level snap key, as before, but this changes it to be inside the linux grouping
more linux builds (.tar.gz, deb, etc) could be added also
> Optimistically fix snap package and also add deb package

- README.md
- website/src/pages/contact.mdx
- website/src/pages/util.tsx
Had a hard time sharing the account settings with the jbrowse2dev@gmail.com so now it is a true shared account with jbrowse2@berkeley.edu that garrett and i can respond to
This PR also removes the community meetings. They ended up basically being kind of one-on-one discussions with maybe 1 or two other people joining, so it might just be better as the office hours system anyways.
I think there has been a reasonable amount of feedback from people from the community meetings but I think the office hours is probably the best going forward
if there are any objections to removing community meetings lemme know :)
> Change office hours link to new berkeley google account and remove community meetings

- packages/core/PluginManager.ts
- packages/core/ReExports/modules.tsx
- packages/core/pluggableElementTypes/models/BaseTrackModel.ts
- packages/core/ui/ErrorMessage.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/gccontent/src/GCContentTrack/configSchema.ts
- plugins/gccontent/src/GCContentTrack/index.ts
- plugins/gccontent/src/LinearGCContentDisplay/config1.ts
- plugins/gccontent/src/LinearGCContentDisplay/config2.ts
- plugins/gccontent/src/LinearGCContentDisplay/index.ts
- plugins/gccontent/src/LinearGCContentDisplay/shared.ts
- plugins/gccontent/src/LinearGCContentDisplay/stateModel1.ts
- plugins/gccontent/src/LinearGCContentDisplay/stateModel2.ts
- plugins/gccontent/src/index.ts
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- test_data/volvox/config.json
this incorporates the "GC content display" but is a separate track type
it requires cloning the display type since a display can only be registered to one track type at a time
> Create GCContentTrack type

- plugins/hic/src/HicAdapter/HicAdapter.ts
- plugins/hic/src/HicRenderer/HicRenderer.tsx
assumed that it should shift the offset by the bp coordinate of the "first data line in the file" but this is actually wrong when it is sparse...I believe the correct shift is just the region start bp coordinate
> Fix Hi-C rendering for some high resolution files

- products/jbrowse-cli/README.md
- products/jbrowse-cli/package.json
- products/jbrowse-cli/src/base.ts
- products/jbrowse-cli/src/commands/add-connection.ts
- products/jbrowse-cli/src/fetchWithProxy.ts
- products/jbrowse-cli/src/types/gff3Adapter.ts
- products/jbrowse-cli/src/types/vcfAdapter.ts
- yarn.lock
This adds a new package, node-fetch-native, for running fetch commands in the CLI. It removes the punycode warning, which while minor, is confusing when running the CLI
it forces the use of the polyfill, as the actual native gives errors with streams. Likely this should get fixed at some point, as our code is therefore overfitting to "non standard fetch behavior" regarding streams, but this PR does work
Fixes #4163
> Use node-fetch-native to fix warning from JBrowse CLI on node 21+

- packages/app-core/src/ui/App/ViewMenu.tsx
- packages/product-core/src/Session/MultipleViews.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- yarn.lock
this is supplementary to pinning track, I think there is still an opportunity to have these operations without track pinning
see screenshot, since it expands the number of menu items significantly the options are placed under a submenu sort of opaquely named "options"
> Add track menu items to move track to up/down/to top/to bottom, and moving views to top/to bottom

- plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx
- plugins/linear-genome-view/src/LaunchLinearGenomeView/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/Highlight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewHighlight.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-react-linear-genome-view/src/createViewState.ts
- products/jbrowse-web/src/SessionLoader.ts
- website/docs/urlparams.md
Some QOL improvements on this small feature:
- adds ability to highlight multiple locations using URL query API
**example:** [&highlight=7:140,636,065..140,680,172;7:140,609,755..140,624,677](https://s3.amazonaws.com/jbrowse.org/code/jb2/improve-url-quer-highlight/index.html?config=test_data/config_demo.json&loc=7:140,307,327..140,730,530&assembly=hg19&tracks=mygene_hg19,nclist_genes_hg19&highlight=7:140,636,065..140,680,172;7:140,609,755..140,624,677)
NOTE: must delimit highlights with a semi-colon to avoid collision with the location string parsing
- adds ability to highlight locations using createViewState
**example:**
```
const state = createViewState({
assembly,
tracks,
location: 'ctgA:1105..1221',
highlight: ['ctgA:1,117..1,135', 'ctgA:1,155..1,174'],
onChange: patch => { …
```
> Adds ability to highlight multiple locations using URL query API

- packages/core/ui/ErrorMessageStackTraceDialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- fixes usage on https sites
- small data display improvements
> Improve error dialog stack trace display

- website/src/pages/index.tsx
- website/src/pages/util.tsx
Fixes #4310 
the usage of the MUI Link component seems a culprit, it gets mixed up with docusaurus styling. however, the styling for, particularly the schedule appointment button is less bold since Button href is the same as a Link essentially in terms of causing the error.
note that one quote suggests that MUI might be discouraged on docusaurus pages
"Please also understand that Docusaurus doesn't have good support for "legacy CSS-in-JS libs" (StyledComponents, Emotion, JSS, MUI...), that require collecting styles during the rendering process (see also https://github.com/facebook/docusaurus/issues/3236).
So I'd simply recommend not using MUI in the first place, unless you clearly understand the tradeoff you make and the risk of having flashes of unstyled content." …
> Fix docusaurus hydration error on page load

- packages/app-core/src/ui/App/Drawer.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/4272
Adds a position:relative to the drawer container
Without this it uses position:absolute relative to the body of the page
> Fix Fab positioning on @jbrowse/react-app

- products/jbrowse-desktop/package.json
This removes snap from our linux options. 
Closes https://github.com/GMOD/jbrowse-components/issues/4260
Closes https://github.com/GMOD/jbrowse-components/issues/3777
Could reconsider in the future if there is interest but snap is just causing problems at release time right now
The deb package i tried out seemed to have trouble too
> Remove snap package 

- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/util.ts
- plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/3977
Currently if you collapse a category in the track selector, then close it, then re-open it, then is not collapsed on re-opening. 
This stores the collapsed category settings and sort settings in localStorage
> Store and retrieve user track selector settings in local storage

- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- plugins/wiggle/src/LinePlotRenderer/LinePlotRenderer.ts
- plugins/wiggle/src/LinearWiggleDisplay/components/SetColorDialog.tsx
- plugins/wiggle/src/WiggleBaseRenderer.tsx
- yarn.lock
Currently was hard coded to use grey
This adapts it to use the #f0f (hard magenta, e.g. not configured) to fallback to grey, and otherwise use what user specified
> Fix ability to choose line plot bigwig coloring

- packages/core/util/calculateDynamicBlocks.ts
- packages/core/util/range.ts
I was using the `intersection2` function in Apollo and realized the return type could be narrowed to `[number, number] | []` instead of the inferred `number[]`.
> Improve return type of `intersection2`

- packages/core/configuration/util.ts
- packages/core/pluggableElementTypes/models/BaseDisplayModel.tsx
- packages/core/pluggableElementTypes/renderers/util/serializableFilterChain.ts
- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/models/configSchema.ts
- plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
- plugins/linear-genome-view/src/LinearBasicDisplay/components/AddFiltersDialog.tsx
- plugins/linear-genome-view/src/LinearBasicDisplay/components/SetMaxHeightDialog.tsx
- plugins/linear-genome-view/src/LinearBasicDisplay/model.ts
- yarn.lock
This allows users to configure a filter in their config.json as an array of jexl strings, or set an array of jexl filters
Fixes #1988 
Screenshot showing the runtime dialog
The filters are stored on the LinearBasicDisplay model as a prop named jexlFilters, and the state model is used if no config filters are supplied (otherwise config filters are used, which is an empty array by default)
As the UI is currently designed, the user actually types out jexl: when they are hand-editing the UI. this is a small code simplification, but we could remove it and  make it automatically prepend this string. Random note regarding that: i am somewhat just discouraged by the limitations of jexl, so we could consider looking at escape routes e.g. trying to create a javascript eval if security concerns can …
> Allow users to configure filters and set them at runtime via a editable dialog

- packages/core/ui/ErrorMessageStackTraceDialog.tsx
This adds a raw version of the function name to the stack traces. It could be a minified name in some cases, but it should make a little more readable stack traces
just for reference the match[1] refers to matching everything before http from lines like this
```
loadDataP@http://localhost:3001/static/js/plugins_gff3_src_Gff3Adapter_Gff3Adapter_ts.chunk.js:41:13
```
so in that case, match[1] would be loadDataP@
here is another example with a longer stack trace
with this PR:
```
Stack trace
Post a new issue at [GitHub](https://github.com/GMOD/jbrowse-components/issues/new?labels=bug&title=JBrowse+issue&body=I%20got%20this%20error%20from%20JBrowse%2C%20here%20is%20the%20stack%20trace%3A%0A%0A%60%60%60%0AError%3A%20test%0A%2FUsers%2Fcolin%2Fsrc%2Fjbrowse-components%2Fplugins%2Flinear-genome-vi …
```
> Include a raw version of function names in error message stack traces

- products/jbrowse-desktop/src/sessionModel/index.ts
the theme is passed in via renderProps on the session model, which gets applied to e.g. the display's renderProps function via getParentRenderProps
the fix is to use the "currently active theme" (state variable) rather than just the pre-configured theme (via getConf, which is what it was on main)
> Fix custom theme being applied in renderings in desktop

- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
- plugins/gff3/src/Gff3Adapter/__snapshots__/Gff3Adapter.test.ts.snap
Uses line-by-line parsing of the Buffer object instead of upfront conversion to the string to avoid the 512Mb string limitation (Buffer can be longer than 512Mb). It also reports the progress with statusCallback which gives some indication of what is happening during possibly long (e.g. 30+ second) loading of larger files
fixes #4403
> Allow loading plaintext GFF3 files larger than 512Mb

- plugins/dotplot-view/src/DotplotView/components/DotplotControls.tsx
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
The current behavior to use "ctrl+key" for the alt click and drag behavior doesn't work on Mac because it is a right click without any recourse to disable this. Therefore, this handles using the cmd key as an alternative. 
This is just a small UI think but this PR also changes the pointer cursor style immediately after the ctrl/cmd key press instead of only triggering the cursor style after the keypress+click
> Allow using Cmd key for alternative click and drag behavior on Mac for dotplot

- website/release_announcement_drafts/v2.11.2.md
* Other
* [#4406](https://github.com/GMOD/jbrowse-components/pull/4406) Allow loading plaintext GFF3 files larger than 512Mb ([@cmdcolin](https://github.com/cmdcolin))
* [#4398](https://github.com/GMOD/jbrowse-components/pull/4398) Adds a context menu option to zoom to a feature ([@carolinebridge](https://github.com/carolinebridge))
* `core`
* [#4405](https://github.com/GMOD/jbrowse-components/pull/4405) Include a raw version of function names in error message stack traces ([@cmdcolin](https://github.com/cmdcolin))
* [#4393](https://github.com/GMOD/jbrowse-components/pull/4393) Allow users to configure filters and set them at runtime via a editable dialog ([@cmdcolin](https://github.com/cmdcolin))
* [#4395](https://github.com/GMOD/jbrowse-components/pull/4395) Remove …
> v2.11.2 release announcement

- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
Small typescript issue related to undefined result of record data access
related to my typescript rant/blogpost https://cmdcolin.github.io/posts/2023-09-27-areyousure
We could consider turning on noUncheckedIndexedAccess tsc setting to try to help this more or less globally...but this just targets the smaller fix
Regression after #4406
> Fix bug parsing GFF3 data on chromosomes where data is empty

- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm/index.tsx
fixes https://github.com/GMOD/jbrowse-components/issues/4372
alternative approaches or add-ons to this PR could be taken include
a) allowing user to use a refname autocomplete on the import form before submitting
b) allow user to tailor the set of chromosomes displayed in some way (similar to https://github.com/GMOD/jbrowse-components/issues/2063) which could help for very fragmented e.g. hundreds of thousands of scaffolds scenarios
the default output comparing hg19 vs hg38 looks like so after this PR
> Show all regions in synteny view after submitting import form

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx
Using the side scroll in the center area of the linear synteny view is useful, but can trigger the native browser 'back' and 'forward' history actions, which we don't want. This switches the react onWheel handler for a global event handler to properly disable the onWheel behavior because react event handlers can not event.preventDefault() [1]
[1] "React binds all events at the root element (not the document), and the wheel event is binded internally using true [option](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters), and I quote MDN:
A Boolean that, if true, indicates that the function specified by listener will never call preventDefault(). If a passive listener does call preventDefault(), the user agent will do nothing other than generate a …
> Avoid browser native back action with wheel side scroll in linear synteny view

- plugins/dotplot-view/src/DotplotView/components/DotplotWarnings.tsx
- yarn.lock
The dotplot can render warnings sometimes, but sometimes these are noisy due to mismatching refnames from the synteny track and the refernce genome fasta. This  PR allows the user to 'dismiss' them with a button that says "DISMISS"
> Add ability to dismiss dotplot warnings

- plugins/alignments/src/AlignmentsFeatureDetail/LaunchBreakpointSplitViewPanel.tsx
- plugins/alignments/src/AlignmentsFeatureDetail/SuppAlignmentsLocStrings.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx
- products/jbrowse-desktop/src/components/StartScreen/RecentSessionList.tsx
I noticed that code in the alignment details widget (plugins/alignments/src/AlignmentsFeatureDetail/SuppAlignmentsLocStrings.tsx) had links with mouseover where the cursor did not use the pointer style, which turns out to be due to missing href prop on the Link element. For Link elements without a true href (e.g. they are more link link buttons), we can use href="#" and then event.preventDefault in the handler. 
The alternative is not having any href and then using the makeStyles to restore the cursor:pointer style, but i think the href="#" is a bit more idiomatic. Just gotta remember to event.preventDefault in those cases.
> Fix cursor:pointer style on an alignments feature detail clickable link

- packages/core/util/Base1DUtils.ts
- packages/core/util/Base1DViewModel.ts
- packages/core/util/index.ts
- packages/core/util/types/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
Pros: 
- can handle very large sets of displayedRegions, which can occur from "show all regions" operations from a linear genome view, or showing entire genome in synteny view
Cons: 
- changes the 'type spec' of the linear genome view, so calling getSnapshot on the displayedRegions object (or individual regions) is a thrown error (kind of annoying)
- can't directly "push" or mutate the self.displayedRegions array since it is not an observable after this
- there are problems with creating gigantic displayedRegions sets anyways because it causes the sessions to be too large to share, but that is sort of an aside
You can see benefit by performing a show all regions on our 'many_contigs' test dataset
main
https://jbrowse.org/code/jb2/main/?config=test_data%2Fmany_contigs%2Fconfig.json
this …
> Convert displayedRegions from MST array of Region[] into a types.frozen<IRegion[]> to speed up large displayedRegions sets

- plugins/wiggle/src/MultiLinearWiggleDisplay/components/DraggableDialog.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SourcesGrid.tsx
This changes the "DraggableDialog" component to use refs instead of findDOMNode which is deprecated
> Use ref instead of deprecated findDOMNode for draggable dialog

- packages/core/BaseFeatureWidget/SequenceFeatureDetails/SequenceFeatureDetails.test.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/SequenceFeatureDetails.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/SequencePanel.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/dialogs/SequenceDialog.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/dialogs/SequenceFeatureMenu.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/dialogs/SequenceTypeSelector.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/model.ts
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/seqtypes/CDNASequence.tsx
- packages/core/BaseFeatureWidget/SequenceFeatureDetails/seqtypes/SequenceDisplay.tsx
- packages/core/stories/examples/WithSequencePanel.tsx
Adds genomic coordinates back into the sequence panel accounting for strand direction
https://github.com/GMOD/jbrowse-components/issues/3873
> Adds genomic coordinates back into the sequence panel accounting for strand direction

- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/model.ts
The concept is somewhat cumbersome to toggle, and now the middle panel of the synteny view can be used instead
A similar thing could be done for breakpoint split view, but it does not have the same idea of a middle area which does challenge it a bit
Would fix #4375 as a round about
> Remove the concept of linking the views in the synteny view

- packages/core/ui/Dialog.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackRenderingContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/src/__snapshots__/jbrowseModel.test.ts.snap
- test_data/volvox/config.json
Currently there are two funny things when storing an `<a href>` in a track label
1) dialog titles display the raw html in track title
2) unable to click links when they are activated tracks due to a pointerEvents:none
this removes the pointerEvents:none and instead just makes it so it doesn't trigger a click and drag side scroll. side benefit is you can copy the track names this way
> Add more support for putting html link in track names

- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.test.tsx
- plugins/config/src/ConfigurationEditorWidget/components/ConfigurationEditor.tsx
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
In the configuration editor, the "array of displays" is listed as e.g. display 1, display 2, display 3...and there is no indication of what they are
This changes it to list the slot.type
main
this branch
fixes #3398
> Add slot.type to configuration editor elements

- products/jbrowse-desktop/linux-sandbox-fix.js
- products/jbrowse-desktop/package.json
Fixes #4457
This is adapted from a script I found that replaces the AppImage launcher script with a bash one-liner that adds the no-sandbox flag
https://github.com/d3473r/jitsi-meet-electron/commit/11b9348f117a87349917c252cbae203cf92062a8
there were other things that discussed adding the no-sandbox flag via the 'main' process with app.appendSwitch('--no-sandbox') but this did not work for me
I also add --no-sandbox to the devmode script. This is a little 'heavy handed' but it only affects dev mode
> Fix sandbox error on AppImage startup on certain linux systems

- website/release_announcement_drafts/v2.12.0.md
* Other
* [#4459](https://github.com/GMOD/jbrowse-components/pull/4459) Allow using keyboard shortcut for devtools in production desktop builds ([@cmdcolin](https://github.com/cmdcolin))
* [#4455](https://github.com/GMOD/jbrowse-components/pull/4455) Add slot.type to configuration editor elements ([@cmdcolin](https://github.com/cmdcolin))
* [#4427](https://github.com/GMOD/jbrowse-components/pull/4427) Add ctrl+wheel scroll to zoom both top and bottom of synteny view ([@cmdcolin](https://github.com/cmdcolin))
* [#4425](https://github.com/GMOD/jbrowse-components/pull/4425) Add ability to dismiss dotplot warnings ([@cmdcolin](https://github.com/cmdcolin))
* [#4422](https://github.com/GMOD/jbrowse-components/pull/4422) Make initial linear synteny view import form submit show all regions by …
> v2.12.0 release announcement

- plugins/legacy-jbrowse/package.json
- yarn.lock
incorporates https://github.com/GMOD/generic-filehandle/pull/112
> Bump generic-filehandle to put URL in error messages

- plugins/gff3/src/Gff3TabixAdapter/configSchema.ts
Fixes https://github.com/GMOD/jbrowse/issues/1649
By adding `contig` to the default dontRedispatch config, we will avoid large data downloads that end up secondarily overflowing the @gmod/gff "buffer size" (we should probably just remove this...) and then causing the error that there are "features reference other features that do not exist in the file" (which is likely false, it's just due to the buffer size being exceeded)
> Add `contig` to the default dontRedispatch list for Gff3TabixAdapter

- products/jbrowse-desktop/electron/electron.ts
- yarn.lock
Fixes error "Error: Error invoking remote method 'createInitialAutosaveFile': ReferenceError: Cannot access 'path' before initialization" in v2.12.2
I changed the typescript config in v2.12.2 and so the generated js code for the electron main script was
```
ipcMain.handle('createInitialAutosaveFile', async (_event, snap) => {
const rows = await readRecentSessions();
const idx = rows.findIndex(r => r.path === path);
const path = getAutosavePath(`${+Date.now()}`);
```
In v2.11.2 it used a complex down-transpilation that resulted in var declarations that were hoisted
```
ipcMain.handle('createInitialAutosaveFile', function (_event, snap) { return __awaiter(void 0, void 0, void 0, function () {
var rows, idx, path, entry;
var _a;
return __generator(this, function (_b) {
switch (_b.label) { …
```
> Fix error launching session on desktop in v2.12.2

- plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeView.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/NoTracksActiveButton.tsx
Currently it was not wrapped in an observer, meaning it did not react to changes in the show/hide state
This just wraps it in an observer and moves to a separate file
> Fix 'no tracks active' button show and hide

- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/Scalebar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
Adds the concept of a scalebar display "prefix" so that the synteny display can show the assembly name in each row
The prefix is "combined with the refname" if a leftmost block is a content block, or otherwise just put at position absolute leftPx:0
with a show all regions the leftmost block is a padding block, so you can see the assemblyname gets detached from the chromosome names
this approach is similar but a little different from the approach mentioned here https://github.com/GMOD/jbrowse-components/issues/3414 which had a always floating leftmost paper, but this would cover up the leftmost refname
It is also a little different from pairing discussion with garrett who proposed adding it to minicontrols (on right side of screen). it just felt a bit off :)
fixes …
> Add assembly name to scalebar in synteny views

- package.json
- packages/core/ReExports/list.ts
- packages/core/ReExports/modules.tsx
- packages/core/package.json
- packages/core/util/types/mst.ts
- plugins/comparative-adapters/package.json
- plugins/lollipop/package.json
- products/jbrowse-desktop/package.json
- products/jbrowse-react-app/package.json
- products/jbrowse-react-circular-genome-view/package.json
- products/jbrowse-react-linear-genome-view/package.json
- products/jbrowse-web/package.json
- yarn.lock
This proposes removing the prop-types package from our usage. The goal is to avoid a peerDependency warning from usage of @jbrowse/core when something that uses @jbrowse/core (like our plugins) doesn't also add the prop-types package.
> Remove prop-types from re-exports

- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/wiggle/src/MultiDensityRenderer/MultiDensityRenderer.ts
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/WiggleDisplayComponent.tsx
the default "Paper" component for the TrackContainer creates an "outline" (via variant="outline" and default elevation box-shadow)
This is observed as a "double line" between each track. it is somewhat nice to see the double outline as it is basically an indicator of the resize handle between tracks, but it can be visually noisy.
this proposes to allow hiding it
screenshots:
without track outlines
with track outlines, and menu item to toggle it
> Add ability to toggle  "Show track outlines"

- plugins/wiggle/src/util.ts
When we apply the log scale, we change the minimum value to 1 in some cases
This helps avoid performing log(0) which is undefined (or...-Infinity in javascript)
The current check applies well to "count data" but less well for "fractional data"
I found that there are ENCODE bigwigs return fractional values between 0-maxval so there are things like 0.02 and 34.8 and 24.5 etc.
The 0.02 causes the log scale to go negative though, in a way that is not super informative. Therefore, we try to make the logscale again snap to 1 with this PR
The caveat is that if the min and max are just between 0-1 then we do not perform this operation, because in that case, the values might be raw p-values, and then just not transforming it gives someone something similar to -log(p), a common unit for graphing, …
> Fix log scale for some types of signal tracks

- package.json
- yarn.lock
The upgrade to the dev dependency `rimraf` 6.0.1 caused `yarn` in jbrowse-components to not work when using node 18. Since node 18 is still a supported release, could we roll back that dependency to still allow node 18 to be used in a development environment?
> Allow node 18 as development environment again

- packages/app-core/src/ui/App/ViewsContainer.tsx
- packages/core/data_adapters/CytobandAdapter/CytobandAdapter.ts
- packages/core/util/index.ts
- plugins/bed/src/BedAdapter/BedAdapter.ts
- plugins/bed/src/BedpeAdapter/BedpeAdapter.ts
- plugins/comparative-adapters/src/ChainAdapter/ChainAdapter.ts
- plugins/comparative-adapters/src/DeltaAdapter/DeltaAdapter.ts
- plugins/comparative-adapters/src/MashMapAdapter/MashMapAdapter.ts
- plugins/comparative-adapters/src/PAFAdapter/PAFAdapter.ts
- plugins/comparative-adapters/src/util.ts
- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
- plugins/gff3/src/Gff3Adapter/featureData.ts
- plugins/gtf/src/GtfAdapter/GtfAdapter.ts
- plugins/variants/src/VcfAdapter/VcfAdapter.ts
This uses the technique (line by line parsing instead of decoding entire buffer into a string, which breaks after >512Mb) adopted by the GFF3 parser to allow large plaintext GTF files
> Allow plaintext GTF and VCF files greater than 512Mb

- plugins/sequence/src/ReferenceSequenceTrack/configSchema.ts
this is probably uncommonly used but it was displaying the string 'undefined' in the tooltip since there was no configslot/defaultvalue empty string for this
> Add description config slot to reference sequence track

- plugins/sequence/src/UnindexedFastaAdapter/UnindexedFastaAdapter.ts
- plugins/sequence/src/UnindexedFastaAdapter/configSchema.ts
- plugins/sequence/src/UnindexedFastaAdapter/index.ts
- plugins/sequence/src/index.ts
this allows fetching plaintext FASTA files from remote resources. this allows e.g. fetching a .fasta file without a .fai file from a remote resource
an example of this is for a protein FASTA browser from UniProt
the below screenshot can be generated by fetching  https://rest.uniprot.org/uniprotkb/P05067.fasta and https://rest.uniprot.org/uniprotkb/P05067.gff on the fly with no indexing (different tracks are the same gff, with repeated jexlFilters applied)
> Add UnindexedFastaAdapter for fetching small plaintext FASTA files

- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
- plugins/sequence/src/LinearReferenceSequenceDisplay/model.ts
- plugins/sequence/src/ReferenceSequenceTrack/configSchema.ts
- plugins/wiggle/src/LinearWiggleDisplay/components/Tooltip.tsx
This is a manually configured setting (e.g. not auto-detected from the fasta file) that lets a user configure a reference sequence to have a non-dna sequence type
This, if sequenceType!=='dna', then it disables the showTranslation/showForward/showReverse  settings on the sequence track, and the "DNA coloring scheme" for the sequence letters. This works well for making a protein type browser
example screenshot
example config
```
{
"name": "P05067",
"sequence": {
"type": "ReferenceSequenceTrack",
"trackId": "P05067-ReferenceSequenceTrack",
"sequenceType": "pep", <-- this line
"adapter": {
"type": "UnindexedFastaAdapter",
"fastaLocation": {
"uri": "https://rest.uniprot.org/uniprotkb/P05067.fasta"
}
}
}
}
```
> Allow setting sequenceType='pep' in ReferenceSequenceTrack configuration

- packages/core/ui/SnackbarModel.tsx
sometimes a (admittedly buggy...) user interface action can create a 'storm' of snackbar events. similar to putting alert('stuff') in a loop. this proposes to de-duplicate these messages
alternative systems that could be considered: a 'dismiss all' button on the snackbar
> De-duplicate snackbar messages

- plugins/linear-genome-view/src/LinearGenomeView/components/Scalebar.tsx
during office hours, saw an issue where there was a crash after a navToLocString
the code assumed that contentBlocks[0] was not undefined, but there may be situations where it is undefined for some amount of time (during loading or if bpPerPx/offsetPx is temporarily way off screen for example)
this code that causes the crash was introduced in v2.13.0 (recently)
> Fix crash after navToLocString in some cases

- packages/core/ui/Menu.tsx
- packages/embedded-core/src/ui/ViewMenu.tsx
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- yarn.lock
The embedded-core ViewMenu (e.g. where there are view level options like Export SVG) ended up diverging slightly from the app-core ViewMenu, where it did not use CascadingMenu, and then a bug introduced during refactoring (removal of Grow component from the @jbrowse/core/ui/Menu) resulted in the cascading effect not working, instead putting all cascading menus on the screen at once
screenshot
This fixes it by both
a) Adding the Grow back to @jbrowse/core/ui/Menu
b) Converting the embedded-core ViewMenu to use CascadingMenu, just because there are benefits to the CascadingMenu (it avoids offscreen behavior)
> Fix cascading sub menus bug in embedded components in v2.14.0

- eslint.config.mjs
- plugins/data-management/src/AddConnectionWidget/components/AddConnectionWidget.test.tsx
- plugins/gff3/package.json
- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
- plugins/gff3/src/Gff3TabixAdapter/Gff3TabixAdapter.ts
- plugins/gff3/src/featureData.ts
- plugins/gtf/package.json
- plugins/gtf/src/GtfAdapter/GtfAdapter.ts
- plugins/legacy-jbrowse/src/JBrowse1TextSearchAdapter/HttpMap.test.ts
- products/jbrowse-web/src/tests/Loader.test.tsx
- products/jbrowse-web/src/tests/Synteny.test.tsx
- yarn.lock
Fixes https://github.com/GMOD/gff-js/issues/62
I extracted the non-streaming parts of the gff and gtf parsers into their own NPM packages that can be used in isolation, and called the packages gff-nostream and gtf-nostream
This reduces the need for node.js polyfills and the stream-browserify workaround
Potentially, even the streaming parts of @gmod/gff could use gff-nostream as a base package to avoid the code duplication, but right now, this would just remove @gmod/gff and @gmod/gtf entirely from the build in favor of the non-streaming new packages
note: the naming gff-nostream is a little awkward but was hard to come up with something clearly named to distinguish it from @gmod/gff
saves about 50kb ungzipped/15kb gzipped js
> Avoid stream polyfill for GFF3/GTF parsing

- CONTRIBUTING.md
- package.json
- packages/core/assemblyManager/assembly.ts
- products/jbrowse-react-app/stories/JBrowseReactApp.stories.tsx
- products/jbrowse-react-app/stories/examples/HumanDemo.tsx
- products/jbrowse-react-app/stories/examples/index.ts
- products/jbrowse-web/src/components/NoConfigMessage.tsx
- yarn.lock
v2.14.0 introduced the NCBI sequence report adapter (xref https://github.com/GMOD/jbrowse-components/pull/4516/files) which allows e.g. NC_000001.11 to be displayed as chr1 in the UI)
Unfortunately there was an unexpected performance regression, due to accessing a mst observable outside of an observable context, causing it to be re-calculated for every invocation which was once per refname so it was a big slowdown
can see that loading a human FASTA takes:
before, 8000milliseconds (8s):
after, 10ms:
> Fix regression performance since v2.14.0 in assembly loading

- packages/core/pluggableElementTypes/DisplayType.ts
- packages/core/pluggableElementTypes/models/BaseTrackModel.ts
- packages/core/ui/CascadingMenu.tsx
- plugins/alignments/src/LinearAlignmentsDisplay/models/alignmentsModel.tsx
- plugins/alignments/src/LinearAlignmentsDisplay/models/util.ts
- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
The @jbrowse/core/ui/Menu has a function for sorting menu items by a priority attribute. The code for doing the same thing for @jbrowse/core/ui/CascadingMenu was missing though. This PR
- adds the same code for sorting by priority to the @jbrowse/core/ui/CascadingMenu (was missing)
- makes it so the "Display types" has a low priority to get sorted last
- re-orders some items in the alignments/pileup display track menu items list
> Fix the ability to sort menu items by priority for CascadingMenu

- plugins/variants/src/VcfFeature/__snapshots__/index.test.ts.snap
- plugins/variants/src/VcfFeature/index.test.ts
- plugins/variants/src/VcfFeature/index.ts
- products/jbrowse-cli/src/commands/text-index.ts
- website/yarn.lock
- yarn.lock
was seen in office hours appointment that jbrowse crashed on this because we assumed ALT to be non-null (the . is turned into null by the parser)
the . in ALT field can be seen in example 1.1 in the VCF 4.3 spec pdf, it indicates "a site that is called monomorphic reference (i.e. with no alternate alleles)"
> Fix handling of "." in VCF ALT field

- plugins/text-indexing/src/TextIndexRpcMethod/TextIndexRpcMethod.ts
- products/jbrowse-desktop/src/indexJobsModel.ts
The name indexing was producing errors on desktop in a way that was actually related to the typescript types not catching an error
there was a argument like this
```typescript
const indexingParams = {
outLocation,
tracks,
exclude,
attributes,
assemblies,
indexType,
statusCallback,
signal,
}
await indexTracks(indexingParams)
```
however, many the parameter names had been renamed (outLocation->outDir, exclude->featureTypesToExclude, attributes->attributesToIndex) at some point and it was not catching that this was an error
however, changing the code to
```typescript
await indexTracks({
outLocation,
tracks,
exclude,
attributes,
assemblies,
indexType,
statusCallback,
signal,
})
```
this instantly produces the typescript errors about providing keys that the function does not want, e.g. it does …
> Fix name indexing on desktop

- .github/workflows/release.yml
- eslint.config.mjs
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/sign.js
this is an attempt to get our SSL code signing back into action for our windows app
it had been apparently broken for awhile i believe our certificate was expired since mid-2023, and even attempting to fix it would not work because at that same time in mid-2023 they disabled the method we were using (downloading the p12/pfx file to the WIN_CSC_LINK env variable)
this PR's new solution closely follows https://github.com/electron-userland/electron-builder/issues/6158
> Fix code signing on the windows for jbrowse desktop

- package.json
- yarn.lock
Uses the electron-builder@next to fix issue like this https://github.com/electron-userland/electron-builder/issues/8503  (which produced crash on startup) which were observed in both windows and appimage installs now
> Update electron-builder to fix broken desktop builds

- eslint.config.mjs
- packages/core/pluggableElementTypes/renderers/RpcRenderedSvgGroup.tsx
- packages/core/pluggableElementTypes/renderers/ServerSideRenderedContent.tsx
- packages/core/util/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/AutocompleteTextField.tsx
- products/jbrowse-aws-lambda-functions/saved-sessions/jbrowse_analytics.js
- products/jbrowse-desktop/src/components/StartScreen/RecentSessionsPanel.tsx
- yarn.lock
Electron made it so file choosers can't get a .path property from a File object in recent versions
Instead you have to call "electron.webUtils.getPathForFile(arg:File)"
> Fix opening .jbrowse files on desktop

- plugins/grid-bookmark/src/GridBookmarkWidget/components/Highlight/Highlight.tsx
The bookmark highlights added a clickable button to "show bookmark widget" or "remove bookmark" recently (#4556), but it caused some minor issues interacting with the track surrounding the highlight. 
The possible cause was creating a pointerEvents:auto inside of a pointerEvents:none div. This seemed to work ok but maybe caused the weird behavior.
This PR tries to fix it by making the click button a separate div from the highlight div, so there is less reliance on this "stacking" of pointerEvents contexts.
Fixes https://github.com/GMOD/jbrowse-components/issues/4579
> Fix highlight button causing issues clicking underlying track features

- yarn.lock
Incorporates fix from https://github.com/GMOD/cram-js/issues/142
> Fix decoding of CRAM ML tag

- packages/app-core/package.json
- packages/app-core/src/ui/App/DrawerWidget.tsx
- packages/app-core/src/ui/App/ViewPanel.tsx
- packages/core/BaseFeatureWidget/BaseFeatureDetail/index.tsx
- packages/core/BaseFeatureWidget/__snapshots__/index.test.tsx.snap
- packages/core/package.json
- packages/core/ui/Dialog.tsx
- packages/core/ui/ErrorBoundary.tsx
- packages/embedded-core/package.json
- packages/product-core/package.json
- packages/web-core/package.json
- plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.tsx.snap
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.tsx.snap
- plugins/data-management/src/HierarchicalTrackSelectorWidget/model.ts
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/linear-genome-view/package.json
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackContainer.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.tsx.snap
- products/jbrowse-desktop/package.json
- products/jbrowse-desktop/src/index.tsx
- products/jbrowse-react-app/package.json
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/package.json
- products/jbrowse-web/src/components/Loader.tsx
- yarn.lock
This removes the react-error-boundary dependency by vendoring a reduced version of the component in core
Reason: react-error-boundary releases new versions once in awhile that are somewhat perplexing to me. Last version produces a console.warn on yarn install regarding use of pnpm in the package.json version field, so i just went ahead and removed the usage of the dependency
> Remove react-error-boundary

- plugins/svg/src/SvgFeatureRenderer/components/Subfeatures.tsx
- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
- plugins/svg/src/SvgFeatureRenderer/components/util.ts
- plugins/svg/src/SvgFeatureRenderer/configSchema.ts
- yarn.lock
it creates the notion of explicit "containerTypes" which create multi-row feature rendering, like the gene glyph. it also makes configurable the notion of "transcriptTypes" which was hardcoded to "transcript","primary_transcript", and "mRNA".
This PR helps address concerns in https://github.com/GMOD/jbrowse-components/issues/4599
The issue brought up previous relied on what was basically a bug to allow a GFF with a parent feature with children to be rendered as multiple rows in the output
This multi-row rendering is pretty specialized to "gene" style rendering but worked well for their case
Therefore, this PR proposes "containerTypes" (which render as multiple rows, like the gene glyph) and then also "transcriptTypes" which corresponds with ProcessedTranscript types.
It would be good to …
> Add notion of transcriptTypes and containerTypes to the svg feature rendering

- plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts
- plugins/wiggle/src/BigWigAdapter/configSchema.ts
- test_data/config_demo.json
Allows a default multiplier to adjust the initially shown resolution in bigwig files
So e.g. setting it to 10 makes it quite low resolution on a whole genome coverage bigwig file
http://jbrowse.org/code/jb2/resolution_multiplier/?config=test_data%2Fconfig_demo.json&session=share-8ItYciPZqJ&password=LsY0O
the example config
```json
{
"type": "QuantitativeTrack",
"trackId": "ngmlr_cov",
"name": "SKBR3 pacbio coverage (NGMLR)",
"assemblyNames": ["hg19"],
"adapter": {
"type": "BigWigAdapter",
"resolutionMultiplier": 10,
"bigWigLocation": {
"uri": "https://s3.amazonaws.com/jbrowse.org/genomes/hg19/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.bam.regions.bw"
}
}
},
```
> Add resolutionMultiplier config slot to BigWigAdapter

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx
- plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/util.ts
- plugins/linear-comparative-view/src/LinearSyntenyDisplay/drawSynteny.ts
Fixes #4625 
the cause of the issue was the the code assumed that the "callback" ctx=>ctx.stroke() or ctx=>ctx.fill() would be the execution of the drawing operation that was performed by the drawMatchSimple, however, it internally would call drawBox or drawBeizierBox which would force a ctx.fill()
this would cause trouble when the canvas had not yet initialized a fillStyle
this PR fixes a number of things
1) restores the assumption that the drawMatchSimple execution of the drawing operation is done by the callback
2) makes sure that fillStyle is set, unneeded but this improves clarity
3) renames some variables in the rendering process, unneeded but this improves clarity
> Fix dark redraw on selected features after vertical resize of the synteny canvas

- plugins/comparative-adapters/src/ChainAdapter/configSchema.ts
- plugins/comparative-adapters/src/DeltaAdapter/configSchema.ts
- plugins/comparative-adapters/src/MashMapAdapter/configSchema.ts
- plugins/comparative-adapters/src/PAFAdapter/configSchema.ts
- plugins/comparative-adapters/src/PairwiseIndexedPAFAdapter/configSchema.ts
> Fix config description of assembly name ordering for synteny data adapters

- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/models/model.ts
- plugins/alignments/src/util.ts
- products/jbrowse-web/src/tests/ReadVsRef.test.tsx
- test_data/config_demo.json
Currently 'unknown' modification types are given a random color, but it is different between top and bottom and between different runs of jbrowse
This changes it to be a deterministic random color based on the input "hash" of the string of the modification type
> Standardize modification colors between snpcov and pileup

- plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.tsx
- products/jbrowse-cli/src/commands/create.ts
- products/jbrowse-cli/src/commands/upgrade.ts
We have the concept of different types of track selectors. Currently, the select box is not dismissed properly though
This was a bit of a tricky one but it was due to not having a Suspense boundary properly wrapping the component.
Diagnosed by removing the rendering of `<Component/>`...confirmed that the behavior went away, realized it was related to rendering the `<Component/>` and that there could be a suspense boundary needed (could be interesting to dive deeper into this behavior for hobby purposes, probably it was going to a suspense boundary higher in the react tree and then the select state was sort of messed up by that somehow)
> Fix "Add track" select box not going away after selecting element

- package.json
- plugins/wiggle/src/MultiWiggleAddTrackWorkflow/AddTrackWorkflow.tsx
- products/jbrowse-desktop/package.json
- website/docs/tutorials/desktop_spec_plugin_tutorial.md
- yarn.lock
The electron 32 update removed the "path" attribute from the File object (https://www.electronjs.org/blog/electron-32-0)
Change to using webUtils.getPathForFile(file) instead of file.path
> Fix opening local files in the multi-wiggle add track selector

- packages/core/data_adapters/CytobandAdapter/CytobandAdapter.ts
- packages/core/util/index.ts
- plugins/bed/src/BedAdapter/__snapshots__/BedAdapter.test.ts.snap
- plugins/bed/src/BedTabixAdapter/__snapshots__/BedTabixAdapter.test.ts.snap
- plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
- plugins/bed/src/BigBedAdapter/__snapshots__/BigBedAdapter.test.ts.snap
- plugins/bed/src/util.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/util.ts
- products/jbrowse-cli/README.md
- products/jbrowse-cli/src/commands/sort-bed.ts
- test_data/hs1.json
UCSC RepeatMasker BED files have extended fields which are somewhat complicated
This PR fixes the rendering of repeatmasker BED, BEDTabix, and BigBed files from UCSC with full fields
Example here https://hgdownload.soe.ucsc.edu/gbdb/hs1/t2tRepeatMasker/
See the "Full mode visualization" which shows, at least from the UCSC UI perspective, how complex these data are...https://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=2372603109_AcR4Yt0XayFS0KE6hJ1sksSrAkTv&db=hub_3671779_hs1&c=chr1&g=hub_3671779_t2tRepeatMasker
In the data format, they re-use UCSC specific BED fields and specifically troublesome is they make negative valued blockSizes to indicate unaligned regions. This caused JBrowse to create negative length SimpleFeature's which crashes the track (we just don't allow negative size …
> Support UCSC repeatmasker BigBed and BED files

- plugins/linear-comparative-view/src/LinearSyntenyDisplay/components/LinearSyntenyRendering.tsx
Currently the mouseover canvas is pixelated due to css style for pixelated being set on it accidentally. The pixelated setting actually is intended for the 'mouseover detection' canvas, not the canvas that displays the mouseover
> Remove mouseover pixelation

- packages/core/ui/CascadingMenu.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
Currently, while opening a cascading menu (e.g. a popover menu with multiple sub-menus), if they mouseover for even a split second the whole menu closes. 
This PR debounces the menu "isOpen" state so if their mouse strays outside the boundaries of the menu, it doesn't immediately close
> Delay cascading menu closing after mouseout

- eslint.config.mjs
- plugins/alignments/src/AlignmentsFeatureDetail/LaunchSupplementaryAlignmentBreakpointSplitViewPanel.tsx
- plugins/breakpoint-split-view/src/BreakpointSplitView/components/util.ts
- yarn.lock
some paired end BAM files, e.g. from GIAB have a weird thing where there is a duplication of the reads at each position. There is no BAM flag indicating it is a duplicate, so there's no real way to distinguish these. Our Breakpoint split view tries to connect features that have the same QNAME (read name) to match pairs (pairs share the same read name) but this weird duplicate reads also share the same QNAME.
This PR filters makes it so paired end reads specifically don't connect with features at the same position
I filtered out just one qname which shows that it matches 4 boxes...typically it should be two (left and right side of pair) and any other matches to the qname should at least be distinguished by something but these aren't …
> Reduce self-pairing for weird paired-end BAM files

- plugins/bed/src/BedAdapter/BedAdapter.ts
- plugins/bed/src/BedGraphAdapter/BedGraphAdapter.ts
- plugins/bed/src/BedGraphAdapter/configSchema.ts
- plugins/bed/src/BedGraphAdapter/index.ts
- plugins/bed/src/BedGraphTabixAdapter/BedGraphTabixAdapter.ts
- plugins/bed/src/BedGraphTabixAdapter/configSchema.ts
- plugins/bed/src/BedGraphTabixAdapter/index.ts
- plugins/bed/src/index.ts
- test_data/config_demo.json
- yarn.lock
As a motivating example, this can visualize the values of from the lab project for transition matrices
This is an older PR that I revitalized. I made it not derive from the BedAdapter base class though
A BedGraphTabixAdapter might be valuable as well
> Add BedGraphAdapter and BedGraphTabixAdapter

- plugins/alignments/src/PileupRenderer/renderAlignmentShape.ts
A regression between v2.16.1 and v2.17.0 resulted in 'mcscan' type features not being rendered on the LGV
It assumed that CIGAR strings would always be present but this is not the case (no CIGAR for MCScan type features)
> Fix MCScanAnchorsAdapter rendering in linear genome view

- plugins/linear-comparative-view/src/LGVSyntenyDisplay/configSchemaF.ts
Example
More info like chr name could be added if interest also, but hopefully this helps
cc @srobb1
Can try this branch with
`jbrowse create --branch mouseover_name` if interested
fixes #4677
> Add mate.name to LGVSyntenyDisplay feature mouseovers

- plugins/linear-comparative-view/src/LinearComparativeView/components/Rubberband.tsx
This might not fix anything but I had a rare issue where zooming in on multiple levels on a linear synteny view produced the wrong offsets and zoomed into a very tiny region when that wasn't what I selected. It is a hard-to-reproduce issue though so i can't necessarily tell whether this PR will fix it entirely, but this PR changes the code to use a 'mobx transaction' to make sure all zoom level changes are committed at the same time. It doesn't seem like this change would fix the issue
> Add mobx transaction to multi-level synteny zoom

- products/jbrowse-desktop/src/rootModel/rootModel.ts
Sometimes users have a hard to locating the "Open track" option. I see this a lot in office hours.
They especially mistake the "Open" menu item in jbrowse desktop because it just says "Open"
This moves all session related options to a subMenu. The session options are fairly specialized
Here is how it looks on jbrowse-web with this PR
The web re-organization here might not be super 'aesthetic' because there are so few other options for web in the File menu, but i think it reduces confusion from session options. Adding an option to open assembly in web (session assemblies) might round it out...
> Move session options from the appbar File menu into a submenu

- plugins/alignments/src/SNPCoverageAdapter/generateCoverageBins.ts
- plugins/alignments/src/SNPCoverageAdapter/processDepth.ts
- plugins/alignments/src/SNPCoverageAdapter/processMismatches.ts
This PR https://github.com/GMOD/jbrowse-components/pull/4647 which addressed primarily rendering modifications made a large number of refactors to make rendering modifications and methylation improved
In the process it introduced a change that fetched the entire sequence. However, there are some cases where
a) jbrowse will decide to render when you are zoomed out super far (for e.g. targetted sequencing)
b) then it will fetch an entire chromosomes worth of data
there is an additional thing where maybe there is something else combining the requests because the indexedfastaadapter is designed to break up requests into smaller chunks, but a user was observing that it was making a single(?) huge HTTP Range request and this was rejected by google cloud servers
> Avoid full length sequence fetch on SNP coverage calculation

- website/release_announcement_drafts/v2.18.0.md
* `app-core`, `core`, `embedded-core`, `product-core`, `sv-core`, `text-indexing`, `web-core`
* [#4682](https://github.com/GMOD/jbrowse-components/pull/4682) Quality of life improvements for SV inspector ([@cmdcolin](https://github.com/cmdcolin))
* `core`, `product-core`
* [#4178](https://github.com/GMOD/jbrowse-components/pull/4178) Add ability to use colorBy and filterBy for alignments track configs, and group by strand ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4672](https://github.com/GMOD/jbrowse-components/pull/4672) Add BedGraphAdapter and BedGraphTabixAdapter ([@cmdcolin](https://github.com/cmdcolin))
* `core`, `product-core`, `text-indexing`
* [#4663](https://github.com/GMOD/jbrowse-components/pull/4663) Replace AbortSignal with "stop token" to …
> v2.18.0 release announcement

- .github/workflows/push.yml
- .github/workflows/release.yml
- .github/workflows/update-docs.yml
These were identified as 'low severity' by the zizmor (a github actions auditor)
these were identified by the following message
"warning[artipacked]: credential persistence through GitHub Actions artifacts
--> /home/cdiesh/src/jbrowse-components/.github/workflows/release.yml:102:9
|
102 |       - uses: actions/checkout@v4
|         ------------------------- does not set persist-credentials: false
|
= note: audit confidence → Low
"
the good news is we do not have any medium or high entries, or any use of pull_request_target which was identified  "is almost always used insecurely" ..https://blog.yossarian.net/2024/12/06/zizmor-ultralytics-injection
i think it's worth looking into a bit more because we do e.g. deploy to jbrowse.org from our gh actions but these, to my knowledge, do not run …
> Add persist_credentials:false to github actions workflows

- packages/core/BaseFeatureWidget/SequenceFeatureDetails/SequenceContents.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/4726
The root cause was that
a) feature.subfeatures was null instead of undefined
b) our type system did not include null in the type signature
c) we used a default assignment, which does not apply to null
d) we use a system that remaps undefined to null in snapshots. this is sort of a questionable thing to do, but it prevents the values from being removed completely from the snapshot. the code comments surrounding this are pretty hard to decipher though, so it could be worth revisiting
This PR fixes it by using "nullish coalescing" which handles both null and undefined. A more extensive fix would probably add null to the type signature, or remove null from being possible
> Fix type confusion where sequence feature details crashes for empty subfeatures

- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
Another regression from https://github.com/GMOD/jbrowse-components/pull/4178
There was an attempt at backwards compatibility after the model schema changed slightly after this PR, but this ended up clearing the new style snapshot values with undefined values while trying to load old style snapshots
This PR prioritizes new style snapshot values over old style snapshot values
> Fix persisting alignments "color by" and "filter by" settings in snapshots/session shares/page reloads

- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/PileupRenderer/configSchema.ts
- plugins/alignments/src/PileupRenderer/makeImageData.ts
- plugins/alignments/src/PileupRenderer/renderMismatches.ts
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- website/docs/models/AssemblyManager.md
- website/docs/models/BaseChordDisplay.md
- website/docs/models/BaseDisplay.md
- website/docs/models/BaseFeatureWidget.md
- website/docs/models/BaseRootModel.md
- website/docs/models/BaseWebSession.md
- website/docs/models/DotplotDisplay.md
- website/docs/models/FacetedModel.md
- website/docs/models/JBrowseDesktopSessionModel.md
- website/docs/models/JBrowseReactCircularGenomeViewRootModel.md
- website/docs/models/JBrowseReactLinearGenomeViewRootModel.md
- website/docs/models/JBrowseReactLinearGenomeViewSessionModel.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/LinearReadArcsDisplay.md
- website/docs/models/LinearReadCloudDisplay.md
- website/docs/models/LinearSyntenyView.md
- website/docs/models/SharedLinearPileupDisplayMixin.md
- yarn.lock
This is something that occurs during long read sequencing a lot
It's hard to find the right balance of what the best behavior is for this setting is as "hifi" reads don't suffer a lot of indels, so it might not make sense to automatically toggle it on, but 
for CLR/nanopore where there are a lot of indels, the track can look like this zoomed out
but with hide indels turned on, cleans it up a bit...
other options include using subpixel rendering so it automatically toggles off at zoomed out scales, this is possible by manually editing the renderer config (`minSubfeatureWidth`) which could also be exposed via track menu potentially
another option is the 'quick consensus mode' (https://github.com/GMOD/jbrowse-components/issues/4292) but that's a bit trickier. kinda involves calculating …
> Add option to 'Hide small indels (<10bp)'

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/ShoppingCart.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabel.tsx
This PR adds the option to add a track to the "selection" (or remove it) using "ctrl+click" (cmd+click on mac) on a track label in the hierarchical selector
Then, it allows users to optionally bulk delete those selected tracks using the shopping cart if they are all session tracks or if they are admin
> Bulk delete session tracks

- plugins/alignments/src/SNPCoverageAdapter/processModifications.ts
- plugins/alignments/src/SNPCoverageRenderer/SNPCoverageRenderer.ts
- plugins/alignments/src/SNPCoverageRenderer/makeImage.ts
- plugins/alignments/src/SNPCoverageRenderer/types.ts
- yarn.lock
Refactors to modifications/methylation rendering in #4647 added the requirement to inspect the reference genome base to get the 'modifiable' status of bases (following igv)
Then it was refactored again to avoid unnecessary fetching of reference genome base for non-modifications rendering modes, especially when viewing the snpcoverage at the level of the whole genome -- Unfortunately this introduced a bug that is 
This fixes it again by forcing the assignment of the reference base
> Fix modifications coverage calculations

- packages/core/BaseFeatureWidget/__snapshots__/index.test.tsx.snap
- packages/core/pluggableElementTypes/models/InternetAccountModel.ts
- packages/core/util/io/RemoteFileWithRangeCache.ts
- plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.tsx.snap
- plugins/bed/src/BedpeAdapter/BedpeAdapter.ts
- plugins/bed/src/generateBedMethylFeature.ts
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/src/AddConnectionWidget/components/__snapshots__/AddConnectionWidget.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/grid-bookmark/src/GridBookmarkWidget/components/AssemblySelector.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebar.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewScalebarPolygon.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/svgcomponents/SVGHeader.tsx
- plugins/linear-genome-view/src/LinearGenomeView/util.ts
- plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.tsx.snap
- plugins/variants/src/shared/BulkEditPanel.tsx
- products/jbrowse-react-circular-genome-view/src/JBrowseCircularGenomeView/__snapshots__/JBrowseCircularGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- products/jbrowse-web/src/index.tsx
- products/jbrowse-web/src/tests/loaderUtil.tsx
- yarn.lock
it is hard to programmatically tell what a particular bed feature represents but we use heuristics to try to determine if we have e.g.
1) BED12 type transcripts
2) bedMethyl type data
3) repeatmasker data
4) something else arbitrary
this changes the heuristic to check for a) if there is a comma in the blockStarts field, it is not bedMethyl. this would be false for bedMethyl because bedMethyl doesn't use blockStarts, it's just a random number field about coverage
it also additionally checks if the 13th field in the file is a string. bedMethyl does not have to contain 13+ fields, and bed12 doesn't either, but if it does, if it's a string and not a number, then it is not bedMethyl
reported by user at PAG to garrett (Toby from Ensembl)
> Fix some bed12 transcripts displaying as bedMethyl features

- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetFilters.tsx
Avoids crash where a user filters on a facet, and then performs a search
Fixes #4760 
There might be a more principalled way of doing this because this PR ultimately hides all the facet filters entirely in this case, but it is better than a crash
> Facet filter crash

- plugins/data-management/package.json
- plugins/data-management/src/UCSCTrackHub/doConnect.ts
- plugins/data-management/src/UCSCTrackHub/ucscTrackHub.ts
- yarn.lock
The ucschub-js package changed from directly storing all info on an object into storing the info on a subkey named "data"
However, the code was not inspecting this data object to detect composite tracks
This fixes that, properly reconstructing UCSC trackhub categories in the track selector
It also appends the label (xeno) to tracks with xeno in their URL, as it's otherwise hard to tell what the cross-species (xeno) alignments are, and the current UCSC trackhubs don't by default add this
Fixes https://github.com/GMOD/jbrowse-components/issues/4762
> Fix generating categories for composite tracks in UCSC hubs

- plugins/linear-genome-view/src/LinearGenomeView/components/ZoomControls.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
Currently to zoom in far and close, you have to click the zoom in or out button multiple times
This adds a 'turbo zoom' button that uses 15x instead of 2x in each direction
This goes from 50kb to 3kb in one click for example
Otherwise you have to click it about 7 times for the same behavior
Motivated by UCSC having zoom in 10x. They also have 100x but that might overload UI
> Add turbo-zoom buttons

- plugins/bed/src/BedAdapter/__snapshots__/BedAdapter.test.ts.snap
- plugins/bed/src/BedTabixAdapter/__snapshots__/BedTabixAdapter.test.ts.snap
- plugins/bed/src/BigBedAdapter/__snapshots__/BigBedAdapter.test.ts.snap
- plugins/bed/src/generateUcscTranscript.ts
Fixes #4772
This adds a phase field to features generated in BED12
The SVG Box renderer uses the existence of the "phase" field to determine whether to color by CDS
Specifically this check https://github.com/GMOD/jbrowse-components/blob/ce9fb70030bfd2dd89c02063bb1968d4e1f4c125/plugins/svg/src/SvgFeatureRenderer/components/Box.tsx#L62-L67
> Fix Color by CDS for BED12 features

- packages/core/BaseFeatureWidget/__snapshots__/index.test.tsx.snap
- packages/core/ui/theme.ts
- plugins/alignments/src/AlignmentsFeatureDetail/__snapshots__/index.test.tsx.snap
- plugins/config/src/ConfigurationEditorWidget/components/__snapshots__/ConfigurationEditor.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/variants/src/VariantFeatureWidget/__snapshots__/VariantFeatureWidget.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This removes the concept of dense margins from the theme
It seems the margin setting in the theme is at the very least inconsistently applied, and it causes e.g. a TextField and Button positioned next to each other to have inconsistent margins and so are at different vertical offsets
we could review whether there are any actual negative consequences on information density, i didn't see anything jump out though
> No margin dense theme

- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/createPluginManager.ts
This adds a couple of special cases to hubURL loading
a) makes it so that specifically a hubURL can be loaded without a config if ?config=none is in the URL
b) otherwise if ?config=none is not in the URL, it will load the config and the hub. this allows plugins define in the config be combined with hubURL for example. it will load all the assemblies and tracks from config also
the above two things combined allow hubURL to survive page refresh better, particularly in the case where there is no default config.json file (for example, our development environment) because the following chain of behavior otherwise occurs
1. visit URL with ?hubURL, goes through custom path in session loader that skips config.json loading
2. the ?hubURL is cleared from URL via the session loader
3. then you …
> Avoid clearing hubURL to allow it to survive page refresh

- packages/core/util/tracks.ts
- plugins/bed/src/index.ts
- plugins/data-management/src/AddTrackWidget/components/AddTrackWidget.test.tsx
- plugins/data-management/src/AddTrackWidget/components/PasteConfigWorkflow.tsx
- plugins/data-management/src/AddTrackWidget/components/TrackAdapterSelector.tsx
- plugins/data-management/src/AddTrackWidget/components/TrackTypeSelector.tsx
- plugins/data-management/src/AddTrackWidget/model.ts
- plugins/data-management/src/AssemblyManager/AssemblyTable.tsx
- plugins/data-management/src/PluginStoreWidget/components/DeletePluginDialog.tsx
- plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.tsx
- plugins/dotplot-view/src/DotplotView/components/ImportForm/ImportSyntenyTrackSelector.tsx
- plugins/gff3/src/GuessGff3/index.ts
- plugins/hic/src/index.ts
- plugins/legacy-jbrowse/src/GuessNCList/index.ts
- plugins/variants/src/extensionPoints.ts
- plugins/wiggle/src/index.ts
It is noticed that somtimes manually choosing an adapter type in the select box has no effect in the add track workflow
It is perhaps odd, but this is because it is because it has to go through all the Core-guessAdapterType callbacks, then get a full adapter config from one of them, and then only then, will it update the adapter type. So if those callbacks are misbehaving, it will fail
and, as it turns out, you have to specifically respond to adapterHint (which is the select box selection) in order to handle this properly. if the gussAdapterType only looks at filename, it misses the "hint" that the user selected something from the select box, and the select box value will not update
Most of the guess routines had the right logic (checking for !adapterHint&&filnameCheck instead of just …
> Refactor add track adapter hinting

- README.md
The python package isn't available in Ubuntu 24.10:
```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
2to3  python-is-python3
Error: Package 'python' has no installation candidate
```
> Change python to python3 for Ubuntu apt install

- packages/core/util/tracks.ts
- packages/product-core/src/ui/AboutDialogContents.tsx
- plugins/data-management/src/UCSCTrackHub/doConnect.ts
- plugins/data-management/src/UCSCTrackHub/ucscTrackHub.ts
- plugins/data-management/src/UCSCTrackHub/util.ts
- Uses the 'group' attribute to categorize tracks
These are short labels like varRep, gene, rna, map. A bit obscure, but better than nothing for track grouping
- Renders track metadata in a custom card in About track dialog
- Adds UCSC track as track metadata
- Adds functional links to the track and assembly "description html" pages in about track dialog
looks like this at link
it could alternatively be fetched via ajax and displayed in the dialog, but this is somewhat ok for now
> Add more track metadata to UCSC assembly hub loading

- plugins/spreadsheet-view/src/SpreadsheetView/importAdapters/__snapshots__/VcfImport.test.ts.snap
- plugins/variants/src/MultiLinearVariantMatrixDisplay/components/LinesConnectingMatrixToGenomicPosition.tsx
- plugins/variants/src/MultiLinearVariantMatrixRenderer/makeImageData.ts
- plugins/variants/src/VcfAdapter/__snapshots__/VcfAdapter.test.ts.snap
- plugins/variants/src/VcfFeature/__snapshots__/index.test.ts.snap
- plugins/variants/src/VcfFeature/index.ts
- plugins/variants/src/VcfTabixAdapter/__snapshots__/VcfTabixAdapter.test.ts.snap
- plugins/variants/src/shared/MultiVariantBaseModel.tsx
- plugins/variants/src/shared/multiVariantColor.ts
- plugins/variants/src/util.ts
phased variants can be "completely phased" or come in sets which are a random 32 bit number indicating a block of shared variants
this colors variants randomly based on the PS value if it exists, and I added a test file with PS values from GIAB to the test data
> Create random color for rendering phase sets in phased variant rendering

- test_data/config_demo.json
- website/release_announcement_drafts/v3.0.0.md
- website/src/pages/demos.mdx
- yarn.lock
* `core`
* [#4716](https://github.com/GMOD/jbrowse-components/pull/4716) Update to generic-filehandle2 ([@cmdcolin](https://github.com/cmdcolin))
* `__mocks__`, `app-core`, `core`, `embedded-core`, `product-core`, `sv-core`
* [#4702](https://github.com/GMOD/jbrowse-components/pull/4702) Update to react 19 ([@cmdcolin](https://github.com/cmdcolin))
* `core`, `web-core`
* [#4799](https://github.com/GMOD/jbrowse-components/pull/4799) Add genotype to multi-variant mouseover  ([@cmdcolin](https://github.com/cmdcolin))
* `core`, `product-core`
* [#4798](https://github.com/GMOD/jbrowse-components/pull/4798) Add more track metadata to UCSC assembly hub loading ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4796](https://github.com/GMOD/jbrowse-components/pull/4796) Make any bigType track …
> v3.0.0 release announcement

- plugins/variants/src/util.ts
The current palettizer code uses a colorbrewer type scheme for the first 10 colors, and then makes random ones after that, but there was a bug in the random generation due to some last minute hacking that made it generate color strings like hsl(hsl(...),...) instead of just hsl(...)
> Fix random palette color generation

- plugins/jobs-management/src/JobsListWidget/model.ts
The JobsListWidget treats the name of a job as an identifier, but also allowed multiple jobs with the same name. This changes the behavior so that if a job is added with the same name as an existing job, it skips adding the job and returns the existing one. There are other ways this could be addressed (e.g. assigning generated ids to jobs), but this seemed the least disruptive.
It also fixes a bug where if a job name that didn't exist was provided to `removeJob` or `removedQueuedJob`, it would remove the last job in the list. Now it doesn't remove any jobs and returns `undefined`.
> Handle multiple jobs with the same name

- plugins/bed/src/BedTabixAdapter/BedTabixAdapter.ts
- plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
- plugins/gff3/src/Gff3TabixAdapter/Gff3TabixAdapter.ts
- plugins/variants/src/VcfTabixAdapter/VcfTabixAdapter.ts
- plugins/wiggle/src/BigWigAdapter/BigWigAdapter.ts
Tells you when index is downloading. Based on some lessons learned from BAM/CRAM #4818
> Improve status updating for BEDTabix, GFF3Tabix, VCFTabix, BigBed

- plugins/svg/src/SvgFeatureRenderer/components/Box.tsx
In an effort to not render very large SVG elements, they are "mathematically cropped" to fit in the visible region. For whatever reason, the math doesn't line up quite right and can lead to ~1px emptyness being rendered. I fixed this by Math.ceil'ing the "screen width" calculation
Possible hypothesis could be...got the math wrong and this is a fudge factor, or lossy large floating points from bpPerPx, and again, fudge factor
Before (can see small gap in orange blocks)
After
> Less gappyness at SVG features block boundaries

- packages/sv-core/package.json
- plugins/breakpoint-split-view/package.json
- plugins/spreadsheet-view/package.json
- plugins/variants/package.json
- yarn.lock
swapped out bzip2 decoder in @gmod/cram in https://github.com/GMOD/cram-js/pull/152
> Update @gmod/cram for fixed decoding of some CRAM files

- plugins/sequence/src/DivSequenceRenderer/components/DivSequenceRendering.tsx
- plugins/sequence/src/DivSequenceRenderer/components/__snapshots__/DivSequenceRendering.test.tsx.snap
Seen here
Due to subpixel width rounding, this PR rounds up the width
> Fix occasional 1px gap in seqeunce track

- plugins/svg/src/SvgFeatureRenderer/components/SvgFeatureRendering.tsx
Currently, if you click on a feature but slightly drag the mouse while doing so, it does not click the feature. This makes it so that it does click the feature if there even if there is a small drag
The reason it currently tries to block the feature click is to prevent feature click when the user intent is click-and-drag scrolling
> Allow clicking feature even if there is a slight mouse drag

- plugins/variants/src/SplitVcfTabixAdapter/SplitVcfTabixAdapter.ts
- plugins/variants/src/SplitVcfTabixAdapter/configSchema.ts
- plugins/variants/src/SplitVcfTabixAdapter/index.ts
- plugins/variants/src/index.ts
There are several VCF resources that split their files by chromosome name. Examples include 1000 genomes (https://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/), 1000 bulls (https://www.ebi.ac.uk/ena/browser/view/PRJEB42783)
Not sure exactly why people do this, but such as it is, this PR adds an adapter that can read these split VCF files
You create a config like this
```
vcfGzLocationMap:{
chr1: {uri:'...path to chr1 vcf'},
chr2: {uri:'...path to chr2 vcf'}
}
```
you can optionally create an indexLocationMap too
the alternative method instead of a fully specified map would be to use "replacement strings" which jbrowse 1 allowed. could potentially allow both but this just does map for now
> Split VCF adapter

- plugins/gtf/src/GtfAdapter/GtfAdapter.ts
- plugins/svg/src/SvgFeatureRenderer/components/ProcessedTranscript.tsx
- plugins/svg/src/SvgFeatureRenderer/components/util.ts
The gene rendering misbehaves if the user has five_prime_utr instead of five_prime_UTR
This makes it case insensitive
> Handle case insensitive UTR

- packages/core/data_adapters/dataAdapterCache.ts
- packages/core/pluggableElementTypes/renderers/BoxRendererType.ts
- packages/core/pluggableElementTypes/renderers/LayoutSession.ts
- packages/core/pluggableElementTypes/renderers/RendererType.tsx
- packages/core/pluggableElementTypes/renderers/ServerSideRendererType.tsx
- packages/core/rpc/methods/CoreFreeResources.ts
- packages/core/rpc/methods/CoreGetFeatureDetails.ts
- packages/core/util/types/index.ts
- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/alignments/src/LinearPileupDisplay/doAfterAttach.ts
- plugins/alignments/src/PileupRenderer/PileupLayoutSession.ts
- plugins/alignments/src/PileupRenderer/PileupRenderer.ts
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/tree/TrackLabel.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/components/BaseLinearDisplay.tsx
- plugins/linear-genome-view/src/BaseLinearDisplay/models/serverSideRenderedBlock.ts
- plugins/lollipop/src/LollipopRenderer/FloatingLayoutSession.ts
- plugins/lollipop/src/LollipopRenderer/LollipopRenderer.ts
- products/jbrowse-web/src/tests/Dotplot.test.tsx
- products/jbrowse-web/src/tests/DotplotImportForm.test.tsx
- products/jbrowse-web/src/tests/JBrowse.test.tsx
- products/jbrowse-web/src/tests/Lollipop.test.tsx
- yarn.lock
The current code fails to free resources associated with the layout, which includes a pointer to the features, when you browse to a new region
This is because it tries to clear the layout in a freeResourcesInClient function, but it needs to run on the worker
This changes it to run the code on the worker
> Free resources associated with layout and cached features when browsing to a new region in worker

- package.json
- packages/core/util/types/index.ts
- plugins/data-management/src/AddTrackWidget/components/doSubmit.ts
- plugins/data-management/src/AddTrackWidget/model.ts
- products/jbrowse-desktop/src/components/OpenSequenceDialog.tsx
- products/jbrowse-desktop/src/indexJobsModel.ts
- yarn.lock
The PR https://github.com/GMOD/jbrowse-components/pull/4786 introduced a regression error in indexing tracks
It made the track config a 'getter' on the model, which includes running Date.now for the trackId
I erroneously thought the getter would be stable and not need re-running after initial creation
Turns out the getter is re-evaluated so if it is evaluated multiple times, the Date.now returns different values between runs, and it fails. probably a bad idea to make that assumption
This is somewhat intermittent but happens most times you try to index
Reported to jbrowse2dev email by user
This fixes it by changing it from a 'getter' to a 'method' to guarantee we invoke the method once to get the config
> Fix name indexing failure on jbrowse desktop

- .husky/pre-commit
- .lintstagedrc
- package.json
- scripts/pre-commit.js
- yarn.lock
This PR adds https://www.npmjs.com/package/lint-staged to run eslint and prettier on changed files before commit
We have a pre-commit for prettier, but eslint was missing
Rather than adopt the scripts/pre-commit.js file to add eslint, i switched to use lint-staged for the purpose
It focuses on .ts, .tsx, .md, and .css
Other file types will be caught be prettier --check in CI
> Add lint-staged to pre-commit hook

- eslint.config.mjs
- plugins/variants/src/VariantRPC/MultiVariantGetGenotypeMatrix.ts
- plugins/variants/src/shared/components/ClusterDialog.tsx
- plugins/variants/src/shared/minorAlleleFrequencyUtils.ts
- yarn.lock
Currently the code basically passes raw genotypes like 0/1 into a matrix for clustering, however, this makes it sensitive to the order of 0/1 or 1/0 (same with 0|1 and 1|0)
These are effectively equivalent for clustering purposes though
This PR takes a hint from vcftools which has a command --012 command line argument
This can potentially lose some subtlety because it just says "any heterozygous is 1, any homozygous non-ref is 2" where if there are multiple alts, or multiple types of hets, it collapses that state, but this PR is probably better than the current even though current takes into account multiple alts somewhat. I added a source code comment where an advanced clustering based on vectors of allele counts could be considered
Before, some clustering, but a little fuzzy
After, …
> Use a '012' matrix for clustering genotypes

- plugins/wiggle/src/MultiLinearWiggleDisplay/components/ClusterDialog.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/model.ts
- plugins/wiggle/src/MultiLinearWiggleDisplay/types.ts
- plugins/wiggle/src/WiggleRPC/MultiWiggleGetScoreMatrix.ts
- plugins/wiggle/src/WiggleRPC/rpcMethods.ts
- plugins/wiggle/src/drawXY.ts
- plugins/wiggle/src/index.ts
The multi-variant track has the abiity to cluster variants on the fly via export to an R script, running it on the users computer, and then re-importing the result
This extends this concept for multi-wiggle tracks
An example of this is CNV data from 1000 genomes, we can cluster all the rows and see patterns in CNV across different populations
The procedure is a little different from how variants work where each variant is entered into the clustering algorithm...instead this samples the data file's score at essentially 1 value per visible pixel on the screen
This is done because there is no reliable "column of scores" like there is a "column of genotypes" for each variant. We could sample at as fine of a grain as 1 score per base pair, but the choice of 1 score per pixel will provide …
> Allow clustering multi-wiggle tracks on the fly

- plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
> Make shift-select tooltips be in the right place

- .ignore
- test_data/config_demo.json
Adds some sample data from the human genome structural variant consortium, including genotyped mobile element insertions across 1000 genomes. I had to convert their MEI csv to VCF to load into jbrowse (https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC3/release/Mobile_Elements/1.0/)
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC3/release
> Add sample data from HGSVCv3

- plugins/breakpoint-split-view/src/BreakpointSplitView/components/BreakpointSplitViewOverlay.tsx
Raises the z-index from 10->1001 to go over the view header
Fixes #4891 
For an alternative, it seems like one potential approach would be for the normal linear-genome-view header to not have a high z-index when it is embedded in the breakpoint split view
> Z-index of breakpoint split view overlay

- website/release_announcement_drafts/v3.1.0.md
* Other
* [#4876](https://github.com/GMOD/jbrowse-components/pull/4876) Allow inferring default values of adapter urls to simplify config.json ([@cmdcolin](https://github.com/cmdcolin))
* [#4875](https://github.com/GMOD/jbrowse-components/pull/4875) Add sample data from HGSVCv3 to 1000 genomes demo and config_demo ([@cmdcolin](https://github.com/cmdcolin))
* [#4880](https://github.com/GMOD/jbrowse-components/pull/4880) Allow selecting track error messages with click and drag ([@cmdcolin](https://github.com/cmdcolin))
* [#4882](https://github.com/GMOD/jbrowse-components/pull/4882) Allow clustering multi-wiggle tracks on the fly ([@cmdcolin](https://github.com/cmdcolin))
* [#4874](https://github.com/GMOD/jbrowse-components/pull/4874) Use a '012' matrix to improve clustering of genotypes …
> v3.1.0 release announcement

- plugins/config/src/RefNameAliasAdapter/RefNameAliasAdapter.ts
This is basically expected behavior if your refNameColumn doesn't match the fasta/2bit refnames, with the change, you can force the default displayed refNames to be from refNameColumn in the aliases file
A demo of this was added for NcbiSequenceReportAdapter but now we add it here so that we can load GenArk UCSC assemblies
This way, you can load a FASTA file with names like NC_000001.10 and it will display as chr1
> Allow refNameColumn in RefNameAliasAdapter to override the default displayed refnames

- plugins/config/src/RefNameAliasAdapter/RefNameAliasAdapter.ts
- plugins/config/src/RefNameAliasAdapter/configSchema.ts
This adds the ability to look for a specific column in a RefNameAliasAdapter
This enables it to reliably get the 'UCSC name' which can change column number
Sort of similar to this PR that was for the NCBI sequence_report alias adapter
https://github.com/GMOD/jbrowse-components/pull/4851
> Allow looking up header column by name for RefNameAliases

- plugins/linear-comparative-view/src/LinearComparativeView/components/Rubberband.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/components/VerticalGuide.tsx
- plugins/linear-comparative-view/src/LinearComparativeView/model.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm/AssemblyRows.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm/LeftPanel.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ImportForm/LinearSyntenyImportForm.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/LinearSyntenyView.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/VerticalGuide.tsx
The code to activate the 'synteny' track selector was returning undefined because the import form was not initializing all the synteny 'levels' (areas between the linear genome views)
This caused this statement to activateTrackSelector to pass an undefined object https://github.com/GMOD/jbrowse-components/blob/ef6d3f895e7d35e7dff78eaea7e5a49ab3386d43/plugins/linear-comparative-view/src/LinearComparativeView/model.ts#L205-L221
This fix makes it so that each level is initialized at least with an empty object, which properly initializes the MST model which can be used for further track selector usage
> Fix issue where multi-level linear synteny view would show a blank tracklist

- packages/core/pluggableElementTypes/renderers/CircularChordRendererType.tsx
- packages/core/pluggableElementTypes/renderers/RpcRenderedSvgGroup.tsx
- packages/core/pluggableElementTypes/renderers/ServerSideRenderedContent.tsx
- packages/core/pluggableElementTypes/renderers/ServerSideRendererType.tsx
- yarn.lock
Fixes https://github.com/GMOD/jbrowse-components/issues/4879
There has been a persistent understanding that we should run hydrateRoot as it is 'needed' for server side  (aka webworker) rendered components
At a high level, a "hydration" is effectively a double render
- The "server" renders it (react-dom/server::renderToString or related, produces html)
- The "client" renders it (react-dom/client::hydrateRoot, which imports the HTML, and 'adds event handlers' to it, but effectively fully rerenders all the components)
The "selling point", of the above routine, particularly in the context of e.g. a "normal" website, is that this can produce better search engine optimization for example, because the HTML is statically available for scrapers, etc. Then when a client loads a webpage, it just …
> Skip running hydration for server side rendering

- plugins/linear-genome-view/src/LinearGenomeView/components/HeaderZoomControls.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
- website/docs/faq.md
This greatly improves the intuition of the slider
Currently the slider is on a 'logarithmic scale' but has no indicators of what zoom level you will end up at
This adds a tooltip while dragging that helps you see the target window size
> Show target zoom level in tooltip on slider

- packages/core/BaseFeatureWidget/BaseFeatureDetail/DataGridDetails.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedDataGrid.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetDataGrid.tsx
- plugins/variants/src/MultiLinearVariantRenderer/components/MultiLinearVariantRendering.tsx
- plugins/variants/src/MultiLinearVariantRenderer/components/util.ts
- plugins/variants/src/MultiLinearVariantRenderer/makeImageData.ts
- plugins/variants/src/VariantFeatureWidget/VariantConsequenceDataGridWrapper.tsx
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/VariantSampleGrid.tsx
- plugins/variants/src/VcfFeature/util.ts
- plugins/variants/src/shared/MultiVariantBaseModel.tsx
- yarn.lock
Follow up to #4944  which added a stringified version of the genotype to the mouseover of the multi-variant view (so instead of just 1/0 it can say T/ref(C) for example)
This adds a column to the variant datagrid for this too
> Add 'genotype' column to the Variant sample grid

- packages/core/BaseFeatureWidget/BaseFeatureDetail/DataGridDetails.tsx
- packages/core/ui/DataGridFlexContainer.tsx
- plugins/data-management/src/AssemblyManager/AssemblyTable.tsx
- plugins/data-management/src/HierarchicalTrackSelectorWidget/components/faceted/FacetedDataGrid.tsx
- plugins/dotplot-view/src/DotplotView/components/WarningDialog.tsx
- plugins/grid-bookmark/src/GridBookmarkWidget/components/BookmarkGrid.tsx
- plugins/menus/src/SessionManager/components/SessionManager.tsx
- plugins/spreadsheet-view/src/SpreadsheetView/components/SpreadsheetDataGrid.tsx
- plugins/variants/src/MultiLinearVariantRenderer/MultiVariantRenderer.ts
- plugins/variants/src/MultiLinearVariantRenderer/components/MultiLinearVariantRendering.tsx
- plugins/variants/src/MultiLinearVariantRenderer/makeImageData.ts
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/FlexContainer.tsx
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/VariantGenotypeFrequencyTable.tsx
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/VariantSampleGrid.tsx
- plugins/variants/src/VariantFeatureWidget/VariantSampleGrid/types.ts
- plugins/variants/src/shared/MultiVariantBaseModel.tsx
- plugins/variants/src/shared/components/SourcesDataGrid.tsx
- plugins/wiggle/src/MultiLinearWiggleDisplay/components/SourcesGrid.tsx
- products/jbrowse-desktop/src/components/StartScreen/RecentSessionList.tsx
- yarn.lock
This frequency table can be used for simple cases of showing the frequency of different genotypes
Includes an 'allele count' mode which can be helpful with polyploid as the you want more of a 'dosage' calculation instead of raw genotype string matching
> Add genotype frequency table to variant feature details

- website/docs/user_guides/multiquantitative_track.md
- website/docs/user_guides/multivariant_track.md
- website/release_announcement_drafts/v3.3.0.md
This release significantly helps showing structural variants in the multi-sample SV display
* Other
* [#4931](https://github.com/GMOD/jbrowse-components/pull/4931) Show target zoom level in tooltip on slider ([@cmdcolin](https://github.com/cmdcolin))
* [#4930](https://github.com/GMOD/jbrowse-components/pull/4930) Upload last release build to https://jbrowse.org/code/jb2/latest ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* [#4922](https://github.com/GMOD/jbrowse-components/pull/4922) Add Multi-variant SV display ([@cmdcolin](https://github.com/cmdcolin))
* Other
* [#4929](https://github.com/GMOD/jbrowse-components/pull/4929) Fix broken bigbed features when there is gene level aggregation ([@cmdcolin](https://github.com/cmdcolin))
* `core`
* …
> v3.3.0 release announcement

- packages/core/ui/theme.ts
Fix #4966
Our view titles uniquely used the dark variants of the secondary color, which if customized by the user, didn't get, apparently, automatically augmented with the dark variant under mui v7
This forces user customized primary+secondary to get augmentations
> Fix theme augmentation for primary/secondary colors in v3.3.0

- plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
- plugins/bed/src/BigBedAdapter/configSchema.ts
- test_data/config_demo.json
This improves the creation of gene level glyphs for certain bigbed files that have geneName==='none'
It also changes the aggregation field from geneName2 to geneName. I think they are generally functionally the same, with maybe one being a identifier and one being a symbol sometimes...
> Avoid aggregating bigbed features with geneName === 'none'

- plugins/linear-genome-view/src/LinearGenomeView/components/Cytobands.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberband.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/OverviewRubberbandHoverTooltip.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/util.ts
I looked at drosophila in UCSC and saw they have some cytoband rendering
The cytoband data file however is tricky because because instead of any actual "staining" information, it just says 'n/a' and the color appears to flip flops are from parsing the 'name' which looks like 89B18. The coloring flip flops when the prefix, which includes the starting number+letter, changes
Added in jbrowse
what it looks like without this PR
> Add basic cytoband for Drosophila

- website/docs/developer_guides/extension_points.md
The first extension point example in the docs didn't work because the extension point didn't return a value that was the same type as its input (input was an object, returned a number).
The fixed version adds types to the `arg` so that typescript ensures that the input and return are the same type. If a more minimal example is desired, the following also works, but typescript complains about being unable to determine types.
```js
pluginManager.addToExtensionPoint('ExtensionPointName', (arg) => {
return { value: arg.value + 1 }
})
pluginManager.addToExtensionPoint('ExtensionPointName', (arg) => {
return { value: arg.value + 1 }
})
```
> Fix `addToExtensionPoint` example in docs

- packages/core/pluggableElementTypes/models/baseTrackConfig.ts
- test_data/volvox/config_spec.json
It has commonly been a piece of advice for people customizing jbrowse that they have to manually supply a displayId
This PR automatically adds a displayId with the format `trackId+displayType` so that this is no longer strictly necessary
It may have been the case that allowing user specified displayId should not even be possible...instead, the displayId should be automatically inferred as e.g. trackID+displayType
This would have allowed displayId to allows be inferred in every case in the UI, without collision or confusion as to what the displayId is
Unfortunately, it would be possibly breaking to try to impose this change at this 'stage in the game' because user customized displayId have been propagated now in various ways
> Synthesize displayId if none provided in display config

- plugins/wiggle/src/drawDensity.ts
This is a bit of an odd issue with a couple of heuristics that are hard to explain properly but here is a list of contextual factors
- We have a "log scale" mode for jbrowse wiggle tracks
- The "log scale" mode can apply to both xy, line, and density renderings
- The d3 scales can create an implicit mapping to a "color range" like grey to blue or red to grey to blue
- The log transformation is applied by d3 scales, we never explicitly call Math.log in our own code
- We have a setting that says: if the minimum value is >0, and the maximum value is greater than 1, then just make the domain [1,maxvalue]
- This helps convince d3 to give a "nice" scale, because fractional values can give very large negative values, and so if you are looking at a coverage track, which has some small fractional …
> Avoid rendering 'yellow' for low scores in wiggle density renderings with 'log-scale' enabled

- package.json
- packages/core/ReExports/list.ts
- packages/core/ReExports/modules.tsx
- packages/core/ui/theme.ts
- products/jbrowse-desktop/package.json
- yarn.lock
Plugins are able to re-use "runtime" jbrowse core libraries via our system of 're-exports'
Without the re-exports, plugins will use a bundled version of a library installed from e.g. NPM, so it can end up duplicating dependencies, not getting the latest version from the "runtime", and even cause potential issues
Currently @jbrowse/core/ui/theme was not re-exported, so it was ending up in the plugins bundle's instead of re-using the runtime
This was compounded by the fact that our @mui/material/styles re-export was incorrect
This fixes both of the above (re-exporting @jbrowse/core/ui/theme and fixing the @mui/material/styles re-export)
> Fix re-export of @mui/material/styles, and re-export theme

- packages/core/TextSearch/BaseResults.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/index.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/util.ts
- products/jbrowse-web/src/tests/BasicLinearGenomeView.test.tsx
Not sure if this is great but for unknown genomes, this could be useful
If we want to go farther down this route, people really like looking at little 'ideograms' of chromosomes also...could just mock them up based on chr length in some cases
> Add sequence length to the searchbox/refnameautocomplete dropdown

- packages/core/ui/index.ts
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- plugins/linear-genome-view/src/LinearGenomeView/util.ts
- plugins/linear-genome-view/src/searchUtils.ts
- products/jbrowse-web/src/tests/TextSearching.test.tsx
- products/jbrowse-web/src/tests/TextSearchingImportForm.test.tsx
Currently, when you search for a gene, it zooms you to the exact boundaries of the gene
It is a bit more 'comfortable' to zoom to the gene +/- a small window
This adds a default margin of "0.2*window_size" to both sides of a search result hit
JBrowse 1 has a similar behavior
> Add padding to the genomic window of search result hits

- plugins/bed/src/BedAdapter/BedAdapter.ts
- plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts
adds the workaround (directly parsing line by line from Uint8Array, rather than converting to string which has a 512Mb limit in chrome) that has been added for other data file formats to BED
> Allow parsing non-indexed BED files larger than 512MB

- packages/core/util/index.ts
- packages/product-core/src/Session/MultipleViews.ts
This PR removes session functions:
addViewOfAssembly
addLinearGenomeViewOfAssembly
These were likely inoperable because they used a field  `displayRegionsFromAssemblyName` that has not been defined since at least 2020
```
commit 3f84c5ae0d404e335cb487d7923f0ebfaa8ad176
Merge: f09fbb792 4d59e0433
Author: Robert Buels <rbuels@gmail.com>
Date:   Fri Mar 13 10:47:25 2020 -0700
Merge pull request #838 from GMOD/remove_displayRegionsFromAssemblyName
Remove displayRegionsFromAssemblyName
```
> Remove some unused functions on the session model

- packages/core/BaseFeatureWidget/BaseFeatureDetail/index.tsx
- packages/core/BaseFeatureWidget/stateModelFactory.ts
- packages/product-core/src/Session/MultipleViews.ts
- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
- website/docs/models/BaseFeatureWidget.md
- website/docs/models/BaseLinearDisplay.md
- website/docs/models/LinearGenomeView.md
- website/docs/models/MultiLinearWiggleDisplay.md
- website/docs/models/MultiVariantBaseModel.md
- website/docs/models/MultipleViewsSessionMixin.md
- yarn.lock
Currently, there is a special function in the variant feature widget that allows mouseover of a field, and it shows you additional info (example: see screenshot below)
This PR adds similar functionality to the BaseFeatureWidget
It calls the adapter's 'getMetadata' function to get any hints about what the fields returned by the adapter might mean, and then uses that for the mouseovers
The BigBedAdapter is an example of a nice self-describing data format that automatically benefits from this
Example
> Add mouseover metadata for fields in the base feature widget

- packages/core/util/index.ts
- plugins/comparative-adapters/src/BlastTabularAdapter/BlastTabularAdapter.ts
- plugins/comparative-adapters/src/ChainAdapter/ChainAdapter.ts
- plugins/comparative-adapters/src/ChainAdapter/util.ts
- plugins/comparative-adapters/src/DeltaAdapter/DeltaAdapter.ts
- plugins/comparative-adapters/src/DeltaAdapter/util.ts
- plugins/comparative-adapters/src/MCScanAnchorsAdapter/MCScanAnchorsAdapter.ts
- plugins/comparative-adapters/src/MCScanSimpleAnchorsAdapter/MCScanSimpleAnchorsAdapter.ts
- plugins/comparative-adapters/src/MashMapAdapter/MashMapAdapter.ts
- plugins/comparative-adapters/src/PAFAdapter/PAFAdapter.ts
- plugins/comparative-adapters/src/util.ts
Some chain files have lines starting with hash
e.g. https://hgdownload.soe.ucsc.edu/goldenPath/hg19/vsPapAnu2/hg19.papAnu2.all.chain.gz
this PR fixes this by skipping header lines
it also adds some better status updating to the parsing procedure
> Fix UCSC chain parsing which have 'header' lines

- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/index.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/SearchBox.tsx
- products/jbrowse-web/src/tests/TextSearching.test.tsx
- products/jbrowse-web/src/tests/TextSearchingImportForm.test.tsx
This PR https://github.com/GMOD/jbrowse-components/pull/4981 introduced a regression in the linear genome view import form where clicking the drop down, selecting "ctgB" then  hitting "Open" would say "Unknown reference sequence (6.1kbp)"
there was no test that did this click->refname select drop down action
This PR reverts the PR #4981 (will take time to debug and fix this properly) and adds a integration test for the click->select refname drop down action
> Revert "Add sequence length to the searchbox/refnameautocomplete dropdown"

- packages/core/BaseFeatureWidget/BaseFeatureDetail/Attributes.tsx
- packages/core/BaseFeatureWidget/BaseFeatureDetail/FeatureDetails.tsx
- packages/core/BaseFeatureWidget/index.test.tsx
- packages/core/BaseFeatureWidget/stateModelFactory.ts
- packages/core/BaseFeatureWidget/types.tsx
- packages/core/BaseFeatureWidget/util.tsx
- plugins/alignments/src/AlignmentsFeatureDetail/AlignmentsFeatureDetail.tsx
- plugins/alignments/src/AlignmentsFeatureDetail/Flags.tsx
- plugins/alignments/src/AlignmentsFeatureDetail/index.test.tsx
- plugins/linear-comparative-view/src/SyntenyFeatureDetail/Formatter.tsx
- plugins/linear-comparative-view/src/SyntenyFeatureDetail/SyntenyFeatureDetail.tsx
- plugins/variants/src/VariantFeatureWidget/VariantFeatureWidget.test.tsx
- yarn.lock
This avoids serializing large features to the session
This follows on from work here that made a quota exceeded message https://github.com/GMOD/jbrowse-components/pull/4997
This message is likely undesirable to run into in most cases though, and just not serializing the feature to the session is probably preferable
> Add checks for large feature fields to avoid exceeding session size

- plugins/linear-comparative-view/src/LinearComparativeDisplay/stateModelFactory.ts
- plugins/linear-comparative-view/src/LinearComparativeView/components/HeaderSearchBoxes.tsx
- plugins/linear-comparative-view/src/LinearSyntenyDisplay/drawSynteny.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/components/ExportSvgDialog.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/components/TextField2.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/model.ts
- plugins/linear-comparative-view/src/LinearSyntenyView/svgcomponents/SVGLinearSyntenyView.tsx
- plugins/linear-comparative-view/src/LinearSyntenyView/types.ts
Our processing of Chain files changes them into 'normal alignments' with a CIGAR string. These files will have a very large insertion directly following by a very large deletion. These are especially prevalent in distant evolutionary distances e.g. human vs mouse. It is not really that informative to see these "giant insertion+giant deletion" (that is just a big substitution or something that completely changed), so this PR adds an option to just hide all insertions and deletions in the CIGAR rendering called "Draw CIGAR matches only"
As implemented in this PR, this setting is a bit obscure that most people may not find, but hopefully could help some users and it might be something that could automatically toggle e.g. the rendering pipeline could detect these (insertion followed by …
> Allow hiding insertion and deletion in synteny view to help chain file visualization

- plugins/data-management/src/PluginStoreWidget/components/PluginStoreWidget.test.tsx
- products/jbrowse-web/src/SessionLoader.ts
- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/createPluginManager.ts
- products/jbrowse-web/src/rootModel/rootModel.ts
Title of this PR ("Add plugins from plugin store without reloading page") is what the end users will see, but this change was motivated by Apollo 3 needs. Here's some background/motivation.
**What Apollo 3 needs:**
A way to reload the plugin manager using the config and session that is already loaded.
The way I solved that also enables plugins from the plugin store to be installed without a whole page refresh, so I also added that in this PR as well.
**How I implemented this:**
I added a callback to the root model in JBrowse Web called `reloadPluginManagerCallback`, inspired by the `setOpenNewSessionCallback` in JBrowse Desktop. This callback can optionally take a config snapshot and a session snapshot. If a config is provided, it is used instead of re-fetching the config.json. If a …
> Add plugins from plugin store without reloading page

- plugins/breakpoint-split-view/src/BreakpointSplitView/components/BreakpointSplitViewOverlay.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/MiniControls.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabel.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/TrackLabelMenu.tsx
- plugins/linear-genome-view/src/LinearGenomeView/components/__snapshots__/LinearGenomeView.test.tsx.snap
- plugins/linear-genome-view/src/LinearGenomeView/model.ts
- products/jbrowse-react-linear-genome-view/src/JBrowseLinearGenomeView/__snapshots__/JBrowseLinearGenomeView.test.tsx.snap
This checks if the linear genome view is in the list of session.views
If it is, it is allowed to set sticky view headers, otherwise it doesn't
This is a 'general' way of expressing "is this linear genomeview a top level view", and captures the similar notion of "is this linear genome view a subview" (e.g. in breakpoint split view)
Fixes #5023
> Only set sticky view headers on "top-level linear genome views"

- packages/core/ReExports/modules.ts
Bug noted by @garrettjstevens  in v3.4.0 regarding x-data-grid reexport, regression from #4994
> Fix data grid re-exports

- plugins/data-management/src/PluginStoreWidget/components/InstalledPlugin.tsx
- plugins/data-management/src/PluginStoreWidget/components/__snapshots__/PluginStoreWidget.test.tsx.snap
- plugins/data-management/src/PluginStoreWidget/components/util.ts
This changes the icon to be "Trash can" for plugin uninstall, and adds disabled state to the "lock" icon
It also adds the plugin version to the description
before
after
> Use trash icon for uninstall in plugin store, and add version number string

- plugins/alignments/src/LinearPileupDisplay/SharedLinearPileupDisplayMixin.ts
- plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx
Placing the async keyword on selectFeature, which was added in #5010, causes issues with any display that tries to override the select feature function
This changes it so the async behavior is wrapped in a IIFE
fixes https://github.com/GMOD/jbrowse-components/issues/5030
> Remove the async keyword from BaseLinearDisplayModel

- packages/core/ui/Dialog.tsx
- yarn.lock
This allows users to provide instance of a ReactNode, e.g. render a custom component into the title area of the Dialog
I used this in a plugin to provide a "Help button" next to the title
I avoided actually allowing the "title prop" to be a ReactNode, because the title specifically a string in MUIDialogProps, and it does not like being overridden with something different. While that type is not necessarily 'sacrosanct', it seemed like it was better to just extend it with a new prop, named titleNode, instead of replacing title with something different.
note that changing title prop would also not be backwards compatible either, because a titleNode would not pass older versions of JBrowse passing title through the SanitizedHTML, so by doing things this way, it is a bit more backwards …
> Add titleNode prop to @jbrowse/core/ui/Dialog

- plugins/alignments/src/LinearAlignmentsDisplay/model.tsx
- plugins/alignments/src/LinearPileupDisplay/model.ts
- plugins/alignments/src/LinearSNPCoverageDisplay/model.ts
- plugins/breakpoint-split-view/src/BreakpointSplitView/getClip.test.ts
- plugins/breakpoint-split-view/src/BreakpointSplitView/getClip.ts
- plugins/breakpoint-split-view/src/BreakpointSplitView/model.ts
- plugins/breakpoint-split-view/src/BreakpointSplitView/util.ts
The breakpoint split view, for better or worse, fetches features independently of the tracks
This is because the tracks don't have full info about the features that they contain, because this is slow due to serialization of data over webworker
The breakpoint split view calls CoreGetFeatures independently of the tracks. However, it doesn't check if it is appropriate to call getFeatures (e.g. if it is looking at too large an area)
This can cause it to trigger very large data downloads accidentally in some cases, and this came up when re-navigating breakpoint split views
This PR fixes it by checking for the track.displays[0] being not not ready. This may not be a complete solution even in itself yet, because it only checks the flag on the first instance of the track e.g. not both levels of …
> Check that the subtracks of breakpoint split view are ready before fetching

- plugins/bed/src/BigBedAdapter/BigBedAdapter.ts
- plugins/bed/src/generateUcscTranscript.ts
- yarn.lock
There is a special field of "gene pred" type files from e.g. bigbed or ucsc exports that is called cdsStartStat and cdsEndStat. If it is set to 'none' then there is no CDS information. This is set to none for non-coding e.g. lncRNAs
Before, thinks entire gene is 'five_prime_UTR'
After
we don't have a built-in way to distinguish between coding and non-coding features on our gene tracks, and it could be argued that the before behavior was 'better' at distinguishing, but it was basically improper behavior, so this PR changes it for the better in that regard
> Avoid inferring CDS subfeatures from non-coding gene pred features

- .github/workflows/push.yml
- .github/workflows/update-docs.yml
- website/docs/user_guides/analyze_trio.md
This avoids running a bunch of CI just to update the docs
New github action was generated with the help of claude + avante.nvim (which is sort of agentic in that it created a new workflow file, applied edits, all by itself)
I touched up the result only slightly
<details>
```
-------
- Datetime: 2025-05-28 23:04:15
- Model: claude/claude-3-7-sonnet-20250219
- Selected files:
- .github/workflows/update-docs.yml
I'll help you create a new workflow that runs the update-docs.yml workflow but skips the workflows in push.yml if the commit message contains "[update docs only]".
Based on the push.yml file, I see there are several jobs that we need to conditionally skip when the commit message includes "[update docs only]".
Here's my plan:
1. Create a new workflow file that will run on push events …
```
> Add ability to make [update docs only] commits to avoid running CI

- packages/core/assemblyManager/assembly.ts
- plugins/linear-genome-view/src/LinearGenomeView/components/RefNameAutocomplete/index.tsx
Fragmented assemblies frequently have millions of little scaffolds/contigs, which can slow down the UI
I found some mobx get'ters in the assembly that were being recomputed instead of being cached, so every time you changed chromosome, it would take 5+ seconds with a UI hang
It is somewhat unclear why they are being recomputed instead of cached, but there is a workaround (which i had found earlier in react-msaview code) which is to make an autorun watch the object you want to keep cached
> Improve speed of navigation for fragmented assemblies

- products/jbrowse-desktop/src/workerPolyfill.js
- products/jbrowse-react-app/src/workerPolyfill.js
- products/jbrowse-react-linear-genome-view/src/workerPolyfill.js
- products/jbrowse-web/src/workerPolyfill.js
Plugins are loaded on both the webworker and main thread
However, some JS code can make inaccurate assumptions about the webworker environment, like that "window" exists on the webworker (it does not normally)
We create a "worker polyfill" to help with this
This PR adds some more entries to our worker polyfill, removeEventListener to fix usage of the useSWR package in plugins
useSWR is basically a react hook that fetches data
> Fix useSWR usage from plugins

- plugins/sequence/src/IndexedFastaAdapter/IndexedFastaAdapter.ts
The jbrowse-plugin-msaview plugin added the concept of MSA datasets
It can fetch MSA data from BgzipFastaAdapter based datasets for example
This involves fetching many different 'refNames'
However this is slow currently because the IndexedFastaAdapter tries to eagerly fetch extra chunks using a cache. Most of those chunks are empty for the MSA use case here, so this PR makes it stop fetching once it encounters a empty block
> Optimize fetching many small sequences from IndexedFasta (e.g. MSA datasets)

- packages/core/data_adapters/dataAdapterCache.ts
- packages/core/rpc/methods/CoreFreeResources.ts
We have a concept of trying to only create a single data adapter for each data file. This makes sure each data file is mapped to a single data adapter, and avoid re-parsing the data multiple times (which is of course slow) 
However, if a request to initialize a data adapter comes multiple times very quickly, then it can cause multiple adapters to be created because we have a race condition
Buggy pseudo-code
```
dataAdapterCache: Record<string,DataAdapter>
async function getDataAdapter(string:adapterId) {
if(!dataAdapterCache[adapterId]) {
dataAdapterCache[adapterId]=await generateNewDataAdapter() //<-- has await, so the cache is not initialized until the await is over
} 
return dataAdapterCache[adapterId] 
}
```
Corrected pseudo-code
```
dataAdapterCache: …
```
> Fix race condition in data adapter cache initialization

- plugins/wiggle/src/MultiWiggleAddTrackWorkflow/AddTrackWorkflow.tsx
Fixes https://github.com/GMOD/jbrowse-components/issues/5072
Was trying to use window.require, a desktop specific function, which is not defined on web and crashed before it could update the forms
> Fix crash on multi-wiggle importer on jbrowse-web

- plugins/linear-genome-view/src/LinearGenomeView/components/RubberbandTooltip.tsx
It was reported in #5083 that the rubberband could get stuck
This happened under 'high CPU load' sometimes
This was a tricky one to debug, but I noticed that there were actually three popovers active at once with the rubberband
1) The rubberband menu (which used a @jbrowse/core/ui/Menu which uses a MUI Popover)
2) The left RubberbandTooltip (which used a MUI Popover)
3) The right RubberbandTooltip (which used a MUI Popover)
I changed the RubberbandTooltip component to use a normal MUI Tooltip instead of a MUI Popover, and I think the error has gone away
this was a hard-to-reproduce bug, so i can't 100% confirm this PR fixes the issue, but I believe that the use of MUI tooltip is probably more natural anyways
Fixes #5083
> Fix rubberband getting stuck under certain conditions

- website/docs/quickstart_web.md
This uses the new single-file bundle of jbrowse to just download a file, chmod +x it, and then execute it
> Document simple wget method of running jbrowse CLI

- package.json
- products/jbrowse-cli/package.json
- products/jbrowse-desktop/scripts/config.js
- yarn.lock
The generic-filehandle ESM conversion made a "browser specific bundle" which sets LocalFile usage to "unimplemented"
This PR forces our webpack config to not use the browser specific bundle on our electron build
Potentially, an alternative way to try to look at this problem, is to fully remove nodeIntegration from our electron app (which is generally advised to be more secure) and then make our local file access go through IPC to the "electron-main" process
(electron-renderers are the "chrome windows" of the app e.g. BrowserWindow, while electron-main is a node.js orchestrator that boots up the electron-renderers)
> Fix local files not being able to be opened in desktop

- packages/core/ui/CascadingMenu.tsx
- packages/core/ui/hooks.ts
We moved away from material-ui-popup-state for handling cascading menu logic because it had issues where submenus would close the instant your mouse left the area, which made it hard to navigate submenus
However, there was a bug in our reimplemented logic, where multiple submenus could get opened at once
This PR fixes it
I used claude AI to guide the fix. It first made a non-effective change but I asked it to analyze the whole structure of the file and it found what looks like a working fix
<details>
> can you look at packages/core/ui/CascadingMenu.tsx. there is a bug where multiple
'submenus' can be opened at the same time. I'd like it to try to make it so only one
submenu can be open at one time
● I'll look at the CascadingMenu component to understand the bug and fix it so only one …
> Fix issue where multiple cascading submenus could be opened at once

- packages/product-core/src/ui/AboutDialogContents.tsx
- packages/product-core/src/ui/HeaderButtons.tsx
- packages/product-core/src/ui/util.ts
- plugins/linear-comparative-view/src/LGVSyntenyDisplay/configSchemaF.ts
this could probably be improved even further, but this adds locstrings so you can see the source of features in the LGV synteny display feature mouseovers
example: 
this could also be made to read the CIGAR string to show where the 'current visible' region maps to but this is just where the entire alignment block maps to
> Add locstrings to synteny mouseovers

- products/jbrowse-web/src/components/Loader.tsx
- products/jbrowse-web/src/tests/Loader.test.tsx
Marking as draft since I'm not sure this is the right way to do this.
If you add a log as described in issue #5139, you'll see that with this branch the `beforeDestroy` hook gets triggered when a plugin is added from the plugin store.
However, this involves violating the rules of hooks, since if you add the plugin manager to the `useEffect` dependencies, it triggers an infinite loop.
Fixes #5139
> Destroy old root model on pm reload

- .github/ISSUE_TEMPLATE/bug_report.md
- packages/app-core/src/HistoryManagement/index.ts
- plugins/dotplot-view/src/DotplotView/components/DotplotView.tsx
- plugins/grid-bookmark/src/index.ts
- products/jbrowse-web/src/rootModel/rootModel.ts
Since #5146 was merged it has highlighted a couple places where models weren't cleaning up keyboard listeners. This wasn't noticeable before since they would act on the orphaned (but still not destroyed) model. Now that models are destroyed, if the listeners fired they would give an warning about trying to act on a detached state tree node. This adds some `removeEventListener`s to fix that.
Also adds an `isAlive` check to an async autorun that sometimes would try to do things after the model was destroyed.
> Clean up listeners when model is destroyed
